In [1]:
import timm

In [2]:
from google.colab import drive
import os
import pandas as pd
from sklearn.model_selection import train_test_split

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
DATASET_DIR = "/content/flickr30k"
IMAGE_DIR = f"{DATASET_DIR}/Images"
CAPTION_FILE = f"{DATASET_DIR}/captions.txt"

In [4]:
# Copying 8k to Colabs local SSD
if not os.path.exists("/content/flickr30k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr30k.zip" /content/

In [5]:
!unzip "/content/flickr30k.zip" -d "/content/flickr30k"

Streaming output truncated to the last 5000 lines.
  inflating: /content/flickr30k/Images/2410320522.jpg
  inflating: /content/flickr30k/Images/2404747797.jpg
  inflating: /content/flickr30k/Images/241046599.jpg
  inflating: /content/flickr30k/Images/241345639.jpg
  inflating: /content/flickr30k/Images/2409312675.jpg
  inflating: /content/flickr30k/Images/241346471.jpg
  inflating: /content/flickr30k/Images/2404959574.jpg
  inflating: /content/flickr30k/Images/2410399168.jpg
  inflating: /content/flickr30k/Images/2406591500.jpg
  inflating: /content/flickr30k/Images/2413495734.jpg
  inflating: /content/flickr30k/Images/241346794.jpg
  inflating: /content/flickr30k/Images/2404488732.jpg
  inflating: /content/flickr30k/Images/241347664.jpg
  inflating: /content/flickr30k/Images/241345522.jpg
  inflating: /content/flickr30k/Images/241347300.jpg
  inflating: /content/flickr30k/Images/241347496.jpg
  inflating: /content/flickr30k/Images/2407214681.jpg
  inflating: /content/flickr30k/Images/241346402.jpg
  inflating: /content/flickr30k/Images/241346105.jpg
  inflating: /content/flickr30k/Images/241347243.jpg
  inflating: /content/flickr30k/Images/2409771090.jpg
  inflating: /content/flickr30k/Images/241031254.jpg
  inflating: /content/flickr30k/Images/241345811.jpg
  inflating: /content/flickr30k/Images/2414352262.jpg
  inflating: /content/flickr30k/Images/2408099454.jpg
  inflating: /content/flickr30k/Images/241347689.jpg
  inflating: /content/flickr30k/Images/2408224709.jpg
  inflating: /content/flickr30k/Images/2412716991.jpg
  inflating: /content/flickr30k/Images/241374292.jpg
  inflating: /content/flickr30k/Images/2412614152.jpg
  inflating: /content/flickr30k/Images/241545422.jpg
  inflating: /content/flickr30k/Images/2419591925.jpg
  inflating: /content/flickr30k/Images/2414710960.jpg
  inflating: /content/flickr30k/Images/241347356.jpg
  inflating: /content/flickr30k/Images/2420516613.jpg
  inflating: /content/flickr30k/Images/2417701468.jpg
  inflating: /content/flickr30k/Images/241345905.jpg
  inflating: /content/flickr30k/Images/2406062461.jpg
  inflating: /content/flickr30k/Images/241345770.jpg
  inflating: /content/flickr30k/Images/2405978603.jpg
  inflating: /content/flickr30k/Images/2414390475.jpg
  inflating: /content/flickr30k/Images/2404046478.jpg
  inflating: /content/flickr30k/Images/24187978.jpg
  inflating: /content/flickr30k/Images/241596333.jpg
  inflating: /content/flickr30k/Images/2415637042.jpg
  inflating: /content/flickr30k/Images/2403544744.jpg
  inflating: /content/flickr30k/Images/2415265825.jpg
  inflating: /content/flickr30k/Images/2419797375.jpg
  inflating: /content/flickr30k/Images/2414035800.jpg
  inflating: /content/flickr30k/Images/241345323.jpg
  inflating: /content/flickr30k/Images/24187497.jpg
  inflating: /content/flickr30k/Images/24183660.jpg
  inflating: /content/flickr30k/Images/2418265815.jpg
  inflating: /content/flickr30k/Images/241347441.jpg
  inflating: /content/flickr30k/Images/241347700.jpg
  inflating: /content/flickr30k/Images/241346215.jpg
  inflating: /content/flickr30k/Images/2415803492.jpg
  inflating: /content/flickr30k/Images/241345446.jpg
  inflating: /content/flickr30k/Images/2412281172.jpg
  inflating: /content/flickr30k/Images/2407528766.jpg
  inflating: /content/flickr30k/Images/2404560299.jpg
  inflating: /content/flickr30k/Images/241347803.jpg
  inflating: /content/flickr30k/Images/2417169797.jpg
  inflating: /content/flickr30k/Images/241347460.jpg
  inflating: /content/flickr30k/Images/241346260.jpg
  inflating: /content/flickr30k/Images/241347760.jpg
  inflating: /content/flickr30k/Images/2414384480.jpg
  inflating: /content/flickr30k/Images/241959826.jpg
  inflating: /content/flickr30k/Images/2404520067.jpg
  inflating: /content/flickr30k/Images/2412390588.jpg
  inflating: /content/flickr30k/Images/241347580.jpg
  inflating: /content/flickr30k/Images/2407470303.jpg
  inflating: /content/flickr30k/Images/2404173027.jpg
  inflating: /content/flickr30k/Images/241347150.jpg
  inflating: /content/flickr30k/Images/2417341107.jpg
  inflating: /content/flickr30k/Images/2416193212.jpg
  inflating: /content/flickr30k/Images/241345656.jpg
  inflating: /content/flickr30k/Images/2409597310.jpg
  inflating: /content/flickr30k/Images/2419816094.jpg
  inflating: /content/flickr30k/Images/241346709.jpg
  inflating: /content/flickr30k/Images/241346317.jpg
  inflating: /content/flickr30k/Images/241345533.jpg
  inflating: /content/flickr30k/Images/240696675.jpg
  inflating: /content/flickr30k/Images/2407091303.jpg
  inflating: /content/flickr30k/Images/2410906422.jpg
  inflating: /content/flickr30k/Images/2403376030.jpg
  inflating: /content/flickr30k/Images/2419569803.jpg
  inflating: /content/flickr30k/Images/2420546021.jpg
  inflating: /content/flickr30k/Images/241347114.jpg
  inflating: /content/flickr30k/Images/2411585767.jpg
  inflating: /content/flickr30k/Images/241347391.jpg
  inflating: /content/flickr30k/Images/24187380.jpg
  inflating: /content/flickr30k/Images/2419186511.jpg
  inflating: /content/flickr30k/Images/241345596.jpg
  inflating: /content/flickr30k/Images/242064301.jpg
  inflating: /content/flickr30k/Images/24188477.jpg
  inflating: /content/flickr30k/Images/2408570692.jpg
  inflating: /content/flickr30k/Images/2410153942.jpg
  inflating: /content/flickr30k/Images/241346434.jpg
  inflating: /content/flickr30k/Images/2413578705.jpg
  inflating: /content/flickr30k/Images/24186977.jpg
  inflating: /content/flickr30k/Images/2426215757.jpg
  inflating: /content/flickr30k/Images/2435166927.jpg
  inflating: /content/flickr30k/Images/2424250856.jpg
  inflating: /content/flickr30k/Images/2429505595.jpg
  inflating: /content/flickr30k/Images/2430037096.jpg
  inflating: /content/flickr30k/Images/2429369147.jpg
  inflating: /content/flickr30k/Images/242324909.jpg
  inflating: /content/flickr30k/Images/2424398046.jpg
  inflating: /content/flickr30k/Images/2423900639.jpg
  inflating: /content/flickr30k/Images/24226660.jpg
  inflating: /content/flickr30k/Images/2421340833.jpg
  inflating: /content/flickr30k/Images/2429366041 (1).jpg
  inflating: /content/flickr30k/Images/2422018883.jpg
  inflating: /content/flickr30k/Images/2427490900.jpg
  inflating: /content/flickr30k/Images/2431470169.jpg
  inflating: /content/flickr30k/Images/2422635544.jpg
  inflating: /content/flickr30k/Images/243380205.jpg
  inflating: /content/flickr30k/Images/242216901.jpg
  inflating: /content/flickr30k/Images/2421156369.jpg
  inflating: /content/flickr30k/Images/2420730259.jpg
  inflating: /content/flickr30k/Images/2425532035.jpg
  inflating: /content/flickr30k/Images/2435536626.jpg
  inflating: /content/flickr30k/Images/2435482148.jpg
  inflating: /content/flickr30k/Images/243728508.jpg
  inflating: /content/flickr30k/Images/2430223532.jpg
  inflating: /content/flickr30k/Images/2422589651.jpg
  inflating: /content/flickr30k/Images/2435685480.jpg
  inflating: /content/flickr30k/Images/2434010943.jpg
  inflating: /content/flickr30k/Images/2421822611.jpg
  inflating: /content/flickr30k/Images/2436549353.jpg
  inflating: /content/flickr30k/Images/2427393337.jpg
  inflating: /content/flickr30k/Images/2429978680.jpg
  inflating: /content/flickr30k/Images/2429284131.jpg
  inflating: /content/flickr30k/Images/2426724282.jpg
  inflating: /content/flickr30k/Images/2421367904.jpg
  inflating: /content/flickr30k/Images/242558556.jpg
  inflating: /content/flickr30k/Images/2430018178.jpg
  inflating: /content/flickr30k/Images/242658502.jpg
  inflating: /content/flickr30k/Images/2423292784.jpg
  inflating: /content/flickr30k/Images/2434006663.jpg
  inflating: /content/flickr30k/Images/2430269210.jpg
  inflating: /content/flickr30k/Images/2434440948.jpg
  inflating: /content/flickr30k/Images/2421446839.jpg
  inflating: /content/flickr30k/Images/243015377.jpg
  inflating: /content/flickr30k/Images/2421801040.jpg
  inflating: /content/flickr30k/Images/2426303900.jpg
  inflating: /content/flickr30k/Images/2426795961.jpg
  inflating: /content/flickr30k/Images/2432061076.jpg
  inflating: /content/flickr30k/Images/2423886164.jpg
  inflating: /content/flickr30k/Images/2437392162.jpg
  inflating: /content/flickr30k/Images/24321040.jpg
  inflating: /content/flickr30k/Images/2423118738.jpg
  inflating: /content/flickr30k/Images/2435804989.jpg
  inflating: /content/flickr30k/Images/2429729667.jpg
  inflating: /content/flickr30k/Images/242984829.jpg
  inflating: /content/flickr30k/Images/2422482455.jpg
  inflating: /content/flickr30k/Images/242109387.jpg
  inflating: /content/flickr30k/Images/2435518586.jpg
  inflating: /content/flickr30k/Images/2436160351.jpg
  inflating: /content/flickr30k/Images/242559369.jpg
  inflating: /content/flickr30k/Images/2428275562.jpg
  inflating: /content/flickr30k/Images/2422637172.jpg
  inflating: /content/flickr30k/Images/2421965120.jpg
  inflating: /content/flickr30k/Images/2429243285.jpg
  inflating: /content/flickr30k/Images/243711191.jpg
  inflating: /content/flickr30k/Images/2433175169.jpg
  inflating: /content/flickr30k/Images/2428912710.jpg
  inflating: /content/flickr30k/Images/2437266971.jpg
  inflating: /content/flickr30k/Images/2427840554.jpg
  inflating: /content/flickr30k/Images/2424620984.jpg
  inflating: /content/flickr30k/Images/243416847.jpg
  inflating: /content/flickr30k/Images/2430860418.jpg
  inflating: /content/flickr30k/Images/2432584943.jpg
  inflating: /content/flickr30k/Images/2429974376.jpg
  inflating: /content/flickr30k/Images/2437695339.jpg
  inflating: /content/flickr30k/Images/2424976964.jpg
  inflating: /content/flickr30k/Images/2423894412.jpg
  inflating: /content/flickr30k/Images/243162937.jpg
  inflating: /content/flickr30k/Images/2436081047.jpg
  inflating: /content/flickr30k/Images/2437766095.jpg
  inflating: /content/flickr30k/Images/2421659692.jpg
  inflating: /content/flickr30k/Images/2437798869.jpg
  inflating: /content/flickr30k/Images/2428797297.jpg
  inflating: /content/flickr30k/Images/2429305809.jpg
  inflating: /content/flickr30k/Images/2423085253.jpg
  inflating: /content/flickr30k/Images/2429366041.jpg
  inflating: /content/flickr30k/Images/2423277850.jpg
  inflating: /content/flickr30k/Images/2423550887.jpg
  inflating: /content/flickr30k/Images/2171576939.jpg
  inflating: /content/flickr30k/Images/2156726763.jpg
  inflating: /content/flickr30k/Images/2163780897.jpg
  inflating: /content/flickr30k/Images/2178306830.jpg
  inflating: /content/flickr30k/Images/216172386.jpg
  inflating: /content/flickr30k/Images/2162469360.jpg
  inflating: /content/flickr30k/Images/2181144377.jpg
  inflating: /content/flickr30k/Images/2176229181.jpg
  inflating: /content/flickr30k/Images/2176364472.jpg
  inflating: /content/flickr30k/Images/2169788484.jpg
  inflating: /content/flickr30k/Images/2174343200.jpg
  inflating: /content/flickr30k/Images/2156328004.jpg
  inflating: /content/flickr30k/Images/21833287.jpg
  inflating: /content/flickr30k/Images/2156122117.jpg
  inflating: /content/flickr30k/Images/2160230494.jpg
  inflating: /content/flickr30k/Images/2170187328.jpg
  inflating: /content/flickr30k/Images/2155994202.jpg
  inflating: /content/flickr30k/Images/2183123018.jpg
  inflating: /content/flickr30k/Images/2174583700.jpg
  inflating: /content/flickr30k/Images/2180726636.jpg
  inflating: /content/flickr30k/Images/2155653460.jpg
  inflating: /content/flickr30k/Images/2178064851.jpg
  inflating: /content/flickr30k/Images/2172570753.jpg
  inflating: /content/flickr30k/Images/2162367970.jpg
  inflating: /content/flickr30k/Images/2162746678.jpg
  inflating: /content/flickr30k/Images/2183114919.jpg
  inflating: /content/flickr30k/Images/2176147758.jpg
  inflating: /content/flickr30k/Images/215806759.jpg
  inflating: /content/flickr30k/Images/2178095150.jpg
  inflating: /content/flickr30k/Images/2158500020.jpg
  inflating: /content/flickr30k/Images/2175758177.jpg
  inflating: /content/flickr30k/Images/2179330298.jpg
  inflating: /content/flickr30k/Images/2152688935.jpg
  inflating: /content/flickr30k/Images/215797019.jpg
  inflating: /content/flickr30k/Images/2168723623.jpg
  inflating: /content/flickr30k/Images/2175980524.jpg
  inflating: /content/flickr30k/Images/2183468990.jpg
  inflating: /content/flickr30k/Images/2161273260.jpg
  inflating: /content/flickr30k/Images/2164363131.jpg
  inflating: /content/flickr30k/Images/2173677067.jpg
  inflating: /content/flickr30k/Images/2168021521.jpg
  inflating: /content/flickr30k/Images/2173828253.jpg
  inflating: /content/flickr30k/Images/217460891.jpg
  inflating: /content/flickr30k/Images/21687074.jpg
  inflating: /content/flickr30k/Images/2159081186.jpg
  inflating: /content/flickr30k/Images/2166529027.jpg
  inflating: /content/flickr30k/Images/2156131463.jpg
  inflating: /content/flickr30k/Images/218211630.jpg
  inflating: /content/flickr30k/Images/2169986652.jpg
  inflating: /content/flickr30k/Images/21688595.jpg
  inflating: /content/flickr30k/Images/2172572633.jpg
  inflating: /content/flickr30k/Images/2183227136.jpg
  inflating: /content/flickr30k/Images/2176776800.jpg
  inflating: /content/flickr30k/Images/215876547.jpg
  inflating: /content/flickr30k/Images/2174206711.jpg
  inflating: /content/flickr30k/Images/2161799386.jpg
  inflating: /content/flickr30k/Images/2171154778.jpg
  inflating: /content/flickr30k/Images/218225539.jpg
  inflating: /content/flickr30k/Images/2166417615.jpg
  inflating: /content/flickr30k/Images/2156331904.jpg
  inflating: /content/flickr30k/Images/2175184797.jpg
  inflating: /content/flickr30k/Images/2178295140.jpg
  inflating: /content/flickr30k/Images/218096711.jpg
  inflating: /content/flickr30k/Images/2176874361.jpg
  inflating: /content/flickr30k/Images/218342358.jpg
  inflating: /content/flickr30k/Images/217949158.jpg
  inflating: /content/flickr30k/Images/2168809436.jpg
  inflating: /content/flickr30k/Images/2162564553.jpg
  inflating: /content/flickr30k/Images/216627488.jpg
  inflating: /content/flickr30k/Images/2154062056.jpg
  inflating: /content/flickr30k/Images/216778085.jpg
  inflating: /content/flickr30k/Images/2166120300.jpg
  inflating: /content/flickr30k/Images/2159447283.jpg
  inflating: /content/flickr30k/Images/2170222061.jpg
  inflating: /content/flickr30k/Images/217593609.jpg
  inflating: /content/flickr30k/Images/2155533127.jpg
  inflating: /content/flickr30k/Images/2182575588.jpg
  inflating: /content/flickr30k/Images/2178985121.jpg
  inflating: /content/flickr30k/Images/2172574039.jpg
  inflating: /content/flickr30k/Images/2173312932.jpg
  inflating: /content/flickr30k/Images/218428071.jpg
  inflating: /content/flickr30k/Images/2167644298.jpg
  inflating: /content/flickr30k/Images/2190227737.jpg
  inflating: /content/flickr30k/Images/2200688503.jpg
  inflating: /content/flickr30k/Images/218620913.jpg
  inflating: /content/flickr30k/Images/2204993532.jpg
  inflating: /content/flickr30k/Images/2192573.jpg
  inflating: /content/flickr30k/Images/2187720319.jpg
  inflating: /content/flickr30k/Images/2203586218.jpg
  inflating: /content/flickr30k/Images/2187356302.jpg
  inflating: /content/flickr30k/Images/2197587684.jpg
  inflating: /content/flickr30k/Images/2192436502.jpg
  inflating: /content/flickr30k/Images/2198511848.jpg
  inflating: /content/flickr30k/Images/2194283350.jpg
  inflating: /content/flickr30k/Images/2192475933.jpg
  inflating: /content/flickr30k/Images/2204777844.jpg
  inflating: /content/flickr30k/Images/21954377.jpg
  inflating: /content/flickr30k/Images/218553496.jpg
  inflating: /content/flickr30k/Images/2199250692.jpg
  inflating: /content/flickr30k/Images/2184898283.jpg
  inflating: /content/flickr30k/Images/2188171629.jpg
  inflating: /content/flickr30k/Images/2189627515.jpg
  inflating: /content/flickr30k/Images/219301553.jpg
  inflating: /content/flickr30k/Images/2195887578.jpg
  inflating: /content/flickr30k/Images/2201192417.jpg
  inflating: /content/flickr30k/Images/2195620255.jpg
  inflating: /content/flickr30k/Images/2184817596.jpg
  inflating: /content/flickr30k/Images/2193980605.jpg
  inflating: /content/flickr30k/Images/2197552440.jpg
  inflating: /content/flickr30k/Images/2194495372.jpg
  inflating: /content/flickr30k/Images/218610963.jpg
  inflating: /content/flickr30k/Images/2185793891.jpg
  inflating: /content/flickr30k/Images/2198494923.jpg
  inflating: /content/flickr30k/Images/2193223202.jpg
  inflating: /content/flickr30k/Images/2186139563.jpg
  inflating: /content/flickr30k/Images/2199083344.jpg
  inflating: /content/flickr30k/Images/2191329761.jpg
  inflating: /content/flickr30k/Images/219070971.jpg
  inflating: /content/flickr30k/Images/2198918037.jpg
  inflating: /content/flickr30k/Images/2184664834.jpg
  inflating: /content/flickr30k/Images/220513228.jpg
  inflating: /content/flickr30k/Images/2192333873.jpg
  inflating: /content/flickr30k/Images/2201858857.jpg
  inflating: /content/flickr30k/Images/2190137367.jpg
  inflating: /content/flickr30k/Images/2190966429.jpg
  inflating: /content/flickr30k/Images/2193001254.jpg
  inflating: /content/flickr30k/Images/219843859.jpg
  inflating: /content/flickr30k/Images/2186367337.jpg
  inflating: /content/flickr30k/Images/2200338547.jpg
  inflating: /content/flickr30k/Images/2185255150.jpg
  inflating: /content/flickr30k/Images/2192547226.jpg
  inflating: /content/flickr30k/Images/2196050115.jpg
  inflating: /content/flickr30k/Images/219357394.jpg
  inflating: /content/flickr30k/Images/2201202388.jpg
  inflating: /content/flickr30k/Images/2204550058.jpg
  inflating: /content/flickr30k/Images/2201877660.jpg
  inflating: /content/flickr30k/Images/2194167019.jpg
  inflating: /content/flickr30k/Images/219730733.jpg
  inflating: /content/flickr30k/Images/218442982.jpg
  inflating: /content/flickr30k/Images/2203234266.jpg
  inflating: /content/flickr30k/Images/2202059975.jpg
  inflating: /content/flickr30k/Images/2201734906.jpg
  inflating: /content/flickr30k/Images/2203398833.jpg
  inflating: /content/flickr30k/Images/2196284168.jpg
  inflating: /content/flickr30k/Images/2188599628.jpg
  inflating: /content/flickr30k/Images/2195316844.jpg
  inflating: /content/flickr30k/Images/2203615439.jpg
  inflating: /content/flickr30k/Images/2185325305.jpg
  inflating: /content/flickr30k/Images/2188192752.jpg
  inflating: /content/flickr30k/Images/219630410.jpg
  inflating: /content/flickr30k/Images/2201050079.jpg
  inflating: /content/flickr30k/Images/2192802444.jpg
  inflating: /content/flickr30k/Images/2198484810.jpg
  inflating: /content/flickr30k/Images/2200337743.jpg
  inflating: /content/flickr30k/Images/219301555.jpg
  inflating: /content/flickr30k/Images/2188535529.jpg
  inflating: /content/flickr30k/Images/2185509485.jpg
  inflating: /content/flickr30k/Images/2189181027.jpg
  inflating: /content/flickr30k/Images/2193223637.jpg
  inflating: /content/flickr30k/Images/2202443907.jpg
  inflating: /content/flickr30k/Images/2203224077.jpg
  inflating: /content/flickr30k/Images/2201951969.jpg
  inflating: /content/flickr30k/Images/2198964806.jpg
  inflating: /content/flickr30k/Images/2202625355.jpg
  inflating: /content/flickr30k/Images/2201480583.jpg
  inflating: /content/flickr30k/Images/2195256068.jpg
  inflating: /content/flickr30k/Images/2194806429.jpg
  inflating: /content/flickr30k/Images/219810920.jpg
  inflating: /content/flickr30k/Images/2191522758.jpg
  inflating: /content/flickr30k/Images/2200070339.jpg
  inflating: /content/flickr30k/Images/2185734339.jpg
  inflating: /content/flickr30k/Images/2197275664.jpg
  inflating: /content/flickr30k/Images/2191779063.jpg
  inflating: /content/flickr30k/Images/2189995738.jpg
  inflating: /content/flickr30k/Images/2191453879.jpg
  inflating: /content/flickr30k/Images/2190899457.jpg
  inflating: /content/flickr30k/Images/2194194725.jpg
  inflating: /content/flickr30k/Images/2200901777.jpg
  inflating: /content/flickr30k/Images/2194797921.jpg
  inflating: /content/flickr30k/Images/2191566772.jpg
  inflating: /content/flickr30k/Images/219288082.jpg
  inflating: /content/flickr30k/Images/2191783475.jpg

In [6]:
print("Images:", len(os.listdir(IMAGE_DIR)))

df = pd.read_csv(CAPTION_FILE)

print(df.head())
print(df.columns)
print(df.shape)

Images: 31811
            image                                            caption
0  1000092795.jpg   Two young guys with shaggy hair look at their...
1  1000092795.jpg   Two young , White males are outside near many...
2  1000092795.jpg   Two men in green shirts are standing in a yard .
3  1000092795.jpg       A man in a blue shirt standing in a garden .
4  1000092795.jpg            Two friends enjoy time spent together .
Index(['image', 'caption'], dtype='object')
(158915, 2)

In [7]:
images = df["image"].unique().tolist()

print("Unique images:", len(images))

Unique images: 31783

In [9]:
# Create fixed split, 80, 10, 10
train_imgs, temp_imgs = train_test_split(
    images,
    train_size=25426,
    random_state=42,
    shuffle=True
)

val_imgs, test_imgs = train_test_split(
    temp_imgs,
    test_size=3178,
    random_state=42,
    shuffle=True
)

print(len(train_imgs))
print(len(val_imgs))
print(len(test_imgs))

25426
3179
3178

In [10]:
# Train test and val dataset
train_df = df[df["image"].isin(train_imgs)].reset_index(drop=True)

val_df = df[df["image"].isin(val_imgs)].reset_index(drop=True)

test_df = df[df["image"].isin(test_imgs)].reset_index(drop=True)

In [11]:
# Save files in drive
import pickle

split_dict = {
    "train": train_imgs,
    "val": val_imgs,
    "test": test_imgs
}

with open(
    f"{DATASET_DIR}/flickr30k_split.pkl",
    "wb"
) as f:
    pickle.dump(split_dict, f)

In [12]:
# Test Load
with open(
    f"{DATASET_DIR}/flickr30k_split.pkl",
    "rb"
) as f:
    split_dict = pickle.load(f)

In [13]:
train_df.head()

            image                                            caption
0  1000092795.jpg   Two young guys with shaggy hair look at their...
1  1000092795.jpg   Two young , White males are outside near many...
2  1000092795.jpg   Two men in green shirts are standing in a yard .
3  1000092795.jpg       A man in a blue shirt standing in a garden .
4  1000092795.jpg            Two friends enjoy time spent together .

Data Preprocessing

In [14]:
import re
from collections import Counter
import pickle

In [15]:
# Clean captions

def clean_caption(text):
    text = text.lower()

    # remove punctuation
    text = re.sub(r"[^a-z0-9\s]", "", text)

    # collapse spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [17]:
print(train_df["caption"].isna().sum())
print(val_df["caption"].isna().sum())
print(test_df["caption"].isna().sum())

1
0
0

In [18]:
train_df["caption"].apply(type).value_counts()

caption
<class 'str'>      127129
<class 'float'>         1
Name: count, dtype: int64

In [19]:
train_df = train_df.dropna(subset=["caption"]).reset_index(drop=True)
val_df = val_df.dropna(subset=["caption"]).reset_index(drop=True)
test_df = test_df.dropna(subset=["caption"]).reset_index(drop=True)

In [20]:
# Apply on the datasets

train_df["caption"] = train_df["caption"].apply(clean_caption)
val_df["caption"] = val_df["caption"].apply(clean_caption)
test_df["caption"] = test_df["caption"].apply(clean_caption)

In [21]:
train_df.head()

            image                                            caption
0  1000092795.jpg  two young guys with shaggy hair look at their ...
1  1000092795.jpg  two young white males are outside near many bu...
2  1000092795.jpg     two men in green shirts are standing in a yard
3  1000092795.jpg         a man in a blue shirt standing in a garden
4  1000092795.jpg              two friends enjoy time spent together

In [22]:
# Add the specialised tokens

PAD_TOKEN = "<PAD>"
UNK_TOKEN = "<UNK>"
SOS_TOKEN = "<SOS>"
EOS_TOKEN = "<EOS>"

In [23]:
# Train data vocab

counter = Counter()

for caption in train_df["caption"]:
    counter.update(caption.split())

In [24]:
print("Unique words:", len(counter))

Unique words: 18251

In [25]:
# Create Vocab

MIN_FREQ = 5

vocab = {
    PAD_TOKEN: 0,
    UNK_TOKEN: 1,
    SOS_TOKEN: 2,
    EOS_TOKEN: 3
}

for word, freq in counter.items():
    if freq >= MIN_FREQ:
        vocab[word] = len(vocab)

idx2word = {idx: word for word, idx in vocab.items()}

In [26]:
print("Vocabulary size:", len(vocab))

Vocabulary size: 6983

In [27]:
# Encoding

def encode_caption(text, vocab):

    tokens = text.split()

    encoded = [vocab["<SOS>"]]

    for token in tokens:
        encoded.append(
            vocab.get(token, vocab["<UNK>"])
        )

    encoded.append(vocab["<EOS>"])

    return encoded

In [28]:
# Set Max caption length for batching

lengths = []

for caption in train_df["caption"]:
    lengths.append(
        len(caption.split()) + 2
    )

print("Max length:", max(lengths))
print("Average length:", sum(lengths)/len(lengths))

Max length: 75
Average length: 14.264581645415287

In [29]:
MAX_LEN = 30

In [30]:
# Save and reload vocab

with open(
    f"{DATASET_DIR}/vocab.pkl",
    "wb"
) as f:
    pickle.dump(vocab, f)

In [31]:
with open(
    f"{DATASET_DIR}/vocab.pkl",
    "rb"
) as f:
    vocab = pickle.load(f)

Dataset Classes

In [32]:
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image
import os
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader

In [33]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [34]:
from collections import defaultdict
import random

train_caption_map = defaultdict(list)
val_caption_map = defaultdict(list)
test_caption_map = defaultdict(list)

bad_img = "861608773_bdafd5c996.jpg"

train_caption_map.pop(bad_img, None)
val_caption_map.pop(bad_img, None)
test_caption_map.pop(bad_img, None)

for _, row in train_df.iterrows():
    train_caption_map[row["image"]].append(row["caption"])

for _, row in val_df.iterrows():
    val_caption_map[row["image"]].append(row["caption"])

for _, row in test_df.iterrows():
    test_caption_map[row["image"]].append(row["caption"])


class Flickr8KRetrievalDataset(Dataset):
    def __init__(self, caption_map, image_dir, vocab, transform=None, random_caption=True):
        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform
        self.random_caption = random_caption

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):
        image_name = self.image_names[idx]

        captions = self.caption_map[image_name]

        if self.random_caption:
            caption = random.choice(captions)
        else:
            caption = captions[0]      # fixed caption for eval

        try:
          image = Image.open(
              os.path.join(self.image_dir, image_name)
          ).convert("RGB")

        except Exception:
            return self.__getitem__(
                (idx + 1) % len(self)
            )

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, caption

In [35]:
class Flickr8KAllCaptionEvalDataset(Dataset):

    def __init__(self, caption_map, image_dir, vocab, transform=None):

        self.samples = []
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform

        for image_name in sorted(caption_map.keys()):

            for caption in caption_map[image_name]:

                self.samples.append(
                    (image_name, caption)
                )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        image_name, caption = self.samples[idx]

        image = Image.open(
            os.path.join(self.image_dir, image_name)
        ).convert("RGB")

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, torch.tensor(caption)

In [36]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    images = []
    captions = []
    lengths = []

    for image, caption in batch:
        images.append(image)
        captions.append(caption)
        lengths.append(len(caption))

    images = torch.stack(images)

    captions = pad_sequence(
        captions,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    lengths = torch.tensor(lengths)

    return images, captions, lengths

In [37]:
train_dataset = Flickr8KRetrievalDataset(
    train_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform,
    random_caption=True
)

val_dataset = Flickr8KRetrievalDataset(
    val_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform,
    random_caption=False
)

test_dataset = Flickr8KRetrievalDataset(
    test_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform,
    random_caption=False
)

In [38]:
all_caption_test_dataset = Flickr8KAllCaptionEvalDataset(
    test_caption_map,
    IMAGE_DIR,
    vocab,
    image_transform
)

In [39]:
print(len(train_dataset))
print(len(val_dataset))
print(len(test_dataset))

25426
3179
3178

In [40]:
# Dataloaders for clip style loading
BATCH_SIZE = 256

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    num_workers=0
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=0
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=0
)

In [41]:
all_caption_test_loader = DataLoader(
    all_caption_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=0
)

In [42]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [43]:
device

'cuda'

In [44]:
print("device" in globals())
print("text_encoder" in globals())
print("train_loader" in globals())

True
False
True

In [45]:
image, caption = train_dataset[0]

print(image.shape)

print(caption)

torch.Size([3, 224, 224])
tensor([ 2, 31, 32, 17, 31, 33, 34, 30, 17, 31, 35,  3])

ResNet50 Image Encoder

In [46]:
EMBED_DIM = 256

In [47]:
import torch
import torch.nn as nn
import torchvision.models as models
import torch.nn.functional as F

In [48]:
# Encoder Image
class ImageEncoder(nn.Module):

    def __init__(self, embed_dim=512):

        super().__init__()

        backbone = models.resnet50(
            weights=models.ResNet50_Weights.IMAGENET1K_V2
        )

        for param in backbone.parameters():
          param.requires_grad = False

        # Fine tune last two ResNet stages
        for param in backbone.layer3.parameters():
            param.requires_grad = True

        for param in backbone.layer4.parameters():
            param.requires_grad = True

        self.backbone = nn.Sequential(
            *list(backbone.children())[:-1]
        )

        self.projection = nn.Sequential(
            nn.Linear(2048, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, embed_dim)
        )

    def forward(self, images):

        features = self.backbone(images)

        features = features.squeeze(-1).squeeze(-1)

        embeddings = self.projection(features)

        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

In [49]:
#Text Encoder
from torch.nn.utils.rnn import pack_padded_sequence

class TextEncoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        embed_dim=300,
        hidden_dim=512,
        pad_idx=0
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=pad_idx
        )

        self.lstm = nn.LSTM(
            embed_dim,
            hidden_dim,
            num_layers=2,
            dropout=0.3,
            bidirectional=True,
            batch_first=True
        )

        self.projection = nn.Sequential(
            nn.Linear(hidden_dim * 2, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, 512)
        )

    def forward(
        self,
        captions,
        lengths
    ):

        embedded = self.embedding(captions)

        packed = pack_padded_sequence(
            embedded,
            lengths.cpu(),
            batch_first=True,
            enforce_sorted=False
        )

        _, (hidden, _) = self.lstm(packed)

        hidden = torch.cat(
            [hidden[-2], hidden[-1]],
            dim=1
        )

        embeddings = self.projection(hidden)

        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

In [50]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

In [51]:
encoder = ImageEncoder(
    embed_dim=512
).to(device)

images, captions, lengths = next(iter(train_loader))

images = images.to(device)

with torch.no_grad():
    image_embeddings = encoder(images)

print(image_embeddings.shape)

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 229MB/s]

torch.Size([256, 512])

In [52]:
# text encoder installation and test
text_encoder = TextEncoder(
    vocab_size=len(vocab),
    embed_dim=300,
    hidden_dim=512,
    pad_idx=vocab["<PAD>"]
).to(device)

images, captions, lengths = next(iter(train_loader))

captions = captions.to(device)

with torch.no_grad():
    text_embeddings = text_encoder(
        captions,
        lengths
    )

print(text_embeddings.shape)

torch.Size([256, 512])

In [53]:
# compatibility verification
with torch.no_grad():
    image_embeddings = encoder(images.to(device))

    text_embeddings = text_encoder(
        captions.to(device),
        lengths
    )

print(image_embeddings.shape)
print(text_embeddings.shape)

torch.Size([256, 512])
torch.Size([256, 512])

In [54]:
# Normalize embedding
import torch.nn.functional as F

image_embeddings = F.normalize(image_embeddings, dim=1)
text_embeddings = F.normalize(text_embeddings, dim=1)

print(image_embeddings.norm(dim=1).mean())
print(text_embeddings.norm(dim=1).mean())

tensor(1., device='cuda:0')
tensor(1., device='cuda:0')

In [55]:
# Joint Model
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class ResNetLSTMRetrieval(nn.Module):
    def __init__(self, image_encoder, text_encoder):
        super().__init__()

        self.image_encoder = image_encoder
        self.text_encoder = text_encoder

        # Learnable temperature parameter
        self.logit_scale = nn.Parameter(
            torch.ones([]) * np.log(1 / 0.07)
        )

    def forward(self, images, captions, lengths):
        image_emb = self.image_encoder(images)
        text_emb = self.text_encoder(captions, lengths)

        # Normalize embeddings
        image_emb = F.normalize(image_emb, p=2, dim=1)
        text_emb = F.normalize(text_emb, p=2, dim=1)

        return image_emb, text_emb



model = ResNetLSTMRetrieval(
    image_encoder=encoder,
    text_encoder=text_encoder
).to(device)

In [56]:
# CLIP-Style Contrastive Loss
def clip_contrastive_loss(image_emb, text_emb, logit_scale):
    # Similarity matrix: [B, B]
    logits = torch.matmul(image_emb, text_emb.T)
    logits = logits * logit_scale.exp()

    targets = torch.arange(
        image_emb.size(0),
        device=image_emb.device
    )

    loss_i2t = F.cross_entropy(logits, targets)
    loss_t2i = F.cross_entropy(logits.T, targets)

    loss = (loss_i2t + loss_t2i) / 2

    return loss, logits

In [57]:
# Forward pass test
images, captions, lengths = next(iter(train_loader))

images = images.to(device)
captions = captions.to(device)

with torch.no_grad():
    image_emb, text_emb = model(
        images,
        captions,
        lengths
    )

print(image_emb.shape)
print(text_emb.shape)

torch.Size([256, 512])
torch.Size([256, 512])

In [58]:
# Loss test
loss, logits = clip_contrastive_loss(
    image_emb,
    text_emb,
    model.logit_scale
)

print(loss.item())
print(logits.shape)

5.625430583953857
torch.Size([256, 256])

In [59]:
# Training
optimizer = torch.optim.AdamW(
    [
        {
            "params": model.image_encoder.backbone.parameters(),
            "lr": 1e-5
        },
        {
            "params": model.image_encoder.projection.parameters(),
            "lr": 3e-4
        },
        {
            "params": model.text_encoder.parameters(),
            "lr": 3e-4
        },
        {
            "params": [model.logit_scale],
            "lr": 1e-4
        }
    ],
    weight_decay=1e-4
)

scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer,
    T_max=50
)

In [60]:
# Add Validation Loop
def evaluate(model, dataloader, device):
    model.eval()
    total_loss = 0.0

    with torch.no_grad():
        for images, captions, lengths in dataloader:
            images = images.to(device)
            captions = captions.to(device)

            image_emb, text_emb = model(
                images,
                captions,
                lengths
            )

            loss, _ = clip_contrastive_loss(
                image_emb,
                text_emb,
                model.logit_scale
            )

            total_loss += loss.item()

    return total_loss / len(dataloader)

In [61]:
import gc
import torch

gc.collect()
torch.cuda.empty_cache()
del images, captions
gc.collect()
torch.cuda.empty_cache()

In [63]:
# training
NUM_EPOCHS = 30
best_val_loss = float("inf")
BEST_MODEL_PATH = "/content/drive/MyDrive/models/30k/best_retrieval_model.pth"

for epoch in range(NUM_EPOCHS):
    model.train()
    running_loss = 0.0

    for batch_idx, (images, captions, lengths) in enumerate(train_loader):
        images = images.to(device)
        captions = captions.to(device)

        optimizer.zero_grad()

        image_emb, text_emb = model(images, captions, lengths)
        loss, _ = clip_contrastive_loss(
            image_emb,
            text_emb,
            model.logit_scale
        )

        loss.backward()
        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=5.0
        )
        optimizer.step()

        running_loss += loss.item()

        if batch_idx % 20 == 0:
          print(
              f"Epoch {epoch+1} | "
              f"Batch {batch_idx}/{len(train_loader)} | "
              f"Loss: {loss.item():.4f}"
          )

    train_loss = running_loss / len(train_loader)
    val_loss = evaluate(model, val_loader, device)

    print(
        f"Epoch {epoch+1:02d} | "
        f"Train: {train_loss:.4f} | "
        f"Val: {val_loss:.4f}"
    )

    scheduler.step()

    # Save the best model based on validation loss
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(
            {
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "epoch": epoch,
                "val_loss": val_loss
            },
            BEST_MODEL_PATH
        )
        print("  ✓ Saved best model")

Epoch 1 | Batch 0/100 | Loss: 4.5371
Epoch 1 | Batch 20/100 | Loss: 4.2276
Epoch 1 | Batch 40/100 | Loss: 3.9528
Epoch 1 | Batch 60/100 | Loss: 3.9699
Epoch 1 | Batch 80/100 | Loss: 3.6888
Epoch 01 | Train: 4.0255 | Val: 3.6847
  ✓ Saved best model
Epoch 2 | Batch 0/100 | Loss: 3.6911
Epoch 2 | Batch 20/100 | Loss: 3.3873
Epoch 2 | Batch 40/100 | Loss: 3.3927
Epoch 2 | Batch 60/100 | Loss: 3.1579
Epoch 2 | Batch 80/100 | Loss: 3.1225
Epoch 02 | Train: 3.3515 | Val: 3.2905
  ✓ Saved best model
Epoch 3 | Batch 0/100 | Loss: 3.0535
Epoch 3 | Batch 20/100 | Loss: 2.9957
Epoch 3 | Batch 40/100 | Loss: 2.8300
Epoch 3 | Batch 60/100 | Loss: 2.7407
Epoch 3 | Batch 80/100 | Loss: 2.6582
Epoch 03 | Train: 2.9297 | Val: 3.0035
  ✓ Saved best model
Epoch 4 | Batch 0/100 | Loss: 2.5718
Epoch 4 | Batch 20/100 | Loss: 2.5726
Epoch 4 | Batch 40/100 | Loss: 2.6258
Epoch 4 | Batch 60/100 | Loss: 2.6341
Epoch 4 | Batch 80/100 | Loss: 2.5877
Epoch 04 | Train: 2.6219 | Val: 2.8174
  ✓ Saved best model
Epoch 5 | Batch 0/100 | Loss: 2.6284
Epoch 5 | Batch 20/100 | Loss: 2.3585
Epoch 5 | Batch 40/100 | Loss: 2.3318
Epoch 5 | Batch 60/100 | Loss: 2.4955
Epoch 5 | Batch 80/100 | Loss: 2.2683
Epoch 05 | Train: 2.3636 | Val: 2.7128
  ✓ Saved best model
Epoch 6 | Batch 0/100 | Loss: 2.0280
Epoch 6 | Batch 20/100 | Loss: 2.0433
Epoch 6 | Batch 40/100 | Loss: 2.2569
Epoch 6 | Batch 60/100 | Loss: 2.1466
Epoch 6 | Batch 80/100 | Loss: 2.1469
Epoch 06 | Train: 2.1475 | Val: 2.6290
  ✓ Saved best model
Epoch 7 | Batch 0/100 | Loss: 2.1263
Epoch 7 | Batch 20/100 | Loss: 1.9675
Epoch 7 | Batch 40/100 | Loss: 1.9380
Epoch 7 | Batch 60/100 | Loss: 2.0579
Epoch 7 | Batch 80/100 | Loss: 1.8759
Epoch 07 | Train: 1.9793 | Val: 2.5531
  ✓ Saved best model
Epoch 8 | Batch 0/100 | Loss: 1.7672
Epoch 8 | Batch 20/100 | Loss: 1.8245
Epoch 8 | Batch 40/100 | Loss: 1.8572
Epoch 8 | Batch 60/100 | Loss: 1.8079
Epoch 8 | Batch 80/100 | Loss: 1.7911
Epoch 08 | Train: 1.8128 | Val: 2.5023
  ✓ Saved best model
Epoch 9 | Batch 0/100 | Loss: 1.6301
Epoch 9 | Batch 20/100 | Loss: 1.6177
Epoch 9 | Batch 40/100 | Loss: 1.4818
Epoch 9 | Batch 60/100 | Loss: 1.6450
Epoch 9 | Batch 80/100 | Loss: 1.7230
Epoch 09 | Train: 1.6629 | Val: 2.4154
  ✓ Saved best model
Epoch 10 | Batch 0/100 | Loss: 1.4362
Epoch 10 | Batch 20/100 | Loss: 1.4395
Epoch 10 | Batch 40/100 | Loss: 1.5827
Epoch 10 | Batch 60/100 | Loss: 1.4214
Epoch 10 | Batch 80/100 | Loss: 1.6011
Epoch 10 | Train: 1.5491 | Val: 2.3781
  ✓ Saved best model
Epoch 11 | Batch 0/100 | Loss: 1.3898
Epoch 11 | Batch 20/100 | Loss: 1.2670
Epoch 11 | Batch 40/100 | Loss: 1.4714
Epoch 11 | Batch 60/100 | Loss: 1.5918
Epoch 11 | Batch 80/100 | Loss: 1.4829
Epoch 11 | Train: 1.4338 | Val: 2.3330
  ✓ Saved best model
Epoch 12 | Batch 0/100 | Loss: 1.2724
Epoch 12 | Batch 20/100 | Loss: 1.3555
Epoch 12 | Batch 40/100 | Loss: 1.2582
Epoch 12 | Batch 60/100 | Loss: 1.4043
Epoch 12 | Batch 80/100 | Loss: 1.4145
Epoch 12 | Train: 1.3352 | Val: 2.3295
  ✓ Saved best model
Epoch 13 | Batch 0/100 | Loss: 1.2467
Epoch 13 | Batch 20/100 | Loss: 1.1287
Epoch 13 | Batch 40/100 | Loss: 1.1760
Epoch 13 | Batch 60/100 | Loss: 1.2372
Epoch 13 | Batch 80/100 | Loss: 1.2985
Epoch 13 | Train: 1.2408 | Val: 2.2935
  ✓ Saved best model
Epoch 14 | Batch 0/100 | Loss: 1.2671
Epoch 14 | Batch 20/100 | Loss: 1.0971
Epoch 14 | Batch 40/100 | Loss: 1.1203
Epoch 14 | Batch 60/100 | Loss: 1.0818
Epoch 14 | Batch 80/100 | Loss: 1.2630
Epoch 14 | Train: 1.1649 | Val: 2.2833
  ✓ Saved best model
Epoch 15 | Batch 0/100 | Loss: 1.0961
Epoch 15 | Batch 20/100 | Loss: 1.0069
Epoch 15 | Batch 40/100 | Loss: 1.0660
Epoch 15 | Batch 60/100 | Loss: 1.0913
Epoch 15 | Batch 80/100 | Loss: 1.0352
Epoch 15 | Train: 1.0951 | Val: 2.3098
Epoch 16 | Batch 0/100 | Loss: 1.0480
Epoch 16 | Batch 20/100 | Loss: 0.9894
Epoch 16 | Batch 40/100 | Loss: 0.9754
Epoch 16 | Batch 60/100 | Loss: 1.1518
Epoch 16 | Batch 80/100 | Loss: 0.9993
Epoch 16 | Train: 1.0272 | Val: 2.2551
  ✓ Saved best model
Epoch 17 | Batch 0/100 | Loss: 0.9579
Epoch 17 | Batch 20/100 | Loss: 0.9829
Epoch 17 | Batch 40/100 | Loss: 0.9389
Epoch 17 | Batch 60/100 | Loss: 0.9525
Epoch 17 | Batch 80/100 | Loss: 0.9368
Epoch 17 | Train: 0.9711 | Val: 2.2343
  ✓ Saved best model
Epoch 18 | Batch 0/100 | Loss: 0.9289
Epoch 18 | Batch 20/100 | Loss: 0.8650
Epoch 18 | Batch 40/100 | Loss: 0.9266
Epoch 18 | Batch 60/100 | Loss: 0.8054
Epoch 18 | Batch 80/100 | Loss: 0.8814
Epoch 18 | Train: 0.9118 | Val: 2.2252
  ✓ Saved best model
Epoch 19 | Batch 0/100 | Loss: 0.8369
Epoch 19 | Batch 20/100 | Loss: 1.0329
Epoch 19 | Batch 40/100 | Loss: 0.8811
Epoch 19 | Batch 60/100 | Loss: 0.8298
Epoch 19 | Batch 80/100 | Loss: 0.8808
Epoch 19 | Train: 0.8671 | Val: 2.2211
  ✓ Saved best model
Epoch 20 | Batch 0/100 | Loss: 0.8860
Epoch 20 | Batch 20/100 | Loss: 0.7419
Epoch 20 | Batch 40/100 | Loss: 0.7369
Epoch 20 | Batch 60/100 | Loss: 0.7213
Epoch 20 | Batch 80/100 | Loss: 0.7295
Epoch 20 | Train: 0.8034 | Val: 2.2064
  ✓ Saved best model
Epoch 21 | Batch 0/100 | Loss: 0.6809
Epoch 21 | Batch 20/100 | Loss: 0.8043
Epoch 21 | Batch 40/100 | Loss: 0.9074
Epoch 21 | Batch 60/100 | Loss: 0.7833
Epoch 21 | Batch 80/100 | Loss: 0.7874
Epoch 21 | Train: 0.7750 | Val: 2.2023
  ✓ Saved best model
Epoch 22 | Batch 0/100 | Loss: 0.6672
Epoch 22 | Batch 20/100 | Loss: 0.7719
Epoch 22 | Batch 40/100 | Loss: 0.8155
Epoch 22 | Batch 60/100 | Loss: 0.8625
Epoch 22 | Batch 80/100 | Loss: 0.7807
Epoch 22 | Train: 0.7334 | Val: 2.1857
  ✓ Saved best model
Epoch 23 | Batch 0/100 | Loss: 0.6087
Epoch 23 | Batch 20/100 | Loss: 0.5978
Epoch 23 | Batch 40/100 | Loss: 0.7767
Epoch 23 | Batch 60/100 | Loss: 0.7033
Epoch 23 | Batch 80/100 | Loss: 0.7384
Epoch 23 | Train: 0.7000 | Val: 2.1808
  ✓ Saved best model
Epoch 24 | Batch 0/100 | Loss: 0.5902
Epoch 24 | Batch 20/100 | Loss: 0.7173
Epoch 24 | Batch 40/100 | Loss: 0.6468
Epoch 24 | Batch 60/100 | Loss: 0.7185
Epoch 24 | Batch 80/100 | Loss: 0.6507
Epoch 24 | Train: 0.6645 | Val: 2.1753
  ✓ Saved best model
Epoch 25 | Batch 0/100 | Loss: 0.6420
Epoch 25 | Batch 20/100 | Loss: 0.6415
Epoch 25 | Batch 40/100 | Loss: 0.6039
Epoch 25 | Batch 60/100 | Loss: 0.6648
Epoch 25 | Batch 80/100 | Loss: 0.6433
Epoch 25 | Train: 0.6383 | Val: 2.1956
Epoch 26 | Batch 0/100 | Loss: 0.5476
Epoch 26 | Batch 20/100 | Loss: 0.5967
Epoch 26 | Batch 40/100 | Loss: 0.6369
Epoch 26 | Batch 60/100 | Loss: 0.6245
Epoch 26 | Batch 80/100 | Loss: 0.7378
Epoch 26 | Train: 0.6111 | Val: 2.1818
Epoch 27 | Batch 0/100 | Loss: 0.6751
Epoch 27 | Batch 20/100 | Loss: 0.5011
Epoch 27 | Batch 40/100 | Loss: 0.5105
Epoch 27 | Batch 60/100 | Loss: 0.5772
Epoch 27 | Batch 80/100 | Loss: 0.5717
Epoch 27 | Train: 0.5835 | Val: 2.1454
  ✓ Saved best model
Epoch 28 | Batch 0/100 | Loss: 0.5238
Epoch 28 | Batch 20/100 | Loss: 0.6630
Epoch 28 | Batch 40/100 | Loss: 0.5567
Epoch 28 | Batch 60/100 | Loss: 0.5579
Epoch 28 | Batch 80/100 | Loss: 0.6572
Epoch 28 | Train: 0.5544 | Val: 2.1757
Epoch 29 | Batch 0/100 | Loss: 0.5257
Epoch 29 | Batch 20/100 | Loss: 0.5238
Epoch 29 | Batch 40/100 | Loss: 0.4923
Epoch 29 | Batch 60/100 | Loss: 0.5421
Epoch 29 | Batch 80/100 | Loss: 0.5685
Epoch 29 | Train: 0.5377 | Val: 2.1518
Epoch 30 | Batch 0/100 | Loss: 0.4865
Epoch 30 | Batch 20/100 | Loss: 0.5161
Epoch 30 | Batch 40/100 | Loss: 0.5658
Epoch 30 | Batch 60/100 | Loss: 0.5206
Epoch 30 | Batch 80/100 | Loss: 0.5258
Epoch 30 | Train: 0.5126 | Val: 2.1449
  ✓ Saved best model

In [64]:
FINAL_MODEL_PATH = "/content/drive/MyDrive/models/30k/best_retrieval_model.pth"

torch.save(model.state_dict(), BEST_MODEL_PATH)

Evaluation

In [65]:
def extract_embeddings(model, dataloader, device):
    model.load_state_dict(
    torch.load(FINAL_MODEL_PATH, map_location=device)
    )

    model.eval()


    image_embeddings = []
    text_embeddings = []

    with torch.no_grad():
        for images, captions, lengths in dataloader:
            images = images.to(device)
            captions = captions.to(device)

            img_emb, txt_emb = model(images, captions, lengths)

            image_embeddings.append(img_emb.cpu())
            text_embeddings.append(txt_emb.cpu())

    image_embeddings = torch.cat(image_embeddings, dim=0)
    text_embeddings = torch.cat(text_embeddings, dim=0)

    return image_embeddings, text_embeddings

In [66]:
image_embs, text_embs = extract_embeddings(
    model,
    all_caption_test_loader,
    device
)

print(image_embs.shape)
print(text_embs.shape)

/tmp/ipykernel_6146/340369310.py:37: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return image, torch.tensor(caption)

torch.Size([15890, 512])
torch.Size([15890, 512])

In [67]:
# Similarity Matrix
unique_image_embs = image_embs[::5]

similarity = unique_image_embs @ text_embs.T

print("Image embeddings:", unique_image_embs.shape)
print("Text embeddings:", text_embs.shape)
print("Similarity:", similarity.shape)

Image embeddings: torch.Size([3178, 512])
Text embeddings: torch.Size([15890, 512])
Similarity: torch.Size([3178, 15890])

In [68]:
# image -> text
def image_to_text_recall(similarity, k):

    correct = 0

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        topk = similarity[img_idx].topk(k).indices.tolist()

        if any(idx in gt_caps for idx in topk):
            correct += 1

    return correct / similarity.shape[0]

In [69]:
def text_to_image_recall(similarity, k):

    similarity_t = similarity.T

    correct = 0

    for cap_idx in range(similarity_t.shape[0]):

        gt_img = cap_idx // 5

        topk = similarity_t[cap_idx]\
            .topk(k)\
            .indices\
            .tolist()

        if gt_img in topk:
            correct += 1

    return correct / similarity_t.shape[0]

In [70]:
def image_to_text_mrr(similarity):

    reciprocal_ranks = []

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        sorted_idx = torch.argsort(
            similarity[img_idx],
            descending=True
        )

        best_rank = float("inf")

        for cap in gt_caps:

            rank = (
                (sorted_idx == cap)
                .nonzero(as_tuple=True)[0]
                .item()
            ) + 1

            best_rank = min(best_rank, rank)

        reciprocal_ranks.append(
            1.0 / best_rank
        )

    return np.mean(reciprocal_ranks)

In [71]:
def text_to_image_mrr(similarity):

    similarity_t2i = similarity.T

    reciprocal_ranks = []

    for cap_idx in range(similarity_t2i.shape[0]):

        gt_image = cap_idx // 5

        sorted_idx = torch.argsort(
            similarity_t2i[cap_idx],
            descending=True
        )

        rank = (
            (sorted_idx == gt_image)
            .nonzero(as_tuple=True)[0]
            .item()
        ) + 1

        reciprocal_ranks.append(
            1.0 / rank
        )

    return np.mean(reciprocal_ranks)

In [72]:
results = pd.DataFrame({
    "Metric": [
        "Recall@1",
        "Recall@5",
        "Recall@10",
        "MRR"
    ],
    "Image→Text": [
        image_to_text_recall(similarity, 1),
        image_to_text_recall(similarity, 5),
        image_to_text_recall(similarity, 10),
        image_to_text_mrr(similarity)
    ],
    "Text→Image": [
        text_to_image_recall(similarity, 1),
        text_to_image_recall(similarity, 5),
        text_to_image_recall(similarity, 10),
        text_to_image_mrr(similarity)
    ]
})

results["Image→Text"] = results["Image→Text"].round(6)
results["Text→Image"] = results["Text→Image"].round(6)

display(results)

      Metric  Image→Text  Text→Image
0   Recall@1    0.209251    0.154185
1   Recall@5    0.444934    0.374449
2  Recall@10    0.566394    0.491001
3        MRR    0.324694    0.262396