In [ ]:
from google.colab import drive
import pickle
import pandas as pd
from collections import defaultdict
import random
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image
import os
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
import timm
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install rouge_score

Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)

In [ ]:
!pip install pycocoevalcap

Requirement already satisfied: pycocoevalcap in /usr/local/lib/python3.12/dist-packages (1.2)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from pycocoevalcap) (2.0.11)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pycocotools>=2.0.2->pycocoevalcap) (2.0.2)

In [ ]:
import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer

from pycocoevalcap.cider.cider import Cider
from pycocoevalcap.spice.spice import Spice

import pandas as pd
import torch

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda

In [ ]:
# Copying 8k to Colabs local SSD
if not os.path.exists("/content/flickr8k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr8k.zip" /content/

In [ ]:
if not os.path.isdir("/content/flickr8k/Images"):
  !unzip "/content/flickr8k.zip" -d "/content/flickr8k"

In [ ]:
print("Images:", len(os.listdir("/content/flickr8k/Images")))

Images: 8091

In [ ]:
# Copying 30k to Colabs local SSD
if not os.path.exists("/content/flickr30k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr30k.zip" /content/

In [ ]:
if not os.path.isdir("/content/flickr30k/Images"):
  !unzip "/content/flickr30k.zip" -d "/content/flickr30k"

In [ ]:
print("Images:", len(os.listdir("/content/flickr30k/Images")))

Images: 31811

In [ ]:
DATASETS = {
    "flickr8k": {
        "ROOT": "/content/flickr8k",
        "IMAGE_DIR": "/content/flickr8k/Images",
        "CAPTION_FILE": "/content/flickr8k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/flickr8k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/vocab.pkl"
    },
    "flickr30k": {
        "ROOT": "/content/flickr30k",
        "IMAGE_DIR": "/content/flickr30k/Images",
        "CAPTION_FILE": "/content/flickr30k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/flickr30k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/vocab.pkl"
    }
}

In [ ]:
def image_caption_map(train_df,val_df,test_df):
  train_caption_map = defaultdict(list)
  val_caption_map = defaultdict(list)
  test_caption_map = defaultdict(list)

  bad_img = "861608773_bdafd5c996.jpg"

  train_caption_map.pop(bad_img, None)
  val_caption_map.pop(bad_img, None)
  test_caption_map.pop(bad_img, None)

  for _, row in train_df.iterrows():
      train_caption_map[row["image"]].append(row["caption"])

  for _, row in val_df.iterrows():
      val_caption_map[row["image"]].append(row["caption"])

  for _, row in test_df.iterrows():
      test_caption_map[row["image"]].append(row["caption"])
  return train_caption_map,val_caption_map,test_caption_map

In [ ]:
train_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomResizedCrop(
        224,
        scale=(0.8, 1.0),
        ratio=(0.9, 1.1)
    ),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(5),
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2,
        hue=0.05
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

In [ ]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [ ]:
# Encoding

def encode_caption(text, vocab):

    tokens = text.split()

    encoded = [vocab["<SOS>"]]

    for token in tokens:
        encoded.append(
            vocab.get(token, vocab["<UNK>"])
        )

    encoded.append(vocab["<EOS>"])

    return encoded

In [ ]:
class FlickrCaptionDataset(Dataset):

    def __init__(
            self,
            caption_map,
            image_dir,
            vocab,
            transform=None,
            random_caption=True):

        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform
        self.random_caption = random_caption

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):

        image_name = self.image_names[idx]

        captions = self.caption_map[image_name]

        if self.random_caption:
            caption = random.choice(captions)
        else:
            caption = captions[0]

        try:
            image = Image.open(
                os.path.join(self.image_dir, image_name)
            ).convert("RGB")
        except Exception:
            return self.__getitem__((idx + 1) % len(self))

        if self.transform:
            image = self.transform(image)

        caption = encode_caption(caption, self.vocab)

        input_caption = torch.tensor(
            caption[:-1],
            dtype=torch.long
        )

        target_caption = torch.tensor(
            caption[1:],
            dtype=torch.long
        )

        return image, input_caption, target_caption

In [ ]:
from torch.utils.data import Dataset
from PIL import Image
import os

class FlickrCaptionTestDataset(Dataset):

    def __init__(
            self,
            caption_map,
            image_dir,
            transform=None
    ):

        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.transform = transform

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):

        image_name = self.image_names[idx]

        # List containing all 5 captions
        captions = self.caption_map[image_name]

        try:
            image = Image.open(
                os.path.join(self.image_dir, image_name)
            ).convert("RGB")

        except Exception:
            return self.__getitem__(
                (idx + 1) % len(self)
            )

        if self.transform:
            image = self.transform(image)

        return image, captions

In [ ]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    images = []
    input_captions = []
    target_captions_list = []

    for image, input_caption, target_caption in batch:
        images.append(image)
        input_captions.append(input_caption)
        target_captions_list.append(target_caption)

    images = torch.stack(images)

    input_captions = pad_sequence(
        input_captions,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    padded_target_captions = pad_sequence(
        target_captions_list,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    return images, input_captions, padded_target_captions

In [ ]:
#encoder
import torchvision.models as tv_models
import torch.nn as nn

class ViTImageEncoder(nn.Module):

    def __init__(self, embed_dim=512):
        super().__init__()

        vit = tv_models.vit_b_16(weights=tv_models.ViT_B_16_Weights.IMAGENET1K_V1)

        # torchvision's ViT internals
        self.conv_proj = vit.conv_proj
        self.class_token = vit.class_token
        self.encoder = vit.encoder


        # freeze everything by default
        for p in self.parameters():
            p.requires_grad = False

        # unfreeze last 4 transformer blocks
        for block in list(self.encoder.layers.children())[-4:]:
            for p in block.parameters():
                p.requires_grad = True

        self.projection = nn.Sequential(
            nn.Linear(768,768),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(768,embed_dim),
            nn.LayerNorm(embed_dim)
        )

    def _process_input(self, x):
        n, c, h, w = x.shape
        p = 16  # patch size
        x = self.conv_proj(x)
        x = x.reshape(n, 768, (h // p) * (w // p))
        x = x.permute(0, 2, 1)
        return x

    def forward(self, x):
        n = x.shape[0]
        x = self._process_input(x)

        batch_class_token = self.class_token.expand(n, -1, -1)
        x = torch.cat([batch_class_token, x], dim=1)

        x = self.encoder(x)

        # CLS token
        x = x[:, 0]

        x = self.projection(x)
        return x

In [ ]:
class LSTMCaptionDecoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        embed_dim=512,
        hidden_dim=512,
        pad_idx=0
    ):
        super().__init__()

        # Word embedding
        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=pad_idx
        )

        self.lstm = nn.LSTM(
            input_size=embed_dim,
            hidden_size=hidden_dim,
            num_layers=1,
            batch_first=True,
            dropout=0.0
        )
        for name, param in self.lstm.named_parameters():
          if "weight_ih" in name:
              nn.init.xavier_uniform_(param)
          elif "weight_hh" in name:
              nn.init.orthogonal_(param)
          elif "bias" in name:
              nn.init.zeros_(param)
        self.norm = nn.LayerNorm(hidden_dim)

        self.dropout = nn.Dropout(0.2)

        # Output vocabulary prediction
        self.fc = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(hidden_dim, vocab_size)
        )

        self.image_proj = nn.Sequential(
            nn.Linear(embed_dim, embed_dim),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.LayerNorm(embed_dim)
        )
        nn.init.xavier_uniform_(self.embedding.weight)

        # Initialize all Linear layers
        for m in self.modules():
          if isinstance(m, nn.Linear):
              nn.init.xavier_uniform_(m.weight)
              if m.bias is not None:
                  nn.init.zeros_(m.bias)
        self.fc[-1].weight = self.embedding.weight
        with torch.no_grad():
          self.embedding.weight[pad_idx].zero_()

    def forward(self, image_features, captions):

      embeddings = self.embedding(captions)

      image_features = self.image_proj(image_features)
      image_features = image_features.unsqueeze(1)

      inputs = torch.cat(
          (image_features, embeddings),
          dim=1
      )

      outputs, _ = self.lstm(inputs)

      outputs = outputs[:, 1:, :]      # remove image timestep
      outputs = self.norm(outputs)
      outputs = self.dropout(outputs)

      outputs = self.fc(outputs)

      return outputs

In [ ]:
#Joint Model
class ViTLSTMCaptioningModel(nn.Module):

    def __init__(self, encoder, decoder):
        super().__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(self, images, captions):

        # Image embedding from ViT
        image_features = self.encoder(images)

        # Caption decoder
        outputs = self.decoder(
            image_features,
            captions
        )

        return outputs

    def generate_caption(self,images,vocab,max_length=30,beam_size=3):
        self.eval()
        with torch.inference_mode():
            device_type = images.device.type
            with torch.autocast(device_type=device_type,enabled=(device_type == "cuda")):
                # Beam search currently supports one image
                images = images[:1]
                image_features = self.encoder(images)
                image_features = self.decoder.image_proj(image_features)
                _, hidden = self.decoder.lstm(image_features.unsqueeze(1))
                beams = [([vocab["<SOS>"]],hidden,0.0)]
                completed = []
                for step in range(max_length):
                    candidates = []
                    for tokens, hidden_state, score in beams:
                        # Already finished
                        if tokens[-1] == vocab["<EOS>"]:
                            completed.append((tokens, hidden_state, score))
                            continue
                        last_token = torch.tensor([tokens[-1]],device=images.device)
                        inputs = self.decoder.embedding(last_token).unsqueeze(1)

                        outputs, new_hidden = self.decoder.lstm(
                            inputs,
                            hidden_state
                        )

                        outputs = self.decoder.norm(outputs)
                        outputs = self.decoder.dropout(outputs)

                        scores = self.decoder.fc(outputs.squeeze(1))

                        # Prevent special tokens
                        scores[:, vocab["<PAD>"]] = float("-inf")
                        scores[:, vocab["<SOS>"]] = float("-inf")
                        scores[:, vocab["<UNK>"]] = float("-inf")

                        if step < 3:
                            scores[:, vocab["<EOS>"]] = float("-inf")

                        log_probs = F.log_softmax(
                            scores,
                            dim=-1
                        )
                        values, indices = torch.topk(
                            log_probs,
                            beam_size*3,
                            dim=-1
                        )

                        for k in range(beam_size * 3):
                            token = indices[0, k].item()

                            # repetition blocking
                            # prevent immediate repetition
                            if len(tokens) > 0 and token == tokens[-1]:
                                continue
                            if token in tokens[-3:]:
                              continue
                            # Trigram blocking
                            if len(tokens) >= 3:
                                trigram = (tokens[-2], tokens[-1], token)
                                exists = False
                                for i in range(len(tokens)-2):
                                    if (tokens[i],tokens[i+1],tokens[i+2]) == trigram:
                                        exists = True
                                        break
                                if exists:
                                    continue
                            new_tokens = tokens + [token]
                            new_score = score + values[0, k].item()
                            new_hidden_clone = (new_hidden[0].clone(),new_hidden[1].clone())

                            candidates.append((new_tokens,new_hidden_clone,new_score))
                    if len(candidates) == 0:
                        break
                    # Length normalization
                    alpha = 0.7

                    candidates = sorted(
                        candidates,
                        key=lambda x:
                        x[2] / (((5 + len(x[0])) / 6) ** alpha),
                        reverse=True
                    )
                    beams = candidates[:beam_size]
                    if all(beam[0][-1] == vocab["<EOS>"] for beam in beams):
                        completed.extend(beams)
                        break
                if len(completed) == 0:
                    completed = beams

                completed = sorted(
                    completed,
                    key=lambda x:
                    x[2] / (((5 + len(x[0])) / 6) ** alpha),
                    reverse=True
                )
                best = completed[0][0]
                # Remove SOS
                best = best[1:]
                # Trim after EOS
                if vocab["<EOS>"] in best:
                    best = best[:best.index(vocab["<EOS>"])]
                return [best]

In [ ]:
def build_image_text_decoder(vocab,device):
  encoder = ViTImageEncoder(embed_dim=512)

  decoder = LSTMCaptionDecoder(
      vocab_size=len(vocab),
      embed_dim=512,
      hidden_dim=512,
      pad_idx=vocab["<PAD>"]
  )

  model = ViTLSTMCaptioningModel(
      encoder,
      decoder
  ).to(device)

  return model

In [ ]:
def define_optimizer(model):

    optimizer = torch.optim.AdamW(
    [
        {
            "params": filter(
                lambda p: p.requires_grad,
                model.encoder.encoder.parameters()
            ),
            "lr":5e-6
        },
        {
            "params": model.encoder.projection.parameters(),
            "lr":2e-4
        },
        {
            "params": model.decoder.parameters(),
            "lr":2e-4
        }
    ],
    betas=(0.9,0.98),
    weight_decay=1e-4
    )

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=50)

    return optimizer, scheduler

In [ ]:
def evaluate(model, dataloader, criterion, device):

    model.eval()

    total_loss = 0.0

    with torch.no_grad():

        for images, input_captions, target_captions in dataloader:

            images = images.to(device)
            input_captions = input_captions.to(device)
            target_captions = target_captions.to(device)

            outputs = model(
                images,
                input_captions
            )

            loss = criterion(
                outputs.reshape(-1, outputs.size(-1)),
                target_captions.reshape(-1)
            )

            total_loss += loss.item()

    return total_loss / len(dataloader)

In [ ]:
import os
import time
import torch
import torch.nn as nn

def model_training(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        criterion,
        dataset_name):

    NUM_EPOCHS = 50

    best_val_loss = float("inf")

    patience = 8
    epochs_without_improvement = 0

    SAVE_DIR = f"/content/drive/MyDrive/MMCaptioning/C3/{dataset_name}"
    os.makedirs(SAVE_DIR, exist_ok=True)

    BEST_MODEL_PATH = os.path.join(
        SAVE_DIR,
        "best_captioning_C3_model.pth"
    )

    for epoch in range(NUM_EPOCHS):

        print(f"\n================ Epoch {epoch+1}/{NUM_EPOCHS} ================")

        model.train()

        running_loss = 0.0

        epoch_start = time.time()

        for batch_idx, (images, input_captions, target_captions) in enumerate(train_loader):

            batch_start = time.time()

            images = images.to(device, non_blocking=True)
            input_captions = input_captions.to(device, non_blocking=True)
            target_captions = target_captions.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            outputs = model(
                images,
                input_captions
            )

            loss = criterion(
                outputs.reshape(-1, outputs.size(-1)),
                target_captions.reshape(-1)
            )

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_norm=1.0
            )

            optimizer.step()

            running_loss += loss.item()

            print(
                f"Batch {batch_idx+1:03d}/{len(train_loader)} | "
                f"Loss: {loss.item():.4f} | "
                f"Time: {time.time()-batch_start:.2f}s"
            )

        train_loss = running_loss / len(train_loader)

        train_time = time.time() - epoch_start

        # Validation

        val_start = time.time()

        val_loss = evaluate(
            model,
            val_loader,
            criterion,
            device
        )

        scheduler.step()

        val_time = time.time() - val_start

        print("\n---------------- Summary ----------------")

        print(f"Train Loss      : {train_loss:.4f}")
        print(f"Validation Loss : {val_loss:.4f}")
        print(f"Training Time   : {train_time:.2f}s")
        print(f"Validation Time : {val_time:.2f}s")

        print(
            f"GPU Memory Used : "
            f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
        )

        # Save Best

        if val_loss < best_val_loss:

            best_val_loss = val_loss
            epochs_without_improvement = 0

            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "scheduler_state_dict": scheduler.state_dict(),
                    "epoch": epoch,
                    "val_loss": val_loss
                },
                BEST_MODEL_PATH
            )

            print(f"✓ Best model saved (Val Loss: {val_loss:.4f})")

        else:

            epochs_without_improvement += 1

            print(
                f"No improvement for "
                f"{epochs_without_improvement}/{patience} epochs"
            )

        if epochs_without_improvement >= patience:

            print("\nEarly stopping triggered!")

            break

    checkpoint = torch.load(
        BEST_MODEL_PATH,
        map_location=device
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    return model, BEST_MODEL_PATH

In [ ]:
import gc
def reset_resources():
  gc.collect()
  torch.cuda.empty_cache()
  print("\nMemory after cleanup")
  print("Allocated:",torch.cuda.memory_allocated()/1024**3)
  print("Reserved:",torch.cuda.memory_reserved()/1024**3)

In [ ]:
def caption_test_collate_fn(batch):

    images = []
    all_references = []

    for image, references in batch:
        images.append(image)
        all_references.append(references)

    images = torch.stack(images)

    return images, all_references

In [ ]:
def prepare_caption_dataloaders(
        train_caption_map,
        val_caption_map,
        test_caption_map):

    BATCH_SIZE = 192

    train_dataset = FlickrCaptionDataset(
        train_caption_map,
        IMAGE_DIR,
        vocab,
        train_transform,
        random_caption=True
    )

    val_dataset = FlickrCaptionDataset(
        val_caption_map,
        IMAGE_DIR,
        vocab,
        image_transform,
        random_caption=False
    )

    # Different dataset for evaluation
    test_dataset = FlickrCaptionTestDataset(
        test_caption_map,
        IMAGE_DIR,
        image_transform
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=8,
        pin_memory=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=8,
        pin_memory=True
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=caption_test_collate_fn,   # Different collate function
        num_workers=8,
        pin_memory=True
    )

    return train_loader, val_loader, test_loader

In [ ]:
def model_testing(model,checkpoint_path,test_loader,vocab,device):
  checkpoint = torch.load(checkpoint_path,map_location=device)
  model.load_state_dict(checkpoint["model_state_dict"])
  model.to(device)
  model.eval()



  idx2word = {v: k for k, v in vocab.items()}

  references = []
  predictions = []

  rouge = rouge_scorer.RougeScorer(["rougeL"],use_stemmer=True)

  rouge_scores = []
  meteor_scores = []

  coco_refs = {}
  coco_preds = {}

  sample_id = 0

  print("Generating captions...")

  with torch.inference_mode():

      for images, all_references in test_loader:

        images = images.to(device)   # move BEFORE running encoder

        predicted_ids = []

        for i in range(images.size(0)):
            pred = model.generate_caption(
                images[i:i+1],
                vocab
            )
            predicted_ids.extend(pred)

        for i in range(images.size(0)):
            # Prediction
            pred_words = []
            for idx in predicted_ids[i]:
              idx = int(idx)

              if idx == vocab["<EOS>"]:
                  break

              if idx in (
                  vocab["<PAD>"],
                  vocab["<SOS>"]
              ):
                  continue

              pred_words.append(idx2word[idx])

            pred_sentence = " ".join(pred_words)

            # References (5 captions)
            ref_words = [ref.split() for ref in all_references[i]]
            references.append(ref_words)
            predictions.append(pred_words)

            # ROUGE-L
            rouge_values = []

            for ref in all_references[i]:

                rouge_values.append(rouge.score(ref,pred_sentence)["rougeL"].fmeasure)

            rouge_scores.append(max(rouge_values))

            # METEOR
            meteor_scores.append(meteor_score(ref_words,pred_words))

            # COCO format
            coco_refs[sample_id] = [str(ref) for ref in all_references[i]]

            coco_preds[sample_id] = [str(pred_sentence)]

            sample_id += 1

  # BLEU
  smoothie = SmoothingFunction().method4
  bleu1 = corpus_bleu(references,predictions,weights=(1,0,0,0),smoothing_function=smoothie)

  bleu2 = corpus_bleu(references,predictions,weights=(0.5,0.5,0,0),smoothing_function=smoothie)

  bleu3 = corpus_bleu(references,predictions,weights=(0.33,0.33,0.33,0),smoothing_function=smoothie)

  bleu4 = corpus_bleu(references,predictions,weights=(0.25,0.25,0.25,0.25),smoothing_function=smoothie)

  # CIDEr
  cider_scorer = Cider()

  cider_score, _ = cider_scorer.compute_score(coco_refs,coco_preds)

  # SPICE

  # Results

  results = pd.DataFrame({

      "Metric":[
          "BLEU-1",
          "BLEU-2",
          "BLEU-3",
          "BLEU-4",
          "ROUGE-L",
          "METEOR",
          "CIDEr",

      ],

      "Score":[
          bleu1,
          bleu2,
          bleu3,
          bleu4,
          sum(rouge_scores)/len(rouge_scores),
          sum(meteor_scores)/len(meteor_scores),
          cider_score,

      ]

  })
  print(coco_refs[0])
  print(coco_preds[0])
  display(results)

  return results

In [ ]:
for dataset_name, cfg in DATASETS.items():

    torch.cuda.reset_peak_memory_stats()

    print("\n************************")
    print(f"\nProcessing - {dataset_name}")
    print("\n************************\n")

    ROOT = cfg["ROOT"]
    IMAGE_DIR = cfg["IMAGE_DIR"]
    CAPTION_FILE = cfg["CAPTION_FILE"]

    with open(cfg["flickr_split"], "rb") as f:
        split = pickle.load(f)

    with open(cfg["vocab"], "rb") as f:
        vocab = pickle.load(f)


    #Build Model

    model = build_image_text_decoder(
        vocab,
        device
    )

    optimizer, scheduler = define_optimizer(model)

    # Dataset

    df = pd.read_csv(CAPTION_FILE)

    train_imgs = split["train"]
    val_imgs = split["val"]
    test_imgs = split["test"]

    print(
        f"Train: {len(train_imgs)} | "
        f"Val: {len(val_imgs)} | "
        f"Test: {len(test_imgs)}"
    )

    train_df = df[df["image"].isin(train_imgs)].reset_index(drop=True)
    val_df = df[df["image"].isin(val_imgs)].reset_index(drop=True)
    test_df = df[df["image"].isin(test_imgs)].reset_index(drop=True)

    train_df = train_df.dropna(subset=["caption"]).reset_index(drop=True)
    val_df = val_df.dropna(subset=["caption"]).reset_index(drop=True)
    test_df = test_df.dropna(subset=["caption"]).reset_index(drop=True)

    train_caption_map, val_caption_map, test_caption_map = image_caption_map(
        train_df,
        val_df,
        test_df
    )

    train_loader, val_loader, test_loader = prepare_caption_dataloaders(
        train_caption_map,
        val_caption_map,
        test_caption_map
    )
    criterion = nn.CrossEntropyLoss(ignore_index=vocab["<PAD>"],label_smoothing=0.1)

    #Train

    best_model, FINAL_MODEL_PATH = model_training(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        criterion,
        dataset_name
    )

    #Test

    model_testing(
        best_model,
        FINAL_MODEL_PATH,
        test_loader,
        vocab,
        device
    )

    # Cleanup

    del model
    del optimizer
    del scheduler

    del train_loader
    del val_loader
    del test_loader

    del train_df
    del val_df
    del test_df

    del train_caption_map
    del val_caption_map
    del test_caption_map

    del split
    del vocab
    del df

    reset_resources()

************************

Processing - flickr8k

************************

Train: 6068 | Val: 1011 | Test: 1012

================ Epoch 1/50 ================
Batch 001/32 | Loss: 7.9909 | Time: 0.74s
Batch 002/32 | Loss: 7.8180 | Time: 0.71s
Batch 003/32 | Loss: 7.6380 | Time: 0.71s
Batch 004/32 | Loss: 7.4562 | Time: 0.72s
Batch 005/32 | Loss: 7.2704 | Time: 0.71s
Batch 006/32 | Loss: 7.0728 | Time: 0.71s
Batch 007/32 | Loss: 6.8629 | Time: 0.71s
Batch 008/32 | Loss: 6.6541 | Time: 0.71s
Batch 009/32 | Loss: 6.4941 | Time: 0.72s
Batch 010/32 | Loss: 6.3140 | Time: 0.71s
Batch 011/32 | Loss: 6.0902 | Time: 0.71s
Batch 012/32 | Loss: 5.9091 | Time: 0.71s
Batch 013/32 | Loss: 5.9343 | Time: 0.71s
Batch 014/32 | Loss: 5.7025 | Time: 0.71s
Batch 015/32 | Loss: 5.6328 | Time: 0.71s
Batch 016/32 | Loss: 5.5884 | Time: 0.71s
Batch 017/32 | Loss: 5.5406 | Time: 0.71s
Batch 018/32 | Loss: 5.4091 | Time: 0.71s
Batch 019/32 | Loss: 5.3895 | Time: 0.71s
Batch 020/32 | Loss: 5.3943 | Time: 0.71s
Batch 021/32 | Loss: 5.2464 | Time: 0.71s
Batch 022/32 | Loss: 5.2300 | Time: 0.71s
Batch 023/32 | Loss: 5.2132 | Time: 0.71s
Batch 024/32 | Loss: 5.1476 | Time: 0.71s
Batch 025/32 | Loss: 5.1176 | Time: 0.71s
Batch 026/32 | Loss: 5.1511 | Time: 0.71s
Batch 027/32 | Loss: 5.1325 | Time: 0.71s
Batch 028/32 | Loss: 5.1373 | Time: 0.71s
Batch 029/32 | Loss: 5.0765 | Time: 0.71s
Batch 030/32 | Loss: 5.0375 | Time: 0.71s
Batch 031/32 | Loss: 5.0532 | Time: 0.71s
Batch 032/32 | Loss: 4.9417 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 5.9265
Validation Loss : 4.8729
Training Time   : 27.13s
Validation Time : 4.06s
GPU Memory Used : 2.47 GB
✓ Best model saved (Val Loss: 4.8729)

================ Epoch 2/50 ================
Batch 001/32 | Loss: 5.0047 | Time: 0.74s
Batch 002/32 | Loss: 4.9976 | Time: 0.71s
Batch 003/32 | Loss: 5.0029 | Time: 0.71s
Batch 004/32 | Loss: 4.9929 | Time: 0.71s
Batch 005/32 | Loss: 5.0038 | Time: 0.71s
Batch 006/32 | Loss: 4.9025 | Time: 0.71s
Batch 007/32 | Loss: 4.8984 | Time: 0.71s
Batch 008/32 | Loss: 4.8391 | Time: 0.71s
Batch 009/32 | Loss: 4.8407 | Time: 0.71s
Batch 010/32 | Loss: 4.7311 | Time: 0.71s
Batch 011/32 | Loss: 4.8282 | Time: 0.72s
Batch 012/32 | Loss: 4.8911 | Time: 0.71s
Batch 013/32 | Loss: 4.7609 | Time: 0.71s
Batch 014/32 | Loss: 4.7721 | Time: 0.71s
Batch 015/32 | Loss: 4.8603 | Time: 0.71s
Batch 016/32 | Loss: 4.8309 | Time: 0.71s
Batch 017/32 | Loss: 4.7380 | Time: 0.71s
Batch 018/32 | Loss: 4.6864 | Time: 0.71s
Batch 019/32 | Loss: 4.7590 | Time: 0.71s
Batch 020/32 | Loss: 4.7040 | Time: 0.71s
Batch 021/32 | Loss: 4.7249 | Time: 0.71s
Batch 022/32 | Loss: 4.6184 | Time: 0.71s
Batch 023/32 | Loss: 4.7278 | Time: 0.71s
Batch 024/32 | Loss: 4.5957 | Time: 0.71s
Batch 025/32 | Loss: 4.7008 | Time: 0.71s
Batch 026/32 | Loss: 4.5608 | Time: 0.71s
Batch 027/32 | Loss: 4.6359 | Time: 0.71s
Batch 028/32 | Loss: 4.6907 | Time: 0.71s
Batch 029/32 | Loss: 4.5868 | Time: 0.71s
Batch 030/32 | Loss: 4.5831 | Time: 0.71s
Batch 031/32 | Loss: 4.6287 | Time: 0.71s
Batch 032/32 | Loss: 4.6682 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 4.7740
Validation Loss : 4.4417
Training Time   : 27.14s
Validation Time : 4.07s
GPU Memory Used : 2.47 GB
✓ Best model saved (Val Loss: 4.4417)

================ Epoch 3/50 ================
Batch 001/32 | Loss: 4.5798 | Time: 0.75s
Batch 002/32 | Loss: 4.5591 | Time: 0.71s
Batch 003/32 | Loss: 4.5784 | Time: 0.71s
Batch 004/32 | Loss: 4.5348 | Time: 0.71s
Batch 005/32 | Loss: 4.5696 | Time: 0.71s
Batch 006/32 | Loss: 4.4971 | Time: 0.71s
Batch 007/32 | Loss: 4.5711 | Time: 0.71s
Batch 008/32 | Loss: 4.4758 | Time: 0.71s
Batch 009/32 | Loss: 4.5062 | Time: 0.71s
Batch 010/32 | Loss: 4.4184 | Time: 0.71s
Batch 011/32 | Loss: 4.4455 | Time: 0.71s
Batch 012/32 | Loss: 4.3316 | Time: 0.71s
Batch 013/32 | Loss: 4.5289 | Time: 0.71s
Batch 014/32 | Loss: 4.5173 | Time: 0.71s
Batch 015/32 | Loss: 4.4475 | Time: 0.71s
Batch 016/32 | Loss: 4.4701 | Time: 0.71s
Batch 017/32 | Loss: 4.3798 | Time: 0.71s
Batch 018/32 | Loss: 4.4319 | Time: 0.71s
Batch 019/32 | Loss: 4.4208 | Time: 0.71s
Batch 020/32 | Loss: 4.3621 | Time: 0.71s
Batch 021/32 | Loss: 4.3965 | Time: 0.71s
Batch 022/32 | Loss: 4.3995 | Time: 0.71s
Batch 023/32 | Loss: 4.3478 | Time: 0.71s
Batch 024/32 | Loss: 4.4702 | Time: 0.71s
Batch 025/32 | Loss: 4.3502 | Time: 0.71s
Batch 026/32 | Loss: 4.3776 | Time: 0.71s
Batch 027/32 | Loss: 4.2920 | Time: 0.71s
Batch 028/32 | Loss: 4.3073 | Time: 0.71s
Batch 029/32 | Loss: 4.2731 | Time: 0.71s
Batch 030/32 | Loss: 4.3221 | Time: 0.71s
Batch 031/32 | Loss: 4.3531 | Time: 0.71s
Batch 032/32 | Loss: 4.2707 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 4.4308
Validation Loss : 4.1862
Training Time   : 25.95s
Validation Time : 3.94s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 4.1862)

================ Epoch 4/50 ================
Batch 001/32 | Loss: 4.2364 | Time: 0.74s
Batch 002/32 | Loss: 4.2852 | Time: 0.71s
Batch 003/32 | Loss: 4.3246 | Time: 0.71s
Batch 004/32 | Loss: 4.3272 | Time: 0.71s
Batch 005/32 | Loss: 4.2934 | Time: 0.71s
Batch 006/32 | Loss: 4.2517 | Time: 0.71s
Batch 007/32 | Loss: 4.1861 | Time: 0.71s
Batch 008/32 | Loss: 4.2731 | Time: 0.71s
Batch 009/32 | Loss: 4.3735 | Time: 0.71s
Batch 010/32 | Loss: 4.2632 | Time: 0.71s
Batch 011/32 | Loss: 4.2666 | Time: 0.71s
Batch 012/32 | Loss: 4.2401 | Time: 0.71s
Batch 013/32 | Loss: 4.2427 | Time: 0.71s
Batch 014/32 | Loss: 4.2004 | Time: 0.71s
Batch 015/32 | Loss: 4.1939 | Time: 0.71s
Batch 016/32 | Loss: 4.2760 | Time: 0.71s
Batch 017/32 | Loss: 4.1353 | Time: 0.71s
Batch 018/32 | Loss: 4.2906 | Time: 0.71s
Batch 019/32 | Loss: 4.2553 | Time: 0.71s
Batch 020/32 | Loss: 4.1313 | Time: 0.71s
Batch 021/32 | Loss: 4.1495 | Time: 0.71s
Batch 022/32 | Loss: 4.1920 | Time: 0.71s
Batch 023/32 | Loss: 4.1429 | Time: 0.71s
Batch 024/32 | Loss: 4.1455 | Time: 0.71s
Batch 025/32 | Loss: 4.2401 | Time: 0.71s
Batch 026/32 | Loss: 4.2039 | Time: 0.71s
Batch 027/32 | Loss: 4.1681 | Time: 0.71s
Batch 028/32 | Loss: 4.2376 | Time: 0.71s
Batch 029/32 | Loss: 4.1288 | Time: 0.71s
Batch 030/32 | Loss: 4.0959 | Time: 0.71s
Batch 031/32 | Loss: 4.0559 | Time: 0.71s
Batch 032/32 | Loss: 4.2722 | Time: 0.43s

---------------- Summary ----------------
Train Loss      : 4.2212
Validation Loss : 4.0335
Training Time   : 27.12s
Validation Time : 4.12s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 4.0335)

================ Epoch 5/50 ================
Batch 001/32 | Loss: 4.1229 | Time: 0.75s
Batch 002/32 | Loss: 4.1322 | Time: 0.71s
Batch 003/32 | Loss: 4.0982 | Time: 0.71s
Batch 004/32 | Loss: 4.1023 | Time: 0.71s
Batch 005/32 | Loss: 4.1364 | Time: 0.71s
Batch 006/32 | Loss: 4.2010 | Time: 0.71s
Batch 007/32 | Loss: 4.0721 | Time: 0.71s
Batch 008/32 | Loss: 4.0997 | Time: 0.71s
Batch 009/32 | Loss: 4.2012 | Time: 0.71s
Batch 010/32 | Loss: 4.1497 | Time: 0.72s
Batch 011/32 | Loss: 4.2004 | Time: 0.71s
Batch 012/32 | Loss: 3.9960 | Time: 0.71s
Batch 013/32 | Loss: 4.0913 | Time: 0.71s
Batch 014/32 | Loss: 4.0904 | Time: 0.71s
Batch 015/32 | Loss: 4.1735 | Time: 0.71s
Batch 016/32 | Loss: 4.0588 | Time: 0.71s
Batch 017/32 | Loss: 4.0838 | Time: 0.71s
Batch 018/32 | Loss: 4.1067 | Time: 0.71s
Batch 019/32 | Loss: 4.0556 | Time: 0.71s
Batch 020/32 | Loss: 4.0122 | Time: 0.71s
Batch 021/32 | Loss: 4.0644 | Time: 0.71s
Batch 022/32 | Loss: 4.1569 | Time: 0.71s
Batch 023/32 | Loss: 4.0531 | Time: 0.71s
Batch 024/32 | Loss: 4.0491 | Time: 0.71s
Batch 025/32 | Loss: 4.0082 | Time: 0.71s
Batch 026/32 | Loss: 4.0414 | Time: 0.71s
Batch 027/32 | Loss: 4.0453 | Time: 0.71s
Batch 028/32 | Loss: 4.0756 | Time: 0.71s
Batch 029/32 | Loss: 4.0259 | Time: 0.71s
Batch 030/32 | Loss: 4.0204 | Time: 0.71s
Batch 031/32 | Loss: 4.0664 | Time: 0.71s
Batch 032/32 | Loss: 4.1181 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 4.0909
Validation Loss : 3.9397
Training Time   : 25.97s
Validation Time : 4.41s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 3.9397)

================ Epoch 6/50 ================
Batch 001/32 | Loss: 4.0099 | Time: 0.74s
Batch 002/32 | Loss: 4.0583 | Time: 0.71s
Batch 003/32 | Loss: 4.0433 | Time: 0.71s
Batch 004/32 | Loss: 3.9947 | Time: 0.71s
Batch 005/32 | Loss: 4.0254 | Time: 0.71s
Batch 006/32 | Loss: 3.9918 | Time: 0.71s
Batch 007/32 | Loss: 4.0746 | Time: 0.71s
Batch 008/32 | Loss: 3.9855 | Time: 0.71s
Batch 009/32 | Loss: 3.9826 | Time: 0.71s
Batch 010/32 | Loss: 4.0418 | Time: 0.72s
Batch 011/32 | Loss: 4.0940 | Time: 0.71s
Batch 012/32 | Loss: 3.9970 | Time: 0.71s
Batch 013/32 | Loss: 3.9407 | Time: 0.71s
Batch 014/32 | Loss: 4.0027 | Time: 0.71s
Batch 015/32 | Loss: 3.9854 | Time: 0.71s
Batch 016/32 | Loss: 4.0080 | Time: 0.71s
Batch 017/32 | Loss: 3.9857 | Time: 0.71s
Batch 018/32 | Loss: 3.9972 | Time: 0.71s
Batch 019/32 | Loss: 3.9409 | Time: 0.71s
Batch 020/32 | Loss: 4.0048 | Time: 0.71s
Batch 021/32 | Loss: 3.9217 | Time: 0.71s
Batch 022/32 | Loss: 4.0571 | Time: 0.71s
Batch 023/32 | Loss: 3.9057 | Time: 0.71s
Batch 024/32 | Loss: 3.9269 | Time: 0.71s
Batch 025/32 | Loss: 4.0378 | Time: 0.71s
Batch 026/32 | Loss: 3.9148 | Time: 0.71s
Batch 027/32 | Loss: 3.9381 | Time: 0.71s
Batch 028/32 | Loss: 3.9979 | Time: 0.71s
Batch 029/32 | Loss: 3.9364 | Time: 0.71s
Batch 030/32 | Loss: 3.9275 | Time: 0.71s
Batch 031/32 | Loss: 4.0021 | Time: 0.71s
Batch 032/32 | Loss: 4.0204 | Time: 0.43s

---------------- Summary ----------------
Train Loss      : 3.9922
Validation Loss : 3.8583
Training Time   : 26.45s
Validation Time : 4.00s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 3.8583)

================ Epoch 7/50 ================
Batch 001/32 | Loss: 3.9515 | Time: 0.73s
Batch 002/32 | Loss: 3.8900 | Time: 0.71s
Batch 003/32 | Loss: 3.9357 | Time: 0.71s
Batch 004/32 | Loss: 3.9856 | Time: 0.71s
Batch 005/32 | Loss: 3.9567 | Time: 0.72s
Batch 006/32 | Loss: 3.8850 | Time: 0.71s
Batch 007/32 | Loss: 3.8724 | Time: 0.71s
Batch 008/32 | Loss: 3.9930 | Time: 0.71s
Batch 009/32 | Loss: 3.9199 | Time: 0.71s
Batch 010/32 | Loss: 3.9660 | Time: 0.71s
Batch 011/32 | Loss: 3.8771 | Time: 0.71s
Batch 012/32 | Loss: 3.9347 | Time: 0.71s
Batch 013/32 | Loss: 3.9323 | Time: 0.71s
Batch 014/32 | Loss: 3.9509 | Time: 0.71s
Batch 015/32 | Loss: 3.8680 | Time: 0.71s
Batch 016/32 | Loss: 3.9277 | Time: 0.71s
Batch 017/32 | Loss: 3.9025 | Time: 0.71s
Batch 018/32 | Loss: 3.8870 | Time: 0.71s
Batch 019/32 | Loss: 3.9712 | Time: 0.71s
Batch 020/32 | Loss: 3.9521 | Time: 0.71s
Batch 021/32 | Loss: 3.9516 | Time: 0.71s
Batch 022/32 | Loss: 3.9167 | Time: 0.71s
Batch 023/32 | Loss: 3.8801 | Time: 0.71s
Batch 024/32 | Loss: 3.8613 | Time: 0.71s
Batch 025/32 | Loss: 3.9467 | Time: 0.71s
Batch 026/32 | Loss: 3.8720 | Time: 0.71s
Batch 027/32 | Loss: 3.8989 | Time: 0.71s
Batch 028/32 | Loss: 3.8842 | Time: 0.71s
Batch 029/32 | Loss: 3.9471 | Time: 0.71s
Batch 030/32 | Loss: 3.8995 | Time: 0.71s
Batch 031/32 | Loss: 3.8975 | Time: 0.71s
Batch 032/32 | Loss: 3.9252 | Time: 0.43s

---------------- Summary ----------------
Train Loss      : 3.9200
Validation Loss : 3.8056
Training Time   : 26.09s
Validation Time : 4.04s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 3.8056)

================ Epoch 8/50 ================
Batch 001/32 | Loss: 3.9306 | Time: 0.74s
Batch 002/32 | Loss: 3.9240 | Time: 0.71s
Batch 003/32 | Loss: 3.8345 | Time: 0.71s
Batch 004/32 | Loss: 3.8974 | Time: 0.71s
Batch 005/32 | Loss: 3.8695 | Time: 0.71s
Batch 006/32 | Loss: 3.8716 | Time: 0.71s
Batch 007/32 | Loss: 3.7914 | Time: 0.71s
Batch 008/32 | Loss: 3.9373 | Time: 0.71s
Batch 009/32 | Loss: 3.7814 | Time: 0.71s
Batch 010/32 | Loss: 3.8514 | Time: 0.71s
Batch 011/32 | Loss: 3.8000 | Time: 0.71s
Batch 012/32 | Loss: 3.8746 | Time: 0.71s
Batch 013/32 | Loss: 3.8627 | Time: 0.71s
Batch 014/32 | Loss: 3.8123 | Time: 0.71s
Batch 015/32 | Loss: 3.9434 | Time: 0.71s
Batch 016/32 | Loss: 3.8650 | Time: 0.71s
Batch 017/32 | Loss: 3.7970 | Time: 0.71s
Batch 018/32 | Loss: 3.8800 | Time: 0.71s
Batch 019/32 | Loss: 3.8664 | Time: 0.71s
Batch 020/32 | Loss: 3.7718 | Time: 0.71s
Batch 021/32 | Loss: 3.9167 | Time: 0.71s
Batch 022/32 | Loss: 3.8548 | Time: 0.71s
Batch 023/32 | Loss: 3.8160 | Time: 0.71s
Batch 024/32 | Loss: 3.8552 | Time: 0.71s
Batch 025/32 | Loss: 3.8338 | Time: 0.71s
Batch 026/32 | Loss: 3.8167 | Time: 0.71s
Batch 027/32 | Loss: 3.8257 | Time: 0.71s
Batch 028/32 | Loss: 3.8695 | Time: 0.71s
Batch 029/32 | Loss: 3.9678 | Time: 0.71s
Batch 030/32 | Loss: 3.9341 | Time: 0.71s
Batch 031/32 | Loss: 3.7999 | Time: 0.71s
Batch 032/32 | Loss: 3.8181 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 3.8585
Validation Loss : 3.7665
Training Time   : 26.31s
Validation Time : 3.97s
GPU Memory Used : 2.47 GB
✓ Best model saved (Val Loss: 3.7665)

================ Epoch 9/50 ================
Batch 001/32 | Loss: 3.8030 | Time: 0.73s
Batch 002/32 | Loss: 3.8462 | Time: 0.72s
Batch 003/32 | Loss: 3.8299 | Time: 0.71s
Batch 004/32 | Loss: 3.8566 | Time: 0.71s
Batch 005/32 | Loss: 3.7818 | Time: 0.71s
Batch 006/32 | Loss: 3.7311 | Time: 0.71s
Batch 007/32 | Loss: 3.7751 | Time: 0.71s
Batch 008/32 | Loss: 3.7508 | Time: 0.71s
Batch 009/32 | Loss: 3.8260 | Time: 0.71s
Batch 010/32 | Loss: 3.8057 | Time: 0.71s
Batch 011/32 | Loss: 3.8459 | Time: 0.71s
Batch 012/32 | Loss: 3.7638 | Time: 0.71s
Batch 013/32 | Loss: 3.9024 | Time: 0.71s
Batch 014/32 | Loss: 3.8117 | Time: 0.71s
Batch 015/32 | Loss: 3.8053 | Time: 0.71s
Batch 016/32 | Loss: 3.7656 | Time: 0.71s
Batch 017/32 | Loss: 3.8578 | Time: 0.71s
Batch 018/32 | Loss: 3.9054 | Time: 0.71s
Batch 019/32 | Loss: 3.8516 | Time: 0.71s
Batch 020/32 | Loss: 3.6794 | Time: 0.71s
Batch 021/32 | Loss: 3.8407 | Time: 0.71s
Batch 022/32 | Loss: 3.8603 | Time: 0.71s
Batch 023/32 | Loss: 3.8263 | Time: 0.71s
Batch 024/32 | Loss: 3.7925 | Time: 0.71s
Batch 025/32 | Loss: 3.7639 | Time: 0.71s
Batch 026/32 | Loss: 3.7917 | Time: 0.71s
Batch 027/32 | Loss: 3.8219 | Time: 0.71s
Batch 028/32 | Loss: 3.8118 | Time: 0.71s
Batch 029/32 | Loss: 3.7496 | Time: 0.71s
Batch 030/32 | Loss: 3.8647 | Time: 0.71s
Batch 031/32 | Loss: 3.8752 | Time: 0.71s
Batch 032/32 | Loss: 3.8325 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 3.8133
Validation Loss : 3.7211
Training Time   : 25.73s
Validation Time : 3.93s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 3.7211)

================ Epoch 10/50 ================
Batch 001/32 | Loss: 3.8142 | Time: 0.76s
Batch 002/32 | Loss: 3.8324 | Time: 0.71s
Batch 003/32 | Loss: 3.9025 | Time: 0.71s
Batch 004/32 | Loss: 3.7766 | Time: 0.71s
Batch 005/32 | Loss: 3.8139 | Time: 0.71s
Batch 006/32 | Loss: 3.7143 | Time: 0.71s
Batch 007/32 | Loss: 3.7457 | Time: 0.71s
Batch 008/32 | Loss: 3.8663 | Time: 0.72s
Batch 009/32 | Loss: 3.7526 | Time: 0.71s
Batch 010/32 | Loss: 3.7671 | Time: 0.71s
Batch 011/32 | Loss: 3.7841 | Time: 0.71s
Batch 012/32 | Loss: 3.8565 | Time: 0.72s
Batch 013/32 | Loss: 3.8194 | Time: 0.71s
Batch 014/32 | Loss: 3.7437 | Time: 0.71s
Batch 015/32 | Loss: 3.7169 | Time: 0.71s
Batch 016/32 | Loss: 3.8250 | Time: 0.71s
Batch 017/32 | Loss: 3.7924 | Time: 0.71s
Batch 018/32 | Loss: 3.8414 | Time: 0.71s
Batch 019/32 | Loss: 3.7850 | Time: 0.71s
Batch 020/32 | Loss: 3.7430 | Time: 0.71s
Batch 021/32 | Loss: 3.6983 | Time: 0.71s
Batch 022/32 | Loss: 3.8335 | Time: 0.71s
Batch 023/32 | Loss: 3.7572 | Time: 0.71s
Batch 024/32 | Loss: 3.7543 | Time: 0.71s
Batch 025/32 | Loss: 3.7737 | Time: 0.71s
Batch 026/32 | Loss: 3.8040 | Time: 0.71s
Batch 027/32 | Loss: 3.7211 | Time: 0.71s
Batch 028/32 | Loss: 3.6781 | Time: 0.71s
Batch 029/32 | Loss: 3.7417 | Time: 0.71s
Batch 030/32 | Loss: 3.7507 | Time: 0.71s
Batch 031/32 | Loss: 3.7824 | Time: 0.71s
Batch 032/32 | Loss: 3.7162 | Time: 0.43s

---------------- Summary ----------------
Train Loss      : 3.7783
Validation Loss : 3.6883
Training Time   : 27.22s
Validation Time : 3.95s
GPU Memory Used : 2.48 GB
✓ Best model saved (Val Loss: 3.6883)

================ Epoch 11/50 ================
Batch 001/32 | Loss: 3.7424 | Time: 0.73s
Batch 002/32 | Loss: 3.8176 | Time: 0.71s
Batch 003/32 | Loss: 3.7657 | Time: 0.71s
Batch 004/32 | Loss: 3.8119 | Time: 0.71s
Batch 005/32 | Loss: 3.6794 | Time: 0.71s
Batch 006/32 | Loss: 3.8670 | Time: 0.71s
Batch 007/32 | Loss: 3.6735 | Time: 0.71s
Batch 008/32 | Loss: 3.7788 | Time: 0.71s
Batch 009/32 | Loss: 3.7666 | Time: 0.71s
Batch 010/32 | Loss: 3.6921 | Time: 0.71s
Batch 011/32 | Loss: 3.6976 | Time: 0.71s
Batch 012/32 | Loss: 3.6787 | Time: 0.71s
Batch 013/32 | Loss: 3.8015 | Time: 0.71s
Batch 014/32 | Loss: 3.6372 | Time: 0.71s
Batch 015/32 | Loss: 3.7964 | Time: 0.71s
Batch 016/32 | Loss: 3.7327 | Time: 0.71s
Batch 017/32 | Loss: 3.7436 | Time: 0.71s
Batch 018/32 | Loss: 3.6805 | Time: 0.71s
Batch 019/32 | Loss: 3.7517 | Time: 0.71s
Batch 020/32 | Loss: 3.7244 | Time: 0.71s
Batch 021/32 | Loss: 3.8019 | Time: 0.71s
Batch 022/32 | Loss: 3.6823 | Time: 0.71s
Batch 023/32 | Loss: 3.6928 | Time: 0.71s
Batch 024/32 | Loss: 3.7422 | Time: 0.71s
Batch 025/32 | Loss: 3.7559 | Time: 0.71s
Batch 026/32 | Loss: 3.6951 | Time: 0.71s
Batch 027/32 | Loss: 3.7181 | Time: 0.71s
Batch 028/32 | Loss: 3.6521 | Time: 0.71s
Batch 029/32 | Loss: 3.7467 | Time: 0.71s
Batch 030/32 | Loss: 3.7518 | Time: 0.71s
Batch 031/32 | Loss: 3.7498 | Time: 0.71s
Batch 032/32 | Loss: 3.6816 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 3.7347
Validation Loss : 3.6521
Training Time   : 26.38s
Validation Time : 4.05s
GPU Memory Used : 2.47 GB
✓ Best model saved (Val Loss: 3.6521)

================ Epoch 12/50 ================
Batch 001/32 | Loss: 3.7571 | Time: 0.76s
Batch 002/32 | Loss: 3.6335 | Time: 0.71s
Batch 003/32 | Loss: 3.7200 | Time: 0.71s
Batch 004/32 | Loss: 3.7004 | Time: 0.71s
Batch 005/32 | Loss: 3.6620 | Time: 0.71s
Batch 006/32 | Loss: 3.7172 | Time: 0.71s
Batch 007/32 | Loss: 3.7323 | Time: 0.71s
Batch 008/32 | Loss: 3.7496 | Time: 0.71s
Batch 009/32 | Loss: 3.6485 | Time: 0.71s
Batch 010/32 | Loss: 3.6339 | Time: 0.71s
Batch 011/32 | Loss: 3.6648 | Time: 0.71s
Batch 012/32 | Loss: 3.6723 | Time: 0.71s
Batch 013/32 | Loss: 3.7601 | Time: 0.71s
Batch 014/32 | Loss: 3.8487 | Time: 0.71s
Batch 015/32 | Loss: 3.7431 | Time: 0.71s
Batch 016/32 | Loss: 3.6701 | Time: 0.71s
Batch 017/32 | Loss: 3.6377 | Time: 0.71s
Batch 018/32 | Loss: 3.7145 | Time: 0.71s
Batch 019/32 | Loss: 3.7358 | Time: 0.71s
Batch 020/32 | Loss: 3.6223 | Time: 0.71s
Batch 021/32 | Loss: 3.7697 | Time: 0.71s
Batch 022/32 | Loss: 3.7329 | Time: 0.71s
Batch 023/32 | Loss: 3.7205 | Time: 0.71s
Batch 024/32 | Loss: 3.7126 | Time: 0.71s
Batch 025/32 | Loss: 3.6701 | Time: 0.71s
Batch 026/32 | Loss: 3.7386 | Time: 0.71s
Batch 027/32 | Loss: 3.6869 | Time: 0.71s
Batch 028/32 | Loss: 3.6138 | Time: 0.71s
Batch 029/32 | Loss: 3.7216 | Time: 0.71s
Batch 030/32 | Loss: 3.6899 | Time: 0.71s
Batch 031/32 | Loss: 3.7355 | Time: 0.71s
Batch 032/32 | Loss: 3.6673 | Time: 0.42s

---------------- Summary ----------------
Train Loss      : 3.7026
Validation Loss : 3.6393
Training Time   : 27.19s
Validation Time : 4.08s
GPU Memory Used : 2.47 GB
✓ Best model saved (Val Loss: 3.6393)

================ Epoch 13/50 ================
Batch 001/32 | Loss: 3.6358 | Time: 0.75s
Batch 002/32 | Loss: 3.7232 | Time: 0.71s
Batch 003/32 | Loss: 3.6702 | Time: 0.71s
Batch 004/32 | Loss: 3.6755 | Time: 0.71s
Batch 005/32 | Loss: 3.6525 | Time: 0.71s
Batch 006/32 | Loss: 3.6729 | Time: 0.71s
Batch 007/32 | Loss: 3.7163 | Time: 0.71s
Batch 008/32 | Loss: 3.7011 | Time: 0.71s
Batch 009/32 | Loss: 3.5680 | Time: 0.71s
Batch 010/32 | Loss: 3.6649 | Time: 0.71s
Batch 011/32 | Loss: 3.6682 | Time: 0.71s
Batch 012/32 | Loss: 3.6582 | Time: 0.71s
Batch 013/32 | Loss: 3.6744 | Time: 0.71s
Batch 014/32 | Loss: 3.6855 | Time: 0.71s
Batch 015/32 | Loss: 3.6311 | Time: 0.71s
Batch 016/32 | Loss: 3.7466 | Time: 0.71s

    Metric     Score
0   BLEU-1  0.516005
1   BLEU-2  0.332974
2   BLEU-3  0.217237
3   BLEU-4  0.137155
4  ROUGE-L  0.429314
5   METEOR  0.374411
6    CIDEr  0.378846

Streaming output truncated to the last 5000 lines.
GPU Memory Used : 2.44 GB
✓ Best model saved (Val Loss: 3.9421)

================ Epoch 14/50 ================
Batch 001/125 | Loss: 3.7852 | Time: 0.74s
Batch 002/125 | Loss: 3.6958 | Time: 0.72s
Batch 003/125 | Loss: 3.8142 | Time: 0.72s
Batch 004/125 | Loss: 3.7024 | Time: 0.72s
Batch 005/125 | Loss: 3.7031 | Time: 0.72s
Batch 006/125 | Loss: 3.8177 | Time: 0.72s
Batch 007/125 | Loss: 3.7551 | Time: 0.72s
Batch 008/125 | Loss: 3.7157 | Time: 0.72s
Batch 009/125 | Loss: 3.8267 | Time: 0.72s
Batch 010/125 | Loss: 3.8585 | Time: 0.72s
Batch 011/125 | Loss: 3.8582 | Time: 0.72s
Batch 012/125 | Loss: 3.7588 | Time: 0.72s
Batch 013/125 | Loss: 3.7918 | Time: 0.72s
Batch 014/125 | Loss: 3.7407 | Time: 0.71s
Batch 015/125 | Loss: 3.8496 | Time: 0.72s
Batch 016/125 | Loss: 3.8357 | Time: 0.72s
Batch 017/125 | Loss: 3.7875 | Time: 0.72s
Batch 018/125 | Loss: 3.7651 | Time: 0.72s
Batch 019/125 | Loss: 3.7693 | Time: 0.72s
Batch 020/125 | Loss: 3.8251 | Time: 0.72s
Batch 021/125 | Loss: 3.8483 | Time: 0.72s
Batch 022/125 | Loss: 3.8256 | Time: 0.72s
Batch 023/125 | Loss: 3.7109 | Time: 0.72s
Batch 024/125 | Loss: 3.7888 | Time: 0.72s
Batch 025/125 | Loss: 3.8231 | Time: 0.72s
Batch 026/125 | Loss: 3.7974 | Time: 0.72s
Batch 027/125 | Loss: 3.7452 | Time: 0.72s
Batch 028/125 | Loss: 3.7417 | Time: 0.72s
Batch 029/125 | Loss: 3.8270 | Time: 0.72s
Batch 030/125 | Loss: 3.8200 | Time: 0.72s
Batch 031/125 | Loss: 3.8404 | Time: 0.73s
Batch 032/125 | Loss: 3.8385 | Time: 0.72s
Batch 033/125 | Loss: 3.7995 | Time: 0.72s
Batch 034/125 | Loss: 3.8187 | Time: 0.72s
Batch 035/125 | Loss: 3.7667 | Time: 0.72s
Batch 036/125 | Loss: 3.6822 | Time: 0.72s
Batch 037/125 | Loss: 3.7611 | Time: 0.72s
Batch 038/125 | Loss: 3.7411 | Time: 0.72s
Batch 039/125 | Loss: 3.6987 | Time: 0.72s
Batch 040/125 | Loss: 3.8716 | Time: 0.72s
Batch 041/125 | Loss: 3.6609 | Time: 0.71s
Batch 042/125 | Loss: 3.8024 | Time: 0.72s
Batch 043/125 | Loss: 3.6992 | Time: 0.71s
Batch 044/125 | Loss: 3.7480 | Time: 0.72s
Batch 045/125 | Loss: 3.7697 | Time: 0.72s
Batch 046/125 | Loss: 3.7650 | Time: 0.72s
Batch 047/125 | Loss: 3.7600 | Time: 0.72s
Batch 048/125 | Loss: 3.7868 | Time: 0.72s
Batch 049/125 | Loss: 3.8380 | Time: 0.71s
Batch 050/125 | Loss: 3.7582 | Time: 0.72s
Batch 051/125 | Loss: 3.7171 | Time: 0.72s
Batch 052/125 | Loss: 3.7268 | Time: 0.72s
Batch 053/125 | Loss: 3.8571 | Time: 0.72s
Batch 054/125 | Loss: 3.7309 | Time: 0.72s
Batch 055/125 | Loss: 3.7172 | Time: 0.72s
Batch 056/125 | Loss: 3.7982 | Time: 0.72s
Batch 057/125 | Loss: 3.8400 | Time: 0.72s
Batch 058/125 | Loss: 3.7830 | Time: 0.72s
Batch 059/125 | Loss: 3.7236 | Time: 0.72s
Batch 060/125 | Loss: 3.8462 | Time: 0.72s
Batch 061/125 | Loss: 3.7387 | Time: 0.72s
Batch 062/125 | Loss: 3.7991 | Time: 0.72s
Batch 063/125 | Loss: 3.7382 | Time: 0.71s
Batch 064/125 | Loss: 3.7569 | Time: 0.71s
Batch 065/125 | Loss: 3.7597 | Time: 0.71s
Batch 066/125 | Loss: 3.8110 | Time: 0.72s
Batch 067/125 | Loss: 3.7871 | Time: 0.72s
Batch 068/125 | Loss: 3.9134 | Time: 0.71s
Batch 069/125 | Loss: 3.7815 | Time: 0.72s
Batch 070/125 | Loss: 3.7876 | Time: 0.72s
Batch 071/125 | Loss: 3.7793 | Time: 0.71s
Batch 072/125 | Loss: 3.7589 | Time: 0.72s
Batch 073/125 | Loss: 3.8964 | Time: 0.72s
Batch 074/125 | Loss: 3.7762 | Time: 0.72s
Batch 075/125 | Loss: 3.7743 | Time: 0.72s
Batch 076/125 | Loss: 3.8299 | Time: 0.72s
Batch 077/125 | Loss: 3.8243 | Time: 0.72s
Batch 078/125 | Loss: 3.7226 | Time: 0.72s
Batch 079/125 | Loss: 3.8288 | Time: 0.72s
Batch 080/125 | Loss: 3.8433 | Time: 0.72s
Batch 081/125 | Loss: 3.8096 | Time: 0.72s
Batch 082/125 | Loss: 3.8179 | Time: 0.72s
Batch 083/125 | Loss: 3.7486 | Time: 0.72s
Batch 084/125 | Loss: 3.8273 | Time: 0.72s
Batch 085/125 | Loss: 3.7739 | Time: 0.71s
Batch 086/125 | Loss: 3.8047 | Time: 0.72s
Batch 087/125 | Loss: 3.7921 | Time: 0.72s
Batch 088/125 | Loss: 3.6749 | Time: 0.72s
Batch 089/125 | Loss: 3.7980 | Time: 0.72s
Batch 090/125 | Loss: 3.8385 | Time: 0.72s
Batch 091/125 | Loss: 3.8498 | Time: 0.72s
Batch 092/125 | Loss: 3.6736 | Time: 0.72s
Batch 093/125 | Loss: 3.7520 | Time: 0.72s
Batch 094/125 | Loss: 3.7503 | Time: 0.71s
Batch 095/125 | Loss: 3.8738 | Time: 0.72s
Batch 096/125 | Loss: 3.7434 | Time: 0.72s
Batch 097/125 | Loss: 3.7927 | Time: 0.72s
Batch 098/125 | Loss: 3.7306 | Time: 0.72s
Batch 099/125 | Loss: 3.7106 | Time: 0.72s
Batch 100/125 | Loss: 3.8117 | Time: 0.72s
Batch 101/125 | Loss: 3.8692 | Time: 0.72s
Batch 102/125 | Loss: 3.7316 | Time: 0.71s
Batch 103/125 | Loss: 3.8192 | Time: 0.72s
Batch 104/125 | Loss: 3.6662 | Time: 0.71s
Batch 105/125 | Loss: 3.7403 | Time: 0.72s
Batch 106/125 | Loss: 3.7906 | Time: 0.72s
Batch 107/125 | Loss: 3.7859 | Time: 0.72s
Batch 108/125 | Loss: 3.7810 | Time: 0.72s
Batch 109/125 | Loss: 3.8096 | Time: 0.72s
Batch 110/125 | Loss: 3.7711 | Time: 0.72s
Batch 111/125 | Loss: 3.7599 | Time: 0.72s
Batch 112/125 | Loss: 3.8027 | Time: 0.72s
Batch 113/125 | Loss: 3.7582 | Time: 0.72s
Batch 114/125 | Loss: 3.7377 | Time: 0.72s
Batch 115/125 | Loss: 3.7890 | Time: 0.72s
Batch 116/125 | Loss: 3.8097 | Time: 0.72s
Batch 117/125 | Loss: 3.7500 | Time: 0.72s
Batch 118/125 | Loss: 3.8178 | Time: 0.73s
Batch 119/125 | Loss: 3.8198 | Time: 0.72s
Batch 120/125 | Loss: 3.7844 | Time: 0.72s
Batch 121/125 | Loss: 3.7456 | Time: 0.72s
Batch 122/125 | Loss: 3.7566 | Time: 0.72s
Batch 123/125 | Loss: 3.7988 | Time: 0.72s
Batch 124/125 | Loss: 3.7461 | Time: 0.72s
Batch 125/125 | Loss: 3.7402 | Time: 0.14s

---------------- Summary ----------------
Train Loss      : 3.7808
Validation Loss : 3.9272
Training Time   : 93.27s
Validation Time : 10.70s
GPU Memory Used : 2.43 GB
✓ Best model saved (Val Loss: 3.9272)

================ Epoch 15/50 ================
Batch 001/125 | Loss: 3.8304 | Time: 0.74s
Batch 002/125 | Loss: 3.7194 | Time: 0.72s
Batch 003/125 | Loss: 3.7547 | Time: 0.72s
Batch 004/125 | Loss: 3.7573 | Time: 0.72s
Batch 005/125 | Loss: 3.7318 | Time: 0.72s
Batch 006/125 | Loss: 3.7870 | Time: 0.72s
Batch 007/125 | Loss: 3.8099 | Time: 0.71s
Batch 008/125 | Loss: 3.8017 | Time: 0.72s
Batch 009/125 | Loss: 3.7485 | Time: 0.72s
Batch 010/125 | Loss: 3.7542 | Time: 0.72s
Batch 011/125 | Loss: 3.7337 | Time: 0.72s
Batch 012/125 | Loss: 3.8179 | Time: 0.72s
Batch 013/125 | Loss: 3.7057 | Time: 0.72s
Batch 014/125 | Loss: 3.7356 | Time: 0.72s
Batch 015/125 | Loss: 3.7057 | Time: 0.72s
Batch 016/125 | Loss: 3.7645 | Time: 0.72s
Batch 017/125 | Loss: 3.8324 | Time: 0.72s
Batch 018/125 | Loss: 3.7897 | Time: 0.72s
Batch 019/125 | Loss: 3.7683 | Time: 0.71s
Batch 020/125 | Loss: 3.8271 | Time: 0.72s
Batch 021/125 | Loss: 3.8356 | Time: 0.72s
Batch 022/125 | Loss: 3.7540 | Time: 0.72s
Batch 023/125 | Loss: 3.7682 | Time: 0.72s
Batch 024/125 | Loss: 3.7570 | Time: 0.72s
Batch 025/125 | Loss: 3.7255 | Time: 0.72s
Batch 026/125 | Loss: 3.8213 | Time: 0.72s
Batch 027/125 | Loss: 3.7654 | Time: 0.72s
Batch 028/125 | Loss: 3.8011 | Time: 0.72s
Batch 029/125 | Loss: 3.7073 | Time: 0.72s
Batch 030/125 | Loss: 3.6280 | Time: 0.72s
Batch 031/125 | Loss: 3.7020 | Time: 0.72s
Batch 032/125 | Loss: 3.7673 | Time: 0.72s
Batch 033/125 | Loss: 3.7312 | Time: 0.72s
Batch 034/125 | Loss: 3.8121 | Time: 0.72s
Batch 035/125 | Loss: 3.7596 | Time: 0.72s
Batch 036/125 | Loss: 3.7590 | Time: 0.72s
Batch 037/125 | Loss: 3.7275 | Time: 0.72s
Batch 038/125 | Loss: 3.7275 | Time: 0.72s
Batch 039/125 | Loss: 3.6871 | Time: 0.72s
Batch 040/125 | Loss: 3.6764 | Time: 0.72s
Batch 041/125 | Loss: 3.6824 | Time: 0.71s
Batch 042/125 | Loss: 3.7301 | Time: 0.72s
Batch 043/125 | Loss: 3.7839 | Time: 0.72s
Batch 044/125 | Loss: 3.7921 | Time: 0.71s
Batch 045/125 | Loss: 3.8010 | Time: 0.72s
Batch 046/125 | Loss: 3.8468 | Time: 0.72s
Batch 047/125 | Loss: 3.7600 | Time: 0.72s
Batch 048/125 | Loss: 3.7183 | Time: 0.72s
Batch 049/125 | Loss: 3.7464 | Time: 0.72s
Batch 050/125 | Loss: 3.7859 | Time: 0.72s
Batch 051/125 | Loss: 3.8607 | Time: 0.72s
Batch 052/125 | Loss: 3.7979 | Time: 0.72s
Batch 053/125 | Loss: 3.7931 | Time: 0.72s
Batch 054/125 | Loss: 3.6790 | Time: 0.71s
Batch 055/125 | Loss: 3.6444 | Time: 0.72s
Batch 056/125 | Loss: 3.7499 | Time: 0.72s
Batch 057/125 | Loss: 3.7178 | Time: 0.72s
Batch 058/125 | Loss: 3.7561 | Time: 0.72s
Batch 059/125 | Loss: 3.7501 | Time: 0.72s
Batch 060/125 | Loss: 3.8319 | Time: 0.72s
Batch 061/125 | Loss: 3.8000 | Time: 0.72s
Batch 062/125 | Loss: 3.7611 | Time: 0.72s
Batch 063/125 | Loss: 3.7871 | Time: 0.72s
Batch 064/125 | Loss: 3.7835 | Time: 0.72s
Batch 065/125 | Loss: 3.7878 | Time: 0.72s
Batch 066/125 | Loss: 3.7441 | Time: 0.72s
Batch 067/125 | Loss: 3.8187 | Time: 0.72s
Batch 068/125 | Loss: 3.7476 | Time: 0.72s
Batch 069/125 | Loss: 3.6724 | Time: 0.72s
Batch 070/125 | Loss: 3.7418 | Time: 0.72s
Batch 071/125 | Loss: 3.7895 | Time: 0.72s
Batch 072/125 | Loss: 3.7498 | Time: 0.72s
Batch 073/125 | Loss: 3.7816 | Time: 0.73s
Batch 074/125 | Loss: 3.8427 | Time: 0.72s
Batch 075/125 | Loss: 3.8004 | Time: 0.72s
Batch 076/125 | Loss: 3.7739 | Time: 0.72s
Batch 077/125 | Loss: 3.7646 | Time: 0.71s
Batch 078/125 | Loss: 3.7824 | Time: 0.72s
Batch 079/125 | Loss: 3.7083 | Time: 0.72s
Batch 080/125 | Loss: 3.7506 | Time: 0.73s
Batch 081/125 | Loss: 3.8286 | Time: 0.72s
Batch 082/125 | Loss: 3.6601 | Time: 0.72s
Batch 083/125 | Loss: 3.8003 | Time: 0.72s
Batch 084/125 | Loss: 3.7586 | Time: 0.72s
Batch 085/125 | Loss: 3.7379 | Time: 0.72s
Batch 086/125 | Loss: 3.7356 | Time: 0.72s
Batch 087/125 | Loss: 3.7287 | Time: 0.72s
Batch 088/125 | Loss: 3.7993 | Time: 0.72s
Batch 089/125 | Loss: 3.7725 | Time: 0.72s
Batch 090/125 | Loss: 3.7478 | Time: 0.72s
Batch 091/125 | Loss: 3.8149 | Time: 0.72s
Batch 092/125 | Loss: 3.7145 | Time: 0.72s
Batch 093/125 | Loss: 3.7328 | Time: 0.72s
Batch 094/125 | Loss: 3.7145 | Time: 0.72s
Batch 095/125 | Loss: 3.7978 | Time: 0.72s
Batch 096/125 | Loss: 3.8269 | Time: 0.72s
Batch 097/125 | Loss: 3.7564 | Time: 0.72s
Batch 098/125 | Loss: 3.7575 | Time: 0.72s
Batch 099/125 | Loss: 3.7919 | Time: 0.72s
Batch 100/125 | Loss: 3.8221 | Time: 0.72s
Batch 101/125 | Loss: 3.7936 | Time: 0.72s
Batch 102/125 | Loss: 3.7363 | Time: 0.71s
Batch 103/125 | Loss: 3.7705 | Time: 0.71s
Batch 104/125 | Loss: 3.7216 | Time: 0.72s
Batch 105/125 | Loss: 3.7259 | Time: 0.72s
Batch 106/125 | Loss: 3.7042 | Time: 0.72s
Batch 107/125 | Loss: 3.8952 | Time: 0.72s
Batch 108/125 | Loss: 3.7074 | Time: 0.72s
Batch 109/125 | Loss: 3.7356 | Time: 0.72s
Batch 110/125 | Loss: 3.7910 | Time: 0.72s
Batch 111/125 | Loss: 3.7601 | Time: 0.72s
Batch 112/125 | Loss: 3.6846 | Time: 0.72s
Batch 113/125 | Loss: 3.7595 | Time: 0.73s
Batch 114/125 | Loss: 3.6936 | Time: 0.72s
Batch 115/125 | Loss: 3.7752 | Time: 0.72s
Batch 116/125 | Loss: 3.7705 | Time: 0.72s
Batch 117/125 | Loss: 3.7474 | Time: 0.71s
Batch 118/125 | Loss: 3.8199 | Time: 0.71s
Batch 119/125 | Loss: 3.6976 | Time: 0.72s
Batch 120/125 | Loss: 3.7308 | Time: 0.71s
Batch 121/125 | Loss: 3.6486 | Time: 0.72s
Batch 122/125 | Loss: 3.7212 | Time: 0.72s
Batch 123/125 | Loss: 3.7835 | Time: 0.72s
Batch 124/125 | Loss: 3.7676 | Time: 0.73s
Batch 125/125 | Loss: 3.7285 | Time: 0.14s

---------------- Summary ----------------
Train Loss      : 3.7590
Validation Loss : 3.9175
Training Time   : 94.00s
Validation Time : 10.36s
GPU Memory Used : 2.43 GB
✓ Best model saved (Val Loss: 3.9175)

================ Epoch 16/50 ================
Batch 001/125 | Loss: 3.6679 | Time: 0.77s
Batch 002/125 | Loss: 3.7549 | Time: 0.71s
Batch 003/125 | Loss: 3.7200 | Time: 0.72s
Batch 004/125 | Loss: 3.7551 | Time: 0.72s
Batch 005/125 | Loss: 3.8374 | Time: 0.72s
Batch 006/125 | Loss: 3.6467 | Time: 0.71s
Batch 007/125 | Loss: 3.7047 | Time: 0.72s
Batch 008/125 | Loss: 3.7614 | Time: 0.73s
Batch 009/125 | Loss: 3.7969 | Time: 0.72s
Batch 010/125 | Loss: 3.7116 | Time: 0.72s
Batch 011/125 | Loss: 3.7508 | Time: 0.72s
Batch 012/125 | Loss: 3.8285 | Time: 0.73s
Batch 013/125 | Loss: 3.7382 | Time: 0.72s
Batch 014/125 | Loss: 3.7951 | Time: 0.72s
Batch 015/125 | Loss: 3.7607 | Time: 0.71s
Batch 016/125 | Loss: 3.8021 | Time: 0.72s
Batch 017/125 | Loss: 3.6752 | Time: 0.72s
Batch 018/125 | Loss: 3.7227 | Time: 0.72s
Batch 019/125 | Loss: 3.6751 | Time: 0.72s
Batch 020/125 | Loss: 3.7149 | Time: 0.73s
Batch 021/125 | Loss: 3.7681 | Time: 0.72s
Batch 022/125 | Loss: 3.8286 | Time: 0.72s
Batch 023/125 | Loss: 3.6569 | Time: 0.71s
Batch 024/125 | Loss: 3.7301 | Time: 0.72s
Batch 025/125 | Loss: 3.6998 | Time: 0.72s
Batch 026/125 | Loss: 3.7917 | Time: 0.72s
Batch 027/125 | Loss: 3.7391 | Time: 0.72s
Batch 028/125 | Loss: 3.6688 | Time: 0.72s
Batch 029/125 | Loss: 3.7101 | Time: 0.72s
Batch 030/125 | Loss: 3.7056 | Time: 0.71s
Batch 031/125 | Loss: 3.7235 | Time: 0.72s
Batch 032/125 | Loss: 3.7510 | Time: 0.72s
Batch 033/125 | Loss: 3.7107 | Time: 0.72s
Batch 034/125 | Loss: 3.7188 | Time: 0.72s
Batch 035/125 | Loss: 3.7492 | Time: 0.72s
Batch 036/125 | Loss: 3.7435 | Time: 0.72s
Batch 037/125 | Loss: 3.8058 | Time: 0.72s
Batch 038/125 | Loss: 3.7523 | Time: 0.72s
Batch 039/125 | Loss: 3.7309 | Time: 0.72s
Batch 040/125 | Loss: 3.7010 | Time: 0.71s
Batch 041/125 | Loss: 3.6488 | Time: 0.72s
Batch 042/125 | Loss: 3.7898 | Time: 0.72s
Batch 043/125 | Loss: 3.7477 | Time: 0.72s
Batch 044/125 | Loss: 3.6821 | Time: 0.72s
Batch 045/125 | Loss: 3.7897 | Time: 0.72s
Batch 046/125 | Loss: 3.7569 | Time: 0.72s
Batch 047/125 | Loss: 3.7191 | Time: 0.71s
Batch 048/125 | Loss: 3.6981 | Time: 0.72s
Batch 049/125 | Loss: 3.7494 | Time: 0.72s
Batch 050/125 | Loss: 3.7337 | Time: 0.72s
Batch 051/125 | Loss: 3.6039 | Time: 0.72s
Batch 052/125 | Loss: 3.6851 | Time: 0.72s
Batch 053/125 | Loss: 3.7262 | Time: 0.72s
Batch 054/125 | Loss: 3.7388 | Time: 0.72s
Batch 055/125 | Loss: 3.7495 | Time: 0.72s
Batch 056/125 | Loss: 3.8103 | Time: 0.72s
Batch 057/125 | Loss: 3.7431 | Time: 0.72s
Batch 058/125 | Loss: 3.7676 | Time: 0.72s
Batch 059/125 | Loss: 3.7268 | Time: 0.72s
Batch 060/125 | Loss: 3.6708 | Time: 0.72s
Batch 061/125 | Loss: 3.7272 | Time: 0.72s
Batch 062/125 | Loss: 3.7990 | Time: 0.72s
Batch 063/125 | Loss: 3.7677 | Time: 0.72s
Batch 064/125 | Loss: 3.8109 | Time: 0.72s
Batch 065/125 | Loss: 3.7113 | Time: 0.72s
Batch 066/125 | Loss: 3.6678 | Time: 0.72s
Batch 067/125 | Loss: 3.7073 | Time: 0.72s
Batch 068/125 | Loss: 3.8256 | Time: 0.72s
Batch 069/125 | Loss: 3.7358 | Time: 0.71s
Batch 070/125 | Loss: 3.7448 | Time: 0.72s
Batch 071/125 | Loss: 3.7738 | Time: 0.72s
Batch 072/125 | Loss: 3.8554 | Time: 0.72s
Batch 073/125 | Loss: 3.7556 | Time: 0.71s
Batch 074/125 | Loss: 3.7744 | Time: 0.72s
Batch 075/125 | Loss: 3.7170 | Time: 0.72s
Batch 076/125 | Loss: 3.7009 | Time: 0.72s
Batch 077/125 | Loss: 3.7353 | Time: 0.72s
Batch 078/125 | Loss: 3.7387 | Time: 0.72s
Batch 079/125 | Loss: 3.7190 | Time: 0.72s
Batch 080/125 | Loss: 3.7885 | Time: 0.72s
Batch 081/125 | Loss: 3.7259 | Time: 0.71s
Batch 082/125 | Loss: 3.7238 | Time: 0.72s
Batch 083/125 | Loss: 3.7617 | Time: 0.72s
Batch 084/125 | Loss: 3.7531 | Time: 0.72s
Batch 085/125 | Loss: 3.7597 | Time: 0.72s
Batch 086/125 | Loss: 3.6327 | Time: 0.72s
Batch 087/125 | Loss: 3.7259 | Time: 0.72s
Batch 088/125 | Loss: 3.7226 | Time: 0.72s
Batch 089/125 | Loss: 3.7759 | Time: 0.72s
Batch 090/125 | Loss: 3.7816 | Time: 0.73s
Batch 091/125 | Loss: 3.7146 | Time: 0.72s
Batch 092/125 | Loss: 3.7137 | Time: 0.72s
Batch 093/125 | Loss: 3.8008 | Time: 0.72s
Batch 094/125 | Loss: 3.7291 | Time: 0.72s
Batch 095/125 | Loss: 3.6698 | Time: 0.72s
Batch 096/125 | Loss: 3.7905 | Time: 0.71s
Batch 097/125 | Loss: 3.8138 | Time: 0.71s
Batch 098/125 | Loss: 3.7558 | Time: 0.71s
Batch 099/125 | Loss: 3.7829 | Time: 0.72s
Batch 100/125 | Loss: 3.6485 | Time: 0.72s
Batch 101/125 | Loss: 3.6972 | Time: 0.72s
Batch 102/125 | Loss: 3.8110 | Time: 0.72s
Batch 103/125 | Loss: 3.7827 | Time: 0.72s
Batch 104/125 | Loss: 3.7699 | Time: 0.72s
Batch 105/125 | Loss: 3.6921 | Time: 0.72s
Batch 106/125 | Loss: 3.7320 | Time: 0.72s
Batch 107/125 | Loss: 3.7463 | Time: 0.72s
Batch 108/125 | Loss: 3.7607 | Time: 0.73s
Batch 109/125 | Loss: 3.7184 | Time: 0.72s
Batch 110/125 | Loss: 3.7987 | Time: 0.72s
Batch 111/125 | Loss: 3.7596 | Time: 0.72s
Batch 112/125 | Loss: 3.7878 | Time: 0.72s
Batch 113/125 | Loss: 3.7942 | Time: 0.72s
Batch 114/125 | Loss: 3.7782 | Time: 0.71s
Batch 115/125 | Loss: 3.7246 | Time: 0.72s
Batch 116/125 | Loss: 3.7670 | Time: 0.72s
Batch 117/125 | Loss: 3.8143 | Time: 0.72s
Batch 118/125 | Loss: 3.7221 | Time: 0.72s
Batch 119/125 | Loss: 3.8265 | Time: 0.72s
Batch 120/125 | Loss: 3.7257 | Time: 0.72s
Batch 121/125 | Loss: 3.7900 | Time: 0.71s
Batch 122/125 | Loss: 3.7655 | Time: 0.72s
Batch 123/125 | Loss: 3.9011 | Time: 0.71s
Batch 124/125 | Loss: 3.6595 | Time: 0.72s
Batch 125/125 | Loss: 3.7218 | Time: 0.14s

---------------- Summary ----------------
Train Loss      : 3.7434
Validation Loss : 3.9105
Training Time   : 93.29s
Validation Time : 10.81s
GPU Memory Used : 2.44 GB
✓ Best model saved (Val Loss: 3.9105)

================ Epoch 17/50 ================
Batch 001/125 | Loss: 3.7617 | Time: 0.76s
Batch 002/125 | Loss: 3.7978 | Time: 0.72s
Batch 003/125 | Loss: 3.7559 | Time: 0.72s
Batch 004/125 | Loss: 3.6968 | Time: 0.72s
Batch 005/125 | Loss: 3.6753 | Time: 0.72s
Batch 006/125 | Loss: 3.8344 | Time: 0.72s
Batch 007/125 | Loss: 3.8017 | Time: 0.72s
Batch 008/125 | Loss: 3.8200 | Time: 0.72s
Batch 009/125 | Loss: 3.7909 | Time: 0.72s
Batch 010/125 | Loss: 3.7379 | Time: 0.72s
Batch 011/125 | Loss: 3.6649 | Time: 0.71s
Batch 012/125 | Loss: 3.7608 | Time: 0.72s
Batch 013/125 | Loss: 3.7470 | Time: 0.72s
Batch 014/125 | Loss: 3.7682 | Time: 0.73s
Batch 015/125 | Loss: 3.6870 | Time: 0.72s
Batch 016/125 | Loss: 3.7855 | Time: 0.73s
Batch 017/125 | Loss: 3.7701 | Time: 0.72s
Batch 018/125 | Loss: 3.6684 | Time: 0.72s
Batch 019/125 | Loss: 3.7656 | Time: 0.72s
Batch 020/125 | Loss: 3.7345 | Time: 0.72s
Batch 021/125 | Loss: 3.6871 | Time: 0.72s
Batch 022/125 | Loss: 3.7277 | Time: 0.72s
Batch 023/125 | Loss: 3.7208 | Time: 0.72s
Batch 024/125 | Loss: 3.6016 | Time: 0.72s
Batch 025/125 | Loss: 3.7470 | Time: 0.72s
Batch 026/125 | Loss: 3.6552 | Time: 0.72s
Batch 027/125 | Loss: 3.7957 | Time: 0.72s
Batch 028/125 | Loss: 3.7109 | Time: 0.72s
Batch 029/125 | Loss: 3.7618 | Time: 0.72s
Batch 030/125 | Loss: 3.6693 | Time: 0.71s
Batch 031/125 | Loss: 3.7161 | Time: 0.72s
Batch 032/125 | Loss: 3.7026 | Time: 0.72s
Batch 033/125 | Loss: 3.7680 | Time: 0.72s
Batch 034/125 | Loss: 3.8059 | Time: 0.72s
Batch 035/125 | Loss: 3.7495 | Time: 0.72s
Batch 036/125 | Loss: 3.6954 | Time: 0.72s
Batch 037/125 | Loss: 3.7575 | Time: 0.71s
Batch 038/125 | Loss: 3.7296 | Time: 0.72s
Batch 039/125 | Loss: 3.6523 | Time: 0.72s
Batch 040/125 | Loss: 3.6661 | Time: 0.72s
Batch 041/125 | Loss: 3.8175 | Time: 0.72s
Batch 042/125 | Loss: 3.7389 | Time: 0.72s
Batch 043/125 | Loss: 3.6942 | Time: 0.72s
Batch 044/125 | Loss: 3.7759 | Time: 0.72s
Batch 045/125 | Loss: 3.7099 | Time: 0.71s
Batch 046/125 | Loss: 3.6906 | Time: 0.72s
Batch 047/125 | Loss: 3.6700 | Time: 0.72s
Batch 048/125 | Loss: 3.8107 | Time: 0.72s
Batch 049/125 | Loss: 3.7594 | Time: 0.72s
Batch 050/125 | Loss: 3.8100 | Time: 0.72s
Batch 051/125 | Loss: 3.7289 | Time: 0.72s
Batch 052/125 | Loss: 3.7356 | Time: 0.71s
Batch 053/125 | Loss: 3.6564 | Time: 0.72s
Batch 054/125 | Loss: 3.7771 | Time: 0.72s
Batch 055/125 | Loss: 3.6886 | Time: 0.72s
Batch 056/125 | Loss: 3.7513 | Time: 0.72s
Batch 057/125 | Loss: 3.8408 | Time: 0.72s
Batch 058/125 | Loss: 3.7487 | Time: 0.71s
Batch 059/125 | Loss: 3.7468 | Time: 0.72s
Batch 060/125 | Loss: 3.7186 | Time: 0.72s
Batch 061/125 | Loss: 3.7107 | Time: 0.72s
Batch 062/125 | Loss: 3.7551 | Time: 0.72s
Batch 063/125 | Loss: 3.7189 | Time: 0.72s
Batch 064/125 | Loss: 3.7476 | Time: 0.72s
Batch 065/125 | Loss: 3.7563 | Time: 0.72s
Batch 066/125 | Loss: 3.7359 | Time: 0.72s
Batch 067/125 | Loss: 3.8520 | Time: 0.72s
Batch 068/125 | Loss: 3.7310 | Time: 0.72s

    Metric     Score
0   BLEU-1  0.487510
1   BLEU-2  0.307515
2   BLEU-3  0.194641
3   BLEU-4  0.118764
4  ROUGE-L  0.389961
5   METEOR  0.354118
6    CIDEr  0.276262

Memory after cleanup
Allocated: 1.6676154136657715
Reserved: 4.154296875