In [ ]:
from google.colab import drive
import pickle
import pandas as pd
from collections import defaultdict
import random
from torchvision import transforms
import torchvision.models as models
from torch.utils.data import Dataset
from PIL import Image
import os
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda

In [ ]:
# Copying 8k to Colabs local SSD
if not os.path.exists("/content/flickr8k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr8k.zip" /content/

In [ ]:
!unzip "/content/flickr8k.zip" -d "/content/flickr8k"

Streaming output truncated to the last 5000 lines.
  inflating: /content/flickr8k/Images/3138399980_d6ab8b2272.jpg
  inflating: /content/flickr8k/Images/3138433655_ea1d59e5b7.jpg
  inflating: /content/flickr8k/Images/3138504165_c7ae396294.jpg
  inflating: /content/flickr8k/Images/3138562460_44227a35cf.jpg
  inflating: /content/flickr8k/Images/3138746531_f6b816c126.jpg
  inflating: /content/flickr8k/Images/3139118874_599b30b116.jpg
  inflating: /content/flickr8k/Images/3139160252_75109e9e05.jpg
  inflating: /content/flickr8k/Images/3139238055_2817a0c7d8.jpg
  inflating: /content/flickr8k/Images/3139389284_f01bd4c236.jpg
  inflating: /content/flickr8k/Images/3139393607_f0a54ca46d.jpg
  inflating: /content/flickr8k/Images/3139837262_fe5ee7ccd9.jpg
  inflating: /content/flickr8k/Images/3139876823_859c7d7c23.jpg
  inflating: /content/flickr8k/Images/3139895886_5a6d495b13.jpg
  inflating: /content/flickr8k/Images/3141293960_74459f0a24.jpg
  inflating: /content/flickr8k/Images/3141440149_00becbbb93.jpg
  inflating: /content/flickr8k/Images/3141613533_595723208d.jpg
  inflating: /content/flickr8k/Images/3142055158_01b9e4caa4.jpg
  inflating: /content/flickr8k/Images/3143155555_32b6d24f34.jpg
  inflating: /content/flickr8k/Images/3143159297_6f2f663ea6.jpg
  inflating: /content/flickr8k/Images/3143574389_8a4048fbe2.jpg
  inflating: /content/flickr8k/Images/3143765063_a7761b16d3.jpg
  inflating: /content/flickr8k/Images/3143953179_1c08c023a5.jpg
  inflating: /content/flickr8k/Images/3143978284_ac086be9a3.jpg
  inflating: /content/flickr8k/Images/3143980056_7a64a94b58.jpg
  inflating: /content/flickr8k/Images/3143982558_9e2d44c155.jpg
  inflating: /content/flickr8k/Images/3143991972_7193381aeb.jpg
  inflating: /content/flickr8k/Images/3144705706_391d7b77c7.jpg
  inflating: /content/flickr8k/Images/3145869775_85dfae43bd.jpg
  inflating: /content/flickr8k/Images/3145967019_1a83ebf712.jpg
  inflating: /content/flickr8k/Images/3145967309_b33abe4d84.jpg
  inflating: /content/flickr8k/Images/314603661_51e05e0e24.jpg
  inflating: /content/flickr8k/Images/3146232740_df3da0163b.jpg
  inflating: /content/flickr8k/Images/3146355833_1b7fc80210.jpg
  inflating: /content/flickr8k/Images/3146630574_05d9ebbed1.jpg
  inflating: /content/flickr8k/Images/314685044_da4390728e.jpg
  inflating: /content/flickr8k/Images/3146937399_8c046b7b1a.jpg
  inflating: /content/flickr8k/Images/3147217787_ed21cd4990.jpg
  inflating: /content/flickr8k/Images/3147758035_e8a70818cb.jpg
  inflating: /content/flickr8k/Images/3147913471_322ea231d9.jpg
  inflating: /content/flickr8k/Images/3148193539_de9dd48fc8.jpg
  inflating: /content/flickr8k/Images/3148286846_40ae914172.jpg
  inflating: /content/flickr8k/Images/3148571800_c5515e6c3d.jpg
  inflating: /content/flickr8k/Images/3148647065_2d6cd88cf6.jpg
  inflating: /content/flickr8k/Images/3148811252_2fa9490a04.jpg
  inflating: /content/flickr8k/Images/3149038044_c7c94688c6.jpg
  inflating: /content/flickr8k/Images/314904143_5a216a192b.jpg
  inflating: /content/flickr8k/Images/314940358_ec1958dc1d.jpg
  inflating: /content/flickr8k/Images/3149804151_1cc8d10783.jpg
  inflating: /content/flickr8k/Images/3149919755_f9272b10b3.jpg
  inflating: /content/flickr8k/Images/315021440_122d56ebd7.jpg
  inflating: /content/flickr8k/Images/3150252702_828a570d46.jpg
  inflating: /content/flickr8k/Images/3150315970_8f045c41a4.jpg
  inflating: /content/flickr8k/Images/3150380412_7021e5444a.jpg
  inflating: /content/flickr8k/Images/3150440350_b0f2a9e774.jpg
  inflating: /content/flickr8k/Images/3150659152_2ace03690b.jpg
  inflating: /content/flickr8k/Images/3150742439_b8a352e1e0.jpg
  inflating: /content/flickr8k/Images/315125146_d9a8e60061.jpg
  inflating: /content/flickr8k/Images/3151365121_e2a685a666.jpg
  inflating: /content/flickr8k/Images/3151492269_28d8edaa68.jpg
  inflating: /content/flickr8k/Images/3151860914_46e30cd5ea.jpg
  inflating: /content/flickr8k/Images/3152317129_177b4678b7.jpg
  inflating: /content/flickr8k/Images/3153067758_53f003b1df.jpg
  inflating: /content/flickr8k/Images/3153828367_5fc2c37c07.jpg
  inflating: /content/flickr8k/Images/3154152744_4e93ec8a62.jpg
  inflating: /content/flickr8k/Images/3154293126_e52bd07524.jpg
  inflating: /content/flickr8k/Images/315436114_6d386b8c36.jpg
  inflating: /content/flickr8k/Images/3154528397_89112faf4b.jpg
  inflating: /content/flickr8k/Images/3154641421_d1b9b8c24c.jpg
  inflating: /content/flickr8k/Images/3154693053_cfcd05c226.jpg
  inflating: /content/flickr8k/Images/3154709407_9b0778cbeb.jpg
  inflating: /content/flickr8k/Images/3154813159_58a195236d.jpg
  inflating: /content/flickr8k/Images/3154886184_ac842655b6.jpg
  inflating: /content/flickr8k/Images/3155279929_d1cddbe7cf.jpg
  inflating: /content/flickr8k/Images/3155361712_2cbf59c78e.jpg
  inflating: /content/flickr8k/Images/3155365418_43df5486f9.jpg
  inflating: /content/flickr8k/Images/3155390408_8e1a81efb2.jpg
  inflating: /content/flickr8k/Images/3155400369_69e3d6d70f.jpg
  inflating: /content/flickr8k/Images/3155451946_c0862c70cb.jpg
  inflating: /content/flickr8k/Images/3155501473_510f9c9f6b.jpg
  inflating: /content/flickr8k/Images/3155657768_b83a7831e5.jpg
  inflating: /content/flickr8k/Images/3155987659_b9ea318dd3.jpg
  inflating: /content/flickr8k/Images/3156113206_53c2a7b5d8.jpg
  inflating: /content/flickr8k/Images/3156406419_38fbd52007.jpg
  inflating: /content/flickr8k/Images/3156991513_3bf03333d8.jpg
  inflating: /content/flickr8k/Images/3157039116_d82da4e66b.jpg
  inflating: /content/flickr8k/Images/3157220149_cc3c8cc84d.jpg
  inflating: /content/flickr8k/Images/3157622277_9f59b4f62f.jpg
  inflating: /content/flickr8k/Images/3157744152_31ace8c9ed.jpg
  inflating: /content/flickr8k/Images/3157847991_463e006a28.jpg
  inflating: /content/flickr8k/Images/3158327361_6f1a518228.jpg
  inflating: /content/flickr8k/Images/3158680604_c1f99b3946.jpg
  inflating: /content/flickr8k/Images/315880837_90db309bab.jpg
  inflating: /content/flickr8k/Images/3159092624_66af4e207e.jpg
  inflating: /content/flickr8k/Images/3159424456_f316bdc1d5.jpg
  inflating: /content/flickr8k/Images/3159447439_c1496cbaea.jpg
  inflating: /content/flickr8k/Images/3159569570_dff24e7be9.jpg
  inflating: /content/flickr8k/Images/3159641529_c2c74f3eaf.jpg
  inflating: /content/flickr8k/Images/3159995270_17334ccb5b.jpg
  inflating: /content/flickr8k/Images/3160531982_37f5636b8a.jpg
  inflating: /content/flickr8k/Images/3161044966_27bf6f9dec.jpg
  inflating: /content/flickr8k/Images/3162045919_c2decbb69b.jpg
  inflating: /content/flickr8k/Images/3162095736_cc41dd41ff.jpg
  inflating: /content/flickr8k/Images/3162289423_4ca8915d0c.jpg
  inflating: /content/flickr8k/Images/3162442331_c9711857c6.jpg
  inflating: /content/flickr8k/Images/3163068926_d28ed3ef53.jpg
  inflating: /content/flickr8k/Images/3163198309_bbfe504f0a.jpg
  inflating: /content/flickr8k/Images/3163273640_8d3ef22eaf.jpg
  inflating: /content/flickr8k/Images/3163281186_e2f43dfb5f.jpg
  inflating: /content/flickr8k/Images/3163323414_d1ce127aa6.jpg
  inflating: /content/flickr8k/Images/3163477256_073605e06e.jpg
  inflating: /content/flickr8k/Images/3163563871_cef3cf33ea.jpg
  inflating: /content/flickr8k/Images/3164328039_2c56acf594.jpg
  inflating: /content/flickr8k/Images/3164347907_2813f8ff0b.jpg
  inflating: /content/flickr8k/Images/3164415865_612f9fd8bc.jpg
  inflating: /content/flickr8k/Images/3164423279_9b27cb6a06.jpg
  inflating: /content/flickr8k/Images/3165123595_8db9f918bf.jpg
  inflating: /content/flickr8k/Images/3165750962_e2e3843679.jpg
  inflating: /content/flickr8k/Images/316577571_27a0e0253e.jpg
  inflating: /content/flickr8k/Images/3165826902_6bf9c4bdb2.jpg
  inflating: /content/flickr8k/Images/3165936115_cb4017d94e.jpg
  inflating: /content/flickr8k/Images/3166366760_e43cf66eda.jpg
  inflating: /content/flickr8k/Images/3166578139_33500f7e8a.jpg
  inflating: /content/flickr8k/Images/3166969425_b5ace2f9c2.jpg
  inflating: /content/flickr8k/Images/3167365436_c379bda282.jpg
  inflating: /content/flickr8k/Images/3167379087_927ff05a35.jpg
  inflating: /content/flickr8k/Images/3168123064_d1983b8f92.jpg
  inflating: /content/flickr8k/Images/316833109_6500b526dc.jpg
  inflating: /content/flickr8k/Images/3168354472_866fe70d36.jpg
  inflating: /content/flickr8k/Images/3168796547_0c14b368f9.jpg
  inflating: /content/flickr8k/Images/3168841415_c0705a327a.jpg
  inflating: /content/flickr8k/Images/3169276423_6918dd4da1.jpg
  inflating: /content/flickr8k/Images/3169394115_2193158cee.jpg
  inflating: /content/flickr8k/Images/3169591322_d0b6d0cd04.jpg
  inflating: /content/flickr8k/Images/3169777863_d745865784.jpg
  inflating: /content/flickr8k/Images/3170110692_d1e0e66cee.jpg
  inflating: /content/flickr8k/Images/3170551725_1276644eab.jpg
  inflating: /content/flickr8k/Images/3170802797_3c851bb475.jpg
  inflating: /content/flickr8k/Images/3170856184_efabfd0297.jpg
  inflating: /content/flickr8k/Images/3170897628_3054087f8c.jpg
  inflating: /content/flickr8k/Images/3171035252_dba286ae5c.jpg
  inflating: /content/flickr8k/Images/3171066023_ec60ba30f3.jpg
  inflating: /content/flickr8k/Images/317109978_cb557802e1.jpg
  inflating: /content/flickr8k/Images/3171188674_717eee0183.jpg
  inflating: /content/flickr8k/Images/3171250845_5ae0d2a8bc.jpg
  inflating: /content/flickr8k/Images/3171347658_f0d5469c56.jpg
  inflating: /content/flickr8k/Images/3171451305_f87b9e09ee.jpg
  inflating: /content/flickr8k/Images/3171651115_e07b9d08f6.jpg
  inflating: /content/flickr8k/Images/3172280520_e7655fb596.jpg
  inflating: /content/flickr8k/Images/3172283002_3c0fc624de.jpg
  inflating: /content/flickr8k/Images/3172369593_eb4d787ffb.jpg
  inflating: /content/flickr8k/Images/3172384527_b107385a20.jpg
  inflating: /content/flickr8k/Images/3173014908_b3e69594b6.jpg
  inflating: /content/flickr8k/Images/3173157541_70b16b4318.jpg
  inflating: /content/flickr8k/Images/3173215794_6bdd1f72d4.jpg
  inflating: /content/flickr8k/Images/3173461705_b5cdeef1eb.jpg
  inflating: /content/flickr8k/Images/317383917_d8bfa350b6.jpg
  inflating: /content/flickr8k/Images/3173928684_4ea0ee5114.jpg
  inflating: /content/flickr8k/Images/3173976185_8a50123050.jpg
  inflating: /content/flickr8k/Images/3174156702_95a1cda2d9.jpg
  inflating: /content/flickr8k/Images/3174196837_800689a2f3.jpg
  inflating: /content/flickr8k/Images/3174228611_6cf9d2266b.jpg
  inflating: /content/flickr8k/Images/3174417550_d2e6100278.jpg
  inflating: /content/flickr8k/Images/3174431688_ae84778db0.jpg
  inflating: /content/flickr8k/Images/3174453534_fcc927c647.jpg
  inflating: /content/flickr8k/Images/3174713468_e22fa7779e.jpg
  inflating: /content/flickr8k/Images/3174726084_c108de0a64.jpg
  inflating: /content/flickr8k/Images/317488612_70ac35493b.jpg
  inflating: /content/flickr8k/Images/3175434849_859f09fe07.jpg
  inflating: /content/flickr8k/Images/3175446111_681a89f873.jpg
  inflating: /content/flickr8k/Images/3175712926_5a470d0886.jpg
  inflating: /content/flickr8k/Images/3175849727_bf30b892cb.jpg
  inflating: /content/flickr8k/Images/3176072448_b84c99cf7f.jpg
  inflating: /content/flickr8k/Images/3176131893_7181c733aa.jpg
  inflating: /content/flickr8k/Images/3176277818_235486a3cd.jpg
  inflating: /content/flickr8k/Images/3176278670_195eea071c.jpg
  inflating: /content/flickr8k/Images/317641829_ab2607a6c0.jpg
  inflating: /content/flickr8k/Images/3176498130_52ab9460b2.jpg
  inflating: /content/flickr8k/Images/3176968956_d942a93513.jpg
  inflating: /content/flickr8k/Images/3177298173_78cea31d64.jpg
  inflating: /content/flickr8k/Images/3177468217_56a9142e46.jpg
  inflating: /content/flickr8k/Images/3177799416_5bd0382370.jpg
  inflating: /content/flickr8k/Images/3178005751_fca19815ac.jpg
  inflating: /content/flickr8k/Images/3178300150_d4605ff02c.jpg
  inflating: /content/flickr8k/Images/3178371973_60c6b8f110.jpg
  inflating: /content/flickr8k/Images/3178489390_13a6ae7524.jpg
  inflating: /content/flickr8k/Images/3178599352_c57fdebcd2.jpg
  inflating: /content/flickr8k/Images/3179336562_c3d0c0a3bd.jpg
  inflating: /content/flickr8k/Images/3179952488_c1c812a03b.jpg
  inflating: /content/flickr8k/Images/318070878_92ead85868.jpg
  inflating: /content/flickr8k/Images/3180806542_49b6de312d.jpg
  inflating: /content/flickr8k/Images/3181322965_ce9da15271.jpg
  inflating: /content/flickr8k/Images/3181328245_7c04ce1691.jpg
  inflating: /content/flickr8k/Images/3181409177_edb09c2718.jpg
  inflating: /content/flickr8k/Images/3181599388_68559cfc17.jpg
  inflating: /content/flickr8k/Images/3181701312_70a379ab6e.jpg
  inflating: /content/flickr8k/Images/3182121297_38c99b2769.jpg
  inflating: /content/flickr8k/Images/3182161610_4d349b257f.jpg
  inflating: /content/flickr8k/Images/3182258223_5b9c8a8c55.jpg
  inflating: /content/flickr8k/Images/3182405529_7692256746.jpg
  inflating: /content/flickr8k/Images/3182558164_488b819f14.jpg
  inflating: /content/flickr8k/Images/3182570190_48214e54c7.jpg
  inflating: /content/flickr8k/Images/3182996527_70d9c323d5.jpg
  inflating: /content/flickr8k/Images/3183060123_ea3af6278b.jpg
  inflating: /content/flickr8k/Images/3183195185_cd0ff994a1.jpg
  inflating: /content/flickr8k/Images/3183195653_11b66acb34.jpg
  inflating: /content/flickr8k/Images/3183519385_311555d5f5.jpg
  inflating: /content/flickr8k/Images/3183777589_460a4f445b.jpg
  inflating: /content/flickr8k/Images/3183875944_b2be694e06.jpg
  inflating: /content/flickr8k/Images/3183883750_b6acc40397.jpg
  inflating: /content/flickr8k/Images/3184031654_34b5c4ffe1.jpg
  inflating: /content/flickr8k/Images/3184112120_6ddcd98016.jpg
  inflating: /content/flickr8k/Images/3184206563_5435f2b494.jpg
  inflating: /content/flickr8k/Images/3184891327_8785194e3c.jpg
  inflating: /content/flickr8k/Images/3185371756_ff4e9fa8a6.jpg
  inflating: /content/flickr8k/Images/3185409663_95f6b958d8.jpg
  inflating: /content/flickr8k/Images/3185645793_49de805194.jpg
  inflating: /content/flickr8k/Images/3185662156_c877583c53.jpg
  inflating: /content/flickr8k/Images/3185695861_86152b2755.jpg
  inflating: /content/flickr8k/Images/3185787277_b412d7f5b7.jpg
  inflating: /content/flickr8k/Images/3186073578_6e115f45f5.jpg
  inflating: /content/flickr8k/Images/3186412658_2ab2ebd397.jpg
  inflating: /content/flickr8k/Images/3186527735_6e9fe2cf88.jpg
  inflating: /content/flickr8k/Images/3186556417_b2d6921a20.jpg
  inflating: /content/flickr8k/Images/318667317_108c402140.jpg
  inflating: /content/flickr8k/Images/3186863842_5832573c5e.jpg
  inflating: /content/flickr8k/Images/3187096035_65dc416291.jpg
  inflating: /content/flickr8k/Images/3187117682_986ffd6b67.jpg
  inflating: /content/flickr8k/Images/3187364311_4c2a87083b.jpg
  inflating: /content/flickr8k/Images/3187395715_f2940c2b72.jpg
  inflating: /content/flickr8k/Images/3187492926_8aa85f80c6.jpg
  inflating: /content/flickr8k/Images/3187924573_203223e6c0.jpg
  inflating: /content/flickr8k/Images/3188036349_8e4e2d6ca8.jpg
  inflating: /content/flickr8k/Images/3188044631_ca3a9cc737.jpg
  inflating: /content/flickr8k/Images/3188319076_71724fcc07.jpg
  inflating: /content/flickr8k/Images/3189002057_3ef61b803e.jpg
  inflating: /content/flickr8k/Images/3189251454_03b76c2e92.jpg
  inflating: /content/flickr8k/Images/3189293145_35dea42679.jpg
  inflating: /content/flickr8k/Images/3189307452_aebc12380b.jpg
  inflating: /content/flickr8k/Images/3189521080_133777bce5.jpg
  inflating: /content/flickr8k/Images/3189941492_a3f4347b1a.jpg
  inflating: /content/flickr8k/Images/3189964753_a95536ced9.jpg
  inflating: /content/flickr8k/Images/3190677999_60bbd330fd.jpg
  inflating: /content/flickr8k/Images/3191027142_33e86636ca.jpg
  inflating: /content/flickr8k/Images/3191135894_2b4bdabb6d.jpg
  inflating: /content/flickr8k/Images/3191805046_77c334b506.jpg
  inflating: /content/flickr8k/Images/319185571_56162796da.jpg
  inflating: /content/flickr8k/Images/3191982761_88793192ed.jpg
  inflating: /content/flickr8k/Images/3192069971_83c5a90b4c.jpg
  inflating: /content/flickr8k/Images/3192266178_f9bf5d3dba.jpg
  inflating: /content/flickr8k/Images/3192311620_99bda27fbd.jpg
  inflating: /content/flickr8k/Images/3193335577_9bdbaf9f70.jpg
  inflating: /content/flickr8k/Images/3193511842_82549c21fb.jpg
  inflating: /content/flickr8k/Images/3194134352_bc1b2a25d7.jpg
  inflating: /content/flickr8k/Images/3195040792_a03954a19f.jpg
  inflating: /content/flickr8k/Images/3195147187_a073d59fa8.jpg
  inflating: /content/flickr8k/Images/3195188609_01afbe46e6.jpg
  inflating: /content/flickr8k/Images/3195701071_81879257f5.jpg
  inflating: /content/flickr8k/Images/3195969533_98f5de0fab.jpg
  inflating: /content/flickr8k/Images/3196100539_102fe877b3.jpg
  inflating: /content/flickr8k/Images/3196995975_3e38eabf01.jpg
  inflating: /content/flickr8k/Images/3197247245_9c93b60b8a.jpg
  inflating: /content/flickr8k/Images/3197482764_2f289cb726.jpg
  inflating: /content/flickr8k/Images/3197791645_601908f26b.jpg
  inflating: /content/flickr8k/Images/3197891333_b1b0fd1702.jpg
  inflating: /content/flickr8k/Images/3197917064_e679a44b8e.jpg
  inflating: /content/flickr8k/Images/3197981073_3156963446.jpg
  inflating: /content/flickr8k/Images/3198231851_6b1727482b.jpg
  inflating: /content/flickr8k/Images/3198237818_cb5eb302f0.jpg
  inflating: /content/flickr8k/Images/3198247669_7493af04a7.jpg
  inflating: /content/flickr8k/Images/319847643_df7c2a1d25.jpg
  inflating: /content/flickr8k/Images/319847657_2c40e14113.jpg
  inflating: /content/flickr8k/Images/319851847_7212423309.jpg
  inflating: /content/flickr8k/Images/319869052_08b000e4af.jpg
  inflating: /content/flickr8k/Images/319870744_0e0138d205.jpg
  inflating: /content/flickr8k/Images/3198962089_e647d1b0cd.jpg
  inflating: /content/flickr8k/Images/319938879_daf0857f91.jpg
  inflating: /content/flickr8k/Images/3199460792_deef518c01.jpg
  inflating: /content/flickr8k/Images/3199645963_a681fe04f8.jpg
  inflating: /content/flickr8k/Images/3199895624_4f01798c6f.jpg
  inflating: /content/flickr8k/Images/3200120942_59cfbb3437.jpg
  inflating: /content/flickr8k/Images/320093980_5388cb3733.jpg
  inflating: /content/flickr8k/Images/3201427741_3033f5b625.jpg
  inflating: /content/flickr8k/Images/3201594926_cd2009eb13.jpg
  inflating: /content/flickr8k/Images/3201666946_04fe837aff.jpg
  inflating: /content/flickr8k/Images/3202255152_08973fa3d7.jpg
  inflating: /content/flickr8k/Images/3202360797_2084743e90.jpg
  inflating: /content/flickr8k/Images/3203453897_6317aac6ff.jpg
  inflating: /content/flickr8k/Images/3203707977_cc9448fecb.jpg
  inflating: /content/flickr8k/Images/3203742047_6a55065411.jpg
  inflating: /content/flickr8k/Images/3203872773_6c30f64be3.jpg
  inflating: /content/flickr8k/Images/3203878596_cbb307ce3b.jpg
  inflating: /content/flickr8k/Images/3203908917_53e53c03d1.jpg
  inflating: /content/flickr8k/Images/3204081508_0e7f408097.jpg
  inflating: /content/flickr8k/Images/3204354161_caf89ec784.jpg
  inflating: /content/flickr8k/Images/3204525212_d548c7fca7.jpg
  inflating: /content/flickr8k/Images/3204686006_88f04547b9.jpg
  inflating: /content/flickr8k/Images/3204712107_5a06a81002.jpg
  inflating: /content/flickr8k/Images/3204922011_185e48949a.jpg
  inflating: /content/flickr8k/Images/3205214191_29b42b9b09.jpg
  inflating: /content/flickr8k/Images/3205336477_037d4b6bd9.jpg
  inflating: /content/flickr8k/Images/3205754736_32c29b5208.jpg
  inflating: /content/flickr8k/Images/3205839744_24504ba179.jpg
  inflating: /content/flickr8k/Images/3206058778_7053ee6b52.jpg
  inflating: /content/flickr8k/Images/3206919175_e3a11b6874.jpg
  inflating: /content/flickr8k/Images/3206999917_e682672cbc.jpg
  inflating: /content/flickr8k/Images/3207264553_8cd4dcde53.jpg
  inflating: /content/flickr8k/Images/3207343907_995f7ac1d2.jpg
  inflating: /content/flickr8k/Images/3207358897_bfa61fa3c6.jpg
  inflating: /content/flickr8k/Images/3207654194_43d6bebd68.jpg
  inflating: /content/flickr8k/Images/3207676216_48478bce97.jpg
  inflating: /content/flickr8k/Images/3207775692_bb897d9afd.jpg
  inflating: /content/flickr8k/Images/3208032657_27b9d6c4f3.jpg

In [ ]:
print("Images:", len(os.listdir("/content/flickr8k/Images")))

Images: 8091

In [ ]:
# Copying 30k to Colabs local SSD
if not os.path.exists("/content/flickr30k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr30k.zip" /content/

In [ ]:
!unzip "/content/flickr30k.zip" -d "/content/flickr30k"

Streaming output truncated to the last 5000 lines.
  inflating: /content/flickr30k/Images/2410320522.jpg
  inflating: /content/flickr30k/Images/2404747797.jpg
  inflating: /content/flickr30k/Images/241046599.jpg
  inflating: /content/flickr30k/Images/241345639.jpg
  inflating: /content/flickr30k/Images/2409312675.jpg
  inflating: /content/flickr30k/Images/241346471.jpg
  inflating: /content/flickr30k/Images/2404959574.jpg
  inflating: /content/flickr30k/Images/2410399168.jpg
  inflating: /content/flickr30k/Images/2406591500.jpg
  inflating: /content/flickr30k/Images/2413495734.jpg
  inflating: /content/flickr30k/Images/241346794.jpg
  inflating: /content/flickr30k/Images/2404488732.jpg
  inflating: /content/flickr30k/Images/241347664.jpg
  inflating: /content/flickr30k/Images/241345522.jpg
  inflating: /content/flickr30k/Images/241347300.jpg
  inflating: /content/flickr30k/Images/241347496.jpg
  inflating: /content/flickr30k/Images/2407214681.jpg
  inflating: /content/flickr30k/Images/241346402.jpg
  inflating: /content/flickr30k/Images/241346105.jpg
  inflating: /content/flickr30k/Images/241347243.jpg
  inflating: /content/flickr30k/Images/2409771090.jpg
  inflating: /content/flickr30k/Images/241031254.jpg
  inflating: /content/flickr30k/Images/241345811.jpg
  inflating: /content/flickr30k/Images/2414352262.jpg
  inflating: /content/flickr30k/Images/2408099454.jpg
  inflating: /content/flickr30k/Images/241347689.jpg
  inflating: /content/flickr30k/Images/2408224709.jpg
  inflating: /content/flickr30k/Images/2412716991.jpg
  inflating: /content/flickr30k/Images/241374292.jpg
  inflating: /content/flickr30k/Images/2412614152.jpg
  inflating: /content/flickr30k/Images/241545422.jpg
  inflating: /content/flickr30k/Images/2419591925.jpg
  inflating: /content/flickr30k/Images/2414710960.jpg
  inflating: /content/flickr30k/Images/241347356.jpg
  inflating: /content/flickr30k/Images/2420516613.jpg
  inflating: /content/flickr30k/Images/2417701468.jpg
  inflating: /content/flickr30k/Images/241345905.jpg
  inflating: /content/flickr30k/Images/2406062461.jpg
  inflating: /content/flickr30k/Images/241345770.jpg
  inflating: /content/flickr30k/Images/2405978603.jpg
  inflating: /content/flickr30k/Images/2414390475.jpg
  inflating: /content/flickr30k/Images/2404046478.jpg
  inflating: /content/flickr30k/Images/24187978.jpg
  inflating: /content/flickr30k/Images/241596333.jpg
  inflating: /content/flickr30k/Images/2415637042.jpg
  inflating: /content/flickr30k/Images/2403544744.jpg
  inflating: /content/flickr30k/Images/2415265825.jpg
  inflating: /content/flickr30k/Images/2419797375.jpg
  inflating: /content/flickr30k/Images/2414035800.jpg
  inflating: /content/flickr30k/Images/241345323.jpg
  inflating: /content/flickr30k/Images/24187497.jpg
  inflating: /content/flickr30k/Images/24183660.jpg
  inflating: /content/flickr30k/Images/2418265815.jpg
  inflating: /content/flickr30k/Images/241347441.jpg
  inflating: /content/flickr30k/Images/241347700.jpg
  inflating: /content/flickr30k/Images/241346215.jpg
  inflating: /content/flickr30k/Images/2415803492.jpg
  inflating: /content/flickr30k/Images/241345446.jpg
  inflating: /content/flickr30k/Images/2412281172.jpg
  inflating: /content/flickr30k/Images/2407528766.jpg
  inflating: /content/flickr30k/Images/2404560299.jpg
  inflating: /content/flickr30k/Images/241347803.jpg
  inflating: /content/flickr30k/Images/2417169797.jpg
  inflating: /content/flickr30k/Images/241347460.jpg
  inflating: /content/flickr30k/Images/241346260.jpg
  inflating: /content/flickr30k/Images/241347760.jpg
  inflating: /content/flickr30k/Images/2414384480.jpg
  inflating: /content/flickr30k/Images/241959826.jpg
  inflating: /content/flickr30k/Images/2404520067.jpg
  inflating: /content/flickr30k/Images/2412390588.jpg
  inflating: /content/flickr30k/Images/241347580.jpg
  inflating: /content/flickr30k/Images/2407470303.jpg
  inflating: /content/flickr30k/Images/2404173027.jpg
  inflating: /content/flickr30k/Images/241347150.jpg
  inflating: /content/flickr30k/Images/2417341107.jpg
  inflating: /content/flickr30k/Images/2416193212.jpg
  inflating: /content/flickr30k/Images/241345656.jpg
  inflating: /content/flickr30k/Images/2409597310.jpg
  inflating: /content/flickr30k/Images/2419816094.jpg
  inflating: /content/flickr30k/Images/241346709.jpg
  inflating: /content/flickr30k/Images/241346317.jpg
  inflating: /content/flickr30k/Images/241345533.jpg
  inflating: /content/flickr30k/Images/240696675.jpg
  inflating: /content/flickr30k/Images/2407091303.jpg
  inflating: /content/flickr30k/Images/2410906422.jpg
  inflating: /content/flickr30k/Images/2403376030.jpg
  inflating: /content/flickr30k/Images/2419569803.jpg
  inflating: /content/flickr30k/Images/2420546021.jpg
  inflating: /content/flickr30k/Images/241347114.jpg
  inflating: /content/flickr30k/Images/2411585767.jpg
  inflating: /content/flickr30k/Images/241347391.jpg
  inflating: /content/flickr30k/Images/24187380.jpg
  inflating: /content/flickr30k/Images/2419186511.jpg
  inflating: /content/flickr30k/Images/241345596.jpg
  inflating: /content/flickr30k/Images/242064301.jpg
  inflating: /content/flickr30k/Images/24188477.jpg
  inflating: /content/flickr30k/Images/2408570692.jpg
  inflating: /content/flickr30k/Images/2410153942.jpg
  inflating: /content/flickr30k/Images/241346434.jpg
  inflating: /content/flickr30k/Images/2413578705.jpg
  inflating: /content/flickr30k/Images/24186977.jpg
  inflating: /content/flickr30k/Images/2426215757.jpg
  inflating: /content/flickr30k/Images/2435166927.jpg
  inflating: /content/flickr30k/Images/2424250856.jpg
  inflating: /content/flickr30k/Images/2429505595.jpg
  inflating: /content/flickr30k/Images/2430037096.jpg
  inflating: /content/flickr30k/Images/2429369147.jpg
  inflating: /content/flickr30k/Images/242324909.jpg
  inflating: /content/flickr30k/Images/2424398046.jpg
  inflating: /content/flickr30k/Images/2423900639.jpg
  inflating: /content/flickr30k/Images/24226660.jpg
  inflating: /content/flickr30k/Images/2421340833.jpg
  inflating: /content/flickr30k/Images/2429366041 (1).jpg
  inflating: /content/flickr30k/Images/2422018883.jpg
  inflating: /content/flickr30k/Images/2427490900.jpg
  inflating: /content/flickr30k/Images/2431470169.jpg
  inflating: /content/flickr30k/Images/2422635544.jpg
  inflating: /content/flickr30k/Images/243380205.jpg
  inflating: /content/flickr30k/Images/242216901.jpg
  inflating: /content/flickr30k/Images/2421156369.jpg
  inflating: /content/flickr30k/Images/2420730259.jpg
  inflating: /content/flickr30k/Images/2425532035.jpg
  inflating: /content/flickr30k/Images/2435536626.jpg
  inflating: /content/flickr30k/Images/2435482148.jpg
  inflating: /content/flickr30k/Images/243728508.jpg
  inflating: /content/flickr30k/Images/2430223532.jpg
  inflating: /content/flickr30k/Images/2422589651.jpg
  inflating: /content/flickr30k/Images/2435685480.jpg
  inflating: /content/flickr30k/Images/2434010943.jpg
  inflating: /content/flickr30k/Images/2421822611.jpg
  inflating: /content/flickr30k/Images/2436549353.jpg
  inflating: /content/flickr30k/Images/2427393337.jpg
  inflating: /content/flickr30k/Images/2429978680.jpg
  inflating: /content/flickr30k/Images/2429284131.jpg
  inflating: /content/flickr30k/Images/2426724282.jpg
  inflating: /content/flickr30k/Images/2421367904.jpg
  inflating: /content/flickr30k/Images/242558556.jpg
  inflating: /content/flickr30k/Images/2430018178.jpg
  inflating: /content/flickr30k/Images/242658502.jpg
  inflating: /content/flickr30k/Images/2423292784.jpg
  inflating: /content/flickr30k/Images/2434006663.jpg
  inflating: /content/flickr30k/Images/2430269210.jpg
  inflating: /content/flickr30k/Images/2434440948.jpg
  inflating: /content/flickr30k/Images/2421446839.jpg
  inflating: /content/flickr30k/Images/243015377.jpg
  inflating: /content/flickr30k/Images/2421801040.jpg
  inflating: /content/flickr30k/Images/2426303900.jpg
  inflating: /content/flickr30k/Images/2426795961.jpg
  inflating: /content/flickr30k/Images/2432061076.jpg
  inflating: /content/flickr30k/Images/2423886164.jpg
  inflating: /content/flickr30k/Images/2437392162.jpg
  inflating: /content/flickr30k/Images/24321040.jpg
  inflating: /content/flickr30k/Images/2423118738.jpg
  inflating: /content/flickr30k/Images/2435804989.jpg
  inflating: /content/flickr30k/Images/2429729667.jpg
  inflating: /content/flickr30k/Images/242984829.jpg
  inflating: /content/flickr30k/Images/2422482455.jpg
  inflating: /content/flickr30k/Images/242109387.jpg
  inflating: /content/flickr30k/Images/2435518586.jpg
  inflating: /content/flickr30k/Images/2436160351.jpg
  inflating: /content/flickr30k/Images/242559369.jpg
  inflating: /content/flickr30k/Images/2428275562.jpg
  inflating: /content/flickr30k/Images/2422637172.jpg
  inflating: /content/flickr30k/Images/2421965120.jpg
  inflating: /content/flickr30k/Images/2429243285.jpg
  inflating: /content/flickr30k/Images/243711191.jpg
  inflating: /content/flickr30k/Images/2433175169.jpg
  inflating: /content/flickr30k/Images/2428912710.jpg
  inflating: /content/flickr30k/Images/2437266971.jpg
  inflating: /content/flickr30k/Images/2427840554.jpg
  inflating: /content/flickr30k/Images/2424620984.jpg
  inflating: /content/flickr30k/Images/243416847.jpg
  inflating: /content/flickr30k/Images/2430860418.jpg
  inflating: /content/flickr30k/Images/2432584943.jpg
  inflating: /content/flickr30k/Images/2429974376.jpg
  inflating: /content/flickr30k/Images/2437695339.jpg
  inflating: /content/flickr30k/Images/2424976964.jpg
  inflating: /content/flickr30k/Images/2423894412.jpg
  inflating: /content/flickr30k/Images/243162937.jpg
  inflating: /content/flickr30k/Images/2436081047.jpg
  inflating: /content/flickr30k/Images/2437766095.jpg
  inflating: /content/flickr30k/Images/2421659692.jpg
  inflating: /content/flickr30k/Images/2437798869.jpg
  inflating: /content/flickr30k/Images/2428797297.jpg
  inflating: /content/flickr30k/Images/2429305809.jpg
  inflating: /content/flickr30k/Images/2423085253.jpg
  inflating: /content/flickr30k/Images/2429366041.jpg
  inflating: /content/flickr30k/Images/2423277850.jpg
  inflating: /content/flickr30k/Images/2423550887.jpg
  inflating: /content/flickr30k/Images/2171576939.jpg
  inflating: /content/flickr30k/Images/2156726763.jpg
  inflating: /content/flickr30k/Images/2163780897.jpg
  inflating: /content/flickr30k/Images/2178306830.jpg
  inflating: /content/flickr30k/Images/216172386.jpg
  inflating: /content/flickr30k/Images/2162469360.jpg
  inflating: /content/flickr30k/Images/2181144377.jpg
  inflating: /content/flickr30k/Images/2176229181.jpg
  inflating: /content/flickr30k/Images/2176364472.jpg
  inflating: /content/flickr30k/Images/2169788484.jpg
  inflating: /content/flickr30k/Images/2174343200.jpg
  inflating: /content/flickr30k/Images/2156328004.jpg
  inflating: /content/flickr30k/Images/21833287.jpg
  inflating: /content/flickr30k/Images/2156122117.jpg
  inflating: /content/flickr30k/Images/2160230494.jpg
  inflating: /content/flickr30k/Images/2170187328.jpg
  inflating: /content/flickr30k/Images/2155994202.jpg
  inflating: /content/flickr30k/Images/2183123018.jpg
  inflating: /content/flickr30k/Images/2174583700.jpg
  inflating: /content/flickr30k/Images/2180726636.jpg
  inflating: /content/flickr30k/Images/2155653460.jpg
  inflating: /content/flickr30k/Images/2178064851.jpg
  inflating: /content/flickr30k/Images/2172570753.jpg
  inflating: /content/flickr30k/Images/2162367970.jpg
  inflating: /content/flickr30k/Images/2162746678.jpg
  inflating: /content/flickr30k/Images/2183114919.jpg
  inflating: /content/flickr30k/Images/2176147758.jpg
  inflating: /content/flickr30k/Images/215806759.jpg
  inflating: /content/flickr30k/Images/2178095150.jpg
  inflating: /content/flickr30k/Images/2158500020.jpg
  inflating: /content/flickr30k/Images/2175758177.jpg
  inflating: /content/flickr30k/Images/2179330298.jpg
  inflating: /content/flickr30k/Images/2152688935.jpg
  inflating: /content/flickr30k/Images/215797019.jpg
  inflating: /content/flickr30k/Images/2168723623.jpg
  inflating: /content/flickr30k/Images/2175980524.jpg
  inflating: /content/flickr30k/Images/2183468990.jpg
  inflating: /content/flickr30k/Images/2161273260.jpg
  inflating: /content/flickr30k/Images/2164363131.jpg
  inflating: /content/flickr30k/Images/2173677067.jpg
  inflating: /content/flickr30k/Images/2168021521.jpg
  inflating: /content/flickr30k/Images/2173828253.jpg
  inflating: /content/flickr30k/Images/217460891.jpg
  inflating: /content/flickr30k/Images/21687074.jpg
  inflating: /content/flickr30k/Images/2159081186.jpg
  inflating: /content/flickr30k/Images/2166529027.jpg
  inflating: /content/flickr30k/Images/2156131463.jpg
  inflating: /content/flickr30k/Images/218211630.jpg
  inflating: /content/flickr30k/Images/2169986652.jpg
  inflating: /content/flickr30k/Images/21688595.jpg
  inflating: /content/flickr30k/Images/2172572633.jpg
  inflating: /content/flickr30k/Images/2183227136.jpg
  inflating: /content/flickr30k/Images/2176776800.jpg
  inflating: /content/flickr30k/Images/215876547.jpg
  inflating: /content/flickr30k/Images/2174206711.jpg
  inflating: /content/flickr30k/Images/2161799386.jpg
  inflating: /content/flickr30k/Images/2171154778.jpg
  inflating: /content/flickr30k/Images/218225539.jpg
  inflating: /content/flickr30k/Images/2166417615.jpg
  inflating: /content/flickr30k/Images/2156331904.jpg
  inflating: /content/flickr30k/Images/2175184797.jpg
  inflating: /content/flickr30k/Images/2178295140.jpg
  inflating: /content/flickr30k/Images/218096711.jpg
  inflating: /content/flickr30k/Images/2176874361.jpg
  inflating: /content/flickr30k/Images/218342358.jpg
  inflating: /content/flickr30k/Images/217949158.jpg
  inflating: /content/flickr30k/Images/2168809436.jpg
  inflating: /content/flickr30k/Images/2162564553.jpg
  inflating: /content/flickr30k/Images/216627488.jpg
  inflating: /content/flickr30k/Images/2154062056.jpg
  inflating: /content/flickr30k/Images/216778085.jpg
  inflating: /content/flickr30k/Images/2166120300.jpg
  inflating: /content/flickr30k/Images/2159447283.jpg
  inflating: /content/flickr30k/Images/2170222061.jpg
  inflating: /content/flickr30k/Images/217593609.jpg
  inflating: /content/flickr30k/Images/2155533127.jpg
  inflating: /content/flickr30k/Images/2182575588.jpg
  inflating: /content/flickr30k/Images/2178985121.jpg
  inflating: /content/flickr30k/Images/2172574039.jpg
  inflating: /content/flickr30k/Images/2173312932.jpg
  inflating: /content/flickr30k/Images/218428071.jpg
  inflating: /content/flickr30k/Images/2167644298.jpg
  inflating: /content/flickr30k/Images/2190227737.jpg
  inflating: /content/flickr30k/Images/2200688503.jpg
  inflating: /content/flickr30k/Images/218620913.jpg
  inflating: /content/flickr30k/Images/2204993532.jpg
  inflating: /content/flickr30k/Images/2192573.jpg
  inflating: /content/flickr30k/Images/2187720319.jpg
  inflating: /content/flickr30k/Images/2203586218.jpg
  inflating: /content/flickr30k/Images/2187356302.jpg
  inflating: /content/flickr30k/Images/2197587684.jpg
  inflating: /content/flickr30k/Images/2192436502.jpg
  inflating: /content/flickr30k/Images/2198511848.jpg
  inflating: /content/flickr30k/Images/2194283350.jpg
  inflating: /content/flickr30k/Images/2192475933.jpg
  inflating: /content/flickr30k/Images/2204777844.jpg
  inflating: /content/flickr30k/Images/21954377.jpg
  inflating: /content/flickr30k/Images/218553496.jpg
  inflating: /content/flickr30k/Images/2199250692.jpg
  inflating: /content/flickr30k/Images/2184898283.jpg
  inflating: /content/flickr30k/Images/2188171629.jpg
  inflating: /content/flickr30k/Images/2189627515.jpg
  inflating: /content/flickr30k/Images/219301553.jpg
  inflating: /content/flickr30k/Images/2195887578.jpg
  inflating: /content/flickr30k/Images/2201192417.jpg
  inflating: /content/flickr30k/Images/2195620255.jpg
  inflating: /content/flickr30k/Images/2184817596.jpg
  inflating: /content/flickr30k/Images/2193980605.jpg
  inflating: /content/flickr30k/Images/2197552440.jpg
  inflating: /content/flickr30k/Images/2194495372.jpg
  inflating: /content/flickr30k/Images/218610963.jpg
  inflating: /content/flickr30k/Images/2185793891.jpg
  inflating: /content/flickr30k/Images/2198494923.jpg
  inflating: /content/flickr30k/Images/2193223202.jpg
  inflating: /content/flickr30k/Images/2186139563.jpg
  inflating: /content/flickr30k/Images/2199083344.jpg
  inflating: /content/flickr30k/Images/2191329761.jpg
  inflating: /content/flickr30k/Images/219070971.jpg
  inflating: /content/flickr30k/Images/2198918037.jpg
  inflating: /content/flickr30k/Images/2184664834.jpg
  inflating: /content/flickr30k/Images/220513228.jpg
  inflating: /content/flickr30k/Images/2192333873.jpg
  inflating: /content/flickr30k/Images/2201858857.jpg
  inflating: /content/flickr30k/Images/2190137367.jpg
  inflating: /content/flickr30k/Images/2190966429.jpg
  inflating: /content/flickr30k/Images/2193001254.jpg
  inflating: /content/flickr30k/Images/219843859.jpg
  inflating: /content/flickr30k/Images/2186367337.jpg
  inflating: /content/flickr30k/Images/2200338547.jpg
  inflating: /content/flickr30k/Images/2185255150.jpg
  inflating: /content/flickr30k/Images/2192547226.jpg
  inflating: /content/flickr30k/Images/2196050115.jpg
  inflating: /content/flickr30k/Images/219357394.jpg
  inflating: /content/flickr30k/Images/2201202388.jpg
  inflating: /content/flickr30k/Images/2204550058.jpg
  inflating: /content/flickr30k/Images/2201877660.jpg
  inflating: /content/flickr30k/Images/2194167019.jpg
  inflating: /content/flickr30k/Images/219730733.jpg
  inflating: /content/flickr30k/Images/218442982.jpg
  inflating: /content/flickr30k/Images/2203234266.jpg
  inflating: /content/flickr30k/Images/2202059975.jpg
  inflating: /content/flickr30k/Images/2201734906.jpg
  inflating: /content/flickr30k/Images/2203398833.jpg
  inflating: /content/flickr30k/Images/2196284168.jpg
  inflating: /content/flickr30k/Images/2188599628.jpg
  inflating: /content/flickr30k/Images/2195316844.jpg
  inflating: /content/flickr30k/Images/2203615439.jpg
  inflating: /content/flickr30k/Images/2185325305.jpg
  inflating: /content/flickr30k/Images/2188192752.jpg
  inflating: /content/flickr30k/Images/219630410.jpg
  inflating: /content/flickr30k/Images/2201050079.jpg
  inflating: /content/flickr30k/Images/2192802444.jpg
  inflating: /content/flickr30k/Images/2198484810.jpg
  inflating: /content/flickr30k/Images/2200337743.jpg
  inflating: /content/flickr30k/Images/219301555.jpg
  inflating: /content/flickr30k/Images/2188535529.jpg
  inflating: /content/flickr30k/Images/2185509485.jpg
  inflating: /content/flickr30k/Images/2189181027.jpg
  inflating: /content/flickr30k/Images/2193223637.jpg
  inflating: /content/flickr30k/Images/2202443907.jpg
  inflating: /content/flickr30k/Images/2203224077.jpg
  inflating: /content/flickr30k/Images/2201951969.jpg
  inflating: /content/flickr30k/Images/2198964806.jpg
  inflating: /content/flickr30k/Images/2202625355.jpg
  inflating: /content/flickr30k/Images/2201480583.jpg
  inflating: /content/flickr30k/Images/2195256068.jpg
  inflating: /content/flickr30k/Images/2194806429.jpg
  inflating: /content/flickr30k/Images/219810920.jpg
  inflating: /content/flickr30k/Images/2191522758.jpg
  inflating: /content/flickr30k/Images/2200070339.jpg
  inflating: /content/flickr30k/Images/2185734339.jpg
  inflating: /content/flickr30k/Images/2197275664.jpg
  inflating: /content/flickr30k/Images/2191779063.jpg
  inflating: /content/flickr30k/Images/2189995738.jpg
  inflating: /content/flickr30k/Images/2191453879.jpg
  inflating: /content/flickr30k/Images/2190899457.jpg
  inflating: /content/flickr30k/Images/2194194725.jpg
  inflating: /content/flickr30k/Images/2200901777.jpg
  inflating: /content/flickr30k/Images/2194797921.jpg
  inflating: /content/flickr30k/Images/2191566772.jpg
  inflating: /content/flickr30k/Images/219288082.jpg
  inflating: /content/flickr30k/Images/2191783475.jpg

In [ ]:
print("Images:", len(os.listdir("/content/flickr30k/Images")))

Images: 31811

In [ ]:
DATASETS = {
    "flickr8k": {
        "ROOT": "/content/flickr8k",
        "IMAGE_DIR": "/content/flickr8k/Images",
        "CAPTION_FILE": "/content/flickr8k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/flickr8k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/vocab.pkl"
    },
    "flickr30k": {
        "ROOT": "/content/flickr30k",
        "IMAGE_DIR": "/content/flickr30k/Images",
        "CAPTION_FILE": "/content/flickr30k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/flickr30k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/vocab.pkl"
    }
}

In [ ]:
def image_caption_map(train_df,val_df,test_df):
  train_caption_map = defaultdict(list)
  val_caption_map = defaultdict(list)
  test_caption_map = defaultdict(list)

  bad_img = "861608773_bdafd5c996.jpg"

  train_caption_map.pop(bad_img, None)
  val_caption_map.pop(bad_img, None)
  test_caption_map.pop(bad_img, None)

  for _, row in train_df.iterrows():
      train_caption_map[row["image"]].append(row["caption"])

  for _, row in val_df.iterrows():
      val_caption_map[row["image"]].append(row["caption"])

  for _, row in test_df.iterrows():
      test_caption_map[row["image"]].append(row["caption"])
  return train_caption_map,val_caption_map,test_caption_map

In [ ]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [ ]:
# Encoding

def encode_caption(text, vocab):

    tokens = text.split()

    encoded = [vocab["<SOS>"]]

    for token in tokens:
        encoded.append(
            vocab.get(token, vocab["<UNK>"])
        )

    encoded.append(vocab["<EOS>"])

    return encoded

In [ ]:
class FlickrRetrievalDataset(Dataset):
    def __init__(self, caption_map, image_dir, vocab, transform=None, random_caption=True):
        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform
        self.random_caption = random_caption

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):
        image_name = self.image_names[idx]

        captions = self.caption_map[image_name]

        if self.random_caption:
            caption = random.choice(captions)
        else:
            caption = captions[0]      # fixed caption for eval

        try:
          image = Image.open(
              os.path.join(self.image_dir, image_name)
          ).convert("RGB")

        except Exception:
            return self.__getitem__(
                (idx + 1) % len(self)
            )

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, caption

In [ ]:
class FlickrAllCaptionEvalDataset(Dataset):

    def __init__(self, caption_map, image_dir, vocab, transform=None):

        self.samples = []
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform

        for image_name in sorted(caption_map.keys()):

            for caption in caption_map[image_name]:

                self.samples.append(
                    (image_name, caption)
                )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        image_name, caption = self.samples[idx]

        image = Image.open(
            os.path.join(self.image_dir, image_name)
        ).convert("RGB")

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, caption

In [ ]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    images = []
    captions = []
    lengths = []

    for image, caption in batch:
        images.append(image)
        captions.append(caption)
        lengths.append(len(caption))

    images = torch.stack(images)

    captions = pad_sequence(
        captions,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    lengths = torch.tensor(lengths)

    return images, captions, lengths

In [ ]:
def prepare_datasets_dataloaders(train_caption_map,val_caption_map,test_caption_map):

  train_dataset = FlickrRetrievalDataset(train_caption_map,IMAGE_DIR,vocab,image_transform,random_caption=True)
  val_dataset = FlickrRetrievalDataset(val_caption_map,IMAGE_DIR,vocab,image_transform,random_caption=False)
  test_dataset = FlickrRetrievalDataset(test_caption_map,IMAGE_DIR,vocab,image_transform,random_caption=False)
  all_caption_test_dataset = FlickrAllCaptionEvalDataset(test_caption_map,IMAGE_DIR,vocab,image_transform)

  BATCH_SIZE = 256
  train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    num_workers=4,
    pin_memory=True,
    )
  val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=4,
        pin_memory=True,
    )
  test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=4,
        pin_memory=True,
    )
  all_caption_test_loader = DataLoader(
    all_caption_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=4
    )
  return train_loader,val_loader,test_loader,all_caption_test_loader

ResnetImage Encoder

In [ ]:
import timm
import torch
import torch.nn as nn
import torch.nn.functional as F

class ImageEncoder(nn.Module):

    def __init__(self, embed_dim=768):

        super().__init__()

        backbone = models.resnet50(
            weights=models.ResNet50_Weights.IMAGENET1K_V2
        )

        for param in backbone.parameters():
          param.requires_grad = False

        # Fine tune last two ResNet stages
        for param in backbone.layer3.parameters():
            param.requires_grad = True

        for param in backbone.layer4.parameters():
            param.requires_grad = True

        self.backbone = nn.Sequential(
            *list(backbone.children())[:-1]
        )

        self.projection = nn.Sequential(
            nn.Linear(2048, 1024),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(1024, embed_dim)
        )

    def forward(self, images):

        features = self.backbone(images)

        features = features.squeeze(-1).squeeze(-1)

        embeddings = self.projection(features)

        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

LSTM Bahdanau Attention Text encoder

In [ ]:
from torch.nn.utils.rnn import (
    pack_padded_sequence,
    pad_packed_sequence
)

class TextEncoderAttention(nn.Module):

    def __init__(
        self,
        vocab_size,
        embed_dim=300,
        hidden_dim=512,
        pad_idx=0
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=pad_idx
        )

        self.lstm = nn.LSTM(
            embed_dim,
            hidden_dim,
            num_layers=2,
            dropout=0.5,
            bidirectional=True,
            batch_first=True
        )

        # Attention layer
        self.attn_W = nn.Linear(hidden_dim * 2, hidden_dim)
        self.attn_U = nn.Linear(hidden_dim * 2, hidden_dim)
        self.attn_v = nn.Linear(hidden_dim, 1, bias=False)

        self.projection = nn.Sequential(
            nn.Linear(hidden_dim * 2, 1024),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(1024, 768)
        )

    def forward(
        self,
        captions,
        lengths
    ):

        embedded = self.embedding(captions)

        packed = pack_padded_sequence(
            embedded,
            lengths.cpu(),
            batch_first=True,
            enforce_sorted=False
        )

        packed_out, (hidden, cell) = self.lstm(packed)

        outputs, _ = pad_packed_sequence(
            packed_out,
            batch_first=True
        )

        # outputs:
        # (batch, seq_len, hidden_dim*2)
        batch_size = outputs.size(0)
        seq_len = outputs.size(1)

        # Final BiLSTM hidden state (query)
        hidden_forward = hidden[-2]
        hidden_backward = hidden[-1]

        query = torch.cat(
            [hidden_forward, hidden_backward],
            dim=1
        )

        query = query.unsqueeze(1).repeat(
            1,
            seq_len,
            1
        )

        # Bahdanau Attention
        energy = torch.tanh(
            self.attn_W(outputs)
            +
            self.attn_U(query)
        )

        attn_scores = self.attn_v(energy).squeeze(-1)

        mask = (
            torch.arange(
                seq_len,
                device=outputs.device
            )
            .expand(batch_size, seq_len)
            >= lengths.unsqueeze(1).to(outputs.device)
        )

        attn_scores = attn_scores.masked_fill(
            mask,
            -1e9
        )

        attn_weights = torch.softmax(
            attn_scores,
            dim=1
        )

        context = torch.sum(
            outputs *
            attn_weights.unsqueeze(-1),
            dim=1
        )



        embeddings = self.projection(context)

        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

In [ ]:
# Joint Model (ViT + LSTM Retrieval)

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

class ResNetLSTMRetrieval(nn.Module):
    def __init__(self, image_encoder, text_encoder):
        super().__init__()

        self.image_encoder = image_encoder
        self.text_encoder = text_encoder

        # Learnable temperature parameter
        self.logit_scale = nn.Parameter(
            torch.ones([]) * np.log(1 / 0.07)
        )

    def forward(self, images, captions, lengths):
        image_emb = self.image_encoder(images)
        text_emb = self.text_encoder(captions, lengths)

        # Normalize embeddings
        image_emb = F.normalize(image_emb, p=2, dim=1)
        text_emb = F.normalize(text_emb, p=2, dim=1)

        return image_emb, text_emb

In [ ]:
def build_image_text_encoder(vocab,device):
  encoder = ImageEncoder(embed_dim=768).to(device)

  text_encoder = TextEncoderAttention(vocab_size=len(vocab),embed_dim=300,hidden_dim=512,pad_idx=vocab["<PAD>"]).to(device)

  model = ResNetLSTMRetrieval(image_encoder=encoder,text_encoder=text_encoder).to(device)

  return model

In [ ]:
# CLIP-Style Contrastive Loss

def clip_contrastive_loss(image_emb, text_emb, logit_scale):

    # CLIP-style learnable temperature
    logit_scale = logit_scale.exp().clamp(max=100)

    # Similarity Matrix
    logits = torch.matmul(image_emb, text_emb.T) * logit_scale

    # Ground truth labels
    targets = torch.arange(
        image_emb.size(0),
        device=image_emb.device
    )

    # Image → Text
    loss_i2t = F.cross_entropy(logits, targets)

    # Text → Image
    loss_t2i = F.cross_entropy(logits.T, targets)

    # Bidirectional InfoNCE
    loss = (loss_i2t + loss_t2i) / 2

    return loss, logits

In [ ]:
# Training
def define_optimizer(model):
  optimizer = torch.optim.AdamW(
      [
          {
              "params": model.image_encoder.backbone.parameters(),
              "lr": 1e-5
          },
          {
              "params": model.image_encoder.projection.parameters(),
              "lr": 3e-4
          },
          {
              "params": model.text_encoder.parameters(),
              "lr": 3e-4
          },
          {
              "params": [model.logit_scale],
              "lr": 1e-4
          }
      ],
      weight_decay=1e-4
  )
  scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer,T_max=50)
  return optimizer,scheduler

In [ ]:
# Add Validation Loop
def evaluate(model, dataloader, device):
    model.eval()
    total_loss = 0.0

    with torch.no_grad():
        for images, captions, lengths in dataloader:
            images = images.to(device)
            captions = captions.to(device)

            image_emb, text_emb = model(
                images,
                captions,
                lengths
            )

            loss, _ = clip_contrastive_loss(
                image_emb,
                text_emb,
                model.logit_scale
            )

            total_loss += loss.item()

    return total_loss / len(dataloader)

In [ ]:
def model_training(model,train_loader,val_loader,optimizer,scheduler,dataset_name):
  import time
  import torch

  # Training
  NUM_EPOCHS = 50
  best_val_loss = float("inf")
  patience = 5
  epochs_without_improvement = 0

  SAVE_DIR = f"/content/drive/MyDrive/MMRetrieval/R3/{dataset_name}"
  os.makedirs(SAVE_DIR, exist_ok=True)

  BEST_MODEL_PATH = os.path.join(
      SAVE_DIR,
      "best_retrieval_R3_model.pth"
  )

  for epoch in range(NUM_EPOCHS):

      print(f"\n================ Epoch {epoch+1}/{NUM_EPOCHS} ================")

      model.train()
      running_loss = 0.0

      epoch_start = time.time()

      for batch_idx, (images, captions, lengths) in enumerate(train_loader):

          batch_start = time.time()

          images = images.to(device, non_blocking=True)
          captions = captions.to(device, non_blocking=True)

          optimizer.zero_grad(set_to_none=True)

          image_emb, text_emb = model(
              images,
              captions,
              lengths
          )

          loss, _ = clip_contrastive_loss(
              image_emb,
              text_emb,
              model.logit_scale
          )

          loss.backward()

          torch.nn.utils.clip_grad_norm_(
              model.parameters(),
              max_norm=1.0
          )

          optimizer.step()

          running_loss += loss.item()

          batch_time = time.time() - batch_start

          print(
              f"Batch {batch_idx+1:02d}/{len(train_loader)} | "
              f"Loss: {loss.item():.4f} | "
              f"Time: {batch_time:.2f}s"
          )

      train_time = time.time() - epoch_start

      train_loss = running_loss / len(train_loader)

      # ---------------- Validation ----------------
      val_start = time.time()

      val_loss = evaluate(
          model,
          val_loader,
          device
      )

      val_time = time.time() - val_start

      scheduler.step()

      print("\n---------------- Summary ----------------")
      print(f"Train Loss     : {train_loss:.4f}")
      print(f"Validation Loss: {val_loss:.4f}")
      print(f"Training Time  : {train_time:.2f} sec")
      print(f"Validation Time: {val_time:.2f} sec")
      print(
          f"GPU Memory Used: "
          f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
      )

      # Save best model
      if val_loss < best_val_loss:

          best_val_loss = val_loss
          epochs_without_improvement = 0

          torch.save(
              {
                  "model_state_dict": model.state_dict(),
                  "optimizer_state_dict": optimizer.state_dict(),
                  "epoch": epoch,
                  "scheduler_state_dict": scheduler.state_dict(),
                  "val_loss": val_loss
              },
              BEST_MODEL_PATH
          )
          print(f"✓ Best model saved(Val Loss: {val_loss:.4f})")
      else:
        epochs_without_improvement += 1
        print(f"No improvement for "f"{epochs_without_improvement}/{patience} epochs")

      if epochs_without_improvement >= patience:
        print("\nEarly stopping triggered!")
        break

  FINAL_MODEL_PATH = BEST_MODEL_PATH
  checkpoint = torch.load(BEST_MODEL_PATH, map_location=device)
  model.load_state_dict(checkpoint["model_state_dict"])

  return model,FINAL_MODEL_PATH

In [ ]:
def extract_embeddings(model, dataloader, device):
    model.eval()

    image_embeddings = []
    text_embeddings = []

    with torch.no_grad():
        for images, captions, lengths in dataloader:
            images = images.to(device)
            captions = captions.to(device)

            img_emb, txt_emb = model(images, captions, lengths)

            image_embeddings.append(img_emb.cpu())
            text_embeddings.append(txt_emb.cpu())

    image_embeddings = torch.cat(image_embeddings, dim=0)
    text_embeddings = torch.cat(text_embeddings, dim=0)

    return image_embeddings, text_embeddings

In [ ]:
# image -> text
def image_to_text_recall(similarity, k):

    correct = 0

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        topk = similarity[img_idx].topk(k).indices.tolist()

        if any(idx in gt_caps for idx in topk):
            correct += 1

    return correct / similarity.shape[0]

In [ ]:
def text_to_image_recall(similarity, k):

    similarity_t = similarity.T

    correct = 0

    for cap_idx in range(similarity_t.shape[0]):

        gt_img = cap_idx // 5

        topk = similarity_t[cap_idx]\
            .topk(k)\
            .indices\
            .tolist()

        if gt_img in topk:
            correct += 1

    return correct / similarity_t.shape[0]

In [ ]:
def image_to_text_mrr(similarity):

    reciprocal_ranks = []

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        sorted_idx = torch.argsort(
            similarity[img_idx],
            descending=True
        )

        best_rank = float("inf")

        for cap in gt_caps:

            rank = (
                (sorted_idx == cap)
                .nonzero(as_tuple=True)[0]
                .item()
            ) + 1

            best_rank = min(best_rank, rank)

        reciprocal_ranks.append(
            1.0 / best_rank
        )

    return np.mean(reciprocal_ranks)

In [ ]:
def text_to_image_mrr(similarity):

    similarity_t2i = similarity.T

    reciprocal_ranks = []

    for cap_idx in range(similarity_t2i.shape[0]):

        gt_image = cap_idx // 5

        sorted_idx = torch.argsort(
            similarity_t2i[cap_idx],
            descending=True
        )

        rank = (
            (sorted_idx == gt_image)
            .nonzero(as_tuple=True)[0]
            .item()
        ) + 1

        reciprocal_ranks.append(
            1.0 / rank
        )

    return np.mean(reciprocal_ranks)

In [ ]:
def model_testing(model,FINAL_MODEL_PATH,all_caption_test_loader):
  checkpoint = torch.load(
        FINAL_MODEL_PATH,
        map_location=device
    )
  model.load_state_dict(
        checkpoint["model_state_dict"]
    )

  model.eval()
  with torch.inference_mode():
    image_embs, text_embs = extract_embeddings(
      model,
      all_caption_test_loader,
      device
    )
  print(image_embs.shape)
  print(text_embs.shape)
  # Similarity Matrix
  unique_image_embs = image_embs[::5]

  similarity = unique_image_embs @ text_embs.T

  print("Image embeddings:", unique_image_embs.shape)
  print("Text embeddings:", text_embs.shape)
  print("Similarity:", similarity.shape)
  results = pd.DataFrame({
      "Metric": [
          "Recall@1",
          "Recall@5",
          "Recall@10",
          "MRR"
      ],
      "Image→Text": [
          image_to_text_recall(similarity, 1),
          image_to_text_recall(similarity, 5),
          image_to_text_recall(similarity, 10),
          image_to_text_mrr(similarity)
      ],
      "Text→Image": [
          text_to_image_recall(similarity, 1),
          text_to_image_recall(similarity, 5),
          text_to_image_recall(similarity, 10),
          text_to_image_mrr(similarity)
      ]
  })

  results["Image→Text"] = results["Image→Text"].round(6)
  results["Text→Image"] = results["Text→Image"].round(6)

  display(results)
  return

In [ ]:
import gc
def reset_resourses():
  gc.collect()
  torch.cuda.empty_cache()
  print("\nMemory after cleanup")
  print("Allocated:",torch.cuda.memory_allocated()/1024**3)
  print("Reserved:",torch.cuda.memory_reserved()/1024**3)

In [ ]:
for dataset_name, cfg in DATASETS.items():
    torch.cuda.reset_peak_memory_stats()
    print("\n************************")
    print(f"\nProcessing - {dataset_name}")
    print("\n************************\n")
    ROOT = cfg["ROOT"]
    IMAGE_DIR = cfg["IMAGE_DIR"]
    CAPTION_FILE = cfg["CAPTION_FILE"]
    with open(cfg["flickr_split"],"rb") as f:
      split = pickle.load(f)

    with open(cfg["vocab"],"rb") as g:
      vocab = pickle.load(g)

    model = build_image_text_encoder(vocab, device)

   # print("MODEL\n",model)

    optimizer,scheduler = define_optimizer(model)

    df = pd.read_csv(CAPTION_FILE)
    train_imgs = split["train"]
    val_imgs = split["val"]
    test_imgs = split["test"]

    print(f"Train: {len(train_imgs)} | Val: {len(val_imgs)} | Test: {len(test_imgs)}")

    train_df = df[df["image"].isin(train_imgs)].reset_index(drop=True)
    val_df = df[df["image"].isin(val_imgs)].reset_index(drop=True)
    test_df = df[df["image"].isin(test_imgs)].reset_index(drop=True)

    train_df = train_df.dropna(subset=["caption"]).reset_index(drop=True)
    val_df = val_df.dropna(subset=["caption"]).reset_index(drop=True)
    test_df = test_df.dropna(subset=["caption"]).reset_index(drop=True)

    train_caption_map,val_caption_map,test_caption_map = image_caption_map(train_df,val_df,test_df)

    train_loader,val_loader,test_loader,all_caption_test_loader = prepare_datasets_dataloaders(train_caption_map,val_caption_map,test_caption_map)

    best_model,FINAL_MODEL_PATH  = model_training(model,train_loader,val_loader,optimizer,scheduler,dataset_name)

    model_testing(best_model,FINAL_MODEL_PATH,all_caption_test_loader)

    del model
    del optimizer
    del scheduler

    del train_loader
    del val_loader
    del test_loader
    del all_caption_test_loader

    del train_df
    del val_df
    del test_df

    del train_caption_map
    del val_caption_map
    del test_caption_map

    del split
    del vocab
    del df

    reset_resourses()

************************

Processing - flickr8k

************************

Train: 6068 | Val: 1011 | Test: 1012

================ Epoch 1/50 ================
Batch 01/24 | Loss: 5.5938 | Time: 0.22s
Batch 02/24 | Loss: 5.5949 | Time: 0.17s
Batch 03/24 | Loss: 5.5442 | Time: 0.17s
Batch 04/24 | Loss: 5.5081 | Time: 0.17s
Batch 05/24 | Loss: 5.4831 | Time: 0.17s
Batch 06/24 | Loss: 5.4093 | Time: 0.17s
Batch 07/24 | Loss: 5.3548 | Time: 0.17s
Batch 08/24 | Loss: 5.2782 | Time: 0.17s
Batch 09/24 | Loss: 5.2099 | Time: 0.17s
Batch 10/24 | Loss: 5.1567 | Time: 0.17s
Batch 11/24 | Loss: 5.1335 | Time: 0.17s
Batch 12/24 | Loss: 5.0949 | Time: 0.17s
Batch 13/24 | Loss: 5.1429 | Time: 0.20s
Batch 14/24 | Loss: 5.0840 | Time: 0.17s
Batch 15/24 | Loss: 5.0443 | Time: 0.18s
Batch 16/24 | Loss: 5.0197 | Time: 0.18s
Batch 17/24 | Loss: 4.9439 | Time: 0.19s
Batch 18/24 | Loss: 4.8775 | Time: 0.17s
Batch 19/24 | Loss: 4.8616 | Time: 0.17s
Batch 20/24 | Loss: 4.8927 | Time: 0.17s
Batch 21/24 | Loss: 4.8589 | Time: 0.18s
Batch 22/24 | Loss: 4.7940 | Time: 0.17s
Batch 23/24 | Loss: 4.7499 | Time: 0.17s
Batch 24/24 | Loss: 4.3283 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 5.1233
Validation Loss: 4.6163
Training Time  : 10.20 sec
Validation Time: 2.45 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 4.6163)

================ Epoch 2/50 ================
Batch 01/24 | Loss: 4.6701 | Time: 0.23s
Batch 02/24 | Loss: 4.5557 | Time: 0.17s
Batch 03/24 | Loss: 4.5450 | Time: 0.17s
Batch 04/24 | Loss: 4.5116 | Time: 0.17s
Batch 05/24 | Loss: 4.4686 | Time: 0.20s
Batch 06/24 | Loss: 4.4695 | Time: 0.18s
Batch 07/24 | Loss: 4.6535 | Time: 0.17s
Batch 08/24 | Loss: 4.4038 | Time: 0.17s
Batch 09/24 | Loss: 4.4418 | Time: 0.17s
Batch 10/24 | Loss: 4.3266 | Time: 0.17s
Batch 11/24 | Loss: 4.4288 | Time: 0.17s
Batch 12/24 | Loss: 4.2342 | Time: 0.17s
Batch 13/24 | Loss: 4.2656 | Time: 0.17s
Batch 14/24 | Loss: 4.2289 | Time: 0.17s
Batch 15/24 | Loss: 4.2089 | Time: 0.17s
Batch 16/24 | Loss: 4.1378 | Time: 0.17s
Batch 17/24 | Loss: 4.2814 | Time: 0.18s
Batch 18/24 | Loss: 4.2596 | Time: 0.17s
Batch 19/24 | Loss: 4.1544 | Time: 0.17s
Batch 20/24 | Loss: 4.1332 | Time: 0.17s
Batch 21/24 | Loss: 4.1024 | Time: 0.17s
Batch 22/24 | Loss: 4.0114 | Time: 0.17s
Batch 23/24 | Loss: 3.9181 | Time: 0.17s
Batch 24/24 | Loss: 3.6238 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 4.2931
Validation Loss: 3.9054
Training Time  : 10.35 sec
Validation Time: 2.50 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 3.9054)

================ Epoch 3/50 ================
Batch 01/24 | Loss: 3.7032 | Time: 0.20s
Batch 02/24 | Loss: 3.9335 | Time: 0.18s
Batch 03/24 | Loss: 3.7427 | Time: 0.18s
Batch 04/24 | Loss: 3.8231 | Time: 0.17s
Batch 05/24 | Loss: 3.8493 | Time: 0.20s
Batch 06/24 | Loss: 3.7063 | Time: 0.18s
Batch 07/24 | Loss: 3.9141 | Time: 0.18s
Batch 08/24 | Loss: 3.8425 | Time: 0.17s
Batch 09/24 | Loss: 3.7627 | Time: 0.19s
Batch 10/24 | Loss: 3.6883 | Time: 0.17s
Batch 11/24 | Loss: 3.6160 | Time: 0.17s
Batch 12/24 | Loss: 3.6126 | Time: 0.17s
Batch 13/24 | Loss: 3.6966 | Time: 0.17s
Batch 14/24 | Loss: 3.6545 | Time: 0.17s
Batch 15/24 | Loss: 3.5850 | Time: 0.17s
Batch 16/24 | Loss: 3.7074 | Time: 0.17s
Batch 17/24 | Loss: 3.8071 | Time: 0.17s
Batch 18/24 | Loss: 3.5195 | Time: 0.17s
Batch 19/24 | Loss: 3.6800 | Time: 0.17s
Batch 20/24 | Loss: 3.4507 | Time: 0.17s
Batch 21/24 | Loss: 3.6296 | Time: 0.17s
Batch 22/24 | Loss: 3.6197 | Time: 0.17s
Batch 23/24 | Loss: 3.5710 | Time: 0.17s
Batch 24/24 | Loss: 3.2350 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 3.6813
Validation Loss: 3.5948
Training Time  : 10.11 sec
Validation Time: 2.44 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 3.5948)

================ Epoch 4/50 ================
Batch 01/24 | Loss: 3.3650 | Time: 0.20s
Batch 02/24 | Loss: 3.4165 | Time: 0.17s
Batch 03/24 | Loss: 3.4014 | Time: 0.17s
Batch 04/24 | Loss: 3.3470 | Time: 0.17s
Batch 05/24 | Loss: 3.3837 | Time: 0.20s
Batch 06/24 | Loss: 3.4258 | Time: 0.18s
Batch 07/24 | Loss: 3.4524 | Time: 0.18s
Batch 08/24 | Loss: 3.2864 | Time: 0.18s
Batch 09/24 | Loss: 3.2487 | Time: 0.20s
Batch 10/24 | Loss: 3.3570 | Time: 0.18s
Batch 11/24 | Loss: 3.2858 | Time: 0.18s
Batch 12/24 | Loss: 3.2818 | Time: 0.18s
Batch 13/24 | Loss: 3.1497 | Time: 0.17s
Batch 14/24 | Loss: 3.4258 | Time: 0.17s
Batch 15/24 | Loss: 3.2431 | Time: 0.17s
Batch 16/24 | Loss: 3.2980 | Time: 0.17s
Batch 17/24 | Loss: 3.3049 | Time: 0.18s
Batch 18/24 | Loss: 3.2198 | Time: 0.17s
Batch 19/24 | Loss: 3.0281 | Time: 0.17s
Batch 20/24 | Loss: 3.2287 | Time: 0.17s
Batch 21/24 | Loss: 3.1577 | Time: 0.17s
Batch 22/24 | Loss: 3.1133 | Time: 0.17s
Batch 23/24 | Loss: 3.2340 | Time: 0.17s
Batch 24/24 | Loss: 2.7397 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 3.2664
Validation Loss: 3.3776
Training Time  : 10.23 sec
Validation Time: 2.42 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 3.3776)

================ Epoch 5/50 ================
Batch 01/24 | Loss: 3.0256 | Time: 0.21s
Batch 02/24 | Loss: 3.1652 | Time: 0.17s
Batch 03/24 | Loss: 3.0005 | Time: 0.17s
Batch 04/24 | Loss: 3.0979 | Time: 0.17s
Batch 05/24 | Loss: 2.9495 | Time: 0.18s
Batch 06/24 | Loss: 2.9212 | Time: 0.17s
Batch 07/24 | Loss: 2.9612 | Time: 0.17s
Batch 08/24 | Loss: 2.8700 | Time: 0.17s
Batch 09/24 | Loss: 2.9394 | Time: 0.17s
Batch 10/24 | Loss: 3.1044 | Time: 0.17s
Batch 11/24 | Loss: 3.0010 | Time: 0.17s
Batch 12/24 | Loss: 2.9254 | Time: 0.17s
Batch 13/24 | Loss: 2.9727 | Time: 0.19s
Batch 14/24 | Loss: 2.9034 | Time: 0.17s
Batch 15/24 | Loss: 2.9277 | Time: 0.17s
Batch 16/24 | Loss: 2.9795 | Time: 0.17s
Batch 17/24 | Loss: 2.8220 | Time: 0.17s
Batch 18/24 | Loss: 2.9607 | Time: 0.18s
Batch 19/24 | Loss: 2.9201 | Time: 0.18s
Batch 20/24 | Loss: 3.0104 | Time: 0.17s
Batch 21/24 | Loss: 2.8776 | Time: 0.17s
Batch 22/24 | Loss: 2.8585 | Time: 0.17s
Batch 23/24 | Loss: 2.9515 | Time: 0.17s
Batch 24/24 | Loss: 2.5855 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 2.9471
Validation Loss: 3.2244
Training Time  : 10.13 sec
Validation Time: 2.44 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 3.2244)

================ Epoch 6/50 ================
Batch 01/24 | Loss: 2.6312 | Time: 0.19s
Batch 02/24 | Loss: 2.8708 | Time: 0.18s
Batch 03/24 | Loss: 2.7080 | Time: 0.18s
Batch 04/24 | Loss: 2.8375 | Time: 0.18s
Batch 05/24 | Loss: 2.6130 | Time: 0.18s
Batch 06/24 | Loss: 2.6596 | Time: 0.18s
Batch 07/24 | Loss: 2.8603 | Time: 0.18s
Batch 08/24 | Loss: 2.6340 | Time: 0.18s
Batch 09/24 | Loss: 2.5303 | Time: 0.18s
Batch 10/24 | Loss: 3.0142 | Time: 0.18s
Batch 11/24 | Loss: 2.5511 | Time: 0.18s
Batch 12/24 | Loss: 2.7836 | Time: 0.18s
Batch 13/24 | Loss: 2.6684 | Time: 0.20s
Batch 14/24 | Loss: 2.5807 | Time: 0.18s
Batch 15/24 | Loss: 2.5908 | Time: 0.17s
Batch 16/24 | Loss: 2.6367 | Time: 0.17s
Batch 17/24 | Loss: 2.6756 | Time: 0.20s
Batch 18/24 | Loss: 2.5506 | Time: 0.17s
Batch 19/24 | Loss: 2.6523 | Time: 0.17s
Batch 20/24 | Loss: 2.7065 | Time: 0.17s
Batch 21/24 | Loss: 2.6733 | Time: 0.17s
Batch 22/24 | Loss: 2.6558 | Time: 0.18s
Batch 23/24 | Loss: 2.6258 | Time: 0.18s
Batch 24/24 | Loss: 2.2565 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 2.6653
Validation Loss: 3.0865
Training Time  : 10.31 sec
Validation Time: 2.40 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 3.0865)

================ Epoch 7/50 ================
Batch 01/24 | Loss: 2.4903 | Time: 0.19s
Batch 02/24 | Loss: 2.4186 | Time: 0.17s
Batch 03/24 | Loss: 2.5093 | Time: 0.17s
Batch 04/24 | Loss: 2.4787 | Time: 0.17s
Batch 05/24 | Loss: 2.4759 | Time: 0.17s
Batch 06/24 | Loss: 2.5061 | Time: 0.17s
Batch 07/24 | Loss: 2.6263 | Time: 0.17s
Batch 08/24 | Loss: 2.5472 | Time: 0.17s
Batch 09/24 | Loss: 2.3732 | Time: 0.17s
Batch 10/24 | Loss: 2.3619 | Time: 0.17s
Batch 11/24 | Loss: 2.5228 | Time: 0.17s
Batch 12/24 | Loss: 2.4040 | Time: 0.17s
Batch 13/24 | Loss: 2.4656 | Time: 0.18s
Batch 14/24 | Loss: 2.4725 | Time: 0.18s
Batch 15/24 | Loss: 2.4507 | Time: 0.18s
Batch 16/24 | Loss: 2.3605 | Time: 0.18s
Batch 17/24 | Loss: 2.5029 | Time: 0.18s
Batch 18/24 | Loss: 2.4927 | Time: 0.18s
Batch 19/24 | Loss: 2.5345 | Time: 0.18s
Batch 20/24 | Loss: 2.3346 | Time: 0.18s
Batch 21/24 | Loss: 2.4554 | Time: 0.17s
Batch 22/24 | Loss: 2.4459 | Time: 0.17s
Batch 23/24 | Loss: 2.4775 | Time: 0.17s
Batch 24/24 | Loss: 2.0804 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 2.4495
Validation Loss: 3.0604
Training Time  : 10.34 sec
Validation Time: 2.40 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 3.0604)

================ Epoch 8/50 ================
Batch 01/24 | Loss: 2.4204 | Time: 0.21s
Batch 02/24 | Loss: 2.2359 | Time: 0.17s
Batch 03/24 | Loss: 2.2354 | Time: 0.17s
Batch 04/24 | Loss: 2.3855 | Time: 0.17s
Batch 05/24 | Loss: 2.3087 | Time: 0.19s
Batch 06/24 | Loss: 2.2140 | Time: 0.17s
Batch 07/24 | Loss: 2.1294 | Time: 0.17s
Batch 08/24 | Loss: 2.2963 | Time: 0.17s
Batch 09/24 | Loss: 2.2191 | Time: 0.22s
Batch 10/24 | Loss: 2.2786 | Time: 0.17s
Batch 11/24 | Loss: 2.3082 | Time: 0.17s
Batch 12/24 | Loss: 2.2909 | Time: 0.18s
Batch 13/24 | Loss: 2.1634 | Time: 0.24s
Batch 14/24 | Loss: 2.2025 | Time: 0.17s
Batch 15/24 | Loss: 2.1895 | Time: 0.18s
Batch 16/24 | Loss: 2.3292 | Time: 0.17s
Batch 17/24 | Loss: 2.1669 | Time: 0.18s
Batch 18/24 | Loss: 2.1779 | Time: 0.18s
Batch 19/24 | Loss: 2.2671 | Time: 0.17s
Batch 20/24 | Loss: 2.2068 | Time: 0.17s
Batch 21/24 | Loss: 2.2865 | Time: 0.17s
Batch 22/24 | Loss: 2.1662 | Time: 0.17s
Batch 23/24 | Loss: 2.1629 | Time: 0.17s
Batch 24/24 | Loss: 1.8616 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 2.2293
Validation Loss: 2.9911
Training Time  : 10.19 sec
Validation Time: 2.44 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 2.9911)

================ Epoch 9/50 ================
Batch 01/24 | Loss: 2.0741 | Time: 0.19s
Batch 02/24 | Loss: 2.2500 | Time: 0.17s
Batch 03/24 | Loss: 2.0962 | Time: 0.17s
Batch 04/24 | Loss: 2.0660 | Time: 0.17s
Batch 05/24 | Loss: 2.1161 | Time: 0.19s
Batch 06/24 | Loss: 2.1257 | Time: 0.17s
Batch 07/24 | Loss: 2.1331 | Time: 0.17s
Batch 08/24 | Loss: 2.1107 | Time: 0.17s
Batch 09/24 | Loss: 2.0775 | Time: 0.21s
Batch 10/24 | Loss: 2.0036 | Time: 0.17s
Batch 11/24 | Loss: 2.1326 | Time: 0.17s
Batch 12/24 | Loss: 2.1343 | Time: 0.17s
Batch 13/24 | Loss: 2.1278 | Time: 0.17s
Batch 14/24 | Loss: 2.1306 | Time: 0.17s
Batch 15/24 | Loss: 1.9183 | Time: 0.18s
Batch 16/24 | Loss: 2.0106 | Time: 0.18s
Batch 17/24 | Loss: 2.2120 | Time: 0.20s
Batch 18/24 | Loss: 2.0981 | Time: 0.17s
Batch 19/24 | Loss: 2.0178 | Time: 0.17s
Batch 20/24 | Loss: 1.9514 | Time: 0.17s
Batch 21/24 | Loss: 2.1095 | Time: 0.18s
Batch 22/24 | Loss: 2.1631 | Time: 0.17s
Batch 23/24 | Loss: 2.0674 | Time: 0.17s
Batch 24/24 | Loss: 1.7346 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 2.0775
Validation Loss: 2.9082
Training Time  : 10.10 sec
Validation Time: 2.43 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 2.9082)

================ Epoch 10/50 ================
Batch 01/24 | Loss: 1.8469 | Time: 0.19s
Batch 02/24 | Loss: 2.0630 | Time: 0.17s
Batch 03/24 | Loss: 1.8001 | Time: 0.17s
Batch 04/24 | Loss: 1.8025 | Time: 0.17s
Batch 05/24 | Loss: 1.8434 | Time: 0.17s
Batch 06/24 | Loss: 1.9259 | Time: 0.17s
Batch 07/24 | Loss: 2.0712 | Time: 0.17s
Batch 08/24 | Loss: 1.9246 | Time: 0.17s
Batch 09/24 | Loss: 1.9700 | Time: 0.18s
Batch 10/24 | Loss: 1.8983 | Time: 0.18s
Batch 11/24 | Loss: 1.8791 | Time: 0.17s
Batch 12/24 | Loss: 1.8482 | Time: 0.17s
Batch 13/24 | Loss: 1.8289 | Time: 0.17s
Batch 14/24 | Loss: 1.8619 | Time: 0.17s
Batch 15/24 | Loss: 2.0384 | Time: 0.17s
Batch 16/24 | Loss: 1.8787 | Time: 0.17s
Batch 17/24 | Loss: 1.8604 | Time: 0.19s
Batch 18/24 | Loss: 2.0741 | Time: 0.18s
Batch 19/24 | Loss: 1.9592 | Time: 0.18s
Batch 20/24 | Loss: 1.9484 | Time: 0.18s
Batch 21/24 | Loss: 1.9328 | Time: 0.19s
Batch 22/24 | Loss: 2.0609 | Time: 0.17s
Batch 23/24 | Loss: 1.8693 | Time: 0.17s
Batch 24/24 | Loss: 1.6353 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 1.9092
Validation Loss: 2.9116
Training Time  : 10.26 sec
Validation Time: 2.45 sec
GPU Memory Used: 1.01 GB
No improvement for 1/5 epochs

================ Epoch 11/50 ================
Batch 01/24 | Loss: 1.6648 | Time: 0.20s
Batch 02/24 | Loss: 1.7791 | Time: 0.18s
Batch 03/24 | Loss: 1.7995 | Time: 0.17s
Batch 04/24 | Loss: 1.7264 | Time: 0.17s
Batch 05/24 | Loss: 1.7520 | Time: 0.20s
Batch 06/24 | Loss: 1.8358 | Time: 0.17s
Batch 07/24 | Loss: 1.7435 | Time: 0.17s
Batch 08/24 | Loss: 1.6862 | Time: 0.17s
Batch 09/24 | Loss: 1.6852 | Time: 0.20s
Batch 10/24 | Loss: 1.7756 | Time: 0.18s
Batch 11/24 | Loss: 1.8247 | Time: 0.17s
Batch 12/24 | Loss: 1.7314 | Time: 0.17s
Batch 13/24 | Loss: 1.8239 | Time: 0.19s
Batch 14/24 | Loss: 1.6978 | Time: 0.18s
Batch 15/24 | Loss: 1.7282 | Time: 0.17s
Batch 16/24 | Loss: 1.7894 | Time: 0.17s
Batch 17/24 | Loss: 1.7693 | Time: 0.18s
Batch 18/24 | Loss: 1.7770 | Time: 0.17s
Batch 19/24 | Loss: 1.7664 | Time: 0.18s
Batch 20/24 | Loss: 1.8248 | Time: 0.18s
Batch 21/24 | Loss: 1.7047 | Time: 0.17s
Batch 22/24 | Loss: 1.7867 | Time: 0.17s
Batch 23/24 | Loss: 1.8078 | Time: 0.17s
Batch 24/24 | Loss: 1.5101 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 1.7496
Validation Loss: 2.8871
Training Time  : 10.45 sec
Validation Time: 2.40 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 2.8871)

================ Epoch 12/50 ================
Batch 01/24 | Loss: 1.6548 | Time: 0.21s
Batch 02/24 | Loss: 1.6835 | Time: 0.17s
Batch 03/24 | Loss: 1.6657 | Time: 0.17s
Batch 04/24 | Loss: 1.7402 | Time: 0.17s
Batch 05/24 | Loss: 1.7675 | Time: 0.22s
Batch 06/24 | Loss: 1.5672 | Time: 0.17s
Batch 07/24 | Loss: 1.6826 | Time: 0.17s
Batch 08/24 | Loss: 1.6159 | Time: 0.17s
Batch 09/24 | Loss: 1.7218 | Time: 0.22s
Batch 10/24 | Loss: 1.6137 | Time: 0.18s
Batch 11/24 | Loss: 1.6440 | Time: 0.18s
Batch 12/24 | Loss: 1.6544 | Time: 0.18s
Batch 13/24 | Loss: 1.5889 | Time: 0.19s
Batch 14/24 | Loss: 1.6478 | Time: 0.17s
Batch 15/24 | Loss: 1.7550 | Time: 0.17s
Batch 16/24 | Loss: 1.6659 | Time: 0.17s
Batch 17/24 | Loss: 1.7299 | Time: 0.19s
Batch 18/24 | Loss: 1.6671 | Time: 0.17s
Batch 19/24 | Loss: 1.5319 | Time: 0.17s
Batch 20/24 | Loss: 1.7271 | Time: 0.17s
Batch 21/24 | Loss: 1.6218 | Time: 0.18s
Batch 22/24 | Loss: 1.7612 | Time: 0.17s
Batch 23/24 | Loss: 1.6871 | Time: 0.17s
Batch 24/24 | Loss: 1.3085 | Time: 0.12s

---------------- Summary ----------------
Train Loss     : 1.6543
Validation Loss: 2.8405
Training Time  : 10.19 sec
Validation Time: 2.38 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 2.8405)

================ Epoch 13/50 ================
Batch 01/24 | Loss: 1.5606 | Time: 0.20s
Batch 02/24 | Loss: 1.5694 | Time: 0.17s
Batch 03/24 | Loss: 1.6092 | Time: 0.17s
Batch 04/24 | Loss: 1.5322 | Time: 0.17s
Batch 05/24 | Loss: 1.6197 | Time: 0.19s
Batch 06/24 | Loss: 1.4985 | Time: 0.17s
Batch 07/24 | Loss: 1.5730 | Time: 0.17s
Batch 08/24 | Loss: 1.4438 | Time: 0.17s
Batch 09/24 | Loss: 1.4724 | Time: 0.21s
Batch 10/24 | Loss: 1.5514 | Time: 0.18s
Batch 11/24 | Loss: 1.4418 | Time: 0.17s
Batch 12/24 | Loss: 1.5530 | Time: 0.17s
Batch 13/24 | Loss: 1.4687 | Time: 0.19s
Batch 14/24 | Loss: 1.4609 | Time: 0.17s
Batch 15/24 | Loss: 1.4729 | Time: 0.17s
Batch 16/24 | Loss: 1.4400 | Time: 0.17s
Batch 17/24 | Loss: 1.5271 | Time: 0.17s
Batch 18/24 | Loss: 1.5288 | Time: 0.18s
Batch 19/24 | Loss: 1.5117 | Time: 0.17s
Batch 20/24 | Loss: 1.5180 | Time: 0.18s
Batch 21/24 | Loss: 1.6214 | Time: 0.19s
Batch 22/24 | Loss: 1.6331 | Time: 0.17s
Batch 23/24 | Loss: 1.5738 | Time: 0.17s
Batch 24/24 | Loss: 1.5580 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 1.5308
Validation Loss: 2.8616
Training Time  : 10.11 sec
Validation Time: 2.41 sec
GPU Memory Used: 1.01 GB
No improvement for 1/5 epochs

================ Epoch 14/50 ================
Batch 01/24 | Loss: 1.5404 | Time: 0.22s
Batch 02/24 | Loss: 1.4608 | Time: 0.18s
Batch 03/24 | Loss: 1.5445 | Time: 0.17s
Batch 04/24 | Loss: 1.5516 | Time: 0.18s
Batch 05/24 | Loss: 1.4973 | Time: 0.18s
Batch 06/24 | Loss: 1.5323 | Time: 0.18s
Batch 07/24 | Loss: 1.4723 | Time: 0.17s
Batch 08/24 | Loss: 1.5087 | Time: 0.18s
Batch 09/24 | Loss: 1.4058 | Time: 0.18s
Batch 10/24 | Loss: 1.5318 | Time: 0.17s
Batch 11/24 | Loss: 1.4712 | Time: 0.18s
Batch 12/24 | Loss: 1.3310 | Time: 0.17s
Batch 13/24 | Loss: 1.3991 | Time: 0.17s
Batch 14/24 | Loss: 1.3316 | Time: 0.17s
Batch 15/24 | Loss: 1.4541 | Time: 0.17s
Batch 16/24 | Loss: 1.4687 | Time: 0.17s
Batch 17/24 | Loss: 1.4313 | Time: 0.17s
Batch 18/24 | Loss: 1.3413 | Time: 0.17s
Batch 19/24 | Loss: 1.3276 | Time: 0.17s
Batch 20/24 | Loss: 1.4296 | Time: 0.17s
Batch 21/24 | Loss: 1.4796 | Time: 0.17s
Batch 22/24 | Loss: 1.5227 | Time: 0.17s
Batch 23/24 | Loss: 1.4244 | Time: 0.17s
Batch 24/24 | Loss: 1.2274 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 1.4452
Validation Loss: 2.8213
Training Time  : 10.42 sec
Validation Time: 2.41 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 2.8213)

================ Epoch 15/50 ================
Batch 01/24 | Loss: 1.4616 | Time: 0.24s
Batch 02/24 | Loss: 1.3215 | Time: 0.18s
Batch 03/24 | Loss: 1.3286 | Time: 0.18s
Batch 04/24 | Loss: 1.4080 | Time: 0.18s
Batch 05/24 | Loss: 1.3616 | Time: 0.20s
Batch 06/24 | Loss: 1.5382 | Time: 0.17s
Batch 07/24 | Loss: 1.2721 | Time: 0.18s
Batch 08/24 | Loss: 1.4650 | Time: 0.18s
Batch 09/24 | Loss: 1.3026 | Time: 0.18s
Batch 10/24 | Loss: 1.2674 | Time: 0.18s
Batch 11/24 | Loss: 1.3982 | Time: 0.18s
Batch 12/24 | Loss: 1.4027 | Time: 0.18s
Batch 13/24 | Loss: 1.4537 | Time: 0.18s
Batch 14/24 | Loss: 1.3457 | Time: 0.18s
Batch 15/24 | Loss: 1.3553 | Time: 0.18s
Batch 16/24 | Loss: 1.6101 | Time: 0.17s
Batch 17/24 | Loss: 1.4152 | Time: 0.18s
Batch 18/24 | Loss: 1.3814 | Time: 0.18s
Batch 19/24 | Loss: 1.2701 | Time: 0.17s
Batch 20/24 | Loss: 1.4809 | Time: 0.17s
Batch 21/24 | Loss: 1.5510 | Time: 0.17s
Batch 22/24 | Loss: 1.4445 | Time: 0.17s
Batch 23/24 | Loss: 1.4907 | Time: 0.17s
Batch 24/24 | Loss: 1.1284 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 1.3939
Validation Loss: 2.7879
Training Time  : 10.09 sec
Validation Time: 2.40 sec
GPU Memory Used: 1.01 GB
✓ Best model saved(Val Loss: 2.7879)

================ Epoch 16/50 ================
Batch 01/24 | Loss: 1.3751 | Time: 0.22s
Batch 02/24 | Loss: 1.2716 | Time: 0.18s
Batch 03/24 | Loss: 1.3115 | Time: 0.17s
Batch 04/24 | Loss: 1.2993 | Time: 0.17s
Batch 05/24 | Loss: 1.3043 | Time: 0.18s
Batch 06/24 | Loss: 1.3834 | Time: 0.18s
Batch 07/24 | Loss: 1.3469 | Time: 0.18s
Batch 08/24 | Loss: 1.3982 | Time: 0.18s
Batch 09/24 | Loss: 1.2640 | Time: 0.18s
Batch 10/24 | Loss: 1.3134 | Time: 0.17s
Batch 11/24 | Loss: 1.3463 | Time: 0.17s
Batch 12/24 | Loss: 1.2574 | Time: 0.18s
Batch 13/24 | Loss: 1.3497 | Time: 0.18s
Batch 14/24 | Loss: 1.3413 | Time: 0.18s
Batch 15/24 | Loss: 1.3265 | Time: 0.18s
Batch 16/24 | Loss: 1.2769 | Time: 0.18s
Batch 17/24 | Loss: 1.3317 | Time: 0.18s
Batch 18/24 | Loss: 1.4285 | Time: 0.18s
Batch 19/24 | Loss: 1.3688 | Time: 0.18s
Batch 20/24 | Loss: 1.2928 | Time: 0.18s
Batch 21/24 | Loss: 1.2214 | Time: 0.17s
Batch 22/24 | Loss: 1.3481 | Time: 0.17s
Batch 23/24 | Loss: 1.3350 | Time: 0.17s
Batch 24/24 | Loss: 1.0415 | Time: 0.13s

---------------- Summary ----------------
Train Loss     : 1.3139
Validation Loss: 2.7880
Training Time  : 10.22 sec
Validation Time: 2.41 sec
GPU Memory Used: 1.01 GB
No improvement for 1/5 epochs

================ Epoch 17/50 ================
Batch 01/24 | Loss: 1.2787 | Time: 0.20s

      Metric  Image→Text  Text→Image
0   Recall@1    0.228261    0.169565
1   Recall@5    0.505929    0.428063
2  Recall@10    0.628458    0.566008
3        MRR    0.359684    0.294560

Memory after cleanup
Allocated: 0.3173823356628418
Reserved: 2.037109375

************************

Processing - flickr30k

************************

Train: 23837 | Val: 3973 | Test: 3973

================ Epoch 1/50 ================
Batch 01/94 | Loss: 5.5949 | Time: 0.20s
Batch 02/94 | Loss: 5.6376 | Time: 0.17s
Batch 03/94 | Loss: 5.5618 | Time: 0.17s
Batch 04/94 | Loss: 5.5682 | Time: 0.17s
Batch 05/94 | Loss: 5.5514 | Time: 0.20s
Batch 06/94 | Loss: 5.5181 | Time: 0.18s
Batch 07/94 | Loss: 5.5296 | Time: 0.18s
Batch 08/94 | Loss: 5.4917 | Time: 0.18s
Batch 09/94 | Loss: 5.4812 | Time: 0.21s
Batch 10/94 | Loss: 5.4780 | Time: 0.18s
Batch 11/94 | Loss: 5.4062 | Time: 0.18s
Batch 12/94 | Loss: 5.4205 | Time: 0.17s
Batch 13/94 | Loss: 5.4005 | Time: 0.21s
Batch 14/94 | Loss: 5.3570 | Time: 0.19s
Batch 15/94 | Loss: 5.2885 | Time: 0.18s
Batch 16/94 | Loss: 5.2277 | Time: 0.18s
Batch 17/94 | Loss: 5.2235 | Time: 0.17s
Batch 18/94 | Loss: 5.2163 | Time: 0.17s
Batch 19/94 | Loss: 5.1155 | Time: 0.17s
Batch 20/94 | Loss: 5.2326 | Time: 0.17s
Batch 21/94 | Loss: 5.2061 | Time: 0.17s
Batch 22/94 | Loss: 5.1232 | Time: 0.17s
Batch 23/94 | Loss: 5.0435 | Time: 0.17s
Batch 24/94 | Loss: 5.0255 | Time: 0.18s
Batch 25/94 | Loss: 5.0723 | Time: 0.17s
Batch 26/94 | Loss: 4.9642 | Time: 0.17s
Batch 27/94 | Loss: 4.9565 | Time: 0.17s
Batch 28/94 | Loss: 5.0141 | Time: 0.17s
Batch 29/94 | Loss: 4.9738 | Time: 0.17s
Batch 30/94 | Loss: 4.8552 | Time: 0.17s
Batch 31/94 | Loss: 4.8630 | Time: 0.18s
Batch 32/94 | Loss: 4.8032 | Time: 0.17s
Batch 33/94 | Loss: 4.7573 | Time: 0.17s
Batch 34/94 | Loss: 4.9070 | Time: 0.18s
Batch 35/94 | Loss: 4.8155 | Time: 0.17s
Batch 36/94 | Loss: 4.7742 | Time: 0.17s
Batch 37/94 | Loss: 4.7589 | Time: 0.18s
Batch 38/94 | Loss: 4.7138 | Time: 0.18s
Batch 39/94 | Loss: 4.7372 | Time: 0.17s
Batch 40/94 | Loss: 4.7033 | Time: 0.17s
Batch 41/94 | Loss: 4.7337 | Time: 0.17s
Batch 42/94 | Loss: 4.6603 | Time: 0.17s
Batch 43/94 | Loss: 4.6409 | Time: 0.18s
Batch 44/94 | Loss: 4.7174 | Time: 0.18s
Batch 45/94 | Loss: 4.7037 | Time: 0.18s
Batch 46/94 | Loss: 4.4604 | Time: 0.18s
Batch 47/94 | Loss: 4.5814 | Time: 0.18s
Batch 48/94 | Loss: 4.6361 | Time: 0.17s
Batch 49/94 | Loss: 4.6411 | Time: 0.18s
Batch 50/94 | Loss: 4.4879 | Time: 0.18s
Batch 51/94 | Loss: 4.5257 | Time: 0.18s
Batch 52/94 | Loss: 4.4081 | Time: 0.18s
Batch 53/94 | Loss: 4.3342 | Time: 0.21s
Batch 54/94 | Loss: 4.5561 | Time: 0.17s
Batch 55/94 | Loss: 4.3878 | Time: 0.17s
Batch 56/94 | Loss: 4.3798 | Time: 0.17s
Batch 57/94 | Loss: 4.3904 | Time: 0.19s
Batch 58/94 | Loss: 4.5292 | Time: 0.18s
Batch 59/94 | Loss: 4.4079 | Time: 0.18s
Batch 60/94 | Loss: 4.4002 | Time: 0.18s
Batch 61/94 | Loss: 4.5141 | Time: 0.19s
Batch 62/94 | Loss: 4.4035 | Time: 0.18s
Batch 63/94 | Loss: 4.3993 | Time: 0.18s
Batch 64/94 | Loss: 4.5491 | Time: 0.19s
Batch 65/94 | Loss: 4.4080 | Time: 0.21s
Batch 66/94 | Loss: 4.3892 | Time: 0.17s
Batch 67/94 | Loss: 4.2986 | Time: 0.17s
Batch 68/94 | Loss: 4.3662 | Time: 0.17s
Batch 69/94 | Loss: 4.4584 | Time: 0.21s
Batch 70/94 | Loss: 4.2727 | Time: 0.17s
Batch 71/94 | Loss: 4.4357 | Time: 0.17s
Batch 72/94 | Loss: 4.3713 | Time: 0.18s
Batch 73/94 | Loss: 4.3637 | Time: 0.20s
Batch 74/94 | Loss: 4.1744 | Time: 0.18s
Batch 75/94 | Loss: 4.3093 | Time: 0.18s
Batch 76/94 | Loss: 4.2864 | Time: 0.18s
Batch 77/94 | Loss: 4.3120 | Time: 0.19s
Batch 78/94 | Loss: 4.2022 | Time: 0.18s
Batch 79/94 | Loss: 4.2405 | Time: 0.18s
Batch 80/94 | Loss: 4.1672 | Time: 0.17s
Batch 81/94 | Loss: 4.3024 | Time: 0.18s
Batch 82/94 | Loss: 4.3598 | Time: 0.18s
Batch 83/94 | Loss: 4.1074 | Time: 0.17s
Batch 84/94 | Loss: 4.0654 | Time: 0.17s
Batch 85/94 | Loss: 4.1088 | Time: 0.17s
Batch 86/94 | Loss: 4.3177 | Time: 0.17s
Batch 87/94 | Loss: 4.2351 | Time: 0.17s
Batch 88/94 | Loss: 4.0798 | Time: 0.17s
Batch 89/94 | Loss: 4.2122 | Time: 0.17s
Batch 90/94 | Loss: 4.2438 | Time: 0.17s
Batch 91/94 | Loss: 4.0470 | Time: 0.17s
Batch 92/94 | Loss: 4.0625 | Time: 0.17s
Batch 93/94 | Loss: 3.9508 | Time: 0.18s
Batch 94/94 | Loss: 1.6995 | Time: 0.04s

---------------- Summary ----------------
Train Loss     : 4.6773
Validation Loss: 3.9183
Training Time  : 37.13 sec
Validation Time: 6.93 sec
GPU Memory Used: 0.94 GB
✓ Best model saved(Val Loss: 3.9183)

================ Epoch 2/50 ================
Batch 01/94 | Loss: 4.0960 | Time: 0.24s
Batch 02/94 | Loss: 3.8170 | Time: 0.18s
Batch 03/94 | Loss: 4.0178 | Time: 0.17s
Batch 04/94 | Loss: 3.8473 | Time: 0.17s
Batch 05/94 | Loss: 3.9674 | Time: 0.17s
Batch 06/94 | Loss: 4.0400 | Time: 0.17s
Batch 07/94 | Loss: 3.8949 | Time: 0.17s
Batch 08/94 | Loss: 3.9304 | Time: 0.18s
Batch 09/94 | Loss: 3.9703 | Time: 0.18s
Batch 10/94 | Loss: 4.0396 | Time: 0.18s
Batch 11/94 | Loss: 3.9417 | Time: 0.18s
Batch 12/94 | Loss: 3.8334 | Time: 0.17s
Batch 13/94 | Loss: 3.7602 | Time: 0.17s
Batch 14/94 | Loss: 3.8322 | Time: 0.18s
Batch 15/94 | Loss: 3.8506 | Time: 0.18s
Batch 16/94 | Loss: 3.7628 | Time: 0.17s
Batch 17/94 | Loss: 3.8334 | Time: 0.18s
Batch 18/94 | Loss: 3.9574 | Time: 0.17s
Batch 19/94 | Loss: 3.9734 | Time: 0.18s
Batch 20/94 | Loss: 3.8597 | Time: 0.17s
Batch 21/94 | Loss: 3.8251 | Time: 0.17s
Batch 22/94 | Loss: 3.9085 | Time: 0.17s
Batch 23/94 | Loss: 3.8735 | Time: 0.18s
Batch 24/94 | Loss: 3.8151 | Time: 0.18s
Batch 25/94 | Loss: 3.6783 | Time: 0.23s
Batch 26/94 | Loss: 3.7487 | Time: 0.17s
Batch 27/94 | Loss: 3.8548 | Time: 0.17s
Batch 28/94 | Loss: 3.7255 | Time: 0.18s
Batch 29/94 | Loss: 3.8239 | Time: 0.21s
Batch 30/94 | Loss: 3.7449 | Time: 0.18s
Batch 31/94 | Loss: 3.8992 | Time: 0.18s
Batch 32/94 | Loss: 3.9104 | Time: 0.18s
Batch 33/94 | Loss: 3.8453 | Time: 0.18s
Batch 34/94 | Loss: 3.8250 | Time: 0.19s
Batch 35/94 | Loss: 3.6577 | Time: 0.18s
Batch 36/94 | Loss: 3.7472 | Time: 0.18s
Batch 37/94 | Loss: 3.7140 | Time: 0.19s
Batch 38/94 | Loss: 3.7550 | Time: 0.17s
Batch 39/94 | Loss: 3.6954 | Time: 0.18s
Batch 40/94 | Loss: 3.6648 | Time: 0.18s
Batch 41/94 | Loss: 3.6386 | Time: 0.20s
Batch 42/94 | Loss: 3.6808 | Time: 0.18s
Batch 43/94 | Loss: 3.7884 | Time: 0.18s
Batch 44/94 | Loss: 3.7216 | Time: 0.18s
Batch 45/94 | Loss: 3.7572 | Time: 0.25s
Batch 46/94 | Loss: 3.6839 | Time: 0.18s
Batch 47/94 | Loss: 3.6213 | Time: 0.17s
Batch 48/94 | Loss: 3.7370 | Time: 0.17s
Batch 49/94 | Loss: 3.6275 | Time: 0.22s
Batch 50/94 | Loss: 3.8749 | Time: 0.17s
Batch 51/94 | Loss: 3.6731 | Time: 0.17s
Batch 52/94 | Loss: 3.8310 | Time: 0.17s
Batch 53/94 | Loss: 3.6484 | Time: 0.20s
Batch 54/94 | Loss: 3.6163 | Time: 0.18s
Batch 55/94 | Loss: 3.6981 | Time: 0.17s
Batch 56/94 | Loss: 3.5284 | Time: 0.17s
Batch 57/94 | Loss: 3.6049 | Time: 0.17s
Batch 58/94 | Loss: 3.5445 | Time: 0.17s
Batch 59/94 | Loss: 3.6427 | Time: 0.18s
Batch 60/94 | Loss: 3.5314 | Time: 0.17s
Batch 61/94 | Loss: 3.7318 | Time: 0.20s
Batch 62/94 | Loss: 3.5385 | Time: 0.18s
Batch 63/94 | Loss: 3.5312 | Time: 0.18s
Batch 64/94 | Loss: 3.7126 | Time: 0.18s
Batch 65/94 | Loss: 3.5127 | Time: 0.19s
Batch 66/94 | Loss: 3.5403 | Time: 0.18s
Batch 67/94 | Loss: 3.4935 | Time: 0.17s
Batch 68/94 | Loss: 3.6151 | Time: 0.19s
Batch 69/94 | Loss: 3.5764 | Time: 0.20s
Batch 70/94 | Loss: 3.5211 | Time: 0.17s
Batch 71/94 | Loss: 3.5950 | Time: 0.18s
Batch 72/94 | Loss: 3.5105 | Time: 0.17s
Batch 73/94 | Loss: 3.5099 | Time: 0.17s
Batch 74/94 | Loss: 3.6919 | Time: 0.17s
Batch 75/94 | Loss: 3.6271 | Time: 0.17s
Batch 76/94 | Loss: 3.7188 | Time: 0.17s
Batch 77/94 | Loss: 3.4763 | Time: 0.17s
Batch 78/94 | Loss: 3.5488 | Time: 0.17s
Batch 79/94 | Loss: 3.7778 | Time: 0.18s
Batch 80/94 | Loss: 3.4502 | Time: 0.18s
Batch 81/94 | Loss: 3.4353 | Time: 0.17s
Batch 82/94 | Loss: 3.4386 | Time: 0.17s
Batch 83/94 | Loss: 3.4617 | Time: 0.17s
Batch 84/94 | Loss: 3.6182 | Time: 0.17s
Batch 85/94 | Loss: 3.6516 | Time: 0.17s
Batch 86/94 | Loss: 3.5858 | Time: 0.18s
Batch 87/94 | Loss: 3.6730 | Time: 0.18s
Batch 88/94 | Loss: 3.4911 | Time: 0.18s
Batch 89/94 | Loss: 3.4844 | Time: 0.17s
Batch 90/94 | Loss: 3.6407 | Time: 0.17s
Batch 91/94 | Loss: 3.6489 | Time: 0.17s
Batch 92/94 | Loss: 3.4442 | Time: 0.17s
Batch 93/94 | Loss: 3.6168 | Time: 0.17s
Batch 94/94 | Loss: 1.8677 | Time: 0.05s

---------------- Summary ----------------
Train Loss     : 3.6928
Validation Loss: 3.3593
Training Time  : 36.86 sec
Validation Time: 7.05 sec
GPU Memory Used: 0.94 GB
✓ Best model saved(Val Loss: 3.3593)

================ Epoch 3/50 ================
Batch 01/94 | Loss: 3.4442 | Time: 0.24s
Batch 02/94 | Loss: 3.3837 | Time: 0.19s
Batch 03/94 | Loss: 3.4615 | Time: 0.17s
Batch 04/94 | Loss: 3.2040 | Time: 0.17s
Batch 05/94 | Loss: 3.4049 | Time: 0.20s
Batch 06/94 | Loss: 3.4843 | Time: 0.17s
Batch 07/94 | Loss: 3.1955 | Time: 0.17s
Batch 08/94 | Loss: 3.3746 | Time: 0.17s
Batch 09/94 | Loss: 3.3210 | Time: 0.20s
Batch 10/94 | Loss: 3.2143 | Time: 0.18s
Batch 11/94 | Loss: 3.3726 | Time: 0.18s
Batch 12/94 | Loss: 3.3122 | Time: 0.18s
Batch 13/94 | Loss: 3.3122 | Time: 0.22s
Batch 14/94 | Loss: 3.3580 | Time: 0.18s
Batch 15/94 | Loss: 3.2407 | Time: 0.17s
Batch 16/94 | Loss: 3.4285 | Time: 0.17s
Batch 17/94 | Loss: 3.1356 | Time: 0.22s
Batch 18/94 | Loss: 3.2455 | Time: 0.18s
Batch 19/94 | Loss: 3.1298 | Time: 0.18s
Batch 20/94 | Loss: 3.2075 | Time: 0.18s
Batch 21/94 | Loss: 3.2349 | Time: 0.20s
Batch 22/94 | Loss: 3.2852 | Time: 0.18s
Batch 23/94 | Loss: 3.3395 | Time: 0.18s
Batch 24/94 | Loss: 3.3208 | Time: 0.18s
Batch 25/94 | Loss: 3.3106 | Time: 0.21s
Batch 26/94 | Loss: 3.3639 | Time: 0.18s
Batch 27/94 | Loss: 3.2679 | Time: 0.19s
Batch 28/94 | Loss: 3.2537 | Time: 0.18s
Batch 29/94 | Loss: 3.1933 | Time: 0.20s
Batch 30/94 | Loss: 3.2250 | Time: 0.18s
Batch 31/94 | Loss: 3.0900 | Time: 0.18s
Batch 32/94 | Loss: 3.2804 | Time: 0.19s
Batch 33/94 | Loss: 3.3229 | Time: 0.25s
Batch 34/94 | Loss: 3.2340 | Time: 0.18s
Batch 35/94 | Loss: 3.1718 | Time: 0.18s
Batch 36/94 | Loss: 3.0285 | Time: 0.18s
Batch 37/94 | Loss: 3.2525 | Time: 0.19s
Batch 38/94 | Loss: 3.3252 | Time: 0.18s
Batch 39/94 | Loss: 3.0581 | Time: 0.18s
Batch 40/94 | Loss: 3.4546 | Time: 0.18s
Batch 41/94 | Loss: 3.4191 | Time: 0.21s
Batch 42/94 | Loss: 3.0384 | Time: 0.18s
Batch 43/94 | Loss: 3.2559 | Time: 0.18s
Batch 44/94 | Loss: 3.1376 | Time: 0.17s
Batch 45/94 | Loss: 3.2128 | Time: 0.17s
Batch 46/94 | Loss: 3.1308 | Time: 0.18s
Batch 47/94 | Loss: 3.2542 | Time: 0.18s
Batch 48/94 | Loss: 3.2623 | Time: 0.19s
Batch 49/94 | Loss: 3.0782 | Time: 0.23s
Batch 50/94 | Loss: 3.1538 | Time: 0.18s
Batch 51/94 | Loss: 2.9985 | Time: 0.18s
Batch 52/94 | Loss: 3.2008 | Time: 0.18s
Batch 53/94 | Loss: 3.1168 | Time: 0.21s
Batch 54/94 | Loss: 3.1250 | Time: 0.18s
Batch 55/94 | Loss: 3.1275 | Time: 0.17s
Batch 56/94 | Loss: 3.3210 | Time: 0.18s
Batch 57/94 | Loss: 3.1494 | Time: 0.20s
Batch 58/94 | Loss: 3.1064 | Time: 0.17s
Batch 59/94 | Loss: 3.2905 | Time: 0.18s
Batch 60/94 | Loss: 3.2361 | Time: 0.17s
Batch 61/94 | Loss: 3.3052 | Time: 0.20s
Batch 62/94 | Loss: 3.2182 | Time: 0.17s
Batch 63/94 | Loss: 3.3107 | Time: 0.17s
Batch 64/94 | Loss: 3.2151 | Time: 0.18s
Batch 65/94 | Loss: 3.2839 | Time: 0.17s
Batch 66/94 | Loss: 2.9943 | Time: 0.17s
Batch 67/94 | Loss: 3.1973 | Time: 0.17s
Batch 68/94 | Loss: 3.0091 | Time: 0.17s
Batch 69/94 | Loss: 3.2674 | Time: 0.20s
Batch 70/94 | Loss: 2.8726 | Time: 0.17s
Batch 71/94 | Loss: 3.1014 | Time: 0.17s
Batch 72/94 | Loss: 2.9710 | Time: 0.18s
Batch 73/94 | Loss: 3.0748 | Time: 0.19s
Batch 74/94 | Loss: 3.2869 | Time: 0.19s
Batch 75/94 | Loss: 3.2633 | Time: 0.18s
Batch 76/94 | Loss: 3.2206 | Time: 0.18s
Batch 77/94 | Loss: 3.1464 | Time: 0.20s
Batch 78/94 | Loss: 3.1428 | Time: 0.18s
Batch 79/94 | Loss: 2.9421 | Time: 0.19s
Batch 80/94 | Loss: 3.0005 | Time: 0.18s
Batch 81/94 | Loss: 3.2476 | Time: 0.25s
Batch 82/94 | Loss: 3.0810 | Time: 0.18s
Batch 83/94 | Loss: 2.9820 | Time: 0.19s
Batch 84/94 | Loss: 3.1506 | Time: 0.18s
Batch 85/94 | Loss: 3.1272 | Time: 0.18s
Batch 86/94 | Loss: 3.0260 | Time: 0.18s
Batch 87/94 | Loss: 3.2296 | Time: 0.18s
Batch 88/94 | Loss: 3.0874 | Time: 0.17s
Batch 89/94 | Loss: 2.9721 | Time: 0.18s
Batch 90/94 | Loss: 3.1920 | Time: 0.19s
Batch 91/94 | Loss: 3.1885 | Time: 0.17s
Batch 92/94 | Loss: 3.0816 | Time: 0.17s
Batch 93/94 | Loss: 3.0039 | Time: 0.17s
Batch 94/94 | Loss: 1.6262 | Time: 0.05s

---------------- Summary ----------------
Train Loss     : 3.1881
Validation Loss: 3.0518
Training Time  : 37.34 sec
Validation Time: 6.79 sec
GPU Memory Used: 0.94 GB
✓ Best model saved(Val Loss: 3.0518)

================ Epoch 4/50 ================
Batch 01/94 | Loss: 2.7792 | Time: 0.24s
Batch 02/94 | Loss: 2.9856 | Time: 0.18s
Batch 03/94 | Loss: 2.7494 | Time: 0.18s
Batch 04/94 | Loss: 2.8135 | Time: 0.18s
Batch 05/94 | Loss: 2.7928 | Time: 0.20s
Batch 06/94 | Loss: 2.8809 | Time: 0.18s
Batch 07/94 | Loss: 3.0171 | Time: 0.19s
Batch 08/94 | Loss: 2.8139 | Time: 0.18s
Batch 09/94 | Loss: 2.9880 | Time: 0.18s
Batch 10/94 | Loss: 2.8535 | Time: 0.18s
Batch 11/94 | Loss: 2.7538 | Time: 0.18s
Batch 12/94 | Loss: 2.7623 | Time: 0.18s
Batch 13/94 | Loss: 3.1012 | Time: 0.18s
Batch 14/94 | Loss: 2.7889 | Time: 0.18s
Batch 15/94 | Loss: 2.6812 | Time: 0.19s
Batch 16/94 | Loss: 2.8341 | Time: 0.18s
Batch 17/94 | Loss: 2.7624 | Time: 0.17s
Batch 18/94 | Loss: 2.6888 | Time: 0.17s
Batch 19/94 | Loss: 2.8472 | Time: 0.17s
Batch 20/94 | Loss: 2.7719 | Time: 0.17s
Batch 21/94 | Loss: 2.7057 | Time: 0.17s
Batch 22/94 | Loss: 3.0323 | Time: 0.18s
Batch 23/94 | Loss: 2.7015 | Time: 0.17s
Batch 24/94 | Loss: 2.8841 | Time: 0.17s
Batch 25/94 | Loss: 2.7632 | Time: 0.18s
Batch 26/94 | Loss: 2.7942 | Time: 0.18s
Batch 27/94 | Loss: 2.7872 | Time: 0.18s
Batch 28/94 | Loss: 2.9576 | Time: 0.18s
Batch 29/94 | Loss: 2.7129 | Time: 0.19s
Batch 30/94 | Loss: 2.8584 | Time: 0.19s
Batch 31/94 | Loss: 2.7690 | Time: 0.18s
Batch 32/94 | Loss: 2.8967 | Time: 0.18s
Batch 33/94 | Loss: 2.8463 | Time: 0.18s
Batch 34/94 | Loss: 2.7346 | Time: 0.18s
Batch 35/94 | Loss: 2.7273 | Time: 0.18s
Batch 36/94 | Loss: 2.9095 | Time: 0.18s
Batch 37/94 | Loss: 2.6985 | Time: 0.21s
Batch 38/94 | Loss: 3.0176 | Time: 0.18s
Batch 39/94 | Loss: 2.7382 | Time: 0.18s
Batch 40/94 | Loss: 2.6949 | Time: 0.18s
Batch 41/94 | Loss: 2.7006 | Time: 0.18s
Batch 42/94 | Loss: 2.7259 | Time: 0.18s
Batch 43/94 | Loss: 3.0323 | Time: 0.18s
Batch 44/94 | Loss: 2.7455 | Time: 0.18s
Batch 45/94 | Loss: 2.8208 | Time: 0.21s
Batch 46/94 | Loss: 2.7017 | Time: 0.18s
Batch 47/94 | Loss: 2.9853 | Time: 0.18s
Batch 48/94 | Loss: 2.9506 | Time: 0.18s
Batch 49/94 | Loss: 2.8920 | Time: 0.21s
Batch 50/94 | Loss: 2.8657 | Time: 0.18s
Batch 51/94 | Loss: 2.8522 | Time: 0.17s
Batch 52/94 | Loss: 3.0455 | Time: 0.17s
Batch 53/94 | Loss: 2.9047 | Time: 0.19s
Batch 54/94 | Loss: 2.6424 | Time: 0.17s
Batch 55/94 | Loss: 2.8446 | Time: 0.18s
Batch 56/94 | Loss: 2.9117 | Time: 0.18s
Batch 57/94 | Loss: 2.9194 | Time: 0.22s
Batch 58/94 | Loss: 2.7895 | Time: 0.19s
Batch 59/94 | Loss: 2.8606 | Time: 0.18s
Batch 60/94 | Loss: 2.6417 | Time: 0.18s
Batch 61/94 | Loss: 2.8442 | Time: 0.18s
Batch 62/94 | Loss: 2.7289 | Time: 0.18s
Batch 63/94 | Loss: 2.8357 | Time: 0.18s
Batch 64/94 | Loss: 2.8171 | Time: 0.18s
Batch 65/94 | Loss: 2.6782 | Time: 0.22s
Batch 66/94 | Loss: 2.9089 | Time: 0.19s
Batch 67/94 | Loss: 2.7789 | Time: 0.19s
Batch 68/94 | Loss: 2.9049 | Time: 0.19s
Batch 69/94 | Loss: 2.9061 | Time: 0.21s
Batch 70/94 | Loss: 2.7558 | Time: 0.18s
Batch 71/94 | Loss: 2.8364 | Time: 0.18s
Batch 72/94 | Loss: 2.7301 | Time: 0.18s
Batch 73/94 | Loss: 2.8156 | Time: 0.22s
Batch 74/94 | Loss: 2.7924 | Time: 0.18s
Batch 75/94 | Loss: 2.8125 | Time: 0.18s
Batch 76/94 | Loss: 2.6368 | Time: 0.18s
Batch 77/94 | Loss: 2.6747 | Time: 0.21s
Batch 78/94 | Loss: 2.7443 | Time: 0.18s
Batch 79/94 | Loss: 2.9505 | Time: 0.18s
Batch 80/94 | Loss: 2.6898 | Time: 0.18s
Batch 81/94 | Loss: 2.6105 | Time: 0.23s
Batch 82/94 | Loss: 2.7639 | Time: 0.17s
Batch 83/94 | Loss: 2.8365 | Time: 0.17s
Batch 84/94 | Loss: 2.7301 | Time: 0.18s
Batch 85/94 | Loss: 2.6783 | Time: 0.22s
Batch 86/94 | Loss: 2.8642 | Time: 0.17s
Batch 87/94 | Loss: 3.0606 | Time: 0.17s
Batch 88/94 | Loss: 2.8918 | Time: 0.18s
Batch 89/94 | Loss: 2.6601 | Time: 0.19s
Batch 90/94 | Loss: 2.8957 | Time: 0.18s
Batch 91/94 | Loss: 2.8866 | Time: 0.17s
Batch 92/94 | Loss: 2.6496 | Time: 0.18s
Batch 93/94 | Loss: 2.7527 | Time: 0.17s
Batch 94/94 | Loss: 1.0030 | Time: 0.04s

---------------- Summary ----------------
Train Loss     : 2.7963
Validation Loss: 2.8427
Training Time  : 37.15 sec
Validation Time: 6.85 sec
GPU Memory Used: 0.94 GB
✓ Best model saved(Val Loss: 2.8427)

================ Epoch 5/50 ================
Batch 01/94 | Loss: 2.5815 | Time: 0.20s
Batch 02/94 | Loss: 2.6626 | Time: 0.19s
Batch 03/94 | Loss: 2.6814 | Time: 0.18s
Batch 04/94 | Loss: 2.4552 | Time: 0.18s
Batch 05/94 | Loss: 2.6699 | Time: 0.18s
Batch 06/94 | Loss: 2.6894 | Time: 0.18s
Batch 07/94 | Loss: 2.6894 | Time: 0.17s
Batch 08/94 | Loss: 2.6504 | Time: 0.17s
Batch 09/94 | Loss: 2.5711 | Time: 0.17s
Batch 10/94 | Loss: 2.5833 | Time: 0.17s
Batch 11/94 | Loss: 2.6414 | Time: 0.17s
Batch 12/94 | Loss: 2.6393 | Time: 0.17s
Batch 13/94 | Loss: 2.5835 | Time: 0.18s
Batch 14/94 | Loss: 2.5638 | Time: 0.18s
Batch 15/94 | Loss: 2.5094 | Time: 0.18s
Batch 16/94 | Loss: 2.5790 | Time: 0.17s
Batch 17/94 | Loss: 2.6106 | Time: 0.17s
Batch 18/94 | Loss: 2.3958 | Time: 0.17s
Batch 19/94 | Loss: 2.4862 | Time: 0.17s
Batch 20/94 | Loss: 2.5638 | Time: 0.17s
Batch 21/94 | Loss: 2.5696 | Time: 0.18s
Batch 22/94 | Loss: 2.5910 | Time: 0.18s
Batch 23/94 | Loss: 2.5308 | Time: 0.17s
Batch 24/94 | Loss: 2.5274 | Time: 0.17s
Batch 25/94 | Loss: 2.5816 | Time: 0.20s
Batch 26/94 | Loss: 2.4590 | Time: 0.18s
Batch 27/94 | Loss: 2.6001 | Time: 0.18s
Batch 28/94 | Loss: 2.4933 | Time: 0.18s
Batch 29/94 | Loss: 2.8383 | Time: 0.18s
Batch 30/94 | Loss: 2.5626 | Time: 0.18s
Batch 31/94 | Loss: 2.4705 | Time: 0.18s
Batch 32/94 | Loss: 2.5194 | Time: 0.18s
Batch 33/94 | Loss: 2.5304 | Time: 0.18s
Batch 34/94 | Loss: 2.6624 | Time: 0.17s
Batch 35/94 | Loss: 2.6016 | Time: 0.17s
Batch 36/94 | Loss: 2.4624 | Time: 0.17s
Batch 37/94 | Loss: 2.5359 | Time: 0.19s
Batch 38/94 | Loss: 2.4366 | Time: 0.17s
Batch 39/94 | Loss: 2.5335 | Time: 0.18s
Batch 40/94 | Loss: 2.5542 | Time: 0.17s
Batch 41/94 | Loss: 2.4587 | Time: 0.18s
Batch 42/94 | Loss: 2.3846 | Time: 0.17s
Batch 43/94 | Loss: 2.4345 | Time: 0.17s
Batch 44/94 | Loss: 2.6008 | Time: 0.18s
Batch 45/94 | Loss: 2.6709 | Time: 0.17s
Batch 46/94 | Loss: 2.4184 | Time: 0.17s
Batch 47/94 | Loss: 2.6112 | Time: 0.17s
Batch 48/94 | Loss: 2.6508 | Time: 0.18s
Batch 49/94 | Loss: 2.5266 | Time: 0.18s
Batch 50/94 | Loss: 2.6584 | Time: 0.18s
Batch 51/94 | Loss: 2.4720 | Time: 0.18s
Batch 52/94 | Loss: 2.5509 | Time: 0.18s
Batch 53/94 | Loss: 2.4667 | Time: 0.19s
Batch 54/94 | Loss: 2.4628 | Time: 0.18s
Batch 55/94 | Loss: 2.5961 | Time: 0.18s
Batch 56/94 | Loss: 2.5401 | Time: 0.18s
Batch 57/94 | Loss: 2.3456 | Time: 0.17s
Batch 58/94 | Loss: 2.5235 | Time: 0.17s
Batch 59/94 | Loss: 2.5169 | Time: 0.18s
Batch 60/94 | Loss: 2.4767 | Time: 0.18s
Batch 61/94 | Loss: 2.4786 | Time: 0.17s
Batch 62/94 | Loss: 2.4788 | Time: 0.18s
Batch 63/94 | Loss: 2.4049 | Time: 0.18s
Batch 64/94 | Loss: 2.5299 | Time: 0.17s
Batch 65/94 | Loss: 2.7890 | Time: 0.18s
Batch 66/94 | Loss: 2.4746 | Time: 0.18s
Batch 67/94 | Loss: 2.5291 | Time: 0.18s
Batch 68/94 | Loss: 2.4206 | Time: 0.19s
Batch 69/94 | Loss: 2.6375 | Time: 0.17s
Batch 70/94 | Loss: 2.6537 | Time: 0.17s
Batch 71/94 | Loss: 2.3973 | Time: 0.18s
Batch 72/94 | Loss: 2.6484 | Time: 0.17s
Batch 73/94 | Loss: 2.5675 | Time: 0.18s
Batch 74/94 | Loss: 2.4887 | Time: 0.18s
Batch 75/94 | Loss: 2.6620 | Time: 0.17s
Batch 76/94 | Loss: 2.4460 | Time: 0.17s
Batch 77/94 | Loss: 2.6115 | Time: 0.18s
Batch 78/94 | Loss: 2.5120 | Time: 0.19s
Batch 79/94 | Loss: 2.5975 | Time: 0.18s
Batch 80/94 | Loss: 2.4534 | Time: 0.18s
Batch 81/94 | Loss: 2.5290 | Time: 0.19s

      Metric  Image→Text  Text→Image
0   Recall@1    0.148251    0.113667
1   Recall@5    0.378555    0.295293
2  Recall@10    0.492827    0.403927
3        MRR    0.259886    0.206854

Memory after cleanup
Allocated: 0.3283367156982422
Reserved: 1.548828125