In [99]:
from google.colab import drive
import pickle
import pandas as pd
from collections import defaultdict
import random
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image
import os
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
import timm
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [100]:
!pip install rouge_score

Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (4.67.3)

In [101]:
!pip install pycocoevalcap

Requirement already satisfied: pycocoevalcap in /usr/local/lib/python3.12/dist-packages (1.2)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from pycocoevalcap) (2.0.11)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pycocotools>=2.0.2->pycocoevalcap) (2.0.2)

In [102]:
import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [103]:
from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer

from pycocoevalcap.cider.cider import Cider
from pycocoevalcap.spice.spice import Spice

import pandas as pd
import torch

In [104]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda

In [105]:
# Copying 8k to Colabs local SSD
if not os.path.exists("/content/flickr8k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr8k.zip" /content/

In [106]:
if not os.path.isdir("/content/flickr8k/Images"):
  !unzip "/content/flickr8k.zip" -d "/content/flickr8k"

In [107]:
print("Images:", len(os.listdir("/content/flickr8k/Images")))

Images: 8091

In [108]:
# Copying 30k to Colabs local SSD
if not os.path.exists("/content/flickr30k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr30k.zip" /content/

In [109]:
if not os.path.isdir("/content/flickr30k/Images"):
  !unzip "/content/flickr30k.zip" -d "/content/flickr30k"

In [110]:
print("Images:", len(os.listdir("/content/flickr30k/Images")))

Images: 31811

In [111]:
DATASETS = {
    "flickr8k": {
        "ROOT": "/content/flickr8k",
        "IMAGE_DIR": "/content/flickr8k/Images",
        "CAPTION_FILE": "/content/flickr8k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/flickr8k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/vocab.pkl"
    },
    "flickr30k": {
        "ROOT": "/content/flickr30k",
        "IMAGE_DIR": "/content/flickr30k/Images",
        "CAPTION_FILE": "/content/flickr30k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/flickr30k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/vocab.pkl"
    }
}

In [112]:
def image_caption_map(train_df,val_df,test_df):
  train_caption_map = defaultdict(list)
  val_caption_map = defaultdict(list)
  test_caption_map = defaultdict(list)

  bad_img = "861608773_bdafd5c996.jpg"

  train_caption_map.pop(bad_img, None)
  val_caption_map.pop(bad_img, None)
  test_caption_map.pop(bad_img, None)

  for _, row in train_df.iterrows():
      train_caption_map[row["image"]].append(row["caption"])

  for _, row in val_df.iterrows():
      val_caption_map[row["image"]].append(row["caption"])

  for _, row in test_df.iterrows():
      test_caption_map[row["image"]].append(row["caption"])
  return train_caption_map,val_caption_map,test_caption_map

In [113]:
train_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomResizedCrop(
        224,
        scale=(0.8, 1.0),
        ratio=(0.9, 1.1)
    ),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(5),
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2,
        hue=0.05
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

In [114]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [115]:
# Encoding

def encode_caption(text, vocab):

    tokens = text.split()

    encoded = [vocab["<SOS>"]]

    for token in tokens:
        encoded.append(
            vocab.get(token, vocab["<UNK>"])
        )

    encoded.append(vocab["<EOS>"])

    return encoded

In [116]:
class FlickrCaptionDataset(Dataset):

    def __init__(
            self,
            caption_map,
            image_dir,
            vocab,
            transform=None,
            random_caption=True):

        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform
        self.random_caption = random_caption

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):

        image_name = self.image_names[idx]

        captions = self.caption_map[image_name]

        if self.random_caption:
            caption = random.choice(captions)
        else:
            caption = captions[0]

        try:
            image = Image.open(
                os.path.join(self.image_dir, image_name)
            ).convert("RGB")
        except Exception:
            return self.__getitem__((idx + 1) % len(self))

        if self.transform:
            image = self.transform(image)

        caption = encode_caption(caption, self.vocab)

        input_caption = torch.tensor(
            caption[:-1],
            dtype=torch.long
        )

        target_caption = torch.tensor(
            caption[1:],
            dtype=torch.long
        )

        return image, input_caption, target_caption

In [117]:
from torch.utils.data import Dataset
from PIL import Image
import os

class FlickrCaptionTestDataset(Dataset):

    def __init__(
            self,
            caption_map,
            image_dir,
            transform=None
    ):

        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.transform = transform

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):

        image_name = self.image_names[idx]

        # List containing all 5 captions
        captions = self.caption_map[image_name]

        try:
            image = Image.open(
                os.path.join(self.image_dir, image_name)
            ).convert("RGB")

        except Exception:
            return self.__getitem__(
                (idx + 1) % len(self)
            )

        if self.transform:
            image = self.transform(image)

        return image, captions

In [118]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    images = []
    input_captions = []
    target_captions_list = []

    for image, input_caption, target_caption in batch:
        images.append(image)
        input_captions.append(input_caption)
        target_captions_list.append(target_caption)

    images = torch.stack(images)

    input_captions = pad_sequence(
        input_captions,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    padded_target_captions = pad_sequence(
        target_captions_list,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    return images, input_captions, padded_target_captions

In [119]:
# Encoder Image
class ResnetImageEncoder(nn.Module):

    def __init__(self, embed_dim=512):
        super().__init__()

        backbone = models.resnet50(
            weights=models.ResNet50_Weights.IMAGENET1K_V2
        )

        # Freeze initially
        for param in backbone.parameters():
            param.requires_grad = False

        # Fine-tune only deeper layers
        for param in backbone.layer4.parameters():
            param.requires_grad = True

        self.backbone = nn.Sequential(
            *list(backbone.children())[:-2]
        )

        self.pool = nn.AdaptiveAvgPool2d((1, 1))

        self.projection = nn.Sequential(
            nn.Linear(2048, 1024),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(1024, embed_dim),
            nn.LayerNorm(embed_dim)
        )

        for m in self.projection:
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def forward(self, images):

        features = self.backbone(images)

        # (B,2048,7,7)

        features = self.pool(features)

        # (B,2048,1,1)

        features = torch.flatten(features, 1)

        # (B,2048)

        features = self.projection(features)

        # (B,512)

        return features

In [120]:
#decoder
class LSTMCaptionDecoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        embed_dim=512,
        hidden_dim=512,
        pad_idx=0
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=pad_idx
        )

        self.embedding_dropout = nn.Dropout(0.3)

        # Initialize LSTM from image feature
        self.init_h = nn.Linear(embed_dim, hidden_dim)
        self.init_c = nn.Linear(embed_dim, hidden_dim)

        self.h_norm = nn.LayerNorm(hidden_dim)
        self.c_norm = nn.LayerNorm(hidden_dim)

        self.lstm = nn.LSTM(
            input_size=embed_dim,
            hidden_size=hidden_dim,
            num_layers=1,
            batch_first=True
        )

        self.output_dropout = nn.Dropout(0.3)

        self.fc = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(hidden_dim, vocab_size)
        )

        # -----------------------
        # Initialization
        # -----------------------

        nn.init.xavier_uniform_(self.embedding.weight)

        with torch.no_grad():
            self.embedding.weight[pad_idx].fill_(0)

        for m in self.fc:
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

        nn.init.xavier_uniform_(self.init_h.weight)
        nn.init.zeros_(self.init_h.bias)

        nn.init.xavier_uniform_(self.init_c.weight)
        nn.init.zeros_(self.init_c.bias)

        for name, param in self.lstm.named_parameters():

            if "weight_ih" in name:
                nn.init.xavier_uniform_(param)

            elif "weight_hh" in name:
                nn.init.orthogonal_(param)

            elif "bias" in name:
                nn.init.zeros_(param)

                # Forget gate bias = 1
                hidden = param.size(0) // 4
                param.data[hidden:2*hidden].fill_(1)

    def forward(
        self,
        image_features,
        captions
    ):

        embeddings = self.embedding(captions)

        embeddings = self.embedding_dropout(embeddings)

        h0 = torch.tanh(
            self.h_norm(
                self.init_h(image_features)
            )
        ).unsqueeze(0)

        c0 = torch.tanh(
            self.c_norm(
                self.init_c(image_features)
            )
        ).unsqueeze(0)

        outputs, _ = self.lstm(
            embeddings,
            (h0, c0)
        )

        outputs = self.output_dropout(outputs)

        outputs = self.fc(outputs)

        return outputs

In [121]:
#joint model
class ResnetLSTMImageCaptioningModel(nn.Module):

    def __init__(self, encoder, decoder):
        super().__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(self, images, captions):

        image_features = self.encoder(images)

        outputs = self.decoder(
            image_features,
            captions
        )

        return outputs

    @staticmethod
    def length_penalty(length, alpha=0.7):
        return ((5 + length) ** alpha) / ((5 + 1) ** alpha)

    def generate_caption(
        self,
        images,
        vocab,
        max_length=30,
        beam_size=5
    ):

        self.eval()

        batch_size = images.size(0)

        assert batch_size == 1, \
            "Beam search currently supports batch_size=1."

        with torch.no_grad():

            image_features = self.encoder(images)

            h = torch.tanh(
                self.decoder.h_norm(
                    self.decoder.init_h(image_features)
                )
            ).unsqueeze(0)

            c = torch.tanh(
                self.decoder.c_norm(
                    self.decoder.init_c(image_features)
                )
            ).unsqueeze(0)

            beams = [
                (
                    [vocab["<SOS>"]],
                    0.0,
                    (h, c)
                )
            ]

            completed = []

            for step in range(max_length):

                candidates = []

                for seq, score, hidden in beams:

                    last_token = seq[-1]

                    if last_token == vocab["<EOS>"]:
                        completed.append((seq, score))
                        continue

                    current_word = torch.tensor(
                        [last_token],
                        device=images.device
                    )

                    embedding = self.decoder.embedding(
                        current_word
                    )

                    embedding = self.decoder.embedding_dropout(
                        embedding
                    )

                    output, hidden_new = self.decoder.lstm(
                        embedding.unsqueeze(1),
                        hidden
                    )

                    scores = self.decoder.fc(
                        self.decoder.output_dropout(
                            output.squeeze(1)
                        )
                    )

                    # Block unwanted tokens
                    scores[:, vocab["<PAD>"]] = -1e9
                    scores[:, vocab["<SOS>"]] = -1e9

                    if "<UNK>" in vocab:
                        scores[:, vocab["<UNK>"]] = -1e9

                    # Prevent early EOS
                    if step < 3:
                        scores[:, vocab["<EOS>"]] = -1e9

                    log_probs = F.log_softmax(
                        scores,
                        dim=1
                    )

                    top_log_probs, top_indices = torch.topk(
                        log_probs,
                        beam_size,
                        dim=1
                    )

                    for k in range(beam_size):

                        token = top_indices[0, k].item()

                        new_seq = seq + [token]

                        new_score = score + \
                            top_log_probs[0, k].item()

                        # Clone hidden state
                        h_new = hidden_new[0].clone()
                        c_new = hidden_new[1].clone()

                        candidates.append(
                            (
                                new_seq,
                                new_score,
                                (h_new, c_new)
                            )
                        )

                if len(candidates) == 0:
                    break

                candidates = sorted(
                    candidates,
                    key=lambda x:
                        x[1] /
                        self.length_penalty(len(x[0])),
                    reverse=True
                )

                beams = candidates[:beam_size]

            if len(completed) == 0:
                completed = [
                    (
                        beams[0][0],
                        beams[0][1]
                    )
                ]

            completed = sorted(
                completed,
                key=lambda x:
                    x[1] /
                    self.length_penalty(len(x[0])),
                reverse=True
            )

            best_seq = completed[0][0]

            return [best_seq]

In [122]:
def build_image_text_decoder(vocab,device):
  encoder = ResnetImageEncoder(embed_dim=512)

  decoder = LSTMCaptionDecoder(
      vocab_size=len(vocab),
      embed_dim=512,
      hidden_dim=512,
      pad_idx=vocab["<PAD>"]
  )

  model = ResnetLSTMImageCaptioningModel(
      encoder,
      decoder
  ).to(device)

  return model

In [123]:
def define_optimizer(model):

    optimizer = torch.optim.AdamW(

        [

            # Fine-tuned ResNet
            {
                "params": filter(
                    lambda p: p.requires_grad,
                    model.encoder.backbone.parameters()
                ),
                "lr": 1e-5
            },

            # Projection layer
            {
                "params": model.encoder.projection.parameters(),
                "lr": 2e-4
            },

            # Embedding
            {
                "params": model.decoder.embedding.parameters(),
                "lr": 2e-4
            },

            # LSTM
            {
                "params": model.decoder.lstm.parameters(),
                "lr": 2e-4
            },

            # Hidden state initialization
            {
                "params": (
                    list(model.decoder.init_h.parameters()) +
                    list(model.decoder.init_c.parameters())
                ),
                "lr": 2e-4
            },

            # Vocabulary prediction head
            {
                "params": model.decoder.fc.parameters(),
                "lr": 3e-4
            }

        ],

        weight_decay=1e-4

    )

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=50
    )

    return optimizer, scheduler

In [124]:
def evaluate(
    model,
    dataloader,
    criterion,
    device
):

    model.eval()

    total_loss = 0.0
    total_tokens = 0

    with torch.inference_mode():

        for images, input_captions, target_captions in dataloader:

            images = images.to(device, non_blocking=True)
            input_captions = input_captions.to(device, non_blocking=True)
            target_captions = target_captions.to(device, non_blocking=True)

            outputs = model(
                images,
                input_captions
            )

            loss = criterion(
                outputs.reshape(-1, outputs.size(-1)),
                target_captions.reshape(-1)
            )

            # Count only non-PAD tokens
            valid_tokens = (
                target_captions != criterion.ignore_index
            ).sum().item()

            total_loss += loss.item() * valid_tokens
            total_tokens += valid_tokens

    return total_loss / total_tokens

In [125]:
import os
import time
import torch
import torch.nn as nn

def model_training(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        criterion,
        dataset_name):

    NUM_EPOCHS = 50

    best_val_loss = float("inf")

    patience = 8
    epochs_without_improvement = 0

    SAVE_DIR = f"/content/drive/MyDrive/MMCaptioning/C1/{dataset_name}"
    os.makedirs(SAVE_DIR, exist_ok=True)

    BEST_MODEL_PATH = os.path.join(
        SAVE_DIR,
        "best_captioning_C1_model.pth"
    )

    for epoch in range(NUM_EPOCHS):

        print(f"\n================ Epoch {epoch+1}/{NUM_EPOCHS} ================")

        model.train()

        running_loss = 0.0

        epoch_start = time.time()

        for batch_idx, (images, input_captions, target_captions) in enumerate(train_loader):

            batch_start = time.time()

            images = images.to(device, non_blocking=True)
            input_captions = input_captions.to(device, non_blocking=True)
            target_captions = target_captions.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            outputs = model(
                images,
                input_captions
            )

            loss = criterion(
                outputs.reshape(-1, outputs.size(-1)),
                target_captions.reshape(-1)
            )

            loss.backward()

            torch.nn.utils.clip_grad_norm_(
                model.parameters(),
                max_norm=1.0
            )

            optimizer.step()

            running_loss += loss.item()

            print(
                f"Batch {batch_idx+1:03d}/{len(train_loader)} | "
                f"Loss: {loss.item():.4f} | "
                f"Time: {time.time()-batch_start:.2f}s"
            )

        train_loss = running_loss / len(train_loader)

        train_time = time.time() - epoch_start

        # Validation

        val_start = time.time()

        val_loss = evaluate(
            model,
            val_loader,
            criterion,
            device
        )

        scheduler.step()

        val_time = time.time() - val_start

        print("\n---------------- Summary ----------------")

        print(f"Train Loss      : {train_loss:.4f}")
        print(f"Validation Loss : {val_loss:.4f}")
        print(f"Training Time   : {train_time:.2f}s")
        print(f"Validation Time : {val_time:.2f}s")

        print(
            f"GPU Memory Used : "
            f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
        )

        # Save Best

        if val_loss < best_val_loss:

            best_val_loss = val_loss
            epochs_without_improvement = 0

            torch.save(
                {
                    "model_state_dict": model.state_dict(),
                    "optimizer_state_dict": optimizer.state_dict(),
                    "scheduler_state_dict": scheduler.state_dict(),
                    "epoch": epoch,
                    "val_loss": val_loss
                },
                BEST_MODEL_PATH
            )

            print(f"✓ Best model saved (Val Loss: {val_loss:.4f})")

        else:

            epochs_without_improvement += 1

            print(
                f"No improvement for "
                f"{epochs_without_improvement}/{patience} epochs"
            )

        if epochs_without_improvement >= patience:

            print("\nEarly stopping triggered!")

            break

    checkpoint = torch.load(
        BEST_MODEL_PATH,
        map_location=device
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    return model, BEST_MODEL_PATH

In [126]:
import gc
def reset_resources():
  gc.collect()
  torch.cuda.empty_cache()
  print("\nMemory after cleanup")
  print("Allocated:",torch.cuda.memory_allocated()/1024**3)
  print("Reserved:",torch.cuda.memory_reserved()/1024**3)

In [127]:
def caption_test_collate_fn(batch):

    images = []
    all_references = []

    for image, references in batch:
        images.append(image)
        all_references.append(references)

    images = torch.stack(images)

    return images, all_references

In [128]:
def prepare_caption_dataloaders(
        train_caption_map,
        val_caption_map,
        test_caption_map):

    BATCH_SIZE = 192

    train_dataset = FlickrCaptionDataset(
        train_caption_map,
        IMAGE_DIR,
        vocab,
        train_transform,
        random_caption=True
    )

    val_dataset = FlickrCaptionDataset(
        val_caption_map,
        IMAGE_DIR,
        vocab,
        image_transform,
        random_caption=False
    )

    # Different dataset for evaluation
    test_dataset = FlickrCaptionTestDataset(
        test_caption_map,
        IMAGE_DIR,
        image_transform
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=8,
        pin_memory=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=8,
        pin_memory=True
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=caption_test_collate_fn,   # Different collate function
        num_workers=8,
        pin_memory=True
    )

    return train_loader, val_loader, test_loader

In [129]:
def model_testing(model,checkpoint_path,test_loader,vocab,device):
  checkpoint = torch.load(checkpoint_path,map_location=device)
  model.load_state_dict(checkpoint["model_state_dict"])
  model.to(device)
  model.eval()



  idx2word = {v: k for k, v in vocab.items()}

  references = []
  predictions = []

  rouge = rouge_scorer.RougeScorer(["rougeL"],use_stemmer=True)

  rouge_scores = []
  meteor_scores = []

  coco_refs = {}
  coco_preds = {}

  sample_id = 0

  print("Generating captions...")

  with torch.inference_mode():

      for images, all_references in test_loader:

        images = images.to(device)   # move BEFORE running encoder

        predicted_ids = []

        for j in range(images.size(0)):

            pred = model.generate_caption(
                images[j:j+1],
                vocab,
                max_length=30,
                beam_size=5
            )

            predicted_ids.extend(pred)

        for i in range(images.size(0)):
            # Prediction
            pred_words = []
            for idx in predicted_ids[i]:
                word = idx2word[idx]
                if word == "<EOS>":
                    break
                if word not in ["<SOS>", "<PAD>"]:
                    pred_words.append(word)

            pred_sentence = " ".join(pred_words)

            # References (5 captions)
            ref_words = [ref.split() for ref in all_references[i]]
            references.append(ref_words)
            predictions.append(pred_words)

            # ROUGE-L
            rouge_values = []

            for ref in all_references[i]:

                rouge_values.append(rouge.score(ref,pred_sentence)["rougeL"].fmeasure)

            rouge_scores.append(max(rouge_values))

            # METEOR
            meteor_scores.append(meteor_score(ref_words,pred_words))

            # COCO format
            coco_refs[sample_id] = [str(ref) for ref in all_references[i]]

            coco_preds[sample_id] = [str(pred_sentence)]

            sample_id += 1

  # BLEU
  smoothie = SmoothingFunction().method4
  bleu1 = corpus_bleu(references,predictions,weights=(1,0,0,0),smoothing_function=smoothie)

  bleu2 = corpus_bleu(references,predictions,weights=(0.5,0.5,0,0),smoothing_function=smoothie)

  bleu3 = corpus_bleu(references,predictions,weights=(0.33,0.33,0.33,0),smoothing_function=smoothie)

  bleu4 = corpus_bleu(references,predictions,weights=(0.25,0.25,0.25,0.25),smoothing_function=smoothie)

  # CIDEr
  cider_scorer = Cider()

  cider_score, _ = cider_scorer.compute_score(coco_refs,coco_preds)

  # SPICE

  # Results

  results = pd.DataFrame({

      "Metric":[
          "BLEU-1",
          "BLEU-2",
          "BLEU-3",
          "BLEU-4",
          "ROUGE-L",
          "METEOR",
          "CIDEr",

      ],

      "Score":[
          bleu1,
          bleu2,
          bleu3,
          bleu4,
          sum(rouge_scores)/len(rouge_scores),
          sum(meteor_scores)/len(meteor_scores),
          cider_score,

      ]

  })
  print(coco_refs[0])
  print(coco_preds[0])
  display(results)

  return results

In [130]:
for dataset_name, cfg in DATASETS.items():

    torch.cuda.reset_peak_memory_stats()

    print("\n************************")
    print(f"\nProcessing - {dataset_name}")
    print("\n************************\n")

    ROOT = cfg["ROOT"]
    IMAGE_DIR = cfg["IMAGE_DIR"]
    CAPTION_FILE = cfg["CAPTION_FILE"]

    with open(cfg["flickr_split"], "rb") as f:
        split = pickle.load(f)

    with open(cfg["vocab"], "rb") as f:
        vocab = pickle.load(f)


    #Build Model

    model = build_image_text_decoder(
        vocab,
        device
    )

    optimizer, scheduler = define_optimizer(model)

    # Dataset

    df = pd.read_csv(CAPTION_FILE)

    train_imgs = split["train"]
    val_imgs = split["val"]
    test_imgs = split["test"]

    print(
        f"Train: {len(train_imgs)} | "
        f"Val: {len(val_imgs)} | "
        f"Test: {len(test_imgs)}"
    )

    train_df = df[df["image"].isin(train_imgs)].reset_index(drop=True)
    val_df = df[df["image"].isin(val_imgs)].reset_index(drop=True)
    test_df = df[df["image"].isin(test_imgs)].reset_index(drop=True)

    train_df = train_df.dropna(subset=["caption"]).reset_index(drop=True)
    val_df = val_df.dropna(subset=["caption"]).reset_index(drop=True)
    test_df = test_df.dropna(subset=["caption"]).reset_index(drop=True)

    train_caption_map, val_caption_map, test_caption_map = image_caption_map(
        train_df,
        val_df,
        test_df
    )

    train_loader, val_loader, test_loader = prepare_caption_dataloaders(
        train_caption_map,
        val_caption_map,
        test_caption_map
    )
    criterion = nn.CrossEntropyLoss(ignore_index=vocab["<PAD>"],label_smoothing=0.1)

    #Train

    best_model, FINAL_MODEL_PATH = model_training(
        model,
        train_loader,
        val_loader,
        optimizer,
        scheduler,
        criterion,
        dataset_name
    )

    #Test

    model_testing(
        best_model,
        FINAL_MODEL_PATH,
        test_loader,
        vocab,
        device
    )

    # Cleanup

    del model
    del optimizer
    del scheduler

    del train_loader
    del val_loader
    del test_loader

    del train_df
    del val_df
    del test_df

    del train_caption_map
    del val_caption_map
    del test_caption_map

    del split
    del vocab
    del df

    reset_resources()

************************

Processing - flickr8k

************************

Train: 6068 | Val: 1011 | Test: 1012

================ Epoch 1/50 ================
Batch 001/32 | Loss: 7.8554 | Time: 0.11s
Batch 002/32 | Loss: 7.8012 | Time: 0.10s
Batch 003/32 | Loss: 7.7439 | Time: 0.09s
Batch 004/32 | Loss: 7.6692 | Time: 0.09s
Batch 005/32 | Loss: 7.5748 | Time: 0.09s
Batch 006/32 | Loss: 7.4649 | Time: 0.09s
Batch 007/32 | Loss: 7.3169 | Time: 0.09s
Batch 008/32 | Loss: 7.1494 | Time: 0.09s
Batch 009/32 | Loss: 6.9428 | Time: 0.10s
Batch 010/32 | Loss: 6.7698 | Time: 0.10s
Batch 011/32 | Loss: 6.5523 | Time: 0.10s
Batch 012/32 | Loss: 6.3521 | Time: 0.10s
Batch 013/32 | Loss: 6.1533 | Time: 0.09s
Batch 014/32 | Loss: 6.0123 | Time: 0.09s
Batch 015/32 | Loss: 5.8523 | Time: 0.09s
Batch 016/32 | Loss: 5.8716 | Time: 0.09s
Batch 017/32 | Loss: 5.7646 | Time: 0.10s
Batch 018/32 | Loss: 5.7113 | Time: 0.10s
Batch 019/32 | Loss: 5.5918 | Time: 0.10s
Batch 020/32 | Loss: 5.5406 | Time: 0.09s
Batch 021/32 | Loss: 5.5164 | Time: 0.09s
Batch 022/32 | Loss: 5.4794 | Time: 0.09s
Batch 023/32 | Loss: 5.4771 | Time: 0.09s
Batch 024/32 | Loss: 5.4448 | Time: 0.09s
Batch 025/32 | Loss: 5.3967 | Time: 0.09s
Batch 026/32 | Loss: 5.4378 | Time: 0.09s
Batch 027/32 | Loss: 5.3458 | Time: 0.09s
Batch 028/32 | Loss: 5.3521 | Time: 0.09s
Batch 029/32 | Loss: 5.3410 | Time: 0.09s
Batch 030/32 | Loss: 5.2914 | Time: 0.09s
Batch 031/32 | Loss: 5.3172 | Time: 0.09s
Batch 032/32 | Loss: 5.2506 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 6.1982
Validation Loss : 5.2037
Training Time   : 15.20s
Validation Time : 2.12s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 5.2037)

================ Epoch 2/50 ================
Batch 001/32 | Loss: 5.2066 | Time: 0.10s
Batch 002/32 | Loss: 5.2534 | Time: 0.09s
Batch 003/32 | Loss: 5.2246 | Time: 0.09s
Batch 004/32 | Loss: 5.1965 | Time: 0.09s
Batch 005/32 | Loss: 5.2922 | Time: 0.09s
Batch 006/32 | Loss: 5.2665 | Time: 0.09s
Batch 007/32 | Loss: 5.2217 | Time: 0.09s
Batch 008/32 | Loss: 5.2739 | Time: 0.09s
Batch 009/32 | Loss: 5.2540 | Time: 0.09s
Batch 010/32 | Loss: 5.2420 | Time: 0.10s
Batch 011/32 | Loss: 5.1381 | Time: 0.10s
Batch 012/32 | Loss: 5.1451 | Time: 0.09s
Batch 013/32 | Loss: 5.2205 | Time: 0.09s
Batch 014/32 | Loss: 5.2449 | Time: 0.09s
Batch 015/32 | Loss: 5.2024 | Time: 0.09s
Batch 016/32 | Loss: 5.1931 | Time: 0.09s
Batch 017/32 | Loss: 5.1966 | Time: 0.09s
Batch 018/32 | Loss: 5.1720 | Time: 0.09s
Batch 019/32 | Loss: 5.1774 | Time: 0.09s
Batch 020/32 | Loss: 5.1483 | Time: 0.09s
Batch 021/32 | Loss: 5.1441 | Time: 0.09s
Batch 022/32 | Loss: 5.1460 | Time: 0.09s
Batch 023/32 | Loss: 5.1026 | Time: 0.10s
Batch 024/32 | Loss: 5.0722 | Time: 0.11s
Batch 025/32 | Loss: 5.1103 | Time: 0.09s
Batch 026/32 | Loss: 5.0612 | Time: 0.09s
Batch 027/32 | Loss: 5.1730 | Time: 0.09s
Batch 028/32 | Loss: 5.1430 | Time: 0.10s
Batch 029/32 | Loss: 5.0834 | Time: 0.09s
Batch 030/32 | Loss: 5.1102 | Time: 0.09s
Batch 031/32 | Loss: 5.1335 | Time: 0.09s
Batch 032/32 | Loss: 5.0210 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 5.1741
Validation Loss : 5.0092
Training Time   : 14.30s
Validation Time : 1.99s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 5.0092)

================ Epoch 3/50 ================
Batch 001/32 | Loss: 5.1030 | Time: 0.10s
Batch 002/32 | Loss: 5.1206 | Time: 0.10s
Batch 003/32 | Loss: 5.0496 | Time: 0.09s
Batch 004/32 | Loss: 5.0780 | Time: 0.09s
Batch 005/32 | Loss: 5.0572 | Time: 0.09s
Batch 006/32 | Loss: 5.0647 | Time: 0.09s
Batch 007/32 | Loss: 5.0264 | Time: 0.09s
Batch 008/32 | Loss: 4.9596 | Time: 0.09s
Batch 009/32 | Loss: 5.0672 | Time: 0.10s
Batch 010/32 | Loss: 5.0593 | Time: 0.10s
Batch 011/32 | Loss: 5.0546 | Time: 0.09s
Batch 012/32 | Loss: 4.9532 | Time: 0.09s
Batch 013/32 | Loss: 4.9662 | Time: 0.09s
Batch 014/32 | Loss: 5.0866 | Time: 0.09s
Batch 015/32 | Loss: 4.9101 | Time: 0.09s
Batch 016/32 | Loss: 5.0387 | Time: 0.09s
Batch 017/32 | Loss: 4.9966 | Time: 0.10s
Batch 018/32 | Loss: 5.0680 | Time: 0.10s
Batch 019/32 | Loss: 5.0205 | Time: 0.10s
Batch 020/32 | Loss: 4.9297 | Time: 0.09s
Batch 021/32 | Loss: 4.9796 | Time: 0.09s
Batch 022/32 | Loss: 4.9804 | Time: 0.09s
Batch 023/32 | Loss: 5.0308 | Time: 0.09s
Batch 024/32 | Loss: 4.9653 | Time: 0.09s
Batch 025/32 | Loss: 4.9421 | Time: 0.10s
Batch 026/32 | Loss: 4.9971 | Time: 0.10s
Batch 027/32 | Loss: 4.9922 | Time: 0.10s
Batch 028/32 | Loss: 5.0077 | Time: 0.09s
Batch 029/32 | Loss: 4.9516 | Time: 0.09s
Batch 030/32 | Loss: 4.9663 | Time: 0.09s
Batch 031/32 | Loss: 4.9522 | Time: 0.09s
Batch 032/32 | Loss: 5.0652 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 5.0138
Validation Loss : 4.8748
Training Time   : 15.04s
Validation Time : 1.98s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.8748)

================ Epoch 4/50 ================
Batch 001/32 | Loss: 4.9424 | Time: 0.10s
Batch 002/32 | Loss: 4.9442 | Time: 0.09s
Batch 003/32 | Loss: 4.8719 | Time: 0.09s
Batch 004/32 | Loss: 4.9165 | Time: 0.09s
Batch 005/32 | Loss: 4.9722 | Time: 0.09s
Batch 006/32 | Loss: 4.9295 | Time: 0.09s
Batch 007/32 | Loss: 4.8885 | Time: 0.09s
Batch 008/32 | Loss: 4.9568 | Time: 0.09s
Batch 009/32 | Loss: 4.9267 | Time: 0.12s
Batch 010/32 | Loss: 4.9129 | Time: 0.10s
Batch 011/32 | Loss: 4.9157 | Time: 0.10s
Batch 012/32 | Loss: 4.9017 | Time: 0.09s
Batch 013/32 | Loss: 4.8134 | Time: 0.11s
Batch 014/32 | Loss: 4.9839 | Time: 0.09s
Batch 015/32 | Loss: 4.9312 | Time: 0.09s
Batch 016/32 | Loss: 4.8446 | Time: 0.09s
Batch 017/32 | Loss: 4.9072 | Time: 0.09s
Batch 018/32 | Loss: 4.8809 | Time: 0.11s
Batch 019/32 | Loss: 4.8914 | Time: 0.10s
Batch 020/32 | Loss: 4.8533 | Time: 0.09s
Batch 021/32 | Loss: 4.7911 | Time: 0.09s
Batch 022/32 | Loss: 4.8534 | Time: 0.09s
Batch 023/32 | Loss: 4.8552 | Time: 0.09s
Batch 024/32 | Loss: 4.8188 | Time: 0.09s
Batch 025/32 | Loss: 4.7353 | Time: 0.09s
Batch 026/32 | Loss: 4.8548 | Time: 0.09s
Batch 027/32 | Loss: 4.8568 | Time: 0.09s
Batch 028/32 | Loss: 4.8940 | Time: 0.09s
Batch 029/32 | Loss: 4.8666 | Time: 0.09s
Batch 030/32 | Loss: 4.8142 | Time: 0.09s
Batch 031/32 | Loss: 4.8958 | Time: 0.09s
Batch 032/32 | Loss: 4.7951 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.8817
Validation Loss : 4.7569
Training Time   : 14.85s
Validation Time : 2.39s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.7569)

================ Epoch 5/50 ================
Batch 001/32 | Loss: 4.7647 | Time: 0.10s
Batch 002/32 | Loss: 4.8194 | Time: 0.09s
Batch 003/32 | Loss: 4.8281 | Time: 0.09s
Batch 004/32 | Loss: 4.7934 | Time: 0.09s
Batch 005/32 | Loss: 4.8766 | Time: 0.09s
Batch 006/32 | Loss: 4.8315 | Time: 0.09s
Batch 007/32 | Loss: 4.7602 | Time: 0.09s
Batch 008/32 | Loss: 4.8047 | Time: 0.09s
Batch 009/32 | Loss: 4.8246 | Time: 0.09s
Batch 010/32 | Loss: 4.8195 | Time: 0.10s
Batch 011/32 | Loss: 4.7580 | Time: 0.09s
Batch 012/32 | Loss: 4.6988 | Time: 0.09s
Batch 013/32 | Loss: 4.7772 | Time: 0.09s
Batch 014/32 | Loss: 4.8474 | Time: 0.09s
Batch 015/32 | Loss: 4.7793 | Time: 0.09s
Batch 016/32 | Loss: 4.6972 | Time: 0.09s
Batch 017/32 | Loss: 4.7484 | Time: 0.09s
Batch 018/32 | Loss: 4.8249 | Time: 0.09s
Batch 019/32 | Loss: 4.7436 | Time: 0.09s
Batch 020/32 | Loss: 4.7954 | Time: 0.09s
Batch 021/32 | Loss: 4.6821 | Time: 0.09s
Batch 022/32 | Loss: 4.8696 | Time: 0.09s
Batch 023/32 | Loss: 4.7512 | Time: 0.09s
Batch 024/32 | Loss: 4.7723 | Time: 0.09s
Batch 025/32 | Loss: 4.7779 | Time: 0.09s
Batch 026/32 | Loss: 4.7820 | Time: 0.09s
Batch 027/32 | Loss: 4.7407 | Time: 0.09s
Batch 028/32 | Loss: 4.7695 | Time: 0.09s
Batch 029/32 | Loss: 4.7211 | Time: 0.09s
Batch 030/32 | Loss: 4.7369 | Time: 0.09s
Batch 031/32 | Loss: 4.7510 | Time: 0.09s
Batch 032/32 | Loss: 4.7207 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.7771
Validation Loss : 4.6461
Training Time   : 14.39s
Validation Time : 2.10s
GPU Memory Used : 0.87 GB
✓ Best model saved (Val Loss: 4.6461)

================ Epoch 6/50 ================
Batch 001/32 | Loss: 4.7729 | Time: 0.10s
Batch 002/32 | Loss: 4.7261 | Time: 0.09s
Batch 003/32 | Loss: 4.6967 | Time: 0.09s
Batch 004/32 | Loss: 4.7731 | Time: 0.09s
Batch 005/32 | Loss: 4.6960 | Time: 0.09s
Batch 006/32 | Loss: 4.7111 | Time: 0.09s
Batch 007/32 | Loss: 4.6642 | Time: 0.09s
Batch 008/32 | Loss: 4.7757 | Time: 0.09s
Batch 009/32 | Loss: 4.6528 | Time: 0.10s
Batch 010/32 | Loss: 4.6992 | Time: 0.10s
Batch 011/32 | Loss: 4.6205 | Time: 0.10s
Batch 012/32 | Loss: 4.6626 | Time: 0.09s
Batch 013/32 | Loss: 4.6660 | Time: 0.09s
Batch 014/32 | Loss: 4.7279 | Time: 0.09s
Batch 015/32 | Loss: 4.6306 | Time: 0.09s
Batch 016/32 | Loss: 4.6921 | Time: 0.09s
Batch 017/32 | Loss: 4.7269 | Time: 0.10s
Batch 018/32 | Loss: 4.7118 | Time: 0.11s
Batch 019/32 | Loss: 4.6647 | Time: 0.09s
Batch 020/32 | Loss: 4.5968 | Time: 0.09s
Batch 021/32 | Loss: 4.6444 | Time: 0.09s
Batch 022/32 | Loss: 4.6464 | Time: 0.09s
Batch 023/32 | Loss: 4.6097 | Time: 0.09s
Batch 024/32 | Loss: 4.6311 | Time: 0.09s
Batch 025/32 | Loss: 4.5871 | Time: 0.09s
Batch 026/32 | Loss: 4.6070 | Time: 0.09s
Batch 027/32 | Loss: 4.6283 | Time: 0.09s
Batch 028/32 | Loss: 4.5511 | Time: 0.09s
Batch 029/32 | Loss: 4.6027 | Time: 0.09s
Batch 030/32 | Loss: 4.6555 | Time: 0.09s
Batch 031/32 | Loss: 4.6380 | Time: 0.09s
Batch 032/32 | Loss: 4.5973 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.6646
Validation Loss : 4.5012
Training Time   : 15.00s
Validation Time : 2.10s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.5012)

================ Epoch 7/50 ================
Batch 001/32 | Loss: 4.5683 | Time: 0.12s
Batch 002/32 | Loss: 4.5461 | Time: 0.09s
Batch 003/32 | Loss: 4.5719 | Time: 0.09s
Batch 004/32 | Loss: 4.5799 | Time: 0.09s
Batch 005/32 | Loss: 4.6337 | Time: 0.09s
Batch 006/32 | Loss: 4.5135 | Time: 0.09s
Batch 007/32 | Loss: 4.5767 | Time: 0.09s
Batch 008/32 | Loss: 4.5648 | Time: 0.09s
Batch 009/32 | Loss: 4.5978 | Time: 0.10s
Batch 010/32 | Loss: 4.4777 | Time: 0.09s
Batch 011/32 | Loss: 4.5458 | Time: 0.09s
Batch 012/32 | Loss: 4.5284 | Time: 0.09s
Batch 013/32 | Loss: 4.5519 | Time: 0.09s
Batch 014/32 | Loss: 4.5191 | Time: 0.09s
Batch 015/32 | Loss: 4.5926 | Time: 0.09s
Batch 016/32 | Loss: 4.6171 | Time: 0.09s
Batch 017/32 | Loss: 4.5562 | Time: 0.10s
Batch 018/32 | Loss: 4.5345 | Time: 0.10s
Batch 019/32 | Loss: 4.5329 | Time: 0.09s
Batch 020/32 | Loss: 4.5462 | Time: 0.09s
Batch 021/32 | Loss: 4.4431 | Time: 0.09s
Batch 022/32 | Loss: 4.4988 | Time: 0.09s
Batch 023/32 | Loss: 4.4508 | Time: 0.09s
Batch 024/32 | Loss: 4.4767 | Time: 0.09s
Batch 025/32 | Loss: 4.5120 | Time: 0.09s
Batch 026/32 | Loss: 4.4577 | Time: 0.09s
Batch 027/32 | Loss: 4.4543 | Time: 0.09s
Batch 028/32 | Loss: 4.4391 | Time: 0.09s
Batch 029/32 | Loss: 4.5167 | Time: 0.09s
Batch 030/32 | Loss: 4.4430 | Time: 0.09s
Batch 031/32 | Loss: 4.4926 | Time: 0.09s
Batch 032/32 | Loss: 4.4203 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.5238
Validation Loss : 4.3722
Training Time   : 14.85s
Validation Time : 2.10s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.3722)

================ Epoch 8/50 ================
Batch 001/32 | Loss: 4.3913 | Time: 0.10s
Batch 002/32 | Loss: 4.4038 | Time: 0.09s
Batch 003/32 | Loss: 4.4299 | Time: 0.11s
Batch 004/32 | Loss: 4.4465 | Time: 0.09s
Batch 005/32 | Loss: 4.4698 | Time: 0.09s
Batch 006/32 | Loss: 4.4660 | Time: 0.09s
Batch 007/32 | Loss: 4.3970 | Time: 0.09s
Batch 008/32 | Loss: 4.4456 | Time: 0.09s
Batch 009/32 | Loss: 4.4203 | Time: 0.09s
Batch 010/32 | Loss: 4.4547 | Time: 0.09s
Batch 011/32 | Loss: 4.3479 | Time: 0.09s
Batch 012/32 | Loss: 4.4068 | Time: 0.09s
Batch 013/32 | Loss: 4.4566 | Time: 0.11s
Batch 014/32 | Loss: 4.3920 | Time: 0.09s
Batch 015/32 | Loss: 4.3671 | Time: 0.09s
Batch 016/32 | Loss: 4.3609 | Time: 0.09s
Batch 017/32 | Loss: 4.3895 | Time: 0.09s
Batch 018/32 | Loss: 4.4535 | Time: 0.09s
Batch 019/32 | Loss: 4.3710 | Time: 0.12s
Batch 020/32 | Loss: 4.4010 | Time: 0.09s
Batch 021/32 | Loss: 4.3767 | Time: 0.09s
Batch 022/32 | Loss: 4.4253 | Time: 0.09s
Batch 023/32 | Loss: 4.3490 | Time: 0.09s
Batch 024/32 | Loss: 4.3116 | Time: 0.09s
Batch 025/32 | Loss: 4.4606 | Time: 0.09s
Batch 026/32 | Loss: 4.4042 | Time: 0.09s
Batch 027/32 | Loss: 4.3696 | Time: 0.09s
Batch 028/32 | Loss: 4.3616 | Time: 0.09s
Batch 029/32 | Loss: 4.4719 | Time: 0.09s
Batch 030/32 | Loss: 4.3886 | Time: 0.09s
Batch 031/32 | Loss: 4.3600 | Time: 0.09s
Batch 032/32 | Loss: 4.3282 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.4025
Validation Loss : 4.2497
Training Time   : 14.30s
Validation Time : 2.03s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.2497)

================ Epoch 9/50 ================
Batch 001/32 | Loss: 4.4024 | Time: 0.13s
Batch 002/32 | Loss: 4.3156 | Time: 0.09s
Batch 003/32 | Loss: 4.3187 | Time: 0.09s
Batch 004/32 | Loss: 4.3828 | Time: 0.09s
Batch 005/32 | Loss: 4.2560 | Time: 0.09s
Batch 006/32 | Loss: 4.2883 | Time: 0.09s
Batch 007/32 | Loss: 4.3475 | Time: 0.09s
Batch 008/32 | Loss: 4.3519 | Time: 0.09s
Batch 009/32 | Loss: 4.4468 | Time: 0.09s
Batch 010/32 | Loss: 4.3315 | Time: 0.09s
Batch 011/32 | Loss: 4.3914 | Time: 0.09s
Batch 012/32 | Loss: 4.3174 | Time: 0.09s
Batch 013/32 | Loss: 4.2510 | Time: 0.09s
Batch 014/32 | Loss: 4.2695 | Time: 0.09s
Batch 015/32 | Loss: 4.2627 | Time: 0.09s
Batch 016/32 | Loss: 4.2591 | Time: 0.09s
Batch 017/32 | Loss: 4.2728 | Time: 0.09s
Batch 018/32 | Loss: 4.3070 | Time: 0.10s
Batch 019/32 | Loss: 4.2511 | Time: 0.10s
Batch 020/32 | Loss: 4.2327 | Time: 0.09s
Batch 021/32 | Loss: 4.2614 | Time: 0.09s
Batch 022/32 | Loss: 4.1927 | Time: 0.09s
Batch 023/32 | Loss: 4.3003 | Time: 0.09s
Batch 024/32 | Loss: 4.2166 | Time: 0.09s
Batch 025/32 | Loss: 4.2838 | Time: 0.09s
Batch 026/32 | Loss: 4.3130 | Time: 0.09s
Batch 027/32 | Loss: 4.3288 | Time: 0.09s
Batch 028/32 | Loss: 4.2757 | Time: 0.09s
Batch 029/32 | Loss: 4.2646 | Time: 0.09s
Batch 030/32 | Loss: 4.3136 | Time: 0.09s
Batch 031/32 | Loss: 4.2716 | Time: 0.09s
Batch 032/32 | Loss: 4.2016 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.2963
Validation Loss : 4.1456
Training Time   : 14.63s
Validation Time : 2.06s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.1456)

================ Epoch 10/50 ================
Batch 001/32 | Loss: 4.2540 | Time: 0.12s
Batch 002/32 | Loss: 4.1863 | Time: 0.09s
Batch 003/32 | Loss: 4.2734 | Time: 0.09s
Batch 004/32 | Loss: 4.3191 | Time: 0.09s
Batch 005/32 | Loss: 4.1424 | Time: 0.09s
Batch 006/32 | Loss: 4.2676 | Time: 0.09s
Batch 007/32 | Loss: 4.2158 | Time: 0.09s
Batch 008/32 | Loss: 4.2756 | Time: 0.09s
Batch 009/32 | Loss: 4.1931 | Time: 0.10s
Batch 010/32 | Loss: 4.2102 | Time: 0.10s
Batch 011/32 | Loss: 4.2206 | Time: 0.10s
Batch 012/32 | Loss: 4.1465 | Time: 0.09s
Batch 013/32 | Loss: 4.2581 | Time: 0.09s
Batch 014/32 | Loss: 4.2232 | Time: 0.09s
Batch 015/32 | Loss: 4.2151 | Time: 0.09s
Batch 016/32 | Loss: 4.2145 | Time: 0.09s
Batch 017/32 | Loss: 4.1827 | Time: 0.10s
Batch 018/32 | Loss: 4.2396 | Time: 0.09s
Batch 019/32 | Loss: 4.2603 | Time: 0.09s
Batch 020/32 | Loss: 4.1448 | Time: 0.09s
Batch 021/32 | Loss: 4.1926 | Time: 0.09s
Batch 022/32 | Loss: 4.2405 | Time: 0.09s
Batch 023/32 | Loss: 4.2237 | Time: 0.09s
Batch 024/32 | Loss: 4.1791 | Time: 0.09s
Batch 025/32 | Loss: 4.2305 | Time: 0.09s
Batch 026/32 | Loss: 4.1780 | Time: 0.09s
Batch 027/32 | Loss: 4.1775 | Time: 0.09s
Batch 028/32 | Loss: 4.2269 | Time: 0.09s
Batch 029/32 | Loss: 4.2244 | Time: 0.09s
Batch 030/32 | Loss: 4.1145 | Time: 0.09s
Batch 031/32 | Loss: 4.2103 | Time: 0.09s
Batch 032/32 | Loss: 4.0731 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.2098
Validation Loss : 4.0671
Training Time   : 14.08s
Validation Time : 2.00s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.0671)

================ Epoch 11/50 ================
Batch 001/32 | Loss: 4.1611 | Time: 0.10s
Batch 002/32 | Loss: 4.2059 | Time: 0.09s
Batch 003/32 | Loss: 4.1679 | Time: 0.09s
Batch 004/32 | Loss: 4.1216 | Time: 0.09s
Batch 005/32 | Loss: 4.1077 | Time: 0.09s
Batch 006/32 | Loss: 4.1661 | Time: 0.09s
Batch 007/32 | Loss: 4.1904 | Time: 0.09s
Batch 008/32 | Loss: 4.0787 | Time: 0.09s
Batch 009/32 | Loss: 4.1291 | Time: 0.10s
Batch 010/32 | Loss: 4.1257 | Time: 0.10s
Batch 011/32 | Loss: 4.0875 | Time: 0.09s
Batch 012/32 | Loss: 4.1248 | Time: 0.09s
Batch 013/32 | Loss: 4.1237 | Time: 0.09s
Batch 014/32 | Loss: 4.1114 | Time: 0.09s
Batch 015/32 | Loss: 4.1485 | Time: 0.09s
Batch 016/32 | Loss: 4.1221 | Time: 0.09s
Batch 017/32 | Loss: 4.0810 | Time: 0.10s
Batch 018/32 | Loss: 4.1103 | Time: 0.09s
Batch 019/32 | Loss: 4.1063 | Time: 0.09s
Batch 020/32 | Loss: 4.1660 | Time: 0.09s
Batch 021/32 | Loss: 4.1596 | Time: 0.09s
Batch 022/32 | Loss: 4.0689 | Time: 0.09s
Batch 023/32 | Loss: 4.0506 | Time: 0.09s
Batch 024/32 | Loss: 4.2176 | Time: 0.09s
Batch 025/32 | Loss: 4.0862 | Time: 0.11s
Batch 026/32 | Loss: 4.1547 | Time: 0.10s
Batch 027/32 | Loss: 4.1319 | Time: 0.09s
Batch 028/32 | Loss: 4.0655 | Time: 0.09s
Batch 029/32 | Loss: 4.0969 | Time: 0.09s
Batch 030/32 | Loss: 4.1476 | Time: 0.09s
Batch 031/32 | Loss: 4.0996 | Time: 0.09s
Batch 032/32 | Loss: 4.2075 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.1288
Validation Loss : 4.0037
Training Time   : 14.64s
Validation Time : 2.01s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 4.0037)

================ Epoch 12/50 ================
Batch 001/32 | Loss: 4.0853 | Time: 0.10s
Batch 002/32 | Loss: 4.1546 | Time: 0.09s
Batch 003/32 | Loss: 4.0932 | Time: 0.09s
Batch 004/32 | Loss: 4.0903 | Time: 0.09s
Batch 005/32 | Loss: 4.0630 | Time: 0.09s
Batch 006/32 | Loss: 4.0646 | Time: 0.09s
Batch 007/32 | Loss: 4.1140 | Time: 0.09s
Batch 008/32 | Loss: 4.1041 | Time: 0.09s
Batch 009/32 | Loss: 4.1341 | Time: 0.10s
Batch 010/32 | Loss: 4.0374 | Time: 0.10s
Batch 011/32 | Loss: 4.0761 | Time: 0.09s
Batch 012/32 | Loss: 4.0494 | Time: 0.09s
Batch 013/32 | Loss: 4.1500 | Time: 0.09s
Batch 014/32 | Loss: 4.1192 | Time: 0.09s
Batch 015/32 | Loss: 4.1326 | Time: 0.09s
Batch 016/32 | Loss: 4.0633 | Time: 0.09s
Batch 017/32 | Loss: 4.0659 | Time: 0.10s
Batch 018/32 | Loss: 4.0726 | Time: 0.10s
Batch 019/32 | Loss: 4.1291 | Time: 0.09s
Batch 020/32 | Loss: 4.0732 | Time: 0.09s
Batch 021/32 | Loss: 4.0253 | Time: 0.09s
Batch 022/32 | Loss: 4.0887 | Time: 0.09s
Batch 023/32 | Loss: 4.0671 | Time: 0.09s
Batch 024/32 | Loss: 4.0458 | Time: 0.09s
Batch 025/32 | Loss: 4.0114 | Time: 0.10s
Batch 026/32 | Loss: 4.1093 | Time: 0.10s
Batch 027/32 | Loss: 4.0978 | Time: 0.10s
Batch 028/32 | Loss: 4.0259 | Time: 0.09s
Batch 029/32 | Loss: 4.0989 | Time: 0.09s
Batch 030/32 | Loss: 4.0285 | Time: 0.09s
Batch 031/32 | Loss: 4.0974 | Time: 0.09s
Batch 032/32 | Loss: 3.9267 | Time: 0.06s

---------------- Summary ----------------
Train Loss      : 4.0780
Validation Loss : 3.9556
Training Time   : 14.60s
Validation Time : 2.04s
GPU Memory Used : 0.86 GB
✓ Best model saved (Val Loss: 3.9556)

================ Epoch 13/50 ================
Batch 001/32 | Loss: 4.0647 | Time: 0.10s
Batch 002/32 | Loss: 4.1251 | Time: 0.10s
Batch 003/32 | Loss: 4.0120 | Time: 0.09s
Batch 004/32 | Loss: 4.0086 | Time: 0.09s
Batch 005/32 | Loss: 4.0163 | Time: 0.09s
Batch 006/32 | Loss: 3.9681 | Time: 0.09s
Batch 007/32 | Loss: 4.1089 | Time: 0.09s
Batch 008/32 | Loss: 4.0103 | Time: 0.09s
Batch 009/32 | Loss: 4.0388 | Time: 0.10s
Batch 010/32 | Loss: 4.0281 | Time: 0.10s
Batch 011/32 | Loss: 4.0580 | Time: 0.09s
Batch 012/32 | Loss: 4.0009 | Time: 0.09s
Batch 013/32 | Loss: 4.0061 | Time: 0.09s
Batch 014/32 | Loss: 3.9629 | Time: 0.09s
Batch 015/32 | Loss: 4.0459 | Time: 0.09s
Batch 016/32 | Loss: 4.0320 | Time: 0.09s

    Metric     Score
0   BLEU-1  0.535045
1   BLEU-2  0.358416
2   BLEU-3  0.236890
3   BLEU-4  0.149452
4  ROUGE-L  0.449882
5   METEOR  0.378598
6    CIDEr  0.412919

Streaming output truncated to the last 5000 lines.
GPU Memory Used : 0.83 GB
✓ Best model saved (Val Loss: 4.1282)

================ Epoch 14/50 ================
Batch 001/125 | Loss: 4.0443 | Time: 0.11s
Batch 002/125 | Loss: 4.0759 | Time: 0.11s
Batch 003/125 | Loss: 4.0315 | Time: 0.12s
Batch 004/125 | Loss: 3.9811 | Time: 0.10s
Batch 005/125 | Loss: 3.9691 | Time: 0.10s
Batch 006/125 | Loss: 4.0326 | Time: 0.10s
Batch 007/125 | Loss: 4.0250 | Time: 0.10s
Batch 008/125 | Loss: 3.9425 | Time: 0.11s
Batch 009/125 | Loss: 4.0215 | Time: 0.10s
Batch 010/125 | Loss: 3.9989 | Time: 0.10s
Batch 011/125 | Loss: 3.9873 | Time: 0.10s
Batch 012/125 | Loss: 3.9214 | Time: 0.10s
Batch 013/125 | Loss: 4.0239 | Time: 0.10s
Batch 014/125 | Loss: 4.0264 | Time: 0.10s
Batch 015/125 | Loss: 4.0248 | Time: 0.10s
Batch 016/125 | Loss: 3.9576 | Time: 0.10s
Batch 017/125 | Loss: 3.9945 | Time: 0.11s
Batch 018/125 | Loss: 3.9824 | Time: 0.11s
Batch 019/125 | Loss: 3.9286 | Time: 0.10s
Batch 020/125 | Loss: 4.0380 | Time: 0.10s
Batch 021/125 | Loss: 3.9071 | Time: 0.10s
Batch 022/125 | Loss: 4.0618 | Time: 0.10s
Batch 023/125 | Loss: 3.8934 | Time: 0.10s
Batch 024/125 | Loss: 3.9362 | Time: 0.10s
Batch 025/125 | Loss: 3.9520 | Time: 0.10s
Batch 026/125 | Loss: 4.0613 | Time: 0.10s
Batch 027/125 | Loss: 3.8424 | Time: 0.10s
Batch 028/125 | Loss: 3.9839 | Time: 0.11s
Batch 029/125 | Loss: 3.9597 | Time: 0.10s
Batch 030/125 | Loss: 3.9317 | Time: 0.10s
Batch 031/125 | Loss: 3.9644 | Time: 0.10s
Batch 032/125 | Loss: 3.9437 | Time: 0.10s
Batch 033/125 | Loss: 4.0343 | Time: 0.10s
Batch 034/125 | Loss: 4.0429 | Time: 0.10s
Batch 035/125 | Loss: 4.0242 | Time: 0.10s
Batch 036/125 | Loss: 3.9299 | Time: 0.10s
Batch 037/125 | Loss: 3.8995 | Time: 0.11s
Batch 038/125 | Loss: 4.0323 | Time: 0.11s
Batch 039/125 | Loss: 3.9723 | Time: 0.10s
Batch 040/125 | Loss: 4.0282 | Time: 0.10s
Batch 041/125 | Loss: 3.9835 | Time: 0.10s
Batch 042/125 | Loss: 4.0580 | Time: 0.10s
Batch 043/125 | Loss: 4.0859 | Time: 0.10s
Batch 044/125 | Loss: 4.0178 | Time: 0.10s
Batch 045/125 | Loss: 4.0232 | Time: 0.11s
Batch 046/125 | Loss: 4.0471 | Time: 0.10s
Batch 047/125 | Loss: 4.0382 | Time: 0.10s
Batch 048/125 | Loss: 3.9654 | Time: 0.10s
Batch 049/125 | Loss: 4.0252 | Time: 0.10s
Batch 050/125 | Loss: 4.2419 | Time: 0.10s
Batch 051/125 | Loss: 4.0078 | Time: 0.10s
Batch 052/125 | Loss: 4.0065 | Time: 0.10s
Batch 053/125 | Loss: 3.9468 | Time: 0.11s
Batch 054/125 | Loss: 3.9121 | Time: 0.10s
Batch 055/125 | Loss: 4.0614 | Time: 0.10s
Batch 056/125 | Loss: 3.8706 | Time: 0.10s
Batch 057/125 | Loss: 3.9483 | Time: 0.10s
Batch 058/125 | Loss: 4.0033 | Time: 0.10s
Batch 059/125 | Loss: 3.9646 | Time: 0.10s
Batch 060/125 | Loss: 3.9635 | Time: 0.10s
Batch 061/125 | Loss: 4.0352 | Time: 0.10s
Batch 062/125 | Loss: 4.0592 | Time: 0.11s
Batch 063/125 | Loss: 3.9371 | Time: 0.10s
Batch 064/125 | Loss: 4.0230 | Time: 0.10s
Batch 065/125 | Loss: 4.0551 | Time: 0.11s
Batch 066/125 | Loss: 3.9389 | Time: 0.10s
Batch 067/125 | Loss: 3.9413 | Time: 0.10s
Batch 068/125 | Loss: 3.9057 | Time: 0.10s
Batch 069/125 | Loss: 3.9187 | Time: 0.10s
Batch 070/125 | Loss: 4.0193 | Time: 0.10s
Batch 071/125 | Loss: 4.0102 | Time: 0.10s
Batch 072/125 | Loss: 3.9453 | Time: 0.10s
Batch 073/125 | Loss: 3.9863 | Time: 0.10s
Batch 074/125 | Loss: 4.0547 | Time: 0.10s
Batch 075/125 | Loss: 3.9883 | Time: 0.10s
Batch 076/125 | Loss: 3.9392 | Time: 0.10s
Batch 077/125 | Loss: 4.0189 | Time: 0.10s
Batch 078/125 | Loss: 3.9404 | Time: 0.10s
Batch 079/125 | Loss: 3.8950 | Time: 0.10s
Batch 080/125 | Loss: 4.0071 | Time: 0.10s
Batch 081/125 | Loss: 4.0186 | Time: 0.10s
Batch 082/125 | Loss: 3.8832 | Time: 0.10s
Batch 083/125 | Loss: 4.0221 | Time: 0.11s
Batch 084/125 | Loss: 3.9459 | Time: 0.10s
Batch 085/125 | Loss: 3.9728 | Time: 0.10s
Batch 086/125 | Loss: 3.9302 | Time: 0.10s
Batch 087/125 | Loss: 3.9193 | Time: 0.10s
Batch 088/125 | Loss: 4.0274 | Time: 0.10s
Batch 089/125 | Loss: 3.9716 | Time: 0.10s
Batch 090/125 | Loss: 3.9928 | Time: 0.10s
Batch 091/125 | Loss: 4.0100 | Time: 0.10s
Batch 092/125 | Loss: 4.0300 | Time: 0.10s
Batch 093/125 | Loss: 3.9907 | Time: 0.10s
Batch 094/125 | Loss: 4.0021 | Time: 0.10s
Batch 095/125 | Loss: 3.9894 | Time: 0.10s
Batch 096/125 | Loss: 4.0144 | Time: 0.10s
Batch 097/125 | Loss: 4.0044 | Time: 0.10s
Batch 098/125 | Loss: 3.8781 | Time: 0.10s
Batch 099/125 | Loss: 3.9842 | Time: 0.10s
Batch 100/125 | Loss: 4.0177 | Time: 0.10s
Batch 101/125 | Loss: 4.0102 | Time: 0.10s
Batch 102/125 | Loss: 3.9013 | Time: 0.10s
Batch 103/125 | Loss: 3.9816 | Time: 0.12s
Batch 104/125 | Loss: 3.9051 | Time: 0.10s
Batch 105/125 | Loss: 3.8832 | Time: 0.10s
Batch 106/125 | Loss: 4.0008 | Time: 0.10s
Batch 107/125 | Loss: 3.9383 | Time: 0.10s
Batch 108/125 | Loss: 3.9230 | Time: 0.10s
Batch 109/125 | Loss: 3.9384 | Time: 0.10s
Batch 110/125 | Loss: 3.9948 | Time: 0.10s
Batch 111/125 | Loss: 3.9081 | Time: 0.10s
Batch 112/125 | Loss: 4.0263 | Time: 0.12s
Batch 113/125 | Loss: 3.9381 | Time: 0.10s
Batch 114/125 | Loss: 4.0246 | Time: 0.10s
Batch 115/125 | Loss: 3.9294 | Time: 0.10s
Batch 116/125 | Loss: 3.9895 | Time: 0.10s
Batch 117/125 | Loss: 3.9626 | Time: 0.10s
Batch 118/125 | Loss: 3.9661 | Time: 0.10s
Batch 119/125 | Loss: 3.9876 | Time: 0.10s
Batch 120/125 | Loss: 3.9395 | Time: 0.11s
Batch 121/125 | Loss: 3.9451 | Time: 0.10s
Batch 122/125 | Loss: 4.0767 | Time: 0.11s
Batch 123/125 | Loss: 3.9987 | Time: 0.10s
Batch 124/125 | Loss: 4.0257 | Time: 0.10s
Batch 125/125 | Loss: 4.1586 | Time: 0.02s

---------------- Summary ----------------
Train Loss      : 3.9853
Validation Loss : 4.1102
Training Time   : 53.14s
Validation Time : 5.03s
GPU Memory Used : 0.84 GB
✓ Best model saved (Val Loss: 4.1102)

================ Epoch 15/50 ================
Batch 001/125 | Loss: 4.0490 | Time: 0.12s
Batch 002/125 | Loss: 3.8909 | Time: 0.10s
Batch 003/125 | Loss: 3.9873 | Time: 0.10s
Batch 004/125 | Loss: 3.9564 | Time: 0.10s
Batch 005/125 | Loss: 4.0832 | Time: 0.10s
Batch 006/125 | Loss: 3.9751 | Time: 0.10s
Batch 007/125 | Loss: 3.9781 | Time: 0.10s
Batch 008/125 | Loss: 3.8854 | Time: 0.10s
Batch 009/125 | Loss: 3.9372 | Time: 0.11s
Batch 010/125 | Loss: 3.8887 | Time: 0.10s
Batch 011/125 | Loss: 3.9556 | Time: 0.10s
Batch 012/125 | Loss: 3.9417 | Time: 0.10s
Batch 013/125 | Loss: 3.9313 | Time: 0.10s
Batch 014/125 | Loss: 4.0425 | Time: 0.10s
Batch 015/125 | Loss: 3.9894 | Time: 0.10s
Batch 016/125 | Loss: 4.0799 | Time: 0.10s
Batch 017/125 | Loss: 3.9436 | Time: 0.11s
Batch 018/125 | Loss: 3.9452 | Time: 0.11s
Batch 019/125 | Loss: 3.8912 | Time: 0.10s
Batch 020/125 | Loss: 3.8567 | Time: 0.10s
Batch 021/125 | Loss: 4.0917 | Time: 0.10s
Batch 022/125 | Loss: 3.9452 | Time: 0.10s
Batch 023/125 | Loss: 4.0186 | Time: 0.11s
Batch 024/125 | Loss: 3.9283 | Time: 0.10s
Batch 025/125 | Loss: 3.9166 | Time: 0.12s
Batch 026/125 | Loss: 3.9630 | Time: 0.11s
Batch 027/125 | Loss: 3.9532 | Time: 0.10s
Batch 028/125 | Loss: 4.0046 | Time: 0.10s
Batch 029/125 | Loss: 3.9849 | Time: 0.10s
Batch 030/125 | Loss: 3.9674 | Time: 0.10s
Batch 031/125 | Loss: 3.9214 | Time: 0.10s
Batch 032/125 | Loss: 3.9854 | Time: 0.10s
Batch 033/125 | Loss: 3.9318 | Time: 0.11s
Batch 034/125 | Loss: 3.9866 | Time: 0.10s
Batch 035/125 | Loss: 3.9100 | Time: 0.10s
Batch 036/125 | Loss: 3.9165 | Time: 0.10s
Batch 037/125 | Loss: 4.0534 | Time: 0.10s
Batch 038/125 | Loss: 4.0422 | Time: 0.11s
Batch 039/125 | Loss: 3.9614 | Time: 0.10s
Batch 040/125 | Loss: 4.0093 | Time: 0.10s
Batch 041/125 | Loss: 4.0013 | Time: 0.12s
Batch 042/125 | Loss: 3.9793 | Time: 0.10s
Batch 043/125 | Loss: 3.9333 | Time: 0.10s
Batch 044/125 | Loss: 3.9668 | Time: 0.10s
Batch 045/125 | Loss: 3.9123 | Time: 0.10s
Batch 046/125 | Loss: 3.8719 | Time: 0.10s
Batch 047/125 | Loss: 3.8789 | Time: 0.10s
Batch 048/125 | Loss: 3.9889 | Time: 0.10s
Batch 049/125 | Loss: 3.9274 | Time: 0.11s
Batch 050/125 | Loss: 3.9369 | Time: 0.11s
Batch 051/125 | Loss: 3.9357 | Time: 0.10s
Batch 052/125 | Loss: 3.9279 | Time: 0.10s
Batch 053/125 | Loss: 3.9860 | Time: 0.10s
Batch 054/125 | Loss: 3.9618 | Time: 0.10s
Batch 055/125 | Loss: 4.0666 | Time: 0.10s
Batch 056/125 | Loss: 4.0479 | Time: 0.10s
Batch 057/125 | Loss: 3.9446 | Time: 0.11s
Batch 058/125 | Loss: 3.9726 | Time: 0.10s
Batch 059/125 | Loss: 3.9181 | Time: 0.10s
Batch 060/125 | Loss: 4.0216 | Time: 0.10s
Batch 061/125 | Loss: 3.9781 | Time: 0.10s
Batch 062/125 | Loss: 3.9879 | Time: 0.11s
Batch 063/125 | Loss: 3.9138 | Time: 0.10s
Batch 064/125 | Loss: 3.9590 | Time: 0.12s
Batch 065/125 | Loss: 3.9931 | Time: 0.10s
Batch 066/125 | Loss: 3.9095 | Time: 0.10s
Batch 067/125 | Loss: 4.0399 | Time: 0.10s
Batch 068/125 | Loss: 4.0308 | Time: 0.10s
Batch 069/125 | Loss: 3.9369 | Time: 0.10s
Batch 070/125 | Loss: 3.9817 | Time: 0.10s
Batch 071/125 | Loss: 3.9532 | Time: 0.10s
Batch 072/125 | Loss: 3.9393 | Time: 0.10s
Batch 073/125 | Loss: 3.9920 | Time: 0.10s
Batch 074/125 | Loss: 3.9670 | Time: 0.11s
Batch 075/125 | Loss: 3.9408 | Time: 0.10s
Batch 076/125 | Loss: 3.9404 | Time: 0.11s
Batch 077/125 | Loss: 3.9682 | Time: 0.11s
Batch 078/125 | Loss: 4.0338 | Time: 0.10s
Batch 079/125 | Loss: 3.9330 | Time: 0.11s
Batch 080/125 | Loss: 3.9673 | Time: 0.10s
Batch 081/125 | Loss: 3.9430 | Time: 0.11s
Batch 082/125 | Loss: 3.9642 | Time: 0.10s
Batch 083/125 | Loss: 3.9596 | Time: 0.10s
Batch 084/125 | Loss: 3.8969 | Time: 0.10s
Batch 085/125 | Loss: 3.8904 | Time: 0.10s
Batch 086/125 | Loss: 3.9563 | Time: 0.10s
Batch 087/125 | Loss: 3.9323 | Time: 0.11s
Batch 088/125 | Loss: 3.9805 | Time: 0.10s
Batch 089/125 | Loss: 3.9135 | Time: 0.11s
Batch 090/125 | Loss: 3.9711 | Time: 0.10s
Batch 091/125 | Loss: 4.0206 | Time: 0.10s
Batch 092/125 | Loss: 3.9965 | Time: 0.10s
Batch 093/125 | Loss: 3.9614 | Time: 0.10s
Batch 094/125 | Loss: 3.9662 | Time: 0.10s
Batch 095/125 | Loss: 3.9320 | Time: 0.10s
Batch 096/125 | Loss: 3.9812 | Time: 0.10s
Batch 097/125 | Loss: 3.9986 | Time: 0.10s
Batch 098/125 | Loss: 4.0613 | Time: 0.10s
Batch 099/125 | Loss: 3.9810 | Time: 0.11s
Batch 100/125 | Loss: 3.9566 | Time: 0.11s
Batch 101/125 | Loss: 3.9904 | Time: 0.11s
Batch 102/125 | Loss: 4.0099 | Time: 0.10s
Batch 103/125 | Loss: 3.9037 | Time: 0.10s
Batch 104/125 | Loss: 3.9640 | Time: 0.11s
Batch 105/125 | Loss: 3.9410 | Time: 0.10s
Batch 106/125 | Loss: 3.9307 | Time: 0.10s
Batch 107/125 | Loss: 3.9428 | Time: 0.10s
Batch 108/125 | Loss: 3.8871 | Time: 0.11s
Batch 109/125 | Loss: 3.8979 | Time: 0.13s
Batch 110/125 | Loss: 3.9114 | Time: 0.10s
Batch 111/125 | Loss: 3.8957 | Time: 0.10s
Batch 112/125 | Loss: 3.9738 | Time: 0.12s
Batch 113/125 | Loss: 3.9012 | Time: 0.10s
Batch 114/125 | Loss: 3.9074 | Time: 0.13s
Batch 115/125 | Loss: 3.9063 | Time: 0.10s
Batch 116/125 | Loss: 3.9068 | Time: 0.10s
Batch 117/125 | Loss: 3.9582 | Time: 0.10s
Batch 118/125 | Loss: 3.9674 | Time: 0.10s
Batch 119/125 | Loss: 3.8834 | Time: 0.10s
Batch 120/125 | Loss: 4.0086 | Time: 0.10s
Batch 121/125 | Loss: 3.9659 | Time: 0.11s
Batch 122/125 | Loss: 3.9777 | Time: 0.10s
Batch 123/125 | Loss: 3.9809 | Time: 0.10s
Batch 124/125 | Loss: 3.8734 | Time: 0.10s
Batch 125/125 | Loss: 3.9113 | Time: 0.02s

---------------- Summary ----------------
Train Loss      : 3.9592
Validation Loss : 4.0864
Training Time   : 53.35s
Validation Time : 4.82s
GPU Memory Used : 0.83 GB
✓ Best model saved (Val Loss: 4.0864)

================ Epoch 16/50 ================
Batch 001/125 | Loss: 4.0038 | Time: 0.11s
Batch 002/125 | Loss: 3.9899 | Time: 0.11s
Batch 003/125 | Loss: 3.9780 | Time: 0.10s
Batch 004/125 | Loss: 3.9403 | Time: 0.10s
Batch 005/125 | Loss: 3.9898 | Time: 0.11s
Batch 006/125 | Loss: 3.9697 | Time: 0.10s
Batch 007/125 | Loss: 3.9008 | Time: 0.10s
Batch 008/125 | Loss: 3.9526 | Time: 0.10s
Batch 009/125 | Loss: 3.9314 | Time: 0.11s
Batch 010/125 | Loss: 3.9171 | Time: 0.11s
Batch 011/125 | Loss: 3.9310 | Time: 0.10s
Batch 012/125 | Loss: 3.9972 | Time: 0.10s
Batch 013/125 | Loss: 3.9056 | Time: 0.10s
Batch 014/125 | Loss: 3.9029 | Time: 0.10s
Batch 015/125 | Loss: 4.0024 | Time: 0.10s
Batch 016/125 | Loss: 3.9657 | Time: 0.10s
Batch 017/125 | Loss: 3.8527 | Time: 0.11s
Batch 018/125 | Loss: 3.9554 | Time: 0.11s
Batch 019/125 | Loss: 3.9858 | Time: 0.10s
Batch 020/125 | Loss: 3.9032 | Time: 0.10s
Batch 021/125 | Loss: 3.9770 | Time: 0.10s
Batch 022/125 | Loss: 3.9186 | Time: 0.10s
Batch 023/125 | Loss: 3.9679 | Time: 0.10s
Batch 024/125 | Loss: 3.9624 | Time: 0.10s
Batch 025/125 | Loss: 3.9449 | Time: 0.13s
Batch 026/125 | Loss: 3.9116 | Time: 0.11s
Batch 027/125 | Loss: 3.9567 | Time: 0.10s
Batch 028/125 | Loss: 3.9339 | Time: 0.10s
Batch 029/125 | Loss: 3.8978 | Time: 0.11s
Batch 030/125 | Loss: 3.9526 | Time: 0.10s
Batch 031/125 | Loss: 3.8972 | Time: 0.10s
Batch 032/125 | Loss: 3.9333 | Time: 0.10s
Batch 033/125 | Loss: 3.8866 | Time: 0.10s
Batch 034/125 | Loss: 3.9432 | Time: 0.10s
Batch 035/125 | Loss: 3.9394 | Time: 0.11s
Batch 036/125 | Loss: 3.9218 | Time: 0.10s
Batch 037/125 | Loss: 3.9558 | Time: 0.10s
Batch 038/125 | Loss: 3.9801 | Time: 0.11s
Batch 039/125 | Loss: 3.8493 | Time: 0.10s
Batch 040/125 | Loss: 3.8963 | Time: 0.10s
Batch 041/125 | Loss: 3.9593 | Time: 0.10s
Batch 042/125 | Loss: 3.8534 | Time: 0.10s
Batch 043/125 | Loss: 3.9425 | Time: 0.10s
Batch 044/125 | Loss: 3.9876 | Time: 0.10s
Batch 045/125 | Loss: 3.9516 | Time: 0.10s
Batch 046/125 | Loss: 3.9442 | Time: 0.10s
Batch 047/125 | Loss: 3.9418 | Time: 0.10s
Batch 048/125 | Loss: 4.0314 | Time: 0.10s
Batch 049/125 | Loss: 3.9011 | Time: 0.10s
Batch 050/125 | Loss: 3.9549 | Time: 0.11s
Batch 051/125 | Loss: 3.8993 | Time: 0.10s
Batch 052/125 | Loss: 3.8894 | Time: 0.10s
Batch 053/125 | Loss: 3.9541 | Time: 0.10s
Batch 054/125 | Loss: 3.8344 | Time: 0.10s
Batch 055/125 | Loss: 3.9332 | Time: 0.10s
Batch 056/125 | Loss: 4.0212 | Time: 0.11s
Batch 057/125 | Loss: 3.9409 | Time: 0.10s
Batch 058/125 | Loss: 3.9268 | Time: 0.10s
Batch 059/125 | Loss: 3.8494 | Time: 0.10s
Batch 060/125 | Loss: 3.9607 | Time: 0.11s
Batch 061/125 | Loss: 3.9488 | Time: 0.10s
Batch 062/125 | Loss: 3.8606 | Time: 0.10s
Batch 063/125 | Loss: 4.0448 | Time: 0.10s
Batch 064/125 | Loss: 4.0311 | Time: 0.10s
Batch 065/125 | Loss: 3.9844 | Time: 0.10s
Batch 066/125 | Loss: 3.9023 | Time: 0.10s
Batch 067/125 | Loss: 3.9038 | Time: 0.10s
Batch 068/125 | Loss: 3.8483 | Time: 0.10s
Batch 069/125 | Loss: 3.9291 | Time: 0.10s
Batch 070/125 | Loss: 3.9136 | Time: 0.10s
Batch 071/125 | Loss: 3.9238 | Time: 0.10s
Batch 072/125 | Loss: 3.9802 | Time: 0.10s
Batch 073/125 | Loss: 3.9544 | Time: 0.10s
Batch 074/125 | Loss: 3.9220 | Time: 0.11s
Batch 075/125 | Loss: 3.9704 | Time: 0.11s
Batch 076/125 | Loss: 3.9377 | Time: 0.10s
Batch 077/125 | Loss: 3.9705 | Time: 0.10s
Batch 078/125 | Loss: 3.9385 | Time: 0.10s
Batch 079/125 | Loss: 3.9319 | Time: 0.13s
Batch 080/125 | Loss: 3.9368 | Time: 0.10s
Batch 081/125 | Loss: 3.9490 | Time: 0.10s
Batch 082/125 | Loss: 3.8685 | Time: 0.11s
Batch 083/125 | Loss: 3.9385 | Time: 0.10s
Batch 084/125 | Loss: 3.9374 | Time: 0.10s
Batch 085/125 | Loss: 3.9409 | Time: 0.10s
Batch 086/125 | Loss: 3.9565 | Time: 0.10s
Batch 087/125 | Loss: 3.9275 | Time: 0.10s
Batch 088/125 | Loss: 3.9637 | Time: 0.10s
Batch 089/125 | Loss: 3.9579 | Time: 0.10s
Batch 090/125 | Loss: 3.9374 | Time: 0.10s
Batch 091/125 | Loss: 3.9378 | Time: 0.11s
Batch 092/125 | Loss: 3.9119 | Time: 0.10s
Batch 093/125 | Loss: 3.9336 | Time: 0.10s
Batch 094/125 | Loss: 3.9425 | Time: 0.10s
Batch 095/125 | Loss: 4.0169 | Time: 0.10s
Batch 096/125 | Loss: 3.8861 | Time: 0.10s
Batch 097/125 | Loss: 3.9007 | Time: 0.10s
Batch 098/125 | Loss: 3.9030 | Time: 0.10s
Batch 099/125 | Loss: 4.0558 | Time: 0.10s
Batch 100/125 | Loss: 3.9603 | Time: 0.10s
Batch 101/125 | Loss: 3.8714 | Time: 0.10s
Batch 102/125 | Loss: 4.0137 | Time: 0.10s
Batch 103/125 | Loss: 3.9313 | Time: 0.10s
Batch 104/125 | Loss: 4.0384 | Time: 0.11s
Batch 105/125 | Loss: 3.9361 | Time: 0.10s
Batch 106/125 | Loss: 3.8758 | Time: 0.10s
Batch 107/125 | Loss: 3.9123 | Time: 0.12s
Batch 108/125 | Loss: 3.9466 | Time: 0.10s
Batch 109/125 | Loss: 4.0084 | Time: 0.10s
Batch 110/125 | Loss: 4.0169 | Time: 0.10s
Batch 111/125 | Loss: 3.9521 | Time: 0.10s
Batch 112/125 | Loss: 3.9132 | Time: 0.10s
Batch 113/125 | Loss: 3.9538 | Time: 0.10s
Batch 114/125 | Loss: 3.9957 | Time: 0.10s
Batch 115/125 | Loss: 3.9196 | Time: 0.12s
Batch 116/125 | Loss: 3.9068 | Time: 0.10s
Batch 117/125 | Loss: 3.9447 | Time: 0.10s
Batch 118/125 | Loss: 3.8735 | Time: 0.10s
Batch 119/125 | Loss: 3.8225 | Time: 0.10s
Batch 120/125 | Loss: 4.0789 | Time: 0.10s
Batch 121/125 | Loss: 3.9710 | Time: 0.10s
Batch 122/125 | Loss: 3.8805 | Time: 0.10s
Batch 123/125 | Loss: 3.8786 | Time: 0.10s
Batch 124/125 | Loss: 3.9104 | Time: 0.11s
Batch 125/125 | Loss: 3.7250 | Time: 0.02s

---------------- Summary ----------------
Train Loss      : 3.9377
Validation Loss : 4.0685
Training Time   : 51.73s
Validation Time : 5.38s
GPU Memory Used : 0.84 GB
✓ Best model saved (Val Loss: 4.0685)

================ Epoch 17/50 ================
Batch 001/125 | Loss: 3.8888 | Time: 0.11s
Batch 002/125 | Loss: 3.9082 | Time: 0.11s
Batch 003/125 | Loss: 3.8995 | Time: 0.10s
Batch 004/125 | Loss: 4.0037 | Time: 0.10s
Batch 005/125 | Loss: 3.9070 | Time: 0.10s
Batch 006/125 | Loss: 3.9283 | Time: 0.10s
Batch 007/125 | Loss: 3.9264 | Time: 0.10s
Batch 008/125 | Loss: 3.9215 | Time: 0.10s
Batch 009/125 | Loss: 3.8171 | Time: 0.10s
Batch 010/125 | Loss: 3.9110 | Time: 0.10s
Batch 011/125 | Loss: 3.9754 | Time: 0.11s
Batch 012/125 | Loss: 3.9044 | Time: 0.10s
Batch 013/125 | Loss: 3.8972 | Time: 0.11s
Batch 014/125 | Loss: 3.9664 | Time: 0.10s
Batch 015/125 | Loss: 3.9480 | Time: 0.10s
Batch 016/125 | Loss: 3.9631 | Time: 0.10s
Batch 017/125 | Loss: 3.8807 | Time: 0.10s
Batch 018/125 | Loss: 3.8942 | Time: 0.10s
Batch 019/125 | Loss: 3.9021 | Time: 0.10s
Batch 020/125 | Loss: 4.0001 | Time: 0.10s
Batch 021/125 | Loss: 4.0198 | Time: 0.10s
Batch 022/125 | Loss: 3.9916 | Time: 0.10s
Batch 023/125 | Loss: 3.9670 | Time: 0.11s
Batch 024/125 | Loss: 3.8896 | Time: 0.10s
Batch 025/125 | Loss: 3.9096 | Time: 0.10s
Batch 026/125 | Loss: 3.8302 | Time: 0.10s
Batch 027/125 | Loss: 3.9019 | Time: 0.10s
Batch 028/125 | Loss: 3.9039 | Time: 0.13s
Batch 029/125 | Loss: 3.9906 | Time: 0.10s
Batch 030/125 | Loss: 3.8302 | Time: 0.10s
Batch 031/125 | Loss: 3.8580 | Time: 0.10s
Batch 032/125 | Loss: 3.9121 | Time: 0.10s
Batch 033/125 | Loss: 3.9275 | Time: 0.10s
Batch 034/125 | Loss: 3.9256 | Time: 0.10s
Batch 035/125 | Loss: 3.9985 | Time: 0.11s
Batch 036/125 | Loss: 3.9513 | Time: 0.10s
Batch 037/125 | Loss: 3.9594 | Time: 0.10s
Batch 038/125 | Loss: 3.9067 | Time: 0.11s
Batch 039/125 | Loss: 3.8285 | Time: 0.10s
Batch 040/125 | Loss: 3.8833 | Time: 0.11s
Batch 041/125 | Loss: 3.8902 | Time: 0.12s
Batch 042/125 | Loss: 3.8975 | Time: 0.10s
Batch 043/125 | Loss: 3.8597 | Time: 0.10s
Batch 044/125 | Loss: 3.9529 | Time: 0.10s
Batch 045/125 | Loss: 3.9339 | Time: 0.10s
Batch 046/125 | Loss: 3.8344 | Time: 0.10s
Batch 047/125 | Loss: 3.9985 | Time: 0.10s
Batch 048/125 | Loss: 3.9058 | Time: 0.10s
Batch 049/125 | Loss: 3.8860 | Time: 0.11s
Batch 050/125 | Loss: 3.9138 | Time: 0.11s
Batch 051/125 | Loss: 3.9329 | Time: 0.10s
Batch 052/125 | Loss: 3.9395 | Time: 0.10s
Batch 053/125 | Loss: 3.9158 | Time: 0.10s
Batch 054/125 | Loss: 3.8626 | Time: 0.11s
Batch 055/125 | Loss: 3.8499 | Time: 0.10s
Batch 056/125 | Loss: 3.8476 | Time: 0.10s
Batch 057/125 | Loss: 3.8896 | Time: 0.10s
Batch 058/125 | Loss: 3.9172 | Time: 0.10s
Batch 059/125 | Loss: 3.8330 | Time: 0.10s
Batch 060/125 | Loss: 3.9155 | Time: 0.10s
Batch 061/125 | Loss: 3.9171 | Time: 0.10s
Batch 062/125 | Loss: 3.8943 | Time: 0.10s
Batch 063/125 | Loss: 3.9375 | Time: 0.10s
Batch 064/125 | Loss: 3.8944 | Time: 0.11s
Batch 065/125 | Loss: 3.9504 | Time: 0.10s
Batch 066/125 | Loss: 3.9623 | Time: 0.10s
Batch 067/125 | Loss: 3.8842 | Time: 0.10s
Batch 068/125 | Loss: 3.8588 | Time: 0.10s

    Metric     Score
0   BLEU-1  0.466214
1   BLEU-2  0.311108
2   BLEU-3  0.205217
3   BLEU-4  0.128546
4  ROUGE-L  0.398789
5   METEOR  0.347604
6    CIDEr  0.283623

Memory after cleanup
Allocated: 0.37775564193725586
Reserved: 1.99609375