In [50]:
from google.colab import drive
import pickle
import pandas as pd
from collections import defaultdict
import random
from torchvision import transforms
from torch.utils.data import Dataset
from PIL import Image
import os
import numpy as np
import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [51]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda

In [52]:
# Copying 8k to Colabs local SSD
if not os.path.exists("/content/flickr8k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr8k.zip" /content/

In [53]:
if not os.path.isdir("/content/flickr8k/Images"):
  !unzip "/content/flickr8k.zip" -d "/content/flickr8k"

In [54]:
print("Images:", len(os.listdir("/content/flickr8k/Images")))

Images: 8091

In [55]:
# Copying 30k to Colabs local SSD
if not os.path.exists("/content/flickr30k.zip"):
  !cp -r "/content/drive/MyDrive/MMRetrieval/flickr30k.zip" /content/

In [56]:
if not os.path.isdir("/content/flickr30k/Images"):
  !unzip "/content/flickr30k.zip" -d "/content/flickr30k"

In [57]:
print("Images:", len(os.listdir("/content/flickr30k/Images")))

Images: 31811

In [58]:
DATASETS = {
    "flickr8k": {
        "ROOT": "/content/flickr8k",
        "IMAGE_DIR": "/content/flickr8k/Images",
        "CAPTION_FILE": "/content/flickr8k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/flickr8k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr8k/vocab.pkl"
    },
    "flickr30k": {
        "ROOT": "/content/flickr30k",
        "IMAGE_DIR": "/content/flickr30k/Images",
        "CAPTION_FILE": "/content/flickr30k/captions.txt",
        "flickr_split": "/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/flickr30k_split.pkl",
        "vocab":"/content/drive/MyDrive/MMRetrieval/Preprocessing/flickr30k/vocab.pkl"
    }
}

In [59]:
def image_caption_map(train_df,val_df,test_df):
  train_caption_map = defaultdict(list)
  val_caption_map = defaultdict(list)
  test_caption_map = defaultdict(list)

  bad_img = "861608773_bdafd5c996.jpg"

  train_caption_map.pop(bad_img, None)
  val_caption_map.pop(bad_img, None)
  test_caption_map.pop(bad_img, None)

  for _, row in train_df.iterrows():
      train_caption_map[row["image"]].append(row["caption"])

  for _, row in val_df.iterrows():
      val_caption_map[row["image"]].append(row["caption"])

  for _, row in test_df.iterrows():
      test_caption_map[row["image"]].append(row["caption"])
  return train_caption_map,val_caption_map,test_caption_map

In [60]:
train_transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.RandomResizedCrop(
        224,
        scale=(0.8, 1.0),
        ratio=(0.9, 1.1)
    ),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(5),
    transforms.ColorJitter(
        brightness=0.2,
        contrast=0.2,
        saturation=0.2,
        hue=0.05
    ),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

In [61]:
image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

In [62]:
# Encoding

def encode_caption(text, vocab):

    tokens = text.split()

    encoded = [vocab["<SOS>"]]

    for token in tokens:
        encoded.append(
            vocab.get(token, vocab["<UNK>"])
        )

    encoded.append(vocab["<EOS>"])

    return encoded

In [63]:
class FlickrRetrievalDataset(Dataset):
    def __init__(self, caption_map, image_dir, vocab, transform=None, random_caption=True):
        self.image_names = sorted(caption_map.keys())
        self.caption_map = caption_map
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform
        self.random_caption = random_caption

    def __len__(self):
        return len(self.image_names)

    def __getitem__(self, idx):
        image_name = self.image_names[idx]

        captions = self.caption_map[image_name]

        if self.random_caption:
            caption = random.choice(captions)
        else:
            caption = captions[0]      # fixed caption for eval

        try:
          image = Image.open(
              os.path.join(self.image_dir, image_name)
          ).convert("RGB")

        except Exception:
            return self.__getitem__(
                (idx + 1) % len(self)
            )

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, caption

In [64]:
class FlickrAllCaptionEvalDataset(Dataset):

    def __init__(self, caption_map, image_dir, vocab, transform=None):

        self.samples = []
        self.image_dir = image_dir
        self.vocab = vocab
        self.transform = transform

        for image_name in sorted(caption_map.keys()):

            for caption in caption_map[image_name]:

                self.samples.append(
                    (image_name, caption)
                )

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):

        image_name, caption = self.samples[idx]

        image = Image.open(
            os.path.join(self.image_dir, image_name)
        ).convert("RGB")

        if self.transform:
            image = self.transform(image)

        caption = torch.tensor(
            encode_caption(caption, self.vocab),
            dtype=torch.long
        )

        return image, caption

In [65]:
from torch.nn.utils.rnn import pad_sequence

def collate_fn(batch):

    images = []
    captions = []
    lengths = []

    for image, caption in batch:
        images.append(image)
        captions.append(caption)
        lengths.append(len(caption))

    images = torch.stack(images)

    captions = pad_sequence(
        captions,
        batch_first=True,
        padding_value=vocab["<PAD>"]
    )

    lengths = torch.tensor(lengths)

    return images, captions, lengths

In [66]:
def prepare_datasets_dataloaders(train_caption_map,val_caption_map,test_caption_map):

  train_dataset = FlickrRetrievalDataset(train_caption_map,IMAGE_DIR,vocab,train_transform,random_caption=True)
  val_dataset = FlickrRetrievalDataset(val_caption_map,IMAGE_DIR,vocab,image_transform,random_caption=False)
  test_dataset = FlickrRetrievalDataset(test_caption_map,IMAGE_DIR,vocab,image_transform,random_caption=False)
  all_caption_test_dataset = FlickrAllCaptionEvalDataset(test_caption_map,IMAGE_DIR,vocab,image_transform)

  BATCH_SIZE = 256
  train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    num_workers=8,
    pin_memory=True,
    )
  val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=8,
        pin_memory=True,
    )
  test_loader = DataLoader(
        test_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=8,
        pin_memory=True,
    )
  all_caption_test_loader = DataLoader(
    all_caption_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=8
    )
  return train_loader,val_loader,test_loader,all_caption_test_loader

ViT(vit_base_patch16_224) Image Encoder

In [67]:
import timm
import torch
import torch.nn as nn
import torch.nn.functional as F

class ViTEncoder(nn.Module):

    def __init__(
        self,
        embed_dim=512,
        freeze_backbone=True,
        dropout=0.15
    ):
        super().__init__()

        self.freeze_backbone = freeze_backbone

        # --------------------------------------------------
        # ViT-B/16
        # Original ImageNet pretrained ViT-B/16
        # --------------------------------------------------

        self.vit = timm.create_model(
            "vit_base_patch16_224",
            pretrained=True,
            num_classes=0
        )

        # --------------------------------------------------
        # Freeze / unfreeze backbone
        # --------------------------------------------------

        for param in self.vit.parameters():
            param.requires_grad = not freeze_backbone

        # --------------------------------------------------
        # Projection Head
        # 768 -> 1024 -> 512
        # --------------------------------------------------

        self.projection = nn.Sequential(

            nn.Linear(768, 1024),

            nn.LayerNorm(1024),

            nn.GELU(),

            nn.Dropout(dropout),

            nn.Linear(1024, embed_dim),

            nn.LayerNorm(embed_dim)
        )

        # --------------------------------------------------
        # Initialization
        # --------------------------------------------------

        for module in self.projection:

            if isinstance(module, nn.Linear):

                nn.init.xavier_uniform_(
                    module.weight
                )

                nn.init.zeros_(
                    module.bias
                )

    def forward(self, images):

        # --------------------------------------------------
        # ViT feature extraction
        # --------------------------------------------------

        if self.freeze_backbone:

            with torch.no_grad():

                features = self.vit.forward_features(
                    images
                )

        else:

            features = self.vit.forward_features(
                images
            )

        # --------------------------------------------------
        # ViT output
        #
        # (B, 197, 768)
        #
        # 1 CLS token
        # 196 patch tokens
        # --------------------------------------------------

        cls_token = features[:, 0]

        # --------------------------------------------------
        # Patch tokens
        # --------------------------------------------------

        patch_tokens = features[:, 1:]

        # --------------------------------------------------
        # Mean pooled patch representation
        # --------------------------------------------------

        patch_mean = patch_tokens.mean(
            dim=1
        )

        # --------------------------------------------------
        # Combine CLS + patch information
        # --------------------------------------------------

        features = (
            cls_token +
            patch_mean
        ) / 2.0

        # --------------------------------------------------
        # Projection
        # --------------------------------------------------

        embeddings = self.projection(
            features
        )

        # --------------------------------------------------
        # L2 normalization
        # --------------------------------------------------

        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

In [68]:
# Text Encoder (Transformer Encoder)

import math
import torch
import torch.nn as nn
import torch.nn.functional as F


class PositionalEncoding(nn.Module):
    def __init__(self, embed_dim, max_len=5000):
        super().__init__()

        pe = torch.zeros(max_len, embed_dim)
        position = torch.arange(0, max_len).unsqueeze(1).float()

        div_term = torch.exp(
            torch.arange(0, embed_dim, 2).float()
            * (-math.log(10000.0) / embed_dim)
        )

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)      # (1, max_len, embed_dim)

        self.register_buffer("pe", pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]


class TextEncoder(nn.Module):

    def __init__(
        self,
        vocab_size,
        embed_dim=512,
        num_heads=8,
        num_layers=4,
        ff_dim=2048,
        pad_idx=0,
        dropout=0.15
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embed_dim,
            padding_idx=pad_idx
        )

        self.position = PositionalEncoding(
            embed_dim
        )

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=num_heads,
            dim_feedforward=ff_dim,
            dropout=dropout,
            activation="gelu",
            batch_first=True,
            norm_first=True
        )

        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=num_layers
        )

        self.projection = nn.Sequential(
            nn.Linear(embed_dim, 1024),
            nn.LayerNorm(1024),
            nn.GELU(),
            nn.Dropout(0.15),
            nn.Linear(1024, 512),
            nn.LayerNorm(512)
        )

        for module in self.projection:

            if isinstance(module, nn.Linear):

                nn.init.xavier_uniform_(
                    module.weight
                )

                nn.init.zeros_(
                    module.bias
                )

    def forward(
        self,
        captions,
        lengths
    ):

        x = self.embedding(captions)

        x = self.position(x)

        device = captions.device

        max_len = captions.size(1)

        lengths = lengths.to(device)

        mask = (
            torch.arange(
                max_len,
                device=device
            )
            .unsqueeze(0)
            .expand(captions.size(0), -1)
            >= lengths.unsqueeze(1)
        )

        x = self.transformer(
            x,
            src_key_padding_mask=mask
        )

        # Masked mean pooling

        valid_mask = (~mask).unsqueeze(-1).float()

        x = (
            x * valid_mask
        ).sum(dim=1) / valid_mask.sum(
            dim=1
        ).clamp(min=1e-8)

        embeddings = self.projection(x)

        embeddings = F.normalize(
            embeddings,
            p=2,
            dim=1
        )

        return embeddings

In [69]:
#Joint model
class ViTTransformerRetrieval(nn.Module):

    def __init__(self, image_encoder, text_encoder):
        super().__init__()

        self.image_encoder = image_encoder
        self.text_encoder = text_encoder

        # Learnable CLIP-style temperature
        self.logit_scale = nn.Parameter(
            torch.tensor(np.log(1 / 0.07), dtype=torch.float32)
        )

    def forward(self, images, captions, lengths):

        image_emb = self.image_encoder(images)

        text_emb = self.text_encoder(
            captions,
            lengths
        )

        return image_emb, text_emb

In [70]:
def build_image_text_encoder(vocab,device):
  image_encoder = ViTEncoder(freeze_backbone=True).to(device)

  text_encoder = TextEncoder(
      vocab_size=len(vocab),
      embed_dim=512,
      pad_idx=vocab["<PAD>"]
  ).to(device)

  model = ViTTransformerRetrieval(
      image_encoder=image_encoder,
      text_encoder=text_encoder
  ).to(device)

  return model

In [71]:
# CLIP-Style Contrastive Loss

def clip_contrastive_loss(image_emb, text_emb, logit_scale):

    # CLIP-style learnable temperature
    logit_scale = logit_scale.exp().clamp(max=100)

    # Similarity Matrix
    logits = torch.matmul(image_emb, text_emb.T) * logit_scale

    # Ground truth labels
    targets = torch.arange(
        image_emb.size(0),
        device=image_emb.device
    )

    # Image → Text
    loss_i2t = F.cross_entropy(logits, targets)

    # Text → Image
    loss_t2i = F.cross_entropy(logits.T, targets)

    # Bidirectional InfoNCE
    loss = (loss_i2t + loss_t2i) / 2

    return loss, logits

In [72]:
def define_optimizer(model):

    optimizer = torch.optim.AdamW(
        [
            {
                "params": model.image_encoder.projection.parameters(),
                "lr": 3e-4
            },
            {
                "params": model.text_encoder.parameters(),
                "lr": 3e-4
            },
            {
                "params": [model.logit_scale],
                "lr": 1e-4
            }
        ],
        weight_decay=1e-4
    )

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=50
    )

    return optimizer, scheduler

In [73]:
# Add Validation Loop
def evaluate(model, dataloader, device):

    model.eval()

    total_loss = 0.0

    with torch.inference_mode():

        for images, captions, lengths in dataloader:

            images = images.to(
                device,
                non_blocking=True
            )

            captions = captions.to(
                device,
                non_blocking=True
            )
            lengths = lengths.to(
                device,
                non_blocking=True
            )

            image_emb, text_emb = model(
                images,
                captions,
                lengths
            )

            loss, _ = clip_contrastive_loss(
                image_emb,
                text_emb,
                model.logit_scale
            )

            total_loss += loss.item()

    return total_loss / len(dataloader)

In [74]:
def model_training(model,train_loader,val_loader,optimizer,scheduler,dataset_name):
  import time
  import torch

  # Training
  NUM_EPOCHS = 50
  best_val_loss = float("inf")
  patience = 8
  epochs_without_improvement = 0

  SAVE_DIR = f"/content/drive/MyDrive/MMRetrieval/R5/{dataset_name}"
  os.makedirs(SAVE_DIR, exist_ok=True)

  BEST_MODEL_PATH = os.path.join(
      SAVE_DIR,
      "best_retrieval_R5_model.pth"
  )

  for epoch in range(NUM_EPOCHS):

      print(f"\n================ Epoch {epoch+1}/{NUM_EPOCHS} ================")

      model.train()
      running_loss = 0.0

      epoch_start = time.time()

      for batch_idx, (images, captions, lengths) in enumerate(train_loader):

          batch_start = time.time()

          images = images.to(device, non_blocking=True)
          captions = captions.to(device, non_blocking=True)
          lengths = lengths.to(
                device,
                non_blocking=True
            )

          optimizer.zero_grad(set_to_none=True)

          image_emb, text_emb = model(
              images,
              captions,
              lengths
          )

          loss, _ = clip_contrastive_loss(
              image_emb,
              text_emb,
              model.logit_scale
          )

          loss.backward()

          torch.nn.utils.clip_grad_norm_(
              model.parameters(),
              max_norm=1.0
          )

          optimizer.step()

          running_loss += loss.item()

          batch_time = time.time() - batch_start

          print(
              f"Batch {batch_idx+1:02d}/{len(train_loader)} | "
              f"Loss: {loss.item():.4f} | "
              f"Time: {batch_time:.2f}s"
          )

      train_time = time.time() - epoch_start

      train_loss = running_loss / len(train_loader)

      # ---------------- Validation ----------------
      val_start = time.time()

      val_loss = evaluate(
          model,
          val_loader,
          device
      )

      val_time = time.time() - val_start

      scheduler.step()

      print("\n---------------- Summary ----------------")
      print(f"Train Loss     : {train_loss:.4f}")
      print(f"Validation Loss: {val_loss:.4f}")
      print(f"Training Time  : {train_time:.2f} sec")
      print(f"Validation Time: {val_time:.2f} sec")
      print(
          f"GPU Memory Used: "
          f"{torch.cuda.memory_allocated()/1024**3:.2f} GB"
      )

      # Save best model
      if val_loss < best_val_loss:

          best_val_loss = val_loss
          epochs_without_improvement = 0

          torch.save(
              {
                  "model_state_dict": model.state_dict(),
                  "optimizer_state_dict": optimizer.state_dict(),
                  "epoch": epoch,
                  "scheduler_state_dict": scheduler.state_dict(),
                  "val_loss": val_loss
              },
              BEST_MODEL_PATH
          )
          print(f"✓ Best model saved(Val Loss: {val_loss:.4f})")
      else:
        epochs_without_improvement += 1
        print(f"No improvement for "f"{epochs_without_improvement}/{patience} epochs")

      if epochs_without_improvement >= patience:
        print("\nEarly stopping triggered!")
        break

  FINAL_MODEL_PATH = BEST_MODEL_PATH
  checkpoint = torch.load(BEST_MODEL_PATH, map_location=device)
  model.load_state_dict(checkpoint["model_state_dict"])

  return model,FINAL_MODEL_PATH

In [75]:
def extract_embeddings(model, dataloader, device):
    model.eval()

    image_embeddings = []
    text_embeddings = []

    with torch.inference_mode():
        for images, captions, lengths in dataloader:
            images = images.to(device, non_blocking=True)
            captions = captions.to(device, non_blocking=True)
            lengths = lengths.to(
                device,
                non_blocking=True
            )

            img_emb, txt_emb = model(images, captions, lengths)

            image_embeddings.append(img_emb.cpu())
            text_embeddings.append(txt_emb.cpu())

    image_embeddings = torch.cat(image_embeddings, dim=0)
    text_embeddings = torch.cat(text_embeddings, dim=0)

    return image_embeddings, text_embeddings

In [76]:
# image -> text
def image_to_text_recall(similarity, k):

    correct = 0

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        topk = similarity[img_idx].topk(k).indices.tolist()

        if any(idx in gt_caps for idx in topk):
            correct += 1

    return correct / similarity.shape[0]

In [77]:
def text_to_image_recall(similarity, k):

    similarity_t = similarity.T

    correct = 0

    for cap_idx in range(similarity_t.shape[0]):

        gt_img = cap_idx // 5

        topk = similarity_t[cap_idx]\
            .topk(k)\
            .indices\
            .tolist()

        if gt_img in topk:
            correct += 1

    return correct / similarity_t.shape[0]

In [78]:
def image_to_text_mrr(similarity):

    reciprocal_ranks = []

    for img_idx in range(similarity.shape[0]):

        gt_caps = set(
            range(
                img_idx * 5,
                img_idx * 5 + 5
            )
        )

        sorted_idx = torch.argsort(
            similarity[img_idx],
            descending=True
        )

        best_rank = float("inf")

        for cap in gt_caps:

            rank = (
                (sorted_idx == cap)
                .nonzero(as_tuple=True)[0]
                .item()
            ) + 1

            best_rank = min(best_rank, rank)

        reciprocal_ranks.append(
            1.0 / best_rank
        )

    return np.mean(reciprocal_ranks)

In [79]:
def text_to_image_mrr(similarity):

    similarity_t2i = similarity.T

    reciprocal_ranks = []

    for cap_idx in range(similarity_t2i.shape[0]):

        gt_image = cap_idx // 5

        sorted_idx = torch.argsort(
            similarity_t2i[cap_idx],
            descending=True
        )

        rank = (
            (sorted_idx == gt_image)
            .nonzero(as_tuple=True)[0]
            .item()
        ) + 1

        reciprocal_ranks.append(
            1.0 / rank
        )

    return np.mean(reciprocal_ranks)

In [80]:
def model_testing(model,FINAL_MODEL_PATH,all_caption_test_loader):


  model.eval()
  with torch.inference_mode():
    image_embs, text_embs = extract_embeddings(
      model,
      all_caption_test_loader,
      device
    )
  print(image_embs.shape)
  print(text_embs.shape)
  # Similarity Matrix
  unique_image_embs = image_embs[::5]

  similarity = unique_image_embs @ text_embs.T

  print("Image embeddings:", unique_image_embs.shape)
  print("Text embeddings:", text_embs.shape)
  print("Similarity:", similarity.shape)
  results = pd.DataFrame({
      "Metric": [
          "Recall@1",
          "Recall@5",
          "Recall@10",
          "MRR"
      ],
      "Image→Text": [
          image_to_text_recall(similarity, 1),
          image_to_text_recall(similarity, 5),
          image_to_text_recall(similarity, 10),
          image_to_text_mrr(similarity)
      ],
      "Text→Image": [
          text_to_image_recall(similarity, 1),
          text_to_image_recall(similarity, 5),
          text_to_image_recall(similarity, 10),
          text_to_image_mrr(similarity)
      ]
  })

  results["Image→Text"] = results["Image→Text"].round(6)
  results["Text→Image"] = results["Text→Image"].round(6)

  display(results)
  return

In [81]:
import gc
def reset_resourses():
  gc.collect()
  torch.cuda.empty_cache()
  print("\nMemory after cleanup")
  print("Allocated:",torch.cuda.memory_allocated()/1024**3)
  print("Reserved:",torch.cuda.memory_reserved()/1024**3)

In [82]:
for dataset_name, cfg in DATASETS.items():
    torch.cuda.reset_peak_memory_stats()
    print("\n************************")
    print(f"\nProcessing - {dataset_name}")
    print("\n************************\n")
    ROOT = cfg["ROOT"]
    IMAGE_DIR = cfg["IMAGE_DIR"]
    CAPTION_FILE = cfg["CAPTION_FILE"]
    with open(cfg["flickr_split"],"rb") as f:
      split = pickle.load(f)

    with open(cfg["vocab"],"rb") as g:
      vocab = pickle.load(g)

    model = build_image_text_encoder(vocab, device)

   # print("MODEL\n",model)

    optimizer,scheduler = define_optimizer(model)

    df = pd.read_csv(CAPTION_FILE)
    train_imgs = split["train"]
    val_imgs = split["val"]
    test_imgs = split["test"]

    print(f"Train: {len(train_imgs)} | Val: {len(val_imgs)} | Test: {len(test_imgs)}")

    train_df = df[df["image"].isin(train_imgs)].reset_index(drop=True)
    val_df = df[df["image"].isin(val_imgs)].reset_index(drop=True)
    test_df = df[df["image"].isin(test_imgs)].reset_index(drop=True)

    train_df = train_df.dropna(subset=["caption"]).reset_index(drop=True)
    val_df = val_df.dropna(subset=["caption"]).reset_index(drop=True)
    test_df = test_df.dropna(subset=["caption"]).reset_index(drop=True)

    train_caption_map,val_caption_map,test_caption_map = image_caption_map(train_df,val_df,test_df)

    train_loader,val_loader,test_loader,all_caption_test_loader = prepare_datasets_dataloaders(train_caption_map,val_caption_map,test_caption_map)

    best_model,FINAL_MODEL_PATH  = model_training(model,train_loader,val_loader,optimizer,scheduler,dataset_name)

    model_testing(best_model,FINAL_MODEL_PATH,all_caption_test_loader)
    del model
    del optimizer
    del scheduler

    del train_loader
    del val_loader
    del test_loader
    del all_caption_test_loader

    del train_df
    del val_df
    del test_df

    del train_caption_map
    del val_caption_map
    del test_caption_map

    del split
    del vocab
    del df

    reset_resourses()

************************

Processing - flickr8k

************************

/tmp/ipykernel_6999/3535708442.py:66: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.transformer = nn.TransformerEncoder(

Train: 6068 | Val: 1011 | Test: 1012

================ Epoch 1/50 ================
Batch 01/24 | Loss: 5.6258 | Time: 0.60s
Batch 02/24 | Loss: 5.5700 | Time: 0.57s
Batch 03/24 | Loss: 5.5437 | Time: 0.56s
Batch 04/24 | Loss: 5.5458 | Time: 0.56s
Batch 05/24 | Loss: 5.4863 | Time: 0.56s
Batch 06/24 | Loss: 5.4605 | Time: 0.55s
Batch 07/24 | Loss: 5.3363 | Time: 0.56s
Batch 08/24 | Loss: 5.2311 | Time: 0.56s
Batch 09/24 | Loss: 5.1194 | Time: 0.56s
Batch 10/24 | Loss: 5.1545 | Time: 0.56s
Batch 11/24 | Loss: 5.0394 | Time: 0.56s
Batch 12/24 | Loss: 5.0537 | Time: 0.56s
Batch 13/24 | Loss: 4.9555 | Time: 0.55s
Batch 14/24 | Loss: 5.0006 | Time: 0.56s
Batch 15/24 | Loss: 4.9249 | Time: 0.56s
Batch 16/24 | Loss: 4.7520 | Time: 0.56s
Batch 17/24 | Loss: 4.7560 | Time: 0.56s
Batch 18/24 | Loss: 4.7642 | Time: 0.57s
Batch 19/24 | Loss: 4.6698 | Time: 0.57s
Batch 20/24 | Loss: 4.6709 | Time: 0.56s
Batch 21/24 | Loss: 4.5999 | Time: 0.56s
Batch 22/24 | Loss: 4.4655 | Time: 0.56s
Batch 23/24 | Loss: 4.6069 | Time: 0.56s
Batch 24/24 | Loss: 4.3958 | Time: 0.40s

---------------- Summary ----------------
Train Loss     : 5.0304
Validation Loss: 4.3596
Training Time  : 18.41 sec
Validation Time: 4.28 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 4.3596)

================ Epoch 2/50 ================
Batch 01/24 | Loss: 4.3031 | Time: 0.59s
Batch 02/24 | Loss: 4.3233 | Time: 0.56s
Batch 03/24 | Loss: 4.2707 | Time: 0.56s
Batch 04/24 | Loss: 4.3349 | Time: 0.56s
Batch 05/24 | Loss: 4.2714 | Time: 0.55s
Batch 06/24 | Loss: 4.2007 | Time: 0.56s
Batch 07/24 | Loss: 4.2616 | Time: 0.55s
Batch 08/24 | Loss: 4.1776 | Time: 0.56s
Batch 09/24 | Loss: 3.9928 | Time: 0.56s
Batch 10/24 | Loss: 4.0670 | Time: 0.56s
Batch 11/24 | Loss: 3.9319 | Time: 0.56s
Batch 12/24 | Loss: 4.0494 | Time: 0.56s
Batch 13/24 | Loss: 3.9593 | Time: 0.56s
Batch 14/24 | Loss: 4.0150 | Time: 0.56s
Batch 15/24 | Loss: 3.9274 | Time: 0.57s
Batch 16/24 | Loss: 4.0394 | Time: 0.56s
Batch 17/24 | Loss: 3.8726 | Time: 0.56s
Batch 18/24 | Loss: 3.7922 | Time: 0.55s
Batch 19/24 | Loss: 3.8884 | Time: 0.56s
Batch 20/24 | Loss: 3.8935 | Time: 0.55s
Batch 21/24 | Loss: 3.7741 | Time: 0.56s
Batch 22/24 | Loss: 3.6897 | Time: 0.56s
Batch 23/24 | Loss: 3.8801 | Time: 0.56s
Batch 24/24 | Loss: 3.4809 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 4.0165
Validation Loss: 3.6739
Training Time  : 19.28 sec
Validation Time: 4.28 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 3.6739)

================ Epoch 3/50 ================
Batch 01/24 | Loss: 3.6719 | Time: 0.59s
Batch 02/24 | Loss: 3.6327 | Time: 0.55s
Batch 03/24 | Loss: 3.6691 | Time: 0.56s
Batch 04/24 | Loss: 3.6512 | Time: 0.55s
Batch 05/24 | Loss: 3.6024 | Time: 0.56s
Batch 06/24 | Loss: 3.5578 | Time: 0.56s
Batch 07/24 | Loss: 3.4761 | Time: 0.56s
Batch 08/24 | Loss: 3.6105 | Time: 0.56s
Batch 09/24 | Loss: 3.3640 | Time: 0.56s
Batch 10/24 | Loss: 3.4646 | Time: 0.56s
Batch 11/24 | Loss: 3.4678 | Time: 0.56s
Batch 12/24 | Loss: 3.4404 | Time: 0.56s
Batch 13/24 | Loss: 3.4689 | Time: 0.56s
Batch 14/24 | Loss: 3.4879 | Time: 0.56s
Batch 15/24 | Loss: 3.3549 | Time: 0.56s
Batch 16/24 | Loss: 3.3525 | Time: 0.56s
Batch 17/24 | Loss: 3.3095 | Time: 0.56s
Batch 18/24 | Loss: 3.5329 | Time: 0.56s
Batch 19/24 | Loss: 3.3804 | Time: 0.56s
Batch 20/24 | Loss: 3.4306 | Time: 0.56s
Batch 21/24 | Loss: 3.4444 | Time: 0.56s
Batch 22/24 | Loss: 3.2589 | Time: 0.57s
Batch 23/24 | Loss: 3.2296 | Time: 0.56s
Batch 24/24 | Loss: 2.9625 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 3.4509
Validation Loss: 3.3190
Training Time  : 18.99 sec
Validation Time: 4.29 sec
GPU Memory Used: 1.17 GB
✓ Best model saved(Val Loss: 3.3190)

================ Epoch 4/50 ================
Batch 01/24 | Loss: 3.1592 | Time: 0.62s
Batch 02/24 | Loss: 3.2440 | Time: 0.55s
Batch 03/24 | Loss: 3.1706 | Time: 0.57s
Batch 04/24 | Loss: 3.1463 | Time: 0.56s
Batch 05/24 | Loss: 3.0678 | Time: 0.55s
Batch 06/24 | Loss: 3.2169 | Time: 0.55s
Batch 07/24 | Loss: 3.1865 | Time: 0.56s
Batch 08/24 | Loss: 3.1034 | Time: 0.56s
Batch 09/24 | Loss: 3.1336 | Time: 0.56s
Batch 10/24 | Loss: 3.0515 | Time: 0.56s
Batch 11/24 | Loss: 2.9367 | Time: 0.56s
Batch 12/24 | Loss: 3.2460 | Time: 0.56s
Batch 13/24 | Loss: 3.1404 | Time: 0.55s
Batch 14/24 | Loss: 3.0056 | Time: 0.56s
Batch 15/24 | Loss: 3.0314 | Time: 0.56s
Batch 16/24 | Loss: 2.9621 | Time: 0.56s
Batch 17/24 | Loss: 3.1381 | Time: 0.56s
Batch 18/24 | Loss: 2.9923 | Time: 0.56s
Batch 19/24 | Loss: 3.0356 | Time: 0.56s
Batch 20/24 | Loss: 3.2035 | Time: 0.56s
Batch 21/24 | Loss: 2.9923 | Time: 0.57s
Batch 22/24 | Loss: 2.9959 | Time: 0.56s
Batch 23/24 | Loss: 3.0473 | Time: 0.56s
Batch 24/24 | Loss: 2.7312 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 3.0808
Validation Loss: 3.1099
Training Time  : 19.29 sec
Validation Time: 4.25 sec
GPU Memory Used: 1.17 GB
✓ Best model saved(Val Loss: 3.1099)

================ Epoch 5/50 ================
Batch 01/24 | Loss: 2.8803 | Time: 0.58s
Batch 02/24 | Loss: 2.8772 | Time: 0.56s
Batch 03/24 | Loss: 3.0117 | Time: 0.58s
Batch 04/24 | Loss: 2.9139 | Time: 0.56s
Batch 05/24 | Loss: 3.0232 | Time: 0.56s
Batch 06/24 | Loss: 2.9428 | Time: 0.56s
Batch 07/24 | Loss: 2.7844 | Time: 0.56s
Batch 08/24 | Loss: 2.9372 | Time: 0.56s
Batch 09/24 | Loss: 2.8818 | Time: 0.56s
Batch 10/24 | Loss: 2.8784 | Time: 0.55s
Batch 11/24 | Loss: 2.9320 | Time: 0.55s
Batch 12/24 | Loss: 2.6376 | Time: 0.56s
Batch 13/24 | Loss: 2.9480 | Time: 0.56s
Batch 14/24 | Loss: 2.9728 | Time: 0.56s
Batch 15/24 | Loss: 2.8732 | Time: 0.56s
Batch 16/24 | Loss: 2.7920 | Time: 0.56s
Batch 17/24 | Loss: 2.7238 | Time: 0.56s
Batch 18/24 | Loss: 2.7335 | Time: 0.56s
Batch 19/24 | Loss: 2.7427 | Time: 0.56s
Batch 20/24 | Loss: 2.9922 | Time: 0.56s
Batch 21/24 | Loss: 2.8035 | Time: 0.56s
Batch 22/24 | Loss: 2.8013 | Time: 0.56s
Batch 23/24 | Loss: 2.9936 | Time: 0.57s
Batch 24/24 | Loss: 2.6082 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 2.8619
Validation Loss: 2.9351
Training Time  : 19.20 sec
Validation Time: 4.36 sec
GPU Memory Used: 1.17 GB
✓ Best model saved(Val Loss: 2.9351)

================ Epoch 6/50 ================
Batch 01/24 | Loss: 2.7530 | Time: 0.61s
Batch 02/24 | Loss: 2.6308 | Time: 0.56s
Batch 03/24 | Loss: 2.5848 | Time: 0.56s
Batch 04/24 | Loss: 2.6189 | Time: 0.56s
Batch 05/24 | Loss: 2.5222 | Time: 0.56s
Batch 06/24 | Loss: 2.7913 | Time: 0.56s
Batch 07/24 | Loss: 2.8447 | Time: 0.56s
Batch 08/24 | Loss: 2.7354 | Time: 0.56s
Batch 09/24 | Loss: 2.5437 | Time: 0.56s
Batch 10/24 | Loss: 2.5098 | Time: 0.56s
Batch 11/24 | Loss: 2.6601 | Time: 0.56s
Batch 12/24 | Loss: 2.6820 | Time: 0.55s
Batch 13/24 | Loss: 2.7597 | Time: 0.55s
Batch 14/24 | Loss: 2.7152 | Time: 0.56s
Batch 15/24 | Loss: 2.7388 | Time: 0.56s
Batch 16/24 | Loss: 2.6751 | Time: 0.56s
Batch 17/24 | Loss: 2.6632 | Time: 0.56s
Batch 18/24 | Loss: 2.5777 | Time: 0.56s
Batch 19/24 | Loss: 2.7183 | Time: 0.56s
Batch 20/24 | Loss: 2.5483 | Time: 0.57s
Batch 21/24 | Loss: 2.6794 | Time: 0.56s
Batch 22/24 | Loss: 2.5882 | Time: 0.56s
Batch 23/24 | Loss: 2.7475 | Time: 0.55s
Batch 24/24 | Loss: 2.2653 | Time: 0.40s

---------------- Summary ----------------
Train Loss     : 2.6481
Validation Loss: 2.7802
Training Time  : 19.13 sec
Validation Time: 4.22 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.7802)

================ Epoch 7/50 ================
Batch 01/24 | Loss: 2.4817 | Time: 0.61s
Batch 02/24 | Loss: 2.5598 | Time: 0.56s
Batch 03/24 | Loss: 2.4504 | Time: 0.56s
Batch 04/24 | Loss: 2.6028 | Time: 0.56s
Batch 05/24 | Loss: 2.5688 | Time: 0.56s
Batch 06/24 | Loss: 2.4835 | Time: 0.56s
Batch 07/24 | Loss: 2.4995 | Time: 0.55s
Batch 08/24 | Loss: 2.5466 | Time: 0.56s
Batch 09/24 | Loss: 2.4438 | Time: 0.58s
Batch 10/24 | Loss: 2.4903 | Time: 0.56s
Batch 11/24 | Loss: 2.3915 | Time: 0.56s
Batch 12/24 | Loss: 2.3935 | Time: 0.56s
Batch 13/24 | Loss: 2.4310 | Time: 0.56s
Batch 14/24 | Loss: 2.5360 | Time: 0.55s
Batch 15/24 | Loss: 2.5269 | Time: 0.57s
Batch 16/24 | Loss: 2.5266 | Time: 0.55s
Batch 17/24 | Loss: 2.4757 | Time: 0.56s
Batch 18/24 | Loss: 2.4496 | Time: 0.56s
Batch 19/24 | Loss: 2.4813 | Time: 0.55s
Batch 20/24 | Loss: 2.3998 | Time: 0.56s
Batch 21/24 | Loss: 2.5147 | Time: 0.57s
Batch 22/24 | Loss: 2.5389 | Time: 0.56s
Batch 23/24 | Loss: 2.4963 | Time: 0.56s
Batch 24/24 | Loss: 2.2669 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 2.4815
Validation Loss: 2.6638
Training Time  : 18.60 sec
Validation Time: 4.39 sec
GPU Memory Used: 1.17 GB
✓ Best model saved(Val Loss: 2.6638)

================ Epoch 8/50 ================
Batch 01/24 | Loss: 2.3257 | Time: 0.59s
Batch 02/24 | Loss: 2.4042 | Time: 0.56s
Batch 03/24 | Loss: 2.3459 | Time: 0.55s
Batch 04/24 | Loss: 2.2889 | Time: 0.56s
Batch 05/24 | Loss: 2.2010 | Time: 0.56s
Batch 06/24 | Loss: 2.4226 | Time: 0.56s
Batch 07/24 | Loss: 2.2635 | Time: 0.56s
Batch 08/24 | Loss: 2.4089 | Time: 0.56s
Batch 09/24 | Loss: 2.4273 | Time: 0.56s
Batch 10/24 | Loss: 2.5084 | Time: 0.56s
Batch 11/24 | Loss: 2.1665 | Time: 0.56s
Batch 12/24 | Loss: 2.3635 | Time: 0.57s
Batch 13/24 | Loss: 2.3507 | Time: 0.56s
Batch 14/24 | Loss: 2.3729 | Time: 0.56s
Batch 15/24 | Loss: 2.4026 | Time: 0.56s
Batch 16/24 | Loss: 2.4401 | Time: 0.56s
Batch 17/24 | Loss: 2.2583 | Time: 0.57s
Batch 18/24 | Loss: 2.2184 | Time: 0.56s
Batch 19/24 | Loss: 2.3852 | Time: 0.56s
Batch 20/24 | Loss: 2.4609 | Time: 0.56s
Batch 21/24 | Loss: 2.3756 | Time: 0.56s
Batch 22/24 | Loss: 2.2831 | Time: 0.56s
Batch 23/24 | Loss: 2.3787 | Time: 0.56s
Batch 24/24 | Loss: 1.9442 | Time: 0.41s

---------------- Summary ----------------
Train Loss     : 2.3332
Validation Loss: 2.6412
Training Time  : 19.31 sec
Validation Time: 4.37 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.6412)

================ Epoch 9/50 ================
Batch 01/24 | Loss: 2.1444 | Time: 0.61s
Batch 02/24 | Loss: 2.1103 | Time: 0.56s
Batch 03/24 | Loss: 2.0730 | Time: 0.57s
Batch 04/24 | Loss: 2.1100 | Time: 0.56s
Batch 05/24 | Loss: 2.1798 | Time: 0.56s
Batch 06/24 | Loss: 2.4007 | Time: 0.56s
Batch 07/24 | Loss: 2.1365 | Time: 0.56s
Batch 08/24 | Loss: 2.2232 | Time: 0.56s
Batch 09/24 | Loss: 2.1728 | Time: 0.56s
Batch 10/24 | Loss: 2.1174 | Time: 0.55s
Batch 11/24 | Loss: 2.1779 | Time: 0.56s
Batch 12/24 | Loss: 2.1608 | Time: 0.55s
Batch 13/24 | Loss: 2.3307 | Time: 0.55s
Batch 14/24 | Loss: 2.2822 | Time: 0.56s
Batch 15/24 | Loss: 2.1929 | Time: 0.56s
Batch 16/24 | Loss: 2.2824 | Time: 0.56s
Batch 17/24 | Loss: 2.1592 | Time: 0.56s
Batch 18/24 | Loss: 2.3517 | Time: 0.55s
Batch 19/24 | Loss: 2.2153 | Time: 0.55s
Batch 20/24 | Loss: 2.2124 | Time: 0.55s
Batch 21/24 | Loss: 2.2964 | Time: 0.56s
Batch 22/24 | Loss: 2.1257 | Time: 0.56s
Batch 23/24 | Loss: 2.3235 | Time: 0.56s
Batch 24/24 | Loss: 1.8690 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 2.1937
Validation Loss: 2.5821
Training Time  : 18.54 sec
Validation Time: 4.37 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.5821)

================ Epoch 10/50 ================
Batch 01/24 | Loss: 2.0749 | Time: 0.59s
Batch 02/24 | Loss: 2.0765 | Time: 0.56s
Batch 03/24 | Loss: 2.0884 | Time: 0.56s
Batch 04/24 | Loss: 2.0468 | Time: 0.55s
Batch 05/24 | Loss: 1.9295 | Time: 0.56s
Batch 06/24 | Loss: 2.0061 | Time: 0.56s
Batch 07/24 | Loss: 2.1578 | Time: 0.58s
Batch 08/24 | Loss: 2.0963 | Time: 0.56s
Batch 09/24 | Loss: 2.1751 | Time: 0.56s
Batch 10/24 | Loss: 2.0923 | Time: 0.56s
Batch 11/24 | Loss: 2.0012 | Time: 0.56s
Batch 12/24 | Loss: 1.9942 | Time: 0.55s
Batch 13/24 | Loss: 2.1189 | Time: 0.56s
Batch 14/24 | Loss: 2.0768 | Time: 0.57s
Batch 15/24 | Loss: 2.1089 | Time: 0.56s
Batch 16/24 | Loss: 2.0783 | Time: 0.56s
Batch 17/24 | Loss: 2.1805 | Time: 0.56s
Batch 18/24 | Loss: 2.0692 | Time: 0.56s
Batch 19/24 | Loss: 2.1819 | Time: 0.56s
Batch 20/24 | Loss: 2.1386 | Time: 0.55s
Batch 21/24 | Loss: 2.1205 | Time: 0.57s
Batch 22/24 | Loss: 2.1500 | Time: 0.56s
Batch 23/24 | Loss: 1.9786 | Time: 0.56s
Batch 24/24 | Loss: 2.0035 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 2.0810
Validation Loss: 2.5185
Training Time  : 19.12 sec
Validation Time: 4.32 sec
GPU Memory Used: 1.17 GB
✓ Best model saved(Val Loss: 2.5185)

================ Epoch 11/50 ================
Batch 01/24 | Loss: 2.1820 | Time: 0.58s
Batch 02/24 | Loss: 1.9566 | Time: 0.56s
Batch 03/24 | Loss: 2.0018 | Time: 0.56s
Batch 04/24 | Loss: 1.9225 | Time: 0.56s
Batch 05/24 | Loss: 1.8304 | Time: 0.56s
Batch 06/24 | Loss: 1.9810 | Time: 0.56s
Batch 07/24 | Loss: 1.9463 | Time: 0.56s
Batch 08/24 | Loss: 1.9905 | Time: 0.55s
Batch 09/24 | Loss: 1.9189 | Time: 0.56s
Batch 10/24 | Loss: 1.9317 | Time: 0.56s
Batch 11/24 | Loss: 1.9715 | Time: 0.56s
Batch 12/24 | Loss: 1.9327 | Time: 0.56s
Batch 13/24 | Loss: 1.8809 | Time: 0.56s
Batch 14/24 | Loss: 1.9885 | Time: 0.56s
Batch 15/24 | Loss: 2.1234 | Time: 0.56s
Batch 16/24 | Loss: 1.9773 | Time: 0.56s
Batch 17/24 | Loss: 1.9388 | Time: 0.56s
Batch 18/24 | Loss: 1.8742 | Time: 0.56s
Batch 19/24 | Loss: 1.9993 | Time: 0.56s
Batch 20/24 | Loss: 2.0549 | Time: 0.56s
Batch 21/24 | Loss: 2.1067 | Time: 0.56s
Batch 22/24 | Loss: 1.9658 | Time: 0.57s
Batch 23/24 | Loss: 1.7844 | Time: 0.56s
Batch 24/24 | Loss: 1.6655 | Time: 0.40s

---------------- Summary ----------------
Train Loss     : 1.9552
Validation Loss: 2.4465
Training Time  : 19.25 sec
Validation Time: 4.41 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.4465)

================ Epoch 12/50 ================
Batch 01/24 | Loss: 1.8166 | Time: 0.59s
Batch 02/24 | Loss: 1.7270 | Time: 0.56s
Batch 03/24 | Loss: 1.8611 | Time: 0.56s
Batch 04/24 | Loss: 1.8066 | Time: 0.56s
Batch 05/24 | Loss: 1.9357 | Time: 0.55s
Batch 06/24 | Loss: 1.8359 | Time: 0.56s
Batch 07/24 | Loss: 1.8634 | Time: 0.56s
Batch 08/24 | Loss: 1.8654 | Time: 0.56s
Batch 09/24 | Loss: 1.8332 | Time: 0.56s
Batch 10/24 | Loss: 1.9395 | Time: 0.58s
Batch 11/24 | Loss: 1.9459 | Time: 0.56s
Batch 12/24 | Loss: 1.8843 | Time: 0.55s
Batch 13/24 | Loss: 1.8852 | Time: 0.56s
Batch 14/24 | Loss: 1.9800 | Time: 0.56s
Batch 15/24 | Loss: 1.9861 | Time: 0.56s
Batch 16/24 | Loss: 1.8612 | Time: 0.56s
Batch 17/24 | Loss: 1.8784 | Time: 0.56s
Batch 18/24 | Loss: 1.9579 | Time: 0.57s
Batch 19/24 | Loss: 1.8655 | Time: 0.56s
Batch 20/24 | Loss: 1.9838 | Time: 0.56s
Batch 21/24 | Loss: 1.9622 | Time: 0.56s
Batch 22/24 | Loss: 2.0377 | Time: 0.56s
Batch 23/24 | Loss: 1.8938 | Time: 0.57s
Batch 24/24 | Loss: 1.6086 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 1.8840
Validation Loss: 2.4342
Training Time  : 18.26 sec
Validation Time: 4.30 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.4342)

================ Epoch 13/50 ================
Batch 01/24 | Loss: 1.6960 | Time: 0.59s
Batch 02/24 | Loss: 1.7983 | Time: 0.56s
Batch 03/24 | Loss: 1.7897 | Time: 0.56s
Batch 04/24 | Loss: 1.9274 | Time: 0.56s
Batch 05/24 | Loss: 1.7214 | Time: 0.56s
Batch 06/24 | Loss: 1.7874 | Time: 0.56s
Batch 07/24 | Loss: 1.8005 | Time: 0.56s
Batch 08/24 | Loss: 1.7683 | Time: 0.56s
Batch 09/24 | Loss: 1.8470 | Time: 0.56s
Batch 10/24 | Loss: 1.7310 | Time: 0.56s
Batch 11/24 | Loss: 1.8970 | Time: 0.55s
Batch 12/24 | Loss: 1.7294 | Time: 0.56s
Batch 13/24 | Loss: 1.7570 | Time: 0.56s
Batch 14/24 | Loss: 1.7853 | Time: 0.55s
Batch 15/24 | Loss: 1.7778 | Time: 0.56s
Batch 16/24 | Loss: 1.7467 | Time: 0.56s
Batch 17/24 | Loss: 1.7664 | Time: 0.56s
Batch 18/24 | Loss: 1.8988 | Time: 0.56s
Batch 19/24 | Loss: 1.8540 | Time: 0.56s
Batch 20/24 | Loss: 1.7887 | Time: 0.56s
Batch 21/24 | Loss: 1.7407 | Time: 0.56s
Batch 22/24 | Loss: 1.8253 | Time: 0.56s
Batch 23/24 | Loss: 1.8821 | Time: 0.55s
Batch 24/24 | Loss: 1.4399 | Time: 0.39s

---------------- Summary ----------------
Train Loss     : 1.7815
Validation Loss: 2.4137
Training Time  : 19.15 sec
Validation Time: 4.43 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.4137)

================ Epoch 14/50 ================
Batch 01/24 | Loss: 1.6080 | Time: 0.58s
Batch 02/24 | Loss: 1.6953 | Time: 0.55s
Batch 03/24 | Loss: 1.7545 | Time: 0.55s
Batch 04/24 | Loss: 1.6820 | Time: 0.57s
Batch 05/24 | Loss: 1.6366 | Time: 0.56s
Batch 06/24 | Loss: 1.8021 | Time: 0.55s
Batch 07/24 | Loss: 1.6409 | Time: 0.57s
Batch 08/24 | Loss: 1.7829 | Time: 0.60s
Batch 09/24 | Loss: 1.7593 | Time: 0.56s
Batch 10/24 | Loss: 1.7498 | Time: 0.56s
Batch 11/24 | Loss: 1.7051 | Time: 0.55s
Batch 12/24 | Loss: 1.6856 | Time: 0.56s
Batch 13/24 | Loss: 1.7838 | Time: 0.57s
Batch 14/24 | Loss: 1.6430 | Time: 0.56s
Batch 15/24 | Loss: 1.6463 | Time: 0.55s
Batch 16/24 | Loss: 1.8122 | Time: 0.56s
Batch 17/24 | Loss: 1.6659 | Time: 0.56s
Batch 18/24 | Loss: 1.7620 | Time: 0.56s
Batch 19/24 | Loss: 1.6966 | Time: 0.55s
Batch 20/24 | Loss: 1.6821 | Time: 0.56s
Batch 21/24 | Loss: 1.6554 | Time: 0.56s
Batch 22/24 | Loss: 1.6736 | Time: 0.56s
Batch 23/24 | Loss: 1.6626 | Time: 0.56s
Batch 24/24 | Loss: 1.4535 | Time: 0.40s

---------------- Summary ----------------
Train Loss     : 1.6933
Validation Loss: 2.3470
Training Time  : 19.34 sec
Validation Time: 4.37 sec
GPU Memory Used: 1.16 GB
✓ Best model saved(Val Loss: 2.3470)

================ Epoch 15/50 ================
Batch 01/24 | Loss: 1.7309 | Time: 0.60s
Batch 02/24 | Loss: 1.6177 | Time: 0.56s
Batch 03/24 | Loss: 1.6842 | Time: 0.56s
Batch 04/24 | Loss: 1.6359 | Time: 0.56s
Batch 05/24 | Loss: 1.6563 | Time: 0.56s
Batch 06/24 | Loss: 1.6625 | Time: 0.55s
Batch 07/24 | Loss: 1.6296 | Time: 0.56s
Batch 08/24 | Loss: 1.5689 | Time: 0.55s
Batch 09/24 | Loss: 1.5773 | Time: 0.56s
Batch 10/24 | Loss: 1.5525 | Time: 0.56s
Batch 11/24 | Loss: 1.5792 | Time: 0.57s
Batch 12/24 | Loss: 1.5817 | Time: 0.56s
Batch 13/24 | Loss: 1.5366 | Time: 0.56s
Batch 14/24 | Loss: 1.6282 | Time: 0.56s
Batch 15/24 | Loss: 1.7029 | Time: 0.57s
Batch 16/24 | Loss: 1.7246 | Time: 0.56s
Batch 17/24 | Loss: 1.7577 | Time: 0.56s
Batch 18/24 | Loss: 1.7333 | Time: 0.56s
Batch 19/24 | Loss: 1.6380 | Time: 0.56s
Batch 20/24 | Loss: 1.6982 | Time: 0.56s
Batch 21/24 | Loss: 1.6562 | Time: 0.56s
Batch 22/24 | Loss: 1.6080 | Time: 0.56s
Batch 23/24 | Loss: 1.5597 | Time: 0.56s
Batch 24/24 | Loss: 1.4973 | Time: 0.40s

---------------- Summary ----------------
Train Loss     : 1.6341
Validation Loss: 2.3622
Training Time  : 18.28 sec
Validation Time: 4.31 sec
GPU Memory Used: 1.16 GB
No improvement for 1/8 epochs

================ Epoch 16/50 ================
Batch 01/24 | Loss: 1.6244 | Time: 0.60s
Batch 02/24 | Loss: 1.4301 | Time: 0.56s
Batch 03/24 | Loss: 1.5063 | Time: 0.56s
Batch 04/24 | Loss: 1.6317 | Time: 0.56s
Batch 05/24 | Loss: 1.5007 | Time: 0.57s
Batch 06/24 | Loss: 1.5661 | Time: 0.56s
Batch 07/24 | Loss: 1.5717 | Time: 0.56s
Batch 08/24 | Loss: 1.6422 | Time: 0.56s
Batch 09/24 | Loss: 1.5492 | Time: 0.56s
Batch 10/24 | Loss: 1.5653 | Time: 0.56s
Batch 11/24 | Loss: 1.5171 | Time: 0.56s
Batch 12/24 | Loss: 1.6196 | Time: 0.56s
Batch 13/24 | Loss: 1.5382 | Time: 0.56s
Batch 14/24 | Loss: 1.5883 | Time: 0.56s
Batch 15/24 | Loss: 1.6651 | Time: 0.56s
Batch 16/24 | Loss: 1.6102 | Time: 0.56s
Batch 17/24 | Loss: 1.5183 | Time: 0.56s
Batch 18/24 | Loss: 1.6849 | Time: 0.55s
Batch 19/24 | Loss: 1.6191 | Time: 0.56s
Batch 20/24 | Loss: 1.4931 | Time: 0.56s
Batch 21/24 | Loss: 1.5352 | Time: 0.56s
Batch 22/24 | Loss: 1.6706 | Time: 0.56s
Batch 23/24 | Loss: 1.5490 | Time: 0.57s
Batch 24/24 | Loss: 1.2642 | Time: 0.40s

---------------- Summary ----------------
Train Loss     : 1.5608
Validation Loss: 2.3214
Training Time  : 18.83 sec
Validation Time: 4.27 sec
GPU Memory Used: 1.17 GB
✓ Best model saved(Val Loss: 2.3214)

================ Epoch 17/50 ================
Batch 01/24 | Loss: 1.4233 | Time: 0.61s
Batch 02/24 | Loss: 1.4878 | Time: 0.57s
Batch 03/24 | Loss: 1.3339 | Time: 0.56s

      Metric  Image→Text  Text→Image
0   Recall@1    0.314229    0.228458
1   Recall@5    0.626482    0.531818
2  Recall@10    0.748024    0.672530
3        MRR    0.456687    0.371273

Memory after cleanup
Allocated: 0.47182273864746094
Reserved: 2.171875

************************

Processing - flickr30k

************************

/tmp/ipykernel_6999/3535708442.py:66: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  self.transformer = nn.TransformerEncoder(

Streaming output truncated to the last 5000 lines.
Validation Time: 10.89 sec
GPU Memory Used: 1.10 GB
✓ Best model saved(Val Loss: 2.9447)

================ Epoch 3/50 ================
Batch 01/94 | Loss: 2.9935 | Time: 0.60s
Batch 02/94 | Loss: 2.9388 | Time: 0.58s
Batch 03/94 | Loss: 3.0149 | Time: 0.58s
Batch 04/94 | Loss: 3.0593 | Time: 0.58s
Batch 05/94 | Loss: 3.0572 | Time: 0.60s
Batch 06/94 | Loss: 3.3051 | Time: 0.57s
Batch 07/94 | Loss: 3.0444 | Time: 0.57s
Batch 08/94 | Loss: 3.1230 | Time: 0.56s
Batch 09/94 | Loss: 3.2037 | Time: 0.57s
Batch 10/94 | Loss: 3.1700 | Time: 0.57s
Batch 11/94 | Loss: 2.9460 | Time: 0.58s
Batch 12/94 | Loss: 3.0794 | Time: 0.59s
Batch 13/94 | Loss: 2.9594 | Time: 0.60s
Batch 14/94 | Loss: 2.7342 | Time: 0.58s
Batch 15/94 | Loss: 3.2104 | Time: 0.57s
Batch 16/94 | Loss: 3.1639 | Time: 0.57s
Batch 17/94 | Loss: 2.9597 | Time: 0.57s
Batch 18/94 | Loss: 2.9053 | Time: 0.57s
Batch 19/94 | Loss: 2.9819 | Time: 0.59s
Batch 20/94 | Loss: 2.9966 | Time: 0.57s
Batch 21/94 | Loss: 2.9740 | Time: 0.62s
Batch 22/94 | Loss: 2.9419 | Time: 0.58s
Batch 23/94 | Loss: 2.9798 | Time: 0.59s
Batch 24/94 | Loss: 2.8242 | Time: 0.58s
Batch 25/94 | Loss: 2.8232 | Time: 0.59s
Batch 26/94 | Loss: 2.8773 | Time: 0.58s
Batch 27/94 | Loss: 3.0516 | Time: 0.57s
Batch 28/94 | Loss: 2.9607 | Time: 0.57s
Batch 29/94 | Loss: 3.0183 | Time: 0.58s
Batch 30/94 | Loss: 3.1154 | Time: 0.57s
Batch 31/94 | Loss: 2.9554 | Time: 0.57s
Batch 32/94 | Loss: 3.0021 | Time: 0.57s
Batch 33/94 | Loss: 3.0151 | Time: 0.58s
Batch 34/94 | Loss: 3.0366 | Time: 0.57s
Batch 35/94 | Loss: 2.9545 | Time: 0.58s
Batch 36/94 | Loss: 2.9978 | Time: 0.59s
Batch 37/94 | Loss: 2.8285 | Time: 0.57s
Batch 38/94 | Loss: 2.8902 | Time: 0.59s
Batch 39/94 | Loss: 3.0650 | Time: 0.58s
Batch 40/94 | Loss: 3.2531 | Time: 0.57s
Batch 41/94 | Loss: 3.0742 | Time: 0.58s
Batch 42/94 | Loss: 2.9238 | Time: 0.57s
Batch 43/94 | Loss: 3.0451 | Time: 0.59s
Batch 44/94 | Loss: 2.9969 | Time: 0.60s
Batch 45/94 | Loss: 3.0273 | Time: 0.57s
Batch 46/94 | Loss: 3.1039 | Time: 0.58s
Batch 47/94 | Loss: 2.8225 | Time: 0.57s
Batch 48/94 | Loss: 2.8968 | Time: 0.59s
Batch 49/94 | Loss: 2.8873 | Time: 0.58s
Batch 50/94 | Loss: 3.0243 | Time: 0.57s
Batch 51/94 | Loss: 2.8733 | Time: 0.57s
Batch 52/94 | Loss: 3.0647 | Time: 0.59s
Batch 53/94 | Loss: 3.0877 | Time: 0.60s
Batch 54/94 | Loss: 2.9156 | Time: 0.59s
Batch 55/94 | Loss: 3.0132 | Time: 0.58s
Batch 56/94 | Loss: 2.8599 | Time: 0.56s
Batch 57/94 | Loss: 2.9647 | Time: 0.58s
Batch 58/94 | Loss: 2.9517 | Time: 0.60s
Batch 59/94 | Loss: 2.8840 | Time: 0.58s
Batch 60/94 | Loss: 2.9580 | Time: 0.57s
Batch 61/94 | Loss: 2.9397 | Time: 0.57s
Batch 62/94 | Loss: 3.0552 | Time: 0.57s
Batch 63/94 | Loss: 3.0368 | Time: 0.57s
Batch 64/94 | Loss: 2.8658 | Time: 0.59s
Batch 65/94 | Loss: 3.0359 | Time: 0.58s
Batch 66/94 | Loss: 2.8696 | Time: 0.60s
Batch 67/94 | Loss: 2.8982 | Time: 0.56s
Batch 68/94 | Loss: 2.8927 | Time: 0.59s
Batch 69/94 | Loss: 2.8727 | Time: 0.61s
Batch 70/94 | Loss: 2.8028 | Time: 0.58s
Batch 71/94 | Loss: 2.7722 | Time: 0.59s
Batch 72/94 | Loss: 2.8249 | Time: 0.57s
Batch 73/94 | Loss: 3.0742 | Time: 0.58s
Batch 74/94 | Loss: 3.0141 | Time: 0.57s
Batch 75/94 | Loss: 3.0422 | Time: 0.57s
Batch 76/94 | Loss: 2.7015 | Time: 0.58s
Batch 77/94 | Loss: 2.8267 | Time: 0.57s
Batch 78/94 | Loss: 2.8230 | Time: 0.59s
Batch 79/94 | Loss: 2.9049 | Time: 0.58s
Batch 80/94 | Loss: 2.9992 | Time: 0.58s
Batch 81/94 | Loss: 3.0049 | Time: 0.58s
Batch 82/94 | Loss: 2.7659 | Time: 0.57s
Batch 83/94 | Loss: 2.8179 | Time: 0.57s
Batch 84/94 | Loss: 2.7720 | Time: 0.57s
Batch 85/94 | Loss: 3.0262 | Time: 0.58s
Batch 86/94 | Loss: 2.7831 | Time: 0.58s
Batch 87/94 | Loss: 3.0468 | Time: 0.57s
Batch 88/94 | Loss: 2.8885 | Time: 0.59s
Batch 89/94 | Loss: 2.8032 | Time: 0.58s
Batch 90/94 | Loss: 2.7606 | Time: 0.58s
Batch 91/94 | Loss: 2.7126 | Time: 0.58s
Batch 92/94 | Loss: 2.8980 | Time: 0.57s
Batch 93/94 | Loss: 2.8324 | Time: 0.59s
Batch 94/94 | Loss: 0.7842 | Time: 0.07s

---------------- Summary ----------------
Train Loss     : 2.9355
Validation Loss: 2.6870
Training Time  : 60.91 sec
Validation Time: 10.85 sec
GPU Memory Used: 1.10 GB
✓ Best model saved(Val Loss: 2.6870)

================ Epoch 4/50 ================
Batch 01/94 | Loss: 2.7017 | Time: 0.59s
Batch 02/94 | Loss: 2.8260 | Time: 0.58s
Batch 03/94 | Loss: 2.8336 | Time: 0.57s
Batch 04/94 | Loss: 2.7671 | Time: 0.59s
Batch 05/94 | Loss: 2.6994 | Time: 0.58s
Batch 06/94 | Loss: 2.9518 | Time: 0.57s
Batch 07/94 | Loss: 2.7873 | Time: 0.58s
Batch 08/94 | Loss: 2.6424 | Time: 0.58s
Batch 09/94 | Loss: 2.6517 | Time: 0.57s
Batch 10/94 | Loss: 2.7411 | Time: 0.58s
Batch 11/94 | Loss: 2.6887 | Time: 0.57s
Batch 12/94 | Loss: 2.6579 | Time: 0.58s
Batch 13/94 | Loss: 2.7224 | Time: 0.60s
Batch 14/94 | Loss: 2.6481 | Time: 0.57s
Batch 15/94 | Loss: 2.6505 | Time: 0.56s
Batch 16/94 | Loss: 2.7350 | Time: 0.59s
Batch 17/94 | Loss: 2.7460 | Time: 0.57s
Batch 18/94 | Loss: 2.6228 | Time: 0.58s
Batch 19/94 | Loss: 2.7460 | Time: 0.57s
Batch 20/94 | Loss: 2.7737 | Time: 0.62s
Batch 21/94 | Loss: 2.6252 | Time: 0.58s
Batch 22/94 | Loss: 2.7136 | Time: 0.58s
Batch 23/94 | Loss: 2.5560 | Time: 0.58s
Batch 24/94 | Loss: 2.7520 | Time: 0.58s
Batch 25/94 | Loss: 2.6925 | Time: 0.57s
Batch 26/94 | Loss: 2.7666 | Time: 0.57s
Batch 27/94 | Loss: 2.6647 | Time: 0.57s
Batch 28/94 | Loss: 2.8614 | Time: 0.56s
Batch 29/94 | Loss: 2.6134 | Time: 0.59s
Batch 30/94 | Loss: 2.5966 | Time: 0.57s
Batch 31/94 | Loss: 2.5933 | Time: 0.61s
Batch 32/94 | Loss: 2.7847 | Time: 0.58s
Batch 33/94 | Loss: 2.6584 | Time: 0.58s
Batch 34/94 | Loss: 2.6351 | Time: 0.60s
Batch 35/94 | Loss: 2.6070 | Time: 0.58s
Batch 36/94 | Loss: 2.5622 | Time: 0.57s
Batch 37/94 | Loss: 2.6649 | Time: 0.58s
Batch 38/94 | Loss: 2.6323 | Time: 0.56s
Batch 39/94 | Loss: 2.5294 | Time: 0.57s
Batch 40/94 | Loss: 2.6680 | Time: 0.59s
Batch 41/94 | Loss: 2.5971 | Time: 0.57s
Batch 42/94 | Loss: 2.6844 | Time: 0.59s
Batch 43/94 | Loss: 2.6102 | Time: 0.57s
Batch 44/94 | Loss: 2.6648 | Time: 0.62s
Batch 45/94 | Loss: 2.6981 | Time: 0.59s
Batch 46/94 | Loss: 2.6751 | Time: 0.56s
Batch 47/94 | Loss: 2.5620 | Time: 0.59s
Batch 48/94 | Loss: 2.7639 | Time: 0.56s
Batch 49/94 | Loss: 2.7477 | Time: 0.58s
Batch 50/94 | Loss: 2.8369 | Time: 0.58s
Batch 51/94 | Loss: 2.8099 | Time: 0.62s
Batch 52/94 | Loss: 2.6448 | Time: 0.57s
Batch 53/94 | Loss: 2.7582 | Time: 0.57s
Batch 54/94 | Loss: 2.5998 | Time: 0.59s
Batch 55/94 | Loss: 2.6303 | Time: 0.57s
Batch 56/94 | Loss: 2.6340 | Time: 0.57s
Batch 57/94 | Loss: 2.6813 | Time: 0.57s
Batch 58/94 | Loss: 2.6111 | Time: 0.57s
Batch 59/94 | Loss: 2.7105 | Time: 0.57s
Batch 60/94 | Loss: 2.6741 | Time: 0.58s
Batch 61/94 | Loss: 2.7974 | Time: 0.58s
Batch 62/94 | Loss: 2.6392 | Time: 0.59s
Batch 63/94 | Loss: 2.4688 | Time: 0.57s
Batch 64/94 | Loss: 2.8350 | Time: 0.57s
Batch 65/94 | Loss: 2.6662 | Time: 0.58s
Batch 66/94 | Loss: 2.6876 | Time: 0.57s
Batch 67/94 | Loss: 2.6548 | Time: 0.57s
Batch 68/94 | Loss: 2.6325 | Time: 0.59s
Batch 69/94 | Loss: 2.6662 | Time: 0.58s
Batch 70/94 | Loss: 2.7280 | Time: 0.58s
Batch 71/94 | Loss: 2.7812 | Time: 0.57s
Batch 72/94 | Loss: 2.6907 | Time: 0.57s
Batch 73/94 | Loss: 2.5448 | Time: 0.57s
Batch 74/94 | Loss: 2.4991 | Time: 0.58s
Batch 75/94 | Loss: 2.7641 | Time: 0.56s
Batch 76/94 | Loss: 2.7139 | Time: 0.57s
Batch 77/94 | Loss: 2.6393 | Time: 0.57s
Batch 78/94 | Loss: 2.6704 | Time: 0.57s
Batch 79/94 | Loss: 2.6829 | Time: 0.58s
Batch 80/94 | Loss: 2.7519 | Time: 0.58s
Batch 81/94 | Loss: 2.6648 | Time: 0.57s
Batch 82/94 | Loss: 2.5430 | Time: 0.57s
Batch 83/94 | Loss: 2.6050 | Time: 0.58s
Batch 84/94 | Loss: 2.5704 | Time: 0.59s
Batch 85/94 | Loss: 2.4455 | Time: 0.59s
Batch 86/94 | Loss: 2.3667 | Time: 0.56s
Batch 87/94 | Loss: 2.5447 | Time: 0.58s
Batch 88/94 | Loss: 2.4426 | Time: 0.58s
Batch 89/94 | Loss: 2.6086 | Time: 0.59s
Batch 90/94 | Loss: 2.5591 | Time: 0.57s
Batch 91/94 | Loss: 2.7017 | Time: 0.57s
Batch 92/94 | Loss: 2.4131 | Time: 0.57s
Batch 93/94 | Loss: 2.3892 | Time: 0.57s
Batch 94/94 | Loss: 0.9704 | Time: 0.07s

---------------- Summary ----------------
Train Loss     : 2.6458
Validation Loss: 2.4703
Training Time  : 59.82 sec
Validation Time: 11.49 sec
GPU Memory Used: 1.10 GB
✓ Best model saved(Val Loss: 2.4703)

================ Epoch 5/50 ================
Batch 01/94 | Loss: 2.4491 | Time: 0.59s
Batch 02/94 | Loss: 2.4942 | Time: 0.58s
Batch 03/94 | Loss: 2.4627 | Time: 0.58s
Batch 04/94 | Loss: 2.4216 | Time: 0.59s
Batch 05/94 | Loss: 2.5210 | Time: 0.59s
Batch 06/94 | Loss: 2.4891 | Time: 0.58s
Batch 07/94 | Loss: 2.5686 | Time: 0.57s
Batch 08/94 | Loss: 2.4629 | Time: 0.57s
Batch 09/94 | Loss: 2.5533 | Time: 0.58s
Batch 10/94 | Loss: 2.5526 | Time: 0.57s
Batch 11/94 | Loss: 2.5784 | Time: 0.57s
Batch 12/94 | Loss: 2.2892 | Time: 0.57s
Batch 13/94 | Loss: 2.5336 | Time: 0.60s
Batch 14/94 | Loss: 2.4708 | Time: 0.58s
Batch 15/94 | Loss: 2.3988 | Time: 0.58s
Batch 16/94 | Loss: 2.3831 | Time: 0.57s
Batch 17/94 | Loss: 2.3950 | Time: 0.57s
Batch 18/94 | Loss: 2.5276 | Time: 0.58s
Batch 19/94 | Loss: 2.5583 | Time: 0.60s
Batch 20/94 | Loss: 2.4992 | Time: 0.58s
Batch 21/94 | Loss: 2.5285 | Time: 0.61s
Batch 22/94 | Loss: 2.6024 | Time: 0.57s
Batch 23/94 | Loss: 2.5169 | Time: 0.56s
Batch 24/94 | Loss: 2.6623 | Time: 0.59s
Batch 25/94 | Loss: 2.7356 | Time: 0.60s
Batch 26/94 | Loss: 2.3260 | Time: 0.57s
Batch 27/94 | Loss: 2.4422 | Time: 0.58s
Batch 28/94 | Loss: 2.3684 | Time: 0.57s
Batch 29/94 | Loss: 2.5793 | Time: 0.58s
Batch 30/94 | Loss: 2.3713 | Time: 0.56s
Batch 31/94 | Loss: 2.6271 | Time: 0.58s
Batch 32/94 | Loss: 2.4395 | Time: 0.60s
Batch 33/94 | Loss: 2.6176 | Time: 0.59s
Batch 34/94 | Loss: 2.4734 | Time: 0.60s
Batch 35/94 | Loss: 2.3826 | Time: 0.56s
Batch 36/94 | Loss: 2.2692 | Time: 0.58s
Batch 37/94 | Loss: 2.3220 | Time: 0.58s
Batch 38/94 | Loss: 2.3711 | Time: 0.59s
Batch 39/94 | Loss: 2.5497 | Time: 0.58s
Batch 40/94 | Loss: 2.4992 | Time: 0.58s
Batch 41/94 | Loss: 2.4364 | Time: 0.58s
Batch 42/94 | Loss: 2.3539 | Time: 0.56s
Batch 43/94 | Loss: 2.3127 | Time: 0.58s
Batch 44/94 | Loss: 2.5417 | Time: 0.57s
Batch 45/94 | Loss: 2.4999 | Time: 0.58s
Batch 46/94 | Loss: 2.4149 | Time: 0.57s
Batch 47/94 | Loss: 2.3682 | Time: 0.57s
Batch 48/94 | Loss: 2.5413 | Time: 0.58s
Batch 49/94 | Loss: 2.6082 | Time: 0.57s
Batch 50/94 | Loss: 2.3912 | Time: 0.59s
Batch 51/94 | Loss: 2.2434 | Time: 0.57s
Batch 52/94 | Loss: 2.2883 | Time: 0.58s
Batch 53/94 | Loss: 2.5225 | Time: 0.56s
Batch 54/94 | Loss: 2.3739 | Time: 0.57s
Batch 55/94 | Loss: 2.4588 | Time: 0.58s
Batch 56/94 | Loss: 2.3426 | Time: 0.58s
Batch 57/94 | Loss: 2.5181 | Time: 0.57s
Batch 58/94 | Loss: 2.3967 | Time: 0.57s
Batch 59/94 | Loss: 2.4592 | Time: 0.57s
Batch 60/94 | Loss: 2.6182 | Time: 0.57s
Batch 61/94 | Loss: 2.6146 | Time: 0.58s
Batch 62/94 | Loss: 2.3759 | Time: 0.59s
Batch 63/94 | Loss: 2.1522 | Time: 0.59s
Batch 64/94 | Loss: 2.6877 | Time: 0.57s
Batch 65/94 | Loss: 2.4110 | Time: 0.59s
Batch 66/94 | Loss: 2.4574 | Time: 0.59s
Batch 67/94 | Loss: 2.6133 | Time: 0.58s
Batch 68/94 | Loss: 2.4345 | Time: 0.58s
Batch 69/94 | Loss: 2.4600 | Time: 0.60s
Batch 70/94 | Loss: 2.4784 | Time: 0.58s
Batch 71/94 | Loss: 2.1784 | Time: 0.58s
Batch 72/94 | Loss: 2.2743 | Time: 0.58s
Batch 73/94 | Loss: 2.5090 | Time: 0.57s
Batch 74/94 | Loss: 2.3204 | Time: 0.59s
Batch 75/94 | Loss: 2.4962 | Time: 0.57s
Batch 76/94 | Loss: 2.4667 | Time: 0.59s
Batch 77/94 | Loss: 2.6447 | Time: 0.59s
Batch 78/94 | Loss: 2.5346 | Time: 0.57s
Batch 79/94 | Loss: 2.3899 | Time: 0.59s
Batch 80/94 | Loss: 2.2409 | Time: 0.58s
Batch 81/94 | Loss: 2.1979 | Time: 0.57s
Batch 82/94 | Loss: 2.3837 | Time: 0.58s
Batch 83/94 | Loss: 2.4508 | Time: 0.58s
Batch 84/94 | Loss: 2.4735 | Time: 0.59s
Batch 85/94 | Loss: 2.4635 | Time: 0.57s
Batch 86/94 | Loss: 2.4640 | Time: 0.57s
Batch 87/94 | Loss: 2.4253 | Time: 0.59s
Batch 88/94 | Loss: 2.5175 | Time: 0.57s
Batch 89/94 | Loss: 2.5253 | Time: 0.56s
Batch 90/94 | Loss: 2.3535 | Time: 0.58s
Batch 91/94 | Loss: 2.4989 | Time: 0.57s
Batch 92/94 | Loss: 2.4964 | Time: 0.57s
Batch 93/94 | Loss: 2.3112 | Time: 0.57s
Batch 94/94 | Loss: 1.3594 | Time: 0.07s

---------------- Summary ----------------
Train Loss     : 2.4430
Validation Loss: 2.3537
Training Time  : 60.34 sec
Validation Time: 11.64 sec
GPU Memory Used: 1.10 GB
✓ Best model saved(Val Loss: 2.3537)

================ Epoch 6/50 ================
Batch 01/94 | Loss: 2.2131 | Time: 0.61s
Batch 02/94 | Loss: 2.4072 | Time: 0.57s
Batch 03/94 | Loss: 2.2221 | Time: 0.60s
Batch 04/94 | Loss: 2.2317 | Time: 0.59s
Batch 05/94 | Loss: 2.2022 | Time: 0.58s
Batch 06/94 | Loss: 2.5092 | Time: 0.58s
Batch 07/94 | Loss: 2.2428 | Time: 0.57s
Batch 08/94 | Loss: 2.4239 | Time: 0.57s
Batch 09/94 | Loss: 2.2759 | Time: 0.57s
Batch 10/94 | Loss: 2.2028 | Time: 0.57s
Batch 11/94 | Loss: 2.2493 | Time: 0.56s
Batch 12/94 | Loss: 2.2685 | Time: 0.60s
Batch 13/94 | Loss: 2.2527 | Time: 0.60s
Batch 14/94 | Loss: 2.1850 | Time: 0.57s
Batch 15/94 | Loss: 2.3779 | Time: 0.57s
Batch 16/94 | Loss: 2.1870 | Time: 0.60s
Batch 17/94 | Loss: 2.3288 | Time: 0.57s
Batch 18/94 | Loss: 2.2765 | Time: 0.58s
Batch 19/94 | Loss: 2.0830 | Time: 0.59s
Batch 20/94 | Loss: 2.3425 | Time: 0.57s
Batch 21/94 | Loss: 2.2383 | Time: 0.57s
Batch 22/94 | Loss: 2.1305 | Time: 0.58s
Batch 23/94 | Loss: 2.1533 | Time: 0.57s
Batch 24/94 | Loss: 2.3967 | Time: 0.58s
Batch 25/94 | Loss: 2.4572 | Time: 0.57s
Batch 26/94 | Loss: 2.4756 | Time: 0.58s
Batch 27/94 | Loss: 2.4180 | Time: 0.56s
Batch 28/94 | Loss: 2.1123 | Time: 0.58s
Batch 29/94 | Loss: 2.3088 | Time: 0.57s
Batch 30/94 | Loss: 2.1907 | Time: 0.57s
Batch 31/94 | Loss: 2.2020 | Time: 0.58s
Batch 32/94 | Loss: 2.3708 | Time: 0.57s
Batch 33/94 | Loss: 2.0451 | Time: 0.57s
Batch 34/94 | Loss: 2.2484 | Time: 0.56s
Batch 35/94 | Loss: 2.3560 | Time: 0.62s
Batch 36/94 | Loss: 2.3061 | Time: 0.58s
Batch 37/94 | Loss: 2.3026 | Time: 0.60s
Batch 38/94 | Loss: 2.4635 | Time: 0.57s
Batch 39/94 | Loss: 2.3383 | Time: 0.60s
Batch 40/94 | Loss: 2.4166 | Time: 0.59s
Batch 41/94 | Loss: 2.1847 | Time: 0.56s
Batch 42/94 | Loss: 2.2877 | Time: 0.59s
Batch 43/94 | Loss: 2.2837 | Time: 0.56s
Batch 44/94 | Loss: 2.1660 | Time: 0.57s
Batch 45/94 | Loss: 2.1884 | Time: 0.58s
Batch 46/94 | Loss: 2.4590 | Time: 0.57s
Batch 47/94 | Loss: 2.3524 | Time: 0.56s
Batch 48/94 | Loss: 2.2494 | Time: 0.57s
Batch 49/94 | Loss: 2.3723 | Time: 0.59s
Batch 50/94 | Loss: 2.3407 | Time: 0.56s
Batch 51/94 | Loss: 2.3455 | Time: 0.59s
Batch 52/94 | Loss: 2.2491 | Time: 0.57s
Batch 53/94 | Loss: 2.3928 | Time: 0.57s
Batch 54/94 | Loss: 2.1792 | Time: 0.57s
Batch 55/94 | Loss: 2.2612 | Time: 0.57s
Batch 56/94 | Loss: 2.2647 | Time: 0.56s
Batch 57/94 | Loss: 2.4008 | Time: 0.60s
Batch 58/94 | Loss: 2.2024 | Time: 0.58s
Batch 59/94 | Loss: 2.2285 | Time: 0.58s
Batch 60/94 | Loss: 2.3569 | Time: 0.57s
Batch 61/94 | Loss: 2.1841 | Time: 0.58s
Batch 62/94 | Loss: 2.2705 | Time: 0.57s
Batch 63/94 | Loss: 2.4741 | Time: 0.57s
Batch 64/94 | Loss: 2.3210 | Time: 0.58s
Batch 65/94 | Loss: 2.3629 | Time: 0.58s
Batch 66/94 | Loss: 2.3039 | Time: 0.63s
Batch 67/94 | Loss: 2.2232 | Time: 0.63s
Batch 68/94 | Loss: 2.1121 | Time: 0.57s
Batch 69/94 | Loss: 2.3774 | Time: 0.56s
Batch 70/94 | Loss: 2.3505 | Time: 0.58s
Batch 71/94 | Loss: 2.2623 | Time: 0.56s
Batch 72/94 | Loss: 2.4906 | Time: 0.56s
Batch 73/94 | Loss: 2.1887 | Time: 0.57s
Batch 74/94 | Loss: 2.0702 | Time: 0.57s
Batch 75/94 | Loss: 2.3062 | Time: 0.58s
Batch 76/94 | Loss: 2.3831 | Time: 0.58s
Batch 77/94 | Loss: 2.0565 | Time: 0.59s
Batch 78/94 | Loss: 2.3722 | Time: 0.58s
Batch 79/94 | Loss: 2.3886 | Time: 0.58s
Batch 80/94 | Loss: 2.2336 | Time: 0.56s
Batch 81/94 | Loss: 2.1931 | Time: 0.60s
Batch 82/94 | Loss: 2.3826 | Time: 0.57s
Batch 83/94 | Loss: 2.2678 | Time: 0.59s
Batch 84/94 | Loss: 2.2732 | Time: 0.59s
Batch 85/94 | Loss: 2.3383 | Time: 0.57s
Batch 86/94 | Loss: 2.3891 | Time: 0.57s
Batch 87/94 | Loss: 2.2781 | Time: 0.57s
Batch 88/94 | Loss: 2.3783 | Time: 0.57s
Batch 89/94 | Loss: 2.2021 | Time: 0.59s
Batch 90/94 | Loss: 2.1582 | Time: 0.58s
Batch 91/94 | Loss: 2.2743 | Time: 0.58s
Batch 92/94 | Loss: 2.2490 | Time: 0.57s
Batch 93/94 | Loss: 2.1825 | Time: 0.59s
Batch 94/94 | Loss: 0.5781 | Time: 0.07s

---------------- Summary ----------------
Train Loss     : 2.2665
Validation Loss: 2.2375
Training Time  : 59.19 sec
Validation Time: 11.52 sec
GPU Memory Used: 1.10 GB
✓ Best model saved(Val Loss: 2.2375)

================ Epoch 7/50 ================
Batch 01/94 | Loss: 2.1183 | Time: 0.60s
Batch 02/94 | Loss: 2.2932 | Time: 0.58s
Batch 03/94 | Loss: 2.3007 | Time: 0.57s
Batch 04/94 | Loss: 2.1477 | Time: 0.58s
Batch 05/94 | Loss: 2.2716 | Time: 0.58s
Batch 06/94 | Loss: 2.1171 | Time: 0.57s
Batch 07/94 | Loss: 2.2721 | Time: 0.57s
Batch 08/94 | Loss: 2.0652 | Time: 0.57s
Batch 09/94 | Loss: 2.2016 | Time: 0.60s
Batch 10/94 | Loss: 2.3744 | Time: 0.58s
Batch 11/94 | Loss: 2.2779 | Time: 0.59s
Batch 12/94 | Loss: 2.0486 | Time: 0.60s
Batch 13/94 | Loss: 2.1447 | Time: 0.59s
Batch 14/94 | Loss: 2.2281 | Time: 0.57s
Batch 15/94 | Loss: 2.2329 | Time: 0.57s
Batch 16/94 | Loss: 2.2021 | Time: 0.58s
Batch 17/94 | Loss: 2.1492 | Time: 0.59s
Batch 18/94 | Loss: 2.0115 | Time: 0.60s
Batch 19/94 | Loss: 2.1002 | Time: 0.57s
Batch 20/94 | Loss: 2.1525 | Time: 0.57s
Batch 21/94 | Loss: 2.2805 | Time: 0.59s
Batch 22/94 | Loss: 2.2500 | Time: 0.58s
Batch 23/94 | Loss: 2.2186 | Time: 0.58s
Batch 24/94 | Loss: 2.1507 | Time: 0.58s
Batch 25/94 | Loss: 2.2517 | Time: 0.59s
Batch 26/94 | Loss: 2.0700 | Time: 0.60s
Batch 27/94 | Loss: 2.1621 | Time: 0.58s
Batch 28/94 | Loss: 1.9769 | Time: 0.60s
Batch 29/94 | Loss: 2.0969 | Time: 0.58s
Batch 30/94 | Loss: 2.2237 | Time: 0.60s
Batch 31/94 | Loss: 2.0076 | Time: 0.59s
Batch 32/94 | Loss: 2.1590 | Time: 0.57s
Batch 33/94 | Loss: 2.0432 | Time: 0.59s
Batch 34/94 | Loss: 2.1927 | Time: 0.59s
Batch 35/94 | Loss: 2.0927 | Time: 0.57s
Batch 36/94 | Loss: 2.1468 | Time: 0.58s
Batch 37/94 | Loss: 2.1227 | Time: 0.57s
Batch 38/94 | Loss: 2.1537 | Time: 0.57s
Batch 39/94 | Loss: 2.2239 | Time: 0.58s
Batch 40/94 | Loss: 2.4861 | Time: 0.56s
Batch 41/94 | Loss: 2.1704 | Time: 0.57s
Batch 42/94 | Loss: 2.2659 | Time: 0.59s
Batch 43/94 | Loss: 2.3349 | Time: 0.56s
Batch 44/94 | Loss: 2.2828 | Time: 0.58s
Batch 45/94 | Loss: 2.1701 | Time: 0.57s
Batch 46/94 | Loss: 2.0194 | Time: 0.59s
Batch 47/94 | Loss: 2.0886 | Time: 0.58s
Batch 48/94 | Loss: 2.0754 | Time: 0.61s
Batch 49/94 | Loss: 2.2344 | Time: 0.60s
Batch 50/94 | Loss: 2.1537 | Time: 0.57s
Batch 51/94 | Loss: 2.0898 | Time: 0.59s
Batch 52/94 | Loss: 2.1939 | Time: 0.58s
Batch 53/94 | Loss: 2.1952 | Time: 0.57s
Batch 54/94 | Loss: 2.1684 | Time: 0.58s
Batch 55/94 | Loss: 2.3111 | Time: 0.59s
Batch 56/94 | Loss: 2.1026 | Time: 0.57s
Batch 57/94 | Loss: 2.2027 | Time: 0.58s
Batch 58/94 | Loss: 2.2776 | Time: 0.58s
Batch 59/94 | Loss: 2.0421 | Time: 0.60s
Batch 60/94 | Loss: 2.2143 | Time: 0.57s
Batch 61/94 | Loss: 2.2536 | Time: 0.58s
Batch 62/94 | Loss: 2.3018 | Time: 0.57s
Batch 63/94 | Loss: 2.1111 | Time: 0.57s
Batch 64/94 | Loss: 1.9800 | Time: 0.58s
Batch 65/94 | Loss: 1.9588 | Time: 0.58s
Batch 66/94 | Loss: 2.1287 | Time: 0.57s
Batch 67/94 | Loss: 2.2737 | Time: 0.59s
Batch 68/94 | Loss: 2.2000 | Time: 0.57s
Batch 69/94 | Loss: 2.3040 | Time: 0.56s
Batch 70/94 | Loss: 2.1381 | Time: 0.58s
Batch 71/94 | Loss: 2.2737 | Time: 0.57s
Batch 72/94 | Loss: 2.1489 | Time: 0.60s
Batch 73/94 | Loss: 2.2467 | Time: 0.57s
Batch 74/94 | Loss: 2.2128 | Time: 0.58s
Batch 75/94 | Loss: 2.0598 | Time: 0.56s
Batch 76/94 | Loss: 2.2398 | Time: 0.57s
Batch 77/94 | Loss: 2.0552 | Time: 0.60s
Batch 78/94 | Loss: 2.2579 | Time: 0.59s
Batch 79/94 | Loss: 2.2845 | Time: 0.59s
Batch 80/94 | Loss: 2.2532 | Time: 0.59s
Batch 81/94 | Loss: 2.0911 | Time: 0.57s
Batch 82/94 | Loss: 1.9007 | Time: 0.57s

      Metric  Image→Text  Text→Image
0   Recall@1    0.261515    0.177397
1   Recall@5    0.537126    0.423861
2  Recall@10    0.662472    0.544375
3        MRR    0.392322    0.295933

Memory after cleanup
Allocated: 0.4864997863769531
Reserved: 2.11328125